### ISSUE TITLE
为什么用RandomAccessFile下载的文件，会比实际的大

### ISSUE THREAD

**Issue by CaptainJno** [AriaLyy/Aria#1]
Aria里文件下载都是用的RandomAccessFile，我下载apk时，为什么服务器上文件大小是3M，但实际上下载完成后，是5M。两端文件大小不一致。希望给予解答

**Comment by AriaLyy** [comment]
RandomAccessFile 只是一个对文件进行读写的工具类而已，它是不会改变文件的实际大小的。在Aria里面是通过HttpURLConnection 的getContentLength() 来读取文件的真实长度，而该长度是由服务端提供；所以是不会存在两个端文件长度不一致的情况。
至于你遇到的情况，我猜测有可能是服务端单位转换算法出现的问题；建议你把下载链接拷贝出来，用迅雷或浏览器下载，然后和Aria下载的apk、服务端保存的apk，进行大小比对。

**Comment by CaptainJno** [comment]
你好。我用您的项目测试后，出现以下情况，如果方便的话，麻烦帮忙分析一下：
1、分别用浏览器和您的项目（多线程），下载项目中自带的链接apk，两种方式文件大小**一致**。
2、分别用浏览器和您的项目（多线程），下载我自己的链接apk，两种方式文件大小**不一致**。 多线程比浏览器下载的大（分别是4.98M和2.98M）。源文件大小2.98M，浏览器下载的大小正确。
我的源文件链接是https，我自己写单线程下载，文件大小也是2.98M，正确。
根据上述描述情况，我觉得问题出现在服务器上。但是，我不确定。
希望您根据您的经验，帮我再分析分析问题所在。
