### ISSUE TITLE
RecyclerView下载文件， 刷新ProgressBar

### ISSUE THREAD

**Issue by candebbs** [AriaLyy/Aria#101]
碰到一个奇怪的bug: RecyclerView下载文件， 刷新ProgressBar，第一次进入RecyclerView列表点击下载，发现可以刷新ProgressBar，第二次进入RecyclerView列表下载文件，就不会刷新ProgressBar
，
但是下载文件进度的方法taskRunning可以回调的，发现notifyDataSetChanged方法无起作用，同时发现把app退出后，出现同样的问题，请问下怎样解决，谢谢。

**Comment by AriaLyy** [comment]
不知道你是什么情况，以我对RecyclerView的理解，刷新不了很大原因是你Activity的数据List和RecyclerView中数据List不是同一个，或者是RecyclerView中的List已经发生了改变，不再是原来的List。
这种情况大多都是直接赋值`List oldList = newList`导致的指针指向错误，如果是这种问题，建议直接使用oldList.addAll(newList)。
如果不是这个问题，就需要进一步的源码分析了

**Comment by candebbs** [comment]
感谢，有了思路，发现Activity的数据List和RecyclerView中数据List不是同一个。
