### ISSUE TITLE
你好，可以对单个任务组进行删除吗？

### ISSUE THREAD

**Issue by matbird** [AriaLyy/Aria#104]

**Comment by AriaLyy** [comment]
意思是删除任务组中的单个子任务？还是直接删除整个任务组？

**Comment by matbird** [comment]
直接删除整个任务~

**Comment by AriaLyy** [comment]
可以，调用canecl就行了

**Comment by matbird** [comment]
Aria.download(this).load(item.getUrls()).cancel(true);
调用之后无效啊~

**Comment by AriaLyy** [comment]
问题是文件没被删除，对吗？我这找到问题了，在任务完成后，删除不了文件，而任务执行中却可以删除..

**Comment by matbird** [comment]
下载完成后，数据库里的记录也没有删除

**Comment by AriaLyy** [comment]
`3.2.25`版本已经修复了这个问题
