### ISSUE TITLE
全部暂停后，全部恢复，崩溃

### ISSUE THREAD

**Issue by gemgao** [AriaLyy/Aria#105]
我用Aria.download(this).stopAllTask();暂停后，然后Aria.download(this).resumeAllTask();开始，就会报空指针异常；然后全部暂停也只是暂停正在下载的，等待的会继续下载；报错如下：
:08.718 9210-9210/com.ruicheng.teacher W/SettingsInterface: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
08-31 17:27:08.725 9210-9210/com.ruicheng.teacher W/SettingsInterface: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.arialyy.aria.core.command.normal.ResumeAllCmd.resumeDownload(ResumeAllCmd.java:49)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.arialyy.aria.core.command.normal.ResumeAllCmd.executeCmd(ResumeAllCmd.java:30)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:160)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.arialyy.aria.core.download.DownloadReceiver.resumeAllTask(DownloadReceiver.java:287)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.ruicheng.teacher.activity.DownloadActivity.onClick(DownloadActivity.java:194)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.ruicheng.teacher.activity.DownloadActivity$$ViewBinder$1.doClick(DownloadActivity$$ViewBinder.java:18)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at android.view.View.performClick(View.java:4909)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at android.view.View$PerformClick.run(View.java:20390)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at android.os.Looper.loop(Looper.java:192)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5917)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1099)
08-31 17:27:08.727 9210-9210/com.ruicheng.teacher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

**Comment by AriaLyy** [comment]
`3.2.25`版本已经修复了这个问题

**Comment by gemgao** [comment]
ok，已经测试过了，可以了
