### ISSUE TITLE
一个很奇怪的bug

### ISSUE THREAD

**Issue by instanceofz** [AriaLyy/Aria#107]
我测试更新app的时候是把一个下载地址写固定了用来测试下载和打开apk到安装的界面。之后对接服务器的返回的数据，也就是正式的更新的时候下载的apk地址。之后，第一次下载是对的，就是服务器上面的apk文件，但是第二次之后，就会自动下载了用来测试的时候的那个地址的apk，是不是弄了缓存还是什么的呢?

**Comment by AriaLyy** [comment]
看这个issues https://github.com/AriaLyy/Aria/issues/89#issuecomment-322364183

**Comment by instanceofz** [comment]
Aria.download(this)
//                    .load("http://gdown.baidu.com/data/wisegame/0904344dee4a2d92/QQ_718.apk")
                    .load(downloadUrl,true)
                    .setDownloadPath(file.getAbsolutePath())
                    .start();
注释掉的哪行就是我用来测试下载文件的地址，downloadUrl为服务器返回的下载地址。但是我 使用了load(downloadUrl,true)还是没有效果，依然下载了QQ_718.apk

**Comment by AriaLyy** [comment]
我重新测试了下，并没有出现你的那个问题，
首先我使用了
`http://gdown.baidu.com/data/wisegame/0904344dee4a2d92/QQ_718.apk`
进行下载，然后我其他参数没变，我将Url更换为`http://static.gaoshouyou.com/d/36/69/2d3699acfa69e9632262442c46516ad8.apk`
是可以正常下载的，建议你在下载前，打印下服务器返回的下载地址，是否和你的那个测试地址一致；

**Comment by instanceofz** [comment]
我刚刚换了台电脑试了下，前面两三次切换URL下载没问题的，但是到后面几次就出现问题了，我把地址写死，下载的是QQ，但是却下载了另外那个url的apk

**Comment by AriaLyy** [comment]
你是否使用了instance run？在下载前控制台打印的url是否正确？

**Comment by instanceofz** [comment]
instance run关闭的，每次重新编译。url是对的，我改成用Okhttp下载就正常

**Comment by AriaLyy** [comment]
`3.2.25`版本已经修复了这个问题
