### ISSUE TITLE
关于任务组列表的问题

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#108]
你好，我在使用Aria.download(this).getGroupTaskList()获取到任务组下载列表后，想获取列表中某个下载任务的urls，获取不到呢。
譬如：List<DownloadGroupEntity> taskList= Aria.download(this).getGroupTaskList()；
DownloadGroupEntity entity= taskList.get(0);
List<String> urllList = entity.getUrls();
这个urlList里面没有值呢，这不应该是获取组下载的下载地址列表吗？

**Comment by AriaLyy** [comment]
`3.2.25`版本已经修复了这个问题
