### ISSUE TITLE
能否增加一个安装完成的回调方法

### ISSUE THREAD

**Issue by rangerTao** [AriaLyy/Aria#109]
如题

**Comment by AriaLyy** [comment]
安装完成的事件是通过广播接收的，完全可以在activity中接收这个广播，如果是Aria中，则广播的接收是会反正全局的，增加了不必要的内存消耗，所有这个回调的意义不是很大。

**Comment by rangerTao** [comment]
抱歉打扰了   这个问题我自己解决了  当时是因为在某些手机上 安装完成的广播会比较慢  所以会出现实际安装完，但是界面没刷新的情况。

**Comment by rangerTao** [comment]
而且，当时理解的有点片面，你这个库针对的是全部的下载场景，所以只关注于下载的状态。而我是把这个场景具体到apk下载和安装上了
