### ISSUE TITLE
网络断开后恢复，下载的apk会无法安装

### ISSUE THREAD

**Issue by rangerTao** [AriaLyy/Aria#110]
网络原因导致下载任务暂停，连接网络后，任务继续。如果多次出现这种情况，下载 的apk大概率出现无法安装的情况

**Comment by AriaLyy** [comment]
这可能是多次断网后导致某几个byte字节出错了，这你可以在onTaskComplete中进行文件md5码验证，验证不通过，再对任务进行失败处理（重下货其它操作）

**Comment by rangerTao** [comment]
是的 已经按照这个方式修改了  但是后续还是要继续看到底是什么原因导致的下载失败，毕竟重新下 也还是会影响体验嘛

**Comment by AriaLyy** [comment]
```
Aria.get(this).getErrorLog()
```
使用这代码可以获取到下载过程中遇到的错误

**Comment by rangerTao** [comment]
有什么方法是可以调用了以后  直接重新下载一个任务的嘛？

**Comment by AriaLyy** [comment]
有个接口，重新下载任务
```
Aria.download(this).load(url).reStart();
```
