### ISSUE TITLE
有关组下载的问题

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#111]
你好，现在有这么一个需求，组下载文件A和文件B，A文件是下载地址不变，但是大小是有变化的。所以，需要多次更新下载A和B。目前组下载测试情况是，只要A和B的下载地址不变，组下载就不会重新下载了，是这样的吧？能不能也和单文件下载似的有个参数设置，可以重新加载一下？

**Comment by AriaLyy** [comment]
这个可以有，后续会增加一个任务组管理的功能
