### ISSUE TITLE
关于删除任务的问题

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#112]
你好，我再调用Aria.download(this).removeAllTask(true)删除所有任务时，单任务下载的task可以删除，但是任务组的下载记录仍有，使用Aria.download(this).getDownloadGroupTask(key)方法，仍可获取下载的记录。这样造成的问题是，我在本地清理缓存后，打开文件时，文件实际已经没有需要重新下载，但是仍会显示已下载完成的状态，麻烦看一下。

**Comment by AriaLyy** [comment]
3.3.0版本已经修复了这个问题
