### ISSUE TITLE
是否能满足该需求？

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#113]
你好，麻烦看一下这个需求目前版本是否可以实现。
1.有A、B、C、D。。。与A1，B1，C1，D1。。。两类文件，其中A、B、C、D这类文件可以通过一个批量更新的功能以任务组的形式进行预下载；在另外一个列表页中A与A1，B与B1又是分别以任务组的形式进行下载，在这里，希望有一个判断，若A在批量更新中下载完成，那么组下载中就只下载A1，对A不再进行下载，若A在批量更新中未下载或下载中，那么组下载包含A与A1两个文件，对两个文件进行下载。这里，如何判断A是否已经下载过？
2.任务组下载中是否有优先下载这一功能？

**Comment by AriaLyy** [comment]
1、任务组现在还不支持夸组的任务
2、优先级任务目前只支持单任务的下载

**Comment by lyxc** [comment]
好的，多谢
