### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by 1big** [AriaLyy/Aria#117]
ftp下载的时候  下载进度是存在了一个实体类里面保存的  但是当我暂停下载后，然后把本地的文件删除掉，在点击下载的时候  仍然显示的是继续下载  下载完成后的其实不是完整的文件。

**Comment by AriaLyy** [comment]
1、你使用的版本是哪个版本的库？
2、重新点击下载的时候，进度条是从0开始，还是从一次的进度继续执行？
3、你的显示文字是通过什么判断的？

**Comment by 1big** [comment]
就是最新的版本，手动删除后点击下载是从上一次的进度继续执行、从@Download.onTaskRunning()中获取到的   
我现在是在下载前判断本地文件是否存在，不存在就移除使用removeAllTask

**Comment by AriaLyy** [comment]
是FTP文件夹下载，还是ftp单任务下载？

**Comment by 1big** [comment]
单任务

**Comment by AriaLyy** [comment]
控制台有报什么错误吗？
你的FTP服务器最大下载速度是多少？有超过20M/S吗？
你的下载文件大小是多少？下载速度是多少

**Comment by 1big** [comment]
没错误啊   最大下载速度给的500kb/s   测试压缩包文件也就20来M   

就是下载的时候暂停后删除本地文件，再次下载的时候文件进度没有重置  所以即使下载成功，压缩包也打不开

**Comment by AriaLyy** [comment]
你用demo提供的工程测试下呢？
我这边尝试了4、5次都是正常的，暂停后删除任务，再重新下载进度都会从0开始，下载完成MD5码和和服务器匹配也是一样的...
