### ISSUE TITLE
获取任务进度的广播呢？你那些注解在kotlin‘上面没用’

### ISSUE THREAD

**Issue by lchben** [AriaLyy/Aria#118]
如题

**Comment by AriaLyy** [comment]
广播不适合任务组子任务的扩展，就这个api去掉的，kotlin正常来说是支持apt的，因为他兼容java，你检查下core 的版本 和compiler 的版本是否一致，如果一致的话，build工程时，打开as右下角的gradle console，看看报什么错误

**Comment by Cjz-Y** [comment]
同是写kotlin，之前有提交过一个issue，当时第一次使用没有注意到ProxyClassCounter没有生成，开始使用annotationProcessor，后面改成kapt后，注解可以使用了，但是当时晚上测试的时候，两个下载任务只能监听一个（当时以为是自己代码的bug，没有管），第二天重新测试的时候，发现ProxyClassCounter又开始生成不了了。。。。

**Comment by AriaLyy** [comment]
kotlin apt 设置 https://www.kotlincn.net/docs/reference/kapt.html
