### ISSUE TITLE
ProxyClassCounter这个类是没有了吗

### ISSUE THREAD

**Issue by Crystalyh** [AriaLyy/Aria#122]
gradle引入的资源，当Aria.load().register()的时候会去ProxyHelper.init()这里
Class clazz = Class.forName("com.arialyy.aria.ProxyClassCounter");
可是这个类文件我看源码里也没有啊，所以每次都报错
 java.lang.ClassNotFoundException: com.arialyy.aria.ProxyClassCounter；
请问是怎么回事呢？

**Comment by SumDev** [comment]
我也遇到了同样的问题，构建项目后没有生成代理类。

**Comment by AriaLyy** [comment]
这是annotationProcessor 生产代理文件失败了
1、检查下你的工程中有没有使用`apply plugin: 'android-apt'`，如果有的话将其转换为annotationProcessor
2、检查下annotationProcessor 和 compile 版本是否一致，不一致的话对导致生成代理文件失败
3、如果都不是的话，build文件时，点击as右下角的gradle console窗口，看看报什么错误

**Comment by Crystalyh** [comment]
apply plugin: 'com.neenbedankt.android-apt'这个是引入Dagger注解时添加的，“如果有的话将其转换为annotationProcessor”请问这句话什么意思呢？不太理解。还有gradle console是没有报错的，谢谢

**Comment by AriaLyy** [comment]
参考链接：http://www.cnblogs.com/whoislcj/p/6148410.html
