### ISSUE TITLE
关于回调onTaskCancel

### ISSUE THREAD

**Issue by yangshaopeng** [AriaLyy/Aria#123]
@Download.onTaskCancel注释的方法中，task对应的实体为什么是STATE_WAIT而不是STATE_CANCEL？？

**Comment by AriaLyy** [comment]
cancel对应的task中的实体是STATE_CANCEL。你是在什么地方打印的状态？

**Comment by yangshaopeng** [comment]
就是在@Download.onTaskCancel注释的方法中，调试你看一下，不知道图片能点开不、

![image](https://user-images.githubusercontent.com/20029905/30770700-93e4ec2a-a069-11e7-92c0-367b90874005.png)

**Comment by yangshaopeng** [comment]
这个有解决方法吗？

**Comment by AriaLyy** [comment]
用3.3.1
