### ISSUE TITLE
请问一下，是否支持从响应头的Content-Disposition中获取文件名？

### ISSUE THREAD

**Issue by SumDev** [AriaLyy/Aria#124]
看api似乎只能用setDownloadPath来设置下载的文件名称？

**Comment by AriaLyy** [comment]
目前还没有这个接口，但是你可以通过entity.getServerFileName()，获取到header的文件名

**Comment by SumDev** [comment]
但getServerFileName()这个方法好像并没有取到文件名，经常返回空字符串

**Comment by AriaLyy** [comment]
我文件获取的键值为：attachment;filename，你可以使用`Aria.download(this).load(url).setHeaderDispositionFileKey()`设置为你的key，或者使用实体的`getDisposition()获取`获取head`Content-Disposition`中的数据

**Comment by yanshao369** [comment]
String str = Aria.download(this).load(nowDownloadUrl).getContentDisposition();
String fileName = str.substring(str.lastIndexOf("fileName=") + 9).trim();
 Aria.download(this) .load(nowDownloadUrl)     //读取下载地址
                    .setDownloadPath(DOWNLOAD_PATH + fileName) //设置文件保存的完整路径
                    .start();
我在下载前获取文件名，但是网络不好的时候获取的名字是空的，后面的下载可以正常下载。。。

**Comment by yanshao369** [comment]
这样就导致我活娶不到文件名字

**Comment by AriaLyy** [comment]
3.4 版本已经支持从Content-Disposition设置文件名了
http://aria.laoyuyu.me/aria_doc/api/task_handle.html#%E4%BD%BF%E7%94%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8F%90%E4%BE%9B%E7%9A%84%E6%96%87%E4%BB%B6%E5%90%8D
