### ISSUE TITLE
onTaskComplete

### ISSUE THREAD

**Issue by zhuzhao404** [AriaLyy/Aria#125]
请问这个注解中怎么知道上传时成功还是失败

**Comment by AriaLyy** [comment]
失败有另外的注解，请看[wiki](https://github.com/AriaLyy/Aria/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8#httpftp%E5%8D%95%E4%BB%BB%E5%8A%A1%E4%B8%8A%E4%BC%A0%E6%B3%A8%E8%A7%A3)
