### ISSUE TITLE
感觉问题好多啊。

### ISSUE THREAD

**Issue by zhuzhao404** [AriaLyy/Aria#127]
1.assets设置上传失败重试次数为2，log还是会打印上传十次，代码也同时设置，同样是十次；
2.FTP上传路径包括中文，中文字段不使用utf-8编码直接拼接的话，使用setUploadUrl会报550错误，我看源码说明好像550是路径未找到或者未创建成功的意思；若中文字段使用utf-8编码文件夹会创建成功，但是图片无法上传，此时如果取消utf-8编码，图片会成功上传；
3.成功上传的图片只会上传一半或者一部分，另一部分是灰色的。

**Comment by AriaLyy** [comment]
1、assets设置的是任务重试次数，而log打印的可能是线程重试的次数（为5），上传任务都为单线程，log打印次数为：任务重试次数 * 线程重试次数
2、检查下FTP服务是否给了该用户Write、append权限，检查FTP服务器是否存在你的那个文件夹（我这边添加了这两个权限，url是可以有中文的）
![gg](http://upload-images.jianshu.io/upload_images/1824042-2ee7de9f3ef3d633.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
3、图片我试了10来次，并没有出现你的那个问题，出问题时，控制台打印的是什么？

**Comment by zhuzhao404** [comment]
1.log重试这个小事，可以先不管；
2.FTP是加了权限的，因为之前有那个中文路径的时候还是可以上传的，但是图是不完整，如果不带中文，就能直接成功创建路径及上传图片
①路径不存在含中文，我首次创建并上传
![v4 ap0le1 j fb3mw0wg](https://user-images.githubusercontent.com/18410594/30838556-be711180-a29e-11e7-9420-1119ca7a7892.png)
![2l f tm02to06s 3 i 52yv](https://user-images.githubusercontent.com/18410594/30838503-700c4e9c-a29e-11e7-8ef2-9adea7e9e76c.png)
这张图里面最后一个目录是中文（安全文明），需要向里面添加图片，但提示550；
登录ftp会发现到中文前的路径是创建成功了，但是到中文就无法继续创建；
![722y3y8duw 7 g h93qrpl](https://user-images.githubusercontent.com/18410594/30838534-99d4d6c2-a29e-11e7-9b7d-c023c228f1a6.png)
②不拼接目录直接在根目录上传，是可以上传成功的
![v m 1j q vu3mbr4a7tpq](https://user-images.githubusercontent.com/18410594/30838566-cf5f615e-a29e-11e7-8112-9c2c3263a3ce.png)
![v6mz22g9y1xh ybsu1 4](https://user-images.githubusercontent.com/18410594/30838604-14ce01f0-a29f-11e7-80fb-5eba4140dc43.png)
但是图片是不完整的
![dyg b2 uy d mkwl1web](https://user-images.githubusercontent.com/18410594/30838617-2b1a8802-a29f-11e7-8b26-a146f3227264.png)
麻烦帮忙看下，搞了比较久了！

**Comment by AriaLyy** [comment]
1、上传不成功，这是客户端远程创建中文名文件夹时S/C间字符串编码不一致导致的问题，现在已经处理（目前你可以先在服务器上创建中文文件夹，或使用英文命名文件夹）
2、图片估计是上传不完整导致的，我这边尝试了20来次，图片2M，一直都没出问题（我用的是FileZilla Server ）

**Comment by zhuzhao404** [comment]
好，文件夹我暂时换个方式命名，老哥您这边尽快更新下，到时候我也更新下版本；
图片的问题很纳闷，我的图片都是压缩过带水印的，我后来测试原图(无水印 无压缩的)也是底部差一些没上传完，很是头疼。。。
我的是在fragment里面上传的，注册的时候还会提示ProxyClassCounter未找到的错误，然后注解方法也没用。。。成功的时候在complete打印也没反应。。。

**Comment by AriaLyy** [comment]
没有ProxyClassCounter表示生成代理文件失败，一般来说，如果代理文件生成失败，gradle constance会有错误日志或警告打印的

**Comment by zhuzhao404** [comment]
这。。。实在没辙了，也用butterknife了  同样是annotationProcessor

**Comment by AriaLyy** [comment]
你新创建一个工程试一下呢，随便创建一个activity，添加一个注解看看

**Comment by zhuzhao404** [comment]
新工程里面是有的，不知道是不是我项目中使用java8和lambda的原因

**Comment by AriaLyy** [comment]
图片的问题，这个你用这个版本试一试，看看还会不会出现上传不完整的情况
```
compile 'com.arialyy.aria:aria-core:3.3.2'
  annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.2'
```

**Comment by zhuzhao404** [comment]
这个版本创建中文路径可以了没问题了，然后新增的照片或者之前没有被上传的图片是完整的；
有一张图片是我上个版本上传的然后不完整，在我换了新版本之后，重新上传覆盖还是不完整的；
可能是使用上个有问题的版本操作过的图片再操作还是会使用之前复制的吧，然后就造成还是会不完整的。。。。

**Comment by AriaLyy** [comment]
覆盖上传需要服务器给客户端del权限，否则是覆盖不成功的，第三句话，估计是删除不了文件的问题

**Comment by zhuzhao404** [comment]
太感谢了，我现在没什么问题了 已经开始写了 你看下我刚才说的文件删除的事情，然后你这边是否需要后期再完善下

**Comment by AriaLyy** [comment]
那个issues?

**Comment by zhuzhao404** [comment]
不是，我这边覆盖是有权限的，我意思是 之前不完整的换了新版本后重新上传还是不完整的。。。。。

**Comment by AriaLyy** [comment]
我后面看下吧

**Comment by zhuzhao404** [comment]
好 谢谢了
