### ISSUE TITLE
上传问题

### ISSUE THREAD

**Issue by zhuzhao404** [AriaLyy/Aria#129]
我这边是多张上传的，所以我加在了循环里面
![fpnj9gmq aeaeb 4 z7 i](https://user-images.githubusercontent.com/18410594/30899217-934550b8-a391-11e7-855d-12dc80702717.png)
我本来是想在upload里面穿list的下标 然后在complete里面通过getTargetName来取得列表中对应的下标，来进行remove，并且我要把上传好的item的对象存起来，但是这样会提示不支持类型，我看源码支持的都是系统方面的，所以有没有好的方法来完成我这样的需求

**Comment by AriaLyy** [comment]
不要这样做，使用[扩展字段处理](https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E7%94%A8api#%E4%BF%9D%E5%AD%98%E6%89%A9%E5%B1%95%E5%AD%97%E6%AE%B5)
