### ISSUE TITLE
当有无效的url 404时候，打开列表会卡顿一会 

### ISSUE THREAD

**Issue by AmbitChen** [AriaLyy/Aria#13]
希望可以优化一下~~

**Comment by AriaLyy** [comment]
是打开列表Activity的时候卡顿吗？如果没有url404会不会也出现卡顿现象？

**Comment by AmbitChen** [comment]
是，目前是404才会卡顿

**Comment by AriaLyy** [comment]
麻烦用 compile 'com.arialyy.aria:Aria:2.4.3' 试一下，看还会不会出现卡顿，我已经对404链接进行了取消任务的处理。

**Comment by AmbitChen** [comment]
OK了

**Comment by AriaLyy** [comment]
感谢反馈^_^
