### ISSUE TITLE
同时下载几个，其中一个完成了，别的还在下载，把完成的调用cancel，然后进度就错乱了

### ISSUE THREAD

**Issue by gemgao** [AriaLyy/Aria#130]
正在下载http://dby-resource-android.duobeiyun.com/jz05fa8faf068145fcb25c93c8091297ad.zip---0 

正在下载0
正在下载http://dby-resource-android.duobeiyun.com/jz22a8508b4265466b9fb4bb29082eaa2d.zip---1 

正在下载1
正在下载http://dby-resource-android.duobeiyun.com/jz58cee9524bad4412945ac73c1ed91162.zip---1 

正在下载1
正在下载http://dby-resource-android.duobeiyun.com/jz684e1b4c2f6b4576979e60fd95edebad.zip---0 

正在下载0
正在下载http://dby-resource-android.duobeiyun.com/jz08c4a6e20a6c431b813836ceb0c9fdd2.zip---0 

正在下载0
正在下载http://dby-resource-android.duobeiyun.com/jz27a49ee47cee478194c2b8be8624f356.zip---0 
正在下载0
正在下载http://dby-resource-android.duobeiyun.com/jz05fa8faf068145fcb25c93c8091297ad.zip---0 

正在下载0
正在下载http://dby-resource-android.duobeiyun.com/jz22a8508b4265466b9fb4bb29082eaa2d.zip---1 

正在下载1
正在下载http://dby-resource-android.duobeiyun.com/jz58cee9524bad4412945ac73c1ed91162.zip---1

**Comment by AriaLyy** [comment]
3.3.3已经修复了这个问题
```
compile 'com.arialyy.aria:aria-core:3.3.3'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.3'
```

**Comment by gemgao** [comment]
ok
