### ISSUE TITLE
文件下载问题，如果下载路径中文件名存在空格始终会提示失败。

### ISSUE THREAD

**Issue by hw2015** [AriaLyy/Aria#131]
文件下载，如果下载路径中文件名存在空格始终会提示失败。例如：http://***/git hub.jpg

**Comment by AriaLyy** [comment]
提示的错误码是什么？能否提供一下带有空格的下载地址？

**Comment by AriaLyy** [comment]
3.3.6已经修复了这个问题

**Comment by hw2015** [comment]
非常感谢，抱歉我没能提供下载地址和错误代码。
