### ISSUE TITLE
获取下载的文件大小经常获取不到

### ISSUE THREAD

**Issue by lizi0588** [AriaLyy/Aria#133]
DownloadTarget target = Aria.download(this).load(DOWNLOAD_URL);
        long fileSize = target.getFileSize();

**Comment by lizi0588** [comment]
我在下载文件前要获取下文件大小显示出来 ，但 经常获取1.0b，请问我改怎么做

**Comment by AriaLyy** [comment]
这个方法是下载过的才会获取，你这个情况可以叫服务器在给你下载地址的时候同时传递给你文件大小
