### ISSUE TITLE
你好，下载的时候无法监听。

### ISSUE THREAD

**Issue by Cjz-Y** [AriaLyy/Aria#136]
在log中出现这样的错误。
java.lang.ClassNotFoundException: com.arialyy.aria.ProxyClassCounter

代码只是很简单的代码

class MainActivity : AppCompatActivity() {

    val DOWNLOAD_URL = "http://speed.myzone.cn/WindowsXP_SP2.exe"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        Aria.download( this ).register()

        Aria.download( this )
                .load( DOWNLOAD_URL )
                .setDownloadPath( Environment.getExternalStorageDirectory().getPath() + "/test.apk" )
                .start()

    }

    @Download.onTaskRunning( "http://speed.myzone.cn/WindowsXP_SP2.exe" ) fun taskRun( task: DownloadTask ){
        Logger.i( "listener to task , and the percent is %d", task.percent )
    }
}

**Comment by AriaLyy** [comment]
[请检查下Apt配置](https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%B3%A8%E8%A7%A3%E6%97%A0%E6%95%88proxyclasscounter%E6%96%87%E4%BB%B6%E6%9C%AA%E7%94%9F%E6%88%90)

**Comment by Cjz-Y** [comment]
谢谢   开始没注意到
