### ISSUE TITLE
table UploadEntity already exists (code 1)

### ISSUE THREAD

**Issue by xyzmst** [AriaLyy/Aria#137]
调用 DbUtil.init 方法 经常会报 table UploadEntity already exists (code 1)

**Comment by AriaLyy** [comment]
Aria是不需要手动调这个方法的~~~

**Comment by xyzmst** [comment]
不可以，需要操作 数据实体，
比如 
用来判断下载的本地文件是否下载完成 通过数据库里记录的文件长度，
本地文件删除后，要再次下载时，需要清空数据才能下载，
没有对 整体操作的 开启，暂停，关闭的方法

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E7%94%A8api#%E8%8E%B7%E5%8F%96%E4%BB%BB%E5%8A%A1%E5%88%97%E8%A1%A8
