### ISSUE TITLE
使用DownloadGroup下载，单个任务下载完成有回调吗

### ISSUE THREAD

**Issue by lizi0588** [AriaLyy/Aria#141]

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8#%E4%BB%BB%E5%8A%A1%E7%BB%84%E5%AD%90%E4%BB%BB%E5%8A%A1%E6%B3%A8%E8%A7%A3

**Comment by lizi0588** [comment]
好的，谢谢
