### ISSUE TITLE
使用DownloadGroup方法批量下载文件的问题

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#142]
使用DownloadGroup批量下载N个文件，其中有某个文件的url不对，404找不到，我如何能够监听到，然后进行下一步的提示操作？

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8#%E4%BB%BB%E5%8A%A1%E7%BB%84%E5%AD%90%E4%BB%BB%E5%8A%A1%E6%B3%A8%E8%A7%A3
