### ISSUE TITLE
能不能提供注册listener的方式监听下载

### ISSUE THREAD

**Issue by vzhilong** [AriaLyy/Aria#143]
主要是我们的业务是单Activity + 多View，另外也不希望将下载监听这样的业务逻辑大量耦合到Activity中去。

**Comment by vzhilong** [comment]
我看了下实现AriaManager注册需要Context这个没问题，但是receiver注册的类是没有限制的。

**Comment by AriaLyy** [comment]
你是希望在自定义View中使用Aria?

**Comment by vzhilong** [comment]
其实更加一般的做法是下载进度回调到Controller类，Controller触发View更新，所以注册的带有注解的类很有可能不是Context类。

**Comment by AriaLyy** [comment]
如果是这样的话，直接传递Context吧，只要Context 是Activity、Service、Application都可以被注册

**Comment by vzhilong** [comment]
注册可以是Context，但是注解回调就不适合到Context上去了。

**Comment by AriaLyy** [comment]
你的需求是：想在任意的C层获取回调？

**Comment by vzhilong** [comment]
对的。或者有个注册C层回调的接口。

**Comment by vzhilong** [comment]
如果Context和下载业务耦合，那么业务和视图的偶尔程度就太高了。

**Comment by AriaLyy** [comment]
现在暂时没有这个接口，你可以在Service接收回调数据，然后传递将实体传递到C层，回调中的实体都是实现Parcelable接口的，你可以直接放到Intent中

**Comment by vzhilong** [comment]
嗯，这也是个方法。

**Comment by vzhilong** [comment]
对了，我看了下代码，感觉FTP的插件化不够彻底，上传那里还是依赖了FTP上传？其实大部分情况下只需要HTTP的上传和下载，FTP可能场景非常少。

**Comment by AriaLyy** [comment]
对的，现在的这个架构不太适合插件化，等有时间会慢慢调整为插件化的架构
