### ISSUE TITLE
拓展字段的问题

### ISSUE THREAD

**Issue by vzhilong** [AriaLyy/Aria#144]
拓展字段目前是通过mDownloadReceiver.load(url).getExtendField()这种方式获取的，和mDownloadReceiver.getDownloadTask(url)、mDownloadReceiver.getDownloadEntity(url)完全不一样，mDownloadReceiver.load(url).getExtendField()其实是会重新创建一个DownloadTarget对象，完全不符合getExtendField的语义，理论上拓展字段直接从DownloadEntity中get更合理。

**Comment by AriaLyy** [comment]
如果是从DownloadEntity中获取，在之前还需要获取实体的操作，有些情况下是不需要先获取实体的。
在DownloadEntity中有一个getStr()的方法，这个是获取扩展字段的
