### ISSUE TITLE
getCurrentProgress()

### ISSUE THREAD

**Issue by junchenChow** [AriaLyy/Aria#145]
long progress = downloadEntity.getCurrentProgress();
int current = size == 0 ? 0 : (int) (progress * 100 / size);

问题比较小 不知道是不是自己的锅。
在多任务同时下载的情况下 偶尔出现了 current 大于100以上 居然还能到160多。
貌似看到的log是这个socket time out了 然后重试之后出现的问题。

**Comment by AriaLyy** [comment]
这有可能是单条线程挂了，重试出的问题，我后续加个判断，你现在可以先将超时时间设置长一点看看

**Comment by AriaLyy** [comment]
3.3.6已经修复了这个问题
