### ISSUE TITLE
Ftp下载不了

### ISSUE THREAD

**Issue by jkfuny** [AriaLyy/Aria#146]
网络上开放的ftp地址下载不了。如：
ftp://z:z@dygod18.com:21211/[电影天堂www.dy2018.com]猩球崛起3：终极之战BD国英双语中英双字.mkv

**Comment by AriaLyy** [comment]
3.3.6现在已经支持公网FTP文件的下载了，公网上的资源如果有中文，建议使用charSet("gbk")；详细demo见https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/download/FtpDownloadActivity.java
