### ISSUE TITLE
多个单任务同时下载，其执行队列中的等待任务状态如何接收并更新UI层?

### ISSUE THREAD

**Issue by pedbeq** [AriaLyy/Aria#147]
多个单任务同时下载，其执行队列中的等待任务状态如何接收并更新UI层？
暂停再重新下载任务，其下载任务已满能否加入到执行队列中？

**Comment by AriaLyy** [comment]
请参考工程多任务下载的demo，https://github.com/AriaLyy/Aria/tree/master/app/src/main/java/com/arialyy/simple/download/multi_download

**Comment by pedbeq** [comment]
您这个例子我仔细研究过，假如说有三个任务的下载队列，设置只能下载两个任务，把其中一个暂停掉，会执行第三个队列，但是我把那个暂停的任务恢复下载，会暂停一个正在下载的任务，而不会排队。

**Comment by pedbeq** [comment]
还有一个问题，不知道怎么回事，我把所有的任务都暂停掉了，竟然还有线程去更新进度，但是都是一样的数据，一开始我以为我写的有问题，但是我在你的例子和代码，也会出现这种情况！

**Comment by AriaLyy** [comment]
1、手动暂停的是不会自动启动的
2、线程更新的问题，控制台有报什么警告或异常吗？

**Comment by AriaLyy** [comment]
3.3.6已经修复了这个问题
