### ISSUE TITLE
下载一个任务，退出APP，重启通过URL加载返回为NULL

### ISSUE THREAD

**Issue by vzhilong** [AriaLyy/Aria#149]
mDownloadReceiver.load(url).setDownloadPath(AppContext.sDownloadDir + "/" + fileName).start(); 下载后，杀手APP，启动，同一个URL，mDownloadReceiver.getDownloadTask(url);返回为NULL。不是有持久化的吗，很奇怪。

**Comment by vzhilong** [comment]
我看了下demo的代码，无论一个URL是否被下载过，查询这个URL对应的任务状态都要用mDownloadReceiver.load(url)？

**Comment by vzhilong** [comment]
mDownloadReceiver.getDownloadTask和mDownloadReceiver.getDownloadEntity又有什么用？

**Comment by vzhilong** [comment]
比如我就想知道这个URL的历史下载状态，我应该用什么？mDownloadReceiver.load(url)会去数据库创建一条记录，这样肯定不行。

**Comment by AriaLyy** [comment]
getDownloadTask是任务实体，对应的是任务；
getDownloadEntity才是和文件相关的，你要获取状态历史，使用这个。
mDownloadReceiver.load(url)，只有数据库查不到才会创建记录。
