### ISSUE TITLE
好像不支持ftp多任务下载。。。。。

### ISSUE THREAD

**Issue by 1big** [AriaLyy/Aria#150]
暂时还不支持ftp多任务下载    是么？

**Comment by AriaLyy** [comment]
支持，但是目前不支持公网的ftp任务

**Comment by 1big** [comment]
是循环调用
Aria.download(this)
            .loadFtp(URL, true)
            .login("lao", "123456")
            .setDownloadPath("/mnt/sdcard/")
            .start();  ？

**Comment by 1big** [comment]
还是指的下载文件夹

**Comment by AriaLyy** [comment]
下载文件夹或多个单文件都支持多任务的的..

**Comment by 1big** [comment]
嗯 是支持的
