### ISSUE TITLE
在设置权限检查中确认已经有sd读写权限，可下载时依然报权限的错误

### ISSUE THREAD

**Issue by YangMian** [AriaLyy/Aria#152]
E/AbsThreadTask: 下载失败【http://file.market.xiaomi.com/download/AppChannel/0625a4f1969c78d44f8940133302051e892401285/%E5%B0%8F%E7%B1%B3%E6%9E%AA%E6%88%98.apk】
                                                              ExceptionDetailed:
 ====================Exception Info====================
                                 java.io.FileNotFoundException: /storage/emulated/01509355146174.apk: open failed: 
                                EACCES (Permission denied)

**Comment by AriaLyy** [comment]
能都提供更加详细的错误信息？

**Comment by YangMian** [comment]
以下是控制台打印的全部错误信息， 这段错误应该是没有存储权限，但我检查应用的权限列表，我确认是有存储权限的。感谢作者的及时回复

10-30 17:36:35.038 18747-19577/com.yijale.game E/AbsThreadTask: 下载失败【https://m.yijale.com/LightGoDemo1.0.0.apk】
                                                                ExceptionDetailed:
 ====================Exception Info====================
java.io.FileNotFoundException: /storage/emulated/01509355146174.apk: open failed: EACCES (Permission denied)
 libcore.io.IoBridge.open(IoBridge.java:455)
java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
 com.arialyy.aria.util.BufferedRandomAccessFile.<init>(BufferedRandomAccessFile.java:123)
                                                                com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:76)
                                                               com.arialyy.aria.core.common.AbsThreadTask$2.run(AbsThreadTask.java:228)
                                                                java.util.TimerThread.mainLoop(Timer.java:555)
                                                                java.util.TimerThread.run(Timer.java:505)
                                                                【Caused by】: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                libcore.io.Posix.open(Native Method)
                                                                libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
                                                                libcore.io.IoBridge.open(IoBridge.java:441)
                                                                java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
                                                                com.arialyy.aria.util.BufferedRandomAccessFile.<init>(BufferedRandomAccessFile.java:123)
                                                                com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:76)
                                                                com.arialyy.aria.core.common.AbsThreadTask$2.run(AbsThreadTask.java:228)
                                                                java.util.TimerThread.mainLoop(Timer.java:555)
                                                                java.util.TimerThread.run(Timer.java:505)

**Comment by AriaLyy** [comment]
除了在代码中请求权限外，AndroidManifest中是否添加了相应的权限配置？

**Comment by YangMian** [comment]
AndroidManifest 中有添加这些权限， 
  <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

# 我在代码这里也加入判断，如果有写入权限，就进入下载，has_permission为turn， 并报了上述存储权限的错误

  PackageManager pm = getPackageManager();

                boolean has_permission = (PackageManager.PERMISSION_GRANTED == pm.checkPermission("android.permission.WRITE_EXTERNAL_STORAGE", "com.yijale.game"));

                if (has_permission){
                    MDToast.makeText(mContext,"有权限", Toast.LENGTH_SHORT).show();

                    Aria.download(this)
                            .load("http://file.market.xiaomi.com/download/AppChannel/0625a4f1969c78d44f8940133302051e892401285/%E5%B0%8F%E7%B1%B3%E6%9E%AA%E6%88%98.apk")
                            .setDownloadPath(Environment.getExternalStorageDirectory().getPath() +System.currentTimeMillis()+".apk")
                            .start();

                }else {
                    MDToast.makeText(mContext,"没有权限", Toast.LENGTH_SHORT).show();
                }

**Comment by AriaLyy** [comment]
建议google 
```
android.system.ErrnoException: open failed: EACCES (Permission denied)
```
真正的Caused错误是这个

估计还是申请权限出的问题[谷歌官方权限申请方法](https://developer.android.com/training/permissions/requesting.html?hl=zh-cn)

**Comment by YangMian** [comment]
感谢作者的耐心回复，这个问题的原因是下载保存的文件路径不正确造成，与权限无关。控制台报错信息有误。也希望后面的同志遇到相同问题的时候检查文件保存的路径。
