### ISSUE TITLE
问什么不添加url注解触发不了

### ISSUE THREAD

**Issue by A0058471** [AriaLyy/Aria#153]
@Download.onTaskComplete
    void taskComplete(DownloadTask task) {
    }
触发类似上诉这些除了register()外还要做其他什么吗

**Comment by AriaLyy** [comment]
不让蛮王url是什么意思？
只要注册就行了

**Comment by A0058471** [comment]
我注册后使用@Download.onTaskComplete 
void taskComplete(DownloadTask task) {
Log.i("aa","完成")
}这样写不打印
private final String url="mmm.apk";
得@Download.onTaskComplete(url)
 void taskComplete(DownloadTask task) {
Log.i("aa","完成")
}才能打印“完成”,不指定下载链接的话所有注解方法都不触发

**Comment by AriaLyy** [comment]
url加了就表示只会回调这个url的信息，你先clean 一下，然后再试试，我demo测试用不用都可以的

**Comment by A0058471** [comment]
哦，我回去试试，谢谢
