### ISSUE TITLE
你好，请问为什么我的下载进度回调不到

### ISSUE THREAD

**Issue by mrsongindezhou** [AriaLyy/Aria#154]
我项目使用的okhttp3并加了个拦截器，我下载视频的时候，为什么我的进度没有回调到呢

**Comment by AriaLyy** [comment]
请看下这个wiki

https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%B3%A8%E8%A7%A3%E6%97%A0%E6%95%88proxyclasscounter%E6%96%87%E4%BB%B6%E6%9C%AA%E7%94%9F%E6%88%90

**Comment by mrsongindezhou** [comment]
还是无法监听到下载进度

注: Version 4.1.1 of Realm is now available: http://static.realm.io/downloads/java/latest
注: Processing class GoldManagerBean
注: Processing class GoldManagerItemBean
注: Processing class ReadStateBean
注: Processing class RealmLikeBean
注: Processing class VideoIndexBean
注: Creating DefaultRealmModule
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by AriaLyy** [comment]
检查下代码：
1、`Aria.download(this).register();`有没有被调用
2、Activity的onDestroy()中有没有调用` Aria.download(this).unRegister();`，有的话请把这句代码移除
```
@Override protected void onDestroy() {
    super.onDestroy();
    Aria.download(this).unRegister();
  }
```
