### ISSUE TITLE
您好！我把任务放在service中， 当用户在任务栏中强行退出应用， 所有注解都不会回调了吗？

### ISSUE THREAD

**Issue by YangMian** [AriaLyy/Aria#155]
此时service 的 onDestroy 并没有被调用，说明service还没有被kill, 但此时文件下载已经停止了，但几个状态的注解都没有回调。

**Comment by AriaLyy** [comment]
你启动下载`Aria.download(this).load(url).start()`的地方是不是在Service中？如果你是在Activity中启动，当把app kill 了的话，下载线程同时也被kill了。因为，你在哪个进程中启动线程，线程就依赖于哪个进程。
如果你希望app  kill后还能下载，建议你在Service启动Aria下载
