### ISSUE TITLE
getcontentlength总返回值为-1

### ISSUE THREAD

**Issue by Hlancan** [AriaLyy/Aria#156]
如题，由于甲方服务端没有设置contentLength导致了getcontentlength总返回值为-1无法下载，网上说加上connection.setRequestProperty("Accept-Encoding", "identity"); 就可以了，但是我加上后返回的还是-1，大神看能不能解决啊，急急急！！！等待救援的苦逼乙方。。。

**Comment by AriaLyy** [comment]
参考这个issue，这应该是header头的问题，把Accept-Encoding设置正确应该就可以了   https://github.com/AriaLyy/Aria/issues/36#issuecomment-307992658

**Comment by Hlancan** [comment]
@AriaLyy 加了也还是不行，我请求下载时响应头中有这么一个字段Transfer-Encoding: chunked，有这个字段就无法获取contentLength了，解释如下：
http返回头中content-length与Transfer-Encoding: chunked的问题释疑http://www.cnblogs.com/foxhengxing/archive/2011/12/02/2272387.html

**Comment by AriaLyy** [comment]
能否提供下载地址？

**Comment by Hlancan** [comment]
@AriaLyy 谢谢了，不过不好意思，不能提供下载地址。主要还是别人后端的问题，既不返回长度也不支持分段下载，所以就只能使用单线程并每次都重新开始下载了
