### ISSUE TITLE
下载排队的问题

### ISSUE THREAD

**Issue by 1big** [AriaLyy/Aria#157]
假如说有三个任务的下载队列，设置只能下载两个任务，把其中一个暂停掉，会执行第三个队列，但是我把那个暂停的任务恢复下载，会暂停一个正在下载的任务，而不会排队。

**Comment by AriaLyy** [comment]
你有3个任务A\B\C，最大下载数是2，这时A\B任务正在下载，C等待下载；
这时你暂停B任务，C任务将会自动下载；
然后，你恢复暂停的B任务，而这个时候最大任务数还是2，根据队列的原则，Aria会自动暂停执行队列队首的任务A，以便让执行队列空出位置执行B；
在Aria中，手动暂停的任务都不会自动下载，因为我根本就不知道暂定的任务是不是用户不希望下载的（这部分可参考迅雷的暂停逻辑）

**Comment by 1big** [comment]
碰到一个问题  就是ftp下载的时候调用 Aria.download(this).stopAllTask();之后再次调用  Aria.download(this).resumeAllTask()时   
任务无法继续下载   控制台报  AbsThreadTask: 无法连接到ftp服务器，错误码为：501

**Comment by AriaLyy** [comment]
能否提供下载地址？

**Comment by 1big** [comment]
提供不了   现在是我本地用FileZilla搭建的ftp服务器

**Comment by AriaLyy** [comment]
你将下载速度限制一下吧，限制到2M/S之内，这是下载速度太快导致的。

**Comment by 1big** [comment]
还是出问题...  我用你那个源码测试也是一样的   报连不到ftp服务器

**Comment by 1big** [comment]
不知道是不是和这个问题一样
就是ftp下载  调用了stop方法后  要是想再次启动  调用
Aria.download(this) .load(entity).start();  也会出现这个问题  无法连接服务器

**Comment by AriaLyy** [comment]
你用3.3.6_dev_2测试一下看看会不会出问题

**Comment by 1big** [comment]
试了下  调用stop方法后，再次启动是正常的     ，但是stopAllTask后 再次调用resumeAllTask会出现：
  
`AbsThreadTask: 获取流失败
                                                                             ExceptionDetailed:
                                                                             ====================Exception Info====================
                                                                             java.lang.NullPointerException: Attempt to read from field 'java.net.InetAddress com.arialyy.aria.core.FtpUrlEntity.validAddr' on a null object reference
                                                                             com.arialyy.aria.core.common.AbsFtpThreadTask.createClient(AbsFtpThreadTask.java:55)
                                                                             com.arialyy.aria.core.download.downloader.FtpThreadTask.run(FtpThreadTask.java:60)
                                                                             com.arialyy.aria.core.common.AbsThreadTask$2.run(AbsThreadTask.java:230)
                                                                             java.util.Timer$TimerImpl.run(Timer.java:284)`

**Comment by 1big** [comment]
还出现一个现象    就是首先我们设置了允许的下载数为1
A/B/C/D   4个任务依次点击下载，A下载，B/C/D等待中，然后再次点击A暂停下载，B继续下载，C/D等待中。如果这个时候在来点击A下载，B会暂停，而C/D也会同时下载。。。。。这个是正常现象，还是其他。。。。迷茫 我感觉我成为了问题少年

**Comment by AriaLyy** [comment]
这是一个bug来的，现在已经修复了

**Comment by AriaLyy** [comment]
3.3.6已经修复了这个问题，如果需要用DownloadEntity进行FTP下载操作，同样需要登录处理，详细demo见https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/download/multi_download/DownloadAdapter.java
