### ISSUE TITLE
组下载单个任务成功回调问题

### ISSUE THREAD

**Issue by jeec** [AriaLyy/Aria#158]
1）用的最新版本3.3.3
2）9个文件在一个任务组里，文件大小都在3--5M之间。
3）偶现的问题是当其中某一个子任务下载完成时
    @DownloadGroup.onSubTaskComplete
    void onSubTaskComplete(DownloadGroupTask groupTask, DownloadEntity subEntity)
方法获取到的String key = subEntity.getKey();是之前已下载完成的某一子任务的key，而不是当前下载完成的key。请看下，谢谢。

**Comment by AriaLyy** [comment]
用最新版本3.3.6试试看，还会不会出现这个情况
