### ISSUE TITLE
支持断点下载时，有可能会有线程重启失败的时候，这时判断下载回调的还是在继续回调

### ISSUE THREAD

**Issue by panfengyu** [AriaLyy/Aria#160]
if (mFailNum < RETRY_NUM && needRetry && NetUtils.isConnected(AriaManager.APP)) {
      if (mFailTimer != null) {
        mFailTimer.purge();
        mFailTimer.cancel();
      }
      mFailTimer = new Timer(true);
      mFailTimer.schedule(new TimerTask() {
        @Override public void run() {
          mFailNum++;
          Log.w(TAG,
              "任务【" + mConfig.TEMP_FILE.getName() + "】thread__" + mConfig.THREAD_ID + "__正在重试");
          final long retryLocation = mChildCurrentLocation;
          mConfig.START_LOCATION = retryLocation;
          AbsThreadTask.this.run();
        }
      }, RETRY_INTERVAL);
    } else {
      STATE.FAIL_NUM++;
      if (STATE.isFail()) {
        STATE.isRunning = false;
        STATE.isStop = true;
        Log.e(TAG, "任务【" + mConfig.TEMP_FILE.getName() + "】执行失败");
        mListener.onFail(true);
      }
    }

如果重启线程·，此时恰好没网，但是另外的线程没有完成，在等待重启的时候·会有bug

**Comment by AriaLyy** [comment]
这个问题3.3.6已经处理了，用3.3.6试试

**Comment by panfengyu** [comment]
但是你这样改，只有一个线程下的的话会不会下载速度太慢了

**Comment by AriaLyy** [comment]
什么意思？线程数你可以自己改啊...

**Comment by panfengyu** [comment]
你这多线程下载的话，问题根本没解决，还是之前的问题，比如我开三个线程下载一个文件，两个成功了，但是有一个线程失败了，会出现进度获取定时器关闭不了的情况，还是多线程的问题，出现问题的关键就是判断当前线程是否重启。

**Comment by AriaLyy** [comment]
了解了，我修改的是另外线程重启的一个问题。

**Comment by panfengyu** [comment]
这样修改STATE.isFail()可以啊

**Comment by panfengyu** [comment]
3.3.7怎么没传上来

**Comment by AriaLyy** [comment]
先用`3.3.7_dev_3`测试看看，还有一些东西需要改动下
