### ISSUE TITLE
老铁，初始化异常，还有一个除0异常，当获取的文件大小为0时

### ISSUE THREAD

**Issue by fanchen001** [AriaLyy/Aria#161]
第一个异常
java.lang.IllegalArgumentException: Expected receiver of type com.arialyy.aria.core.Configuration$BaseConfig, but got com.arialyy.aria.core.Configuration$UploadConfig
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:5816)
3 ......
4 Caused by:
5 java.lang.IllegalArgumentException:Expected receiver of type com.arialyy.aria.core.Configuration$BaseConfig, but got com.arialyy.aria.core.Configuration$UploadConfig
6 java.lang.reflect.Field.setInt(Native Method)
7 com.arialyy.aria.core.Configuration$BaseConfig.loadConfig(Unknown Source:158)
8 com.arialyy.aria.core.Configuration$UploadConfig.<init>(Unknown Source:3)
9 com.arialyy.aria.core.Configuration$UploadConfig.getInstance(Unknown Source:9)
10 com.arialyy.aria.core.AriaManager.initConfig(Unknown Source:83)
11 com.arialyy.aria.core.AriaManager.<init>(Unknown Source:33)
12 com.arialyy.aria.core.AriaManager.getInstance(Unknown Source:9)
13 com.arialyy.aria.core.Aria.get(Unknown Source:16)
14 com.arialyy.aria.core.Aria.download(Unknown Source:0)
15 com.fanchen.imovie.IMovieAppliction.getDownloadReceiver(Unknown Source:11)

修改
int m = 1;
try{
	m = field.getModifiers();
} catch (Exception e) {
	e.printStackTrace();
}
if (field.getName().equals("oldMaxTaskNum") || Modifier.isFinal(m) || Modifier.isStatic(m)) {
    continue;
 }

第二个异常

java.lang.ArithmeticException
divide by zero
1 com.arialyy.aria.core.download.BaseDListener.handleSpeed(BaseDListener.java)
--
2 com.arialyy.aria.core.download.BaseDListener.onProgress(BaseDListener.java)
3 com.arialyy.aria.core.common.AbsFileer$1.run(AbsFileer.java)

修改
if(mEntity.getFileSize() <= 0){
	mEntity.setPercent((int) (mEntity.getCurrentProgress() * 100 / Integer.MAX_VALUE));
}else{
	mEntity.setPercent((int) (mEntity.getCurrentProgress() * 100 / mEntity.getFileSize()));
}

这两个问题都好解决。只是我引用你的库，修改比较麻烦。就麻烦作者自己修改了

**Comment by fanchen001** [comment]
老铁看的回复一下

**Comment by AriaLyy** [comment]
已经看到了，我会尽快处理的吗，感谢支持

**Comment by AriaLyy** [comment]
按照错误提示来看，第一个异常应该不是`field.getModifiers();`导致的。能否重现下，然后把警告和异常完整贴来一下呢

**Comment by fanchen001** [comment]
异常是来自bugly收集。是在用户方发生的异常。我也不知道怎么操作重现。但是根据bugly那个上面的显示的使用时长无法获取，估计是在初始化aria时候直接就崩掉了。机器是 一加 A3000。目前该异常影响3个用户。

511-13 22:20:08.453 6581 6581 E AndroidRuntime: Process: com.fanchen.imovie, PID: 6581
--
611-13 22:20:08.453 6581 6581 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.stub.StubApp: java.lang.IllegalArgumentException: Expected receiver of type com.arialyy.aria.core.Configuration$BaseConfig, but got com.arialyy.aria.core.Configuration$UploadConfig
711-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
811-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.app.ActivityThread.-wrap1(Unknown Source:0)
911-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
1011-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:105)
1111-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
1211-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6809)
1311-13 22:20:08.453 6581 6581 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
1411-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
1511-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
1611-13 22:20:08.453 6581 6581 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Expected receiver of type com.arialyy.aria.core.Configuration$BaseConfig, but got com.arialyy.aria.core.Configuration$UploadConfig
1711-13 22:20:08.453 6581 6581 E AndroidRuntime: at java.lang.reflect.Field.setInt(Native Method)
1811-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.Configuration$BaseConfig.loadConfig(Unknown Source:158)
1911-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.Configuration$UploadConfig.<init>(Unknown Source:3)
2011-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.Configuration$UploadConfig.getInstance(Unknown Source:9)
2111-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.AriaManager.initConfig(Unknown Source:83)
2211-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.AriaManager.<init>(Unknown Source:33)
2311-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.AriaManager.getInstance(Unknown Source:9)
2411-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.Aria.get(Unknown Source:16)
2511-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.arialyy.aria.core.Aria.download(Unknown Source:0)
2611-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.fanchen.imovie.IMovieAppliction.getDownloadReceiver(Unknown Source:11)
2711-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.fanchen.imovie.IMovieAppliction.initMainSdk(Unknown Source:32)
2811-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.fanchen.imovie.IMovieAppliction.onCreate(Unknown Source:83)
2911-13 22:20:08.453 6581 6581 E AndroidRuntime: at com.stub.StubApp.onCreate(StubApplication.java:86)
3011-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
3111-13 22:20:08.453 6581 6581 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6034)
3211-13 22:20:08.453 6581 6581 E AndroidRuntime: ... 8 more

**Comment by AriaLyy** [comment]
你用3.3.7_dev_3测试下看看还会不会出问题，我改了class的获取方式

**Comment by fanchen001** [comment]
wo shishi

**Comment by AriaLyy** [comment]
用3.3.7测吧，可能是 5.0的手机会给class自动增加两个`shadow$_klass_`、`shadow$_monitor_`导致的
