### ISSUE TITLE
Error on Android studio 3.0 run

### ISSUE THREAD

**Issue by CattleFoot** [AriaLyy/Aria#162]
你好，使用3.1.7源码时在Android studio  3.0编译ok，但是在运行项目是爆出如下的错误：
Error:Execution failed for task ':Aria:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - AriaCompiler.jar (project :AriaCompiler)
    - auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

按网址（https://developer.android.com/r/tools/annotation-processor-error-message.html）处理也不行。

**Comment by AriaLyy** [comment]
这个应该是AS的问题，你按照你的那个网址在build文件中，修改下defaultConfig看看呢
```
android {
    ...
    defaultConfig {
        ...
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
    }
}
```

**Comment by congqin** [comment]
@AriaLyy 你好，AS3.0修改defaultConfig后，编译可以，但运行时，似乎没有Download事件回调，貌似注解不起作用了。

**Comment by AriaLyy** [comment]
@congqin 看下这个
 https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
