### ISSUE TITLE
支持多个组任务同时下载吗？支持的话怎么使用？

### ISSUE THREAD

**Issue by lizi0588** [AriaLyy/Aria#164]
我使用时，当一个组任务正在下载或者已经下载完成时，进行另一个组任人下载，但是停留在onGroupPre这一步不进行下载，这是怎么回事？

**Comment by AriaLyy** [comment]
支持，这是3.3.7_dev_3版本的bug，你可以使用3.3.6或3.3.7_dev_4版本
