### ISSUE TITLE
求解决：AbsFtpInfoThread: 文件不存在，任务链接.....

### ISSUE THREAD

**Issue by 1big** [AriaLyy/Aria#168]
在使用Aria.download(context)
                    .loadFtp(fileInfo.getFtpFilePath(), true)
                    .login(App.getSpUtils().getString("ftpName", "bigone"), App.getSpUtils().getString("ftpPsw", "123456"))
                    .setDownloadPath(GeoesbMethod.getDownloadPath(fileInfo.getFtpFilePath()))
                    .start();
下载的时候，报错 AbsFtpInfoThread: 文件不存在......

**Comment by 1big** [comment]
ftp是在linux环境下部署的

**Comment by AriaLyy** [comment]
信息太少，不好判断是什么问题，能否提供更加详细的信息？

**Comment by 1big** [comment]
解决了  我自己在linux下部署了vsftp，是因为地址的原因
