### ISSUE TITLE
文件总是下载失败，这是怎么回事。

### ISSUE THREAD

**Issue by Android-WangYanBin** [AriaLyy/Aria#169]
![image](https://user-images.githubusercontent.com/30645886/33362852-f1d46c46-d518-11e7-8afc-ec0f19c472fd.png)
![image](https://user-images.githubusercontent.com/30645886/33362810-e38d69a8-d518-11e7-8fca-26e16b9fff82.png)

**Comment by AriaLyy** [comment]
哥，你检查下保存的文件路径.....
