### ISSUE TITLE
下载状态几点疑问

### ISSUE THREAD

**Issue by lxpeng** [AriaLyy/Aria#172]
大佬，有几点疑问，
1. 如果下载完成后，文件被删掉了，如果此时获取状态仍为完成状态。
2. 如果相同的文件，我需要下载两次，并存在不同路径，要如何操作，需要先清除下载任务吗？
3. 是否可以判断文件是否存在状态，并已不同存放路径做区分

**Comment by lxpeng** [comment]
如果进程杀掉，下载状态仍是Running，不知道大佬会不会有此情况

**Comment by AriaLyy** [comment]
1、如果用户是在文件管理器删除的文件，我是判断不到的，这个需要需要你自己去处理
2、是的
3、不能

**Comment by AriaLyy** [comment]
```
 Aria.download(this).load("ss").isDownloading()
```
可以判断任务是否在下载

**Comment by lxpeng** [comment]
感谢回答
