### ISSUE TITLE
removeRecord问题

### ISSUE THREAD

**Issue by lxpeng** [AriaLyy/Aria#174]
发现一个必现问题，执行.removeRecord()后，下载相同url的文件，在onTaskComplete执行完之后，Aria.download(mContext).getDownloadEntity(url)  返回值为null；
不知大神 是否可重现

**Comment by lxpeng** [comment]
再下载一次的话，就是正常的了

**Comment by AriaLyy** [comment]
抱歉，最近有点忙，现在才验证，你是在下载的过程中调用removeRecord()的吗？这个方法是回将数据库的记录删除的。

**Comment by AriaLyy** [comment]
3.3.9已经添加了运行中删除记录时的处理了

**Comment by lxpeng** [comment]
感谢您的付出。
