### ISSUE TITLE
android 7.0系统上使用组任务下载没有回调

### ISSUE THREAD

**Issue by lizi0588** [AriaLyy/Aria#175]
文件是下载下来了，但是groupTaskRunning（）和 groupTaskComplete（）这两个回调没有作用，在5.0上可以用

**Comment by AriaLyy** [comment]
控制台有报什么警告或错误吗？参考下这个https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
