### ISSUE TITLE
下载中杀掉进程出现的问题

### ISSUE THREAD

**Issue by EricInCD** [AriaLyy/Aria#178]
Nexus 5，Android 8.0，调试运行，在下载一个apk的时候，如果在下载过程中，杀掉进程，然后打开app再次开启下载，打印日志如下：
com.xxx.xxx.xxx D/BaseExecutePool: 任务添加成功
com.xxx.xxx.xxx D/AbsFileer: 任务【xxx.apk】线程__0__已完成
com.xxx.xxx.xxx D/AbsFileer: 任务【xxx.apk】线程__1__已完成
com.xxx.xxx.xxx D/AbsFileer: 任务【xxx.apk】线程__2__已完成
com.xxx.xxx.xxx D/TAG:onPre
com.xxx.xxx.xxx D/TAG:onTaskResume
只回调了onPre和onTaskResume，其他方法并没有回调。

求解这个问题该如何解决，谢谢。

**Comment by EricInCD** [comment]
试了下， 在其他手机上也是如此。求解。

**Comment by AriaLyy** [comment]
能否提供下下载地址，我这demo测试是正常的呢。或者你用demo进行测试看看

**Comment by AriaLyy** [comment]
第二次下载的时候，控制台有恢复下载这个日志的打印吗？

**Comment by 425540302** [comment]
我也遇到了类似的问题，

**Comment by 425540302** [comment]
我杀死进程，再次打开继续下载，所下载的apk不全
