### ISSUE TITLE
关于重复下载相同路径的问题。

### ISSUE THREAD

**Issue by OuGaoJun** [AriaLyy/Aria#179]
我用一个url下载到一个目录，如：/mnt/sdcard/test.zip。

下载完毕后我在文件管理器将其删除，然后再用一个不一样的url下载到相同的路径：/mnt/sdcard/test.zip。就会出现问题。

具体问题是：
`java.lang.IllegalArgumentException: 保存路径【/storage/emulated/0/Music/test.mp3】已经被其它任务占用，请设置其它保存路径
at com.arialyy.aria.core.download.DownloadTarget.setDownloadPath(DownloadTarget.java:117)`

具体出错代码：
```java
if (!mTaskEntity.refreshInfo && DbEntity.checkDataExist(DownloadEntity.class,
          "downloadPath=?", downloadPath)) {
        throw new IllegalArgumentException("保存路径【" + downloadPath + "】已经被其它任务占用，请设置其它保存路径");
      }
```
应该是这个下载路径被写到数据库，然后重新下载的时候`mTaskEntity.refreshInfo`没有设置好。

但我不知道怎么改。

以上是我发现的问题。

**Comment by OuGaoJun** [comment]
目前可以使用`removeAllTask`或者重装应用达到清空数据库来解决。

**Comment by OuGaoJun** [comment]
看了下，可以通过在`load(String url, boolean refreshInfo)`里面将refreshInfo设为true就可以了，我之前没看到这个方法有这个参数，抱歉。

**Comment by AriaLyy** [comment]
不客气，可以用就好

**Comment by heil23333** [comment]
现在这个参数没有了  如何解决
