### ISSUE TITLE
求教几个问题

### ISSUE THREAD

**Issue by wlxfxy** [AriaLyy/Aria#18]
1. 在暂停状态下，调用Aria.download(this).load(mData.get(position).getDownloadUrl()).cancel()会闪退

2. 下载完成后，如何删除下载记录？我调用的
Aria.download(this).load(mData.get(position).getDownloadUrl()).cancel()，但是同时也会删除掉下载好的文件

**Comment by AriaLyy** [comment]
很感谢您的反馈，
1、`compile 'com.arialyy.aria:Aria:3.0.3'` 已经修复了该bug
2、现在可以调用`Aria.download(this).load(DOWNLOAD_URL).removeRecord();`来实现记录的删除
