### ISSUE TITLE
下载不成功

### ISSUE THREAD

**Issue by chaopengTan** [AriaLyy/Aria#180]
![33d r0djd9lm6z6ze s](https://user-images.githubusercontent.com/12883454/34377503-42df909c-eb2c-11e7-8de1-3c0bf8efce83.png)

**Comment by AriaLyy** [comment]
你检查下网络吧，看错误提示是网络的原因，我用demo测试时正常的
![qq 20171227203337](https://user-images.githubusercontent.com/10437293/34381775-98f1ae34-eb45-11e7-9bc1-902683fa7580.png)
![qq 20171227203409](https://user-images.githubusercontent.com/10437293/34381777-9a73dc5a-eb45-11e7-8ead-60a02b14de46.png)

**Comment by chaopengTan** [comment]
网络是可以的，其他apk文件都可以下载，只有这一个

**Comment by AriaLyy** [comment]
我302跳转拿的新地址和你错误的地址不是同一个啊...确认服务器没有改过吗？你看我的截图，新url那个提示...

**Comment by chaopengTan** [comment]
地址是没有变的，我通过网页打开跳迅雷上面的链接和你上面的提示的url是一样的，
![image](https://user-images.githubusercontent.com/12883454/34382235-6b1a0dc8-eb48-11e7-8788-1cda651541e7.png)  这是打印出来的log

**Comment by AriaLyy** [comment]
你拿到的怎么是down.5535.cn 我拿到的是http://d.5535.cn/games/android/mjhcjbtb/mjhcjbtb_xiaoeryu2_10200.apk
这个估计你得咨询下你们的后端开发了....

**Comment by chaopengTan** [comment]
恩，好的，谢谢

**Comment by AriaLyy** [comment]
不客气
