### ISSUE TITLE
如果将文件下载记录删除后，再重新下载该文件，将获取不到该文件的下载记录

### ISSUE THREAD

**Issue by chaopengTan** [AriaLyy/Aria#181]
并且点击暂停之后再点击继续的话，将会从零开始重新下载

**Comment by chaopengTan** [comment]
并且如果在下载过程中取消了该任务并删除了记录，再进行该文件的下载，很大几率无法下载并且会重复启动任务（同一个下载两个同时进行并且进度不一样）

**Comment by AriaLyy** [comment]
删除记录是下载过程中删除还是下载完成后删除？
你是通过那个api获取下载记录的？
你的url支持断点续传吗？方便的话，能否提供下下载的地址。

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:aria-core:3.3.10'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.10'
```
3.3.10已修复了这个问题
