### ISSUE TITLE
把下载的文件删除，原下载地址替换其他文件，新文件永远都是下载失败，而且失败文件的MD5码非常稳定

### ISSUE THREAD

**Issue by yangbiyao** [AriaLyy/Aria#182]
比对文件，下载的文件比原文件，一直少一段。

**Comment by yangbiyao** [comment]
url是变得，下载路径及文件为原来的。 替换后下载永远是错文件。

**Comment by yangbiyao** [comment]
文件名不变。下载路径不变。下载地址有变化。

**Comment by yangbiyao** [comment]
可以留个联系方式吗？我的邮箱yangbiyao@163.com

**Comment by AriaLyy** [comment]
你用的是哪个版本的？切换下载地址，保存路径不变的话，会抛异常的...

**Comment by yangbiyao** [comment]
3.3.9 组下载 下载后我把文件拷贝到别的路径，原地址文件删除。路径没变，log没看到异常呀？
再次下载到相同路径下，下载的文件一直缺一块，而且比较固定。

**Comment by yangbiyao** [comment]
01-02 20:13:09.423 32565-32565/com.neusoft.ssp.assistant D/DownloadGroupTask: FTP_TASK_MD5:265165850
01-02 20:13:09.437 32565-32565/com.neusoft.ssp.assistant D/BaseCachePool: 任务添加成功
01-02 20:13:09.437 32565-32565/com.neusoft.ssp.assistant D/BaseExecutePool: 任务添加成功
01-02 20:13:09.450 32565-24647/com.neusoft.ssp.assistant D/CommonUtil: 创建文件成功:/data/user/0/com.neusoft.ssp.assistant/files/Aria/temp/download/QIEFM.apk.properties
01-02 20:13:09.450 32565-24648/com.neusoft.ssp.assistant D/CommonUtil: 创建文件成功:/data/user/0/com.neusoft.ssp.assistant/files/Aria/temp/download/QIEFM.7z.properties
01-02 20:13:09.485 32565-24647/com.neusoft.ssp.assistant D/CommonUtil: 目标文件所在路径不存在，准备创建……
01-02 20:13:09.486 32565-24647/com.neusoft.ssp.assistant D/CommonUtil: 创建文件成功:/data/user/0/com.neusoft.ssp.assistant/files/DownloadApk/SGMW180C_HY235/QIEFM.apk
01-02 20:13:09.491 32565-24648/com.neusoft.ssp.assistant D/CommonUtil: 创建文件成功:/data/user/0/com.neusoft.ssp.assistant/files/DownloadApk/SGMW180C_HY235/QIEFM.7z
01-02 20:13:09.509 32565-24651/com.neusoft.ssp.assistant D/HttpThreadTask: 任务【QIEFM.apk】线程__0__开始下载【开始位置 : 0，结束位置：5004061】
01-02 20:13:09.510 32565-24651/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.510 32565-24653/com.neusoft.ssp.assistant D/HttpThreadTask: 任务【QIEFM.apk】线程__2__开始下载【开始位置 : 10008122，结束位置：15012184】
01-02 20:13:09.510 32565-24651/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.511 32565-24653/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.511 32565-24652/com.neusoft.ssp.assistant D/HttpThreadTask: 任务【QIEFM.apk】线程__1__开始下载【开始位置 : 5004061，结束位置：10008122】
01-02 20:13:09.511 32565-24653/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.511 32565-24652/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.512 32565-24652/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.533 32565-24657/com.neusoft.ssp.assistant D/HttpThreadTask: 任务【QIEFM.7z】线程__0__开始下载【开始位置 : 0，结束位置：624957】
01-02 20:13:09.534 32565-24657/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.535 32565-24657/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:09.542 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:09.547 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:09.676 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:09.844 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:09.884 32565-24657/com.neusoft.ssp.assistant I/HttpThreadTask: 任务【QIEFM.7z】线程__0__下载完毕
01-02 20:13:10.107 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:10.304 32565-32565/com.neusoft.ssp.assistant I/QD_AppAndGpsUseUtil$2: onRequestError: dataCollectExecutoron onRequestError arg0==网络超时，请检查网络！
01-02 20:13:10.608 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:10.614 32565-24652/com.neusoft.ssp.assistant I/HttpThreadTask: 任务【QIEFM.apk】线程__1__下载完毕
01-02 20:13:10.642 32565-32723/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:10.643 32565-32723/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:10.643 32565-32764/com.neusoft.ssp.assistant V/MediaPlayer: isPlaying: no active player
01-02 20:13:10.690 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:10.705 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:10.869 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:11.109 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:11.282 32565-32565/com.neusoft.ssp.assistant I/QD_AppAndGpsUseUtil$2: onRequestError: dataCollectExecutoron onRequestError arg0==网络超时，请检查网络！
01-02 20:13:11.462 32565-24653/com.neusoft.ssp.assistant I/HttpThreadTask: 任务【QIEFM.apk】线程__2__下载完毕
01-02 20:13:11.626 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:11.708 32565-24651/com.neusoft.ssp.assistant I/HttpThreadTask: 任务【QIEFM.apk】线程__0__下载完毕
01-02 20:13:11.730 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:11.733 32565-32565/com.neusoft.ssp.assistant E/RecommendFrag: new picture invisible
01-02 20:13:11.805 32565-32565/com.neusoft.ssp.assistant D/AbsTaskQueue: 从执行池删除任务，删除成功
01-02 20:13:11.806 32565-32565/com.neusoft.ssp.assistant I/AbsSchedulers: 没有下一任务
01-02 20:13:11.808 32565-32565/com.neusoft.ssp.assistant I/System.out: 0===状态===DISCONNECTED
01-02 20:13:11.808 32565-32565/com.neusoft.ssp.assistant I/System.out: 0===类型===MOBILE
01-02 20:13:11.808 32565-32565/com.neusoft.ssp.assistant I/System.out: 1===状态===CONNECTED
01-02 20:13:11.808 32565-32565/com.neusoft.ssp.assistant I/System.out: 1===类型===WIFI
01-02 20:13:11.813 32565-32597/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:11.814 32565-32597/com.neusoft.ssp.assistant I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-02 20:13:11.839 32565-32565/com.neusoft.ssp.assistant E/qbox: countup{"list":[],"msg":"获取成功!"}
01-02 20:13:11.842 32565-32565/com.neusoft.ssp.assistant D/ViewRootImpl@475bfca[Toast]: ThreadedRenderer.create() translucent=true
01-02 20:13:11.845 32565-32565/com.neusoft.ssp.assistant D/InputTransport: Input channel constructed: fd=87
01-02 20:13:11.845 32565-32565/com.neusoft.ssp.assistant D/ViewRootImpl@475bfca[Toast]: setView = android.widget.LinearLayout{6ce653b V.E...... ......I. 0,0-0,0} touchMode=true
01-02 20:13:11.847 32565-32565/com.neusoft.ssp.assistant D/ViewRootImpl@475bfca[Toast]: dispatchAttachedToWindow

**Comment by AriaLyy** [comment]
任务组下载，下载完成后，把所有子任务移动到其它文件夹，然后修改url地址，然后就出现了问题？
是这样一个步骤吗？

**Comment by yangbiyao** [comment]
1. 先在那个下载地址下载到A文件夹一个文件a，a会被移动到B文件夹，然后相关目录删除，B状态正常。
2. 服务器重新上传了一个文件b,我重新下载b到A文件夹，且a，b的文件名一致，则下载到的b文件始终是损坏的，我这里校验md5码失败可以重下，重下后也是损坏的，且损坏文件的md5码每次都一样。
3. 与正常文件比对，损坏的文件会在某个地方比正常文件缺几段。

**Comment by AriaLyy** [comment]
能否提供下 b文件的下载地址和MD5

**Comment by yangbiyao** [comment]
谢谢回复，
公司邮件不方便.更新了一下issue ，把log和，问题又描述了一遍，大牛帮忙看看。




发自网易邮箱大师
在2018年01月02日 20:04，laoyuyu 写道：

你用的是哪个版本的？切换下载地址，保存路径不变的话，会抛异常的...

**Comment by yangbiyao** [comment]
下载地址目前只有内网，md5值。 
我用内网，PC下载后，重新计算，和服务器是一致的。
清APP数据后，下载就正常了。

**Comment by AriaLyy** [comment]
切换地址的过程中有没有退出过app，还是只改变了服务器的地址？

**Comment by AriaLyy** [comment]
这是缓存的问题导致的，你用
```
TEManager.getInstance().removeTEntity(task.getEntity().getKey());
```
这个方法先清空缓存再进行下载看看

**Comment by yangbiyao** [comment]
groupTaskComplete 是在这里加吗？

**Comment by AriaLyy** [comment]
对

**Comment by yangbiyao** [comment]
刚试了下，好像不行。
顺着您的思路，我在结束时候又调用了一下
        List<String> urls = new ArrayList<>();
        urls.add(appDaoBean.getCar_dl_url());
        urls.add(appDaoBean.getPhone_dl_url());
        String md5Code = CommonUtil.getMd5Code(urls);
        AriaManager.getInstance(MApplication.getInstance()).delRecord(2, md5Code);
似乎好了。
只调用我加的，也会有异常，percent会一下变到几十万，不再返回下载成功和失败。
我这样改可以吗？
单文件这样加？
  AriaManager.getInstance(MApplication.getInstance()).delRecord(1, appDaoBean.getCar_dl_url());

**Comment by AriaLyy** [comment]
我刚才重新看了下代码，我在调度器中是删除了缓存了。然后我自己测试了一下是可以的..
我的操作如下：
1、先下载一个任务组，待任务完成后，删除拿两个文件
2、不退出应用，按另外一个按钮，只是把两个文件的下载地址给修改了，其它的不变，然后进行下载
这样操作不知道是否和你的一样？

**Comment by yangbiyao** [comment]
辛苦了，刚又确认了下，Url应该不是不变，在同一url下不同文件。。




发自网易邮箱大师
在2018年01月02日 21:06，laoyuyu 写道：

我刚才重新看了下代码，我在调度器中是删除了缓存了。然后我自己测试了一下是可以的..
我的操作如下：
1、先下载一个任务组，待任务完成后，删除拿两个文件
2、不退出应用，按另外一个按钮，只是把两个文件的下载地址给修改了，其它的不变，然后进行下载
这样操作不知道是否和你的一样？

**Comment by AriaLyy** [comment]
只是修改了文件路径，下载地址不变？

**Comment by yangbiyao** [comment]
路径不变，下载地址不变，下载的文件变了，不过与原文件同名。




发自网易邮箱大师
在2018年01月02日 21:10，laoyuyu 写道：

只是修改了文件路径，下载地址不变？

**Comment by AriaLyy** [comment]
意思是，只是服务器替换了文件，其它什么都没有动？如果是这个的话，目前任务组并没有支持重新刷新下载信息的api，我今晚弄下那个api，你明天再测试下吧

**Comment by AriaLyy** [comment]
或者你用`Aria.download(this).load(mUrls).removeRecord()`，先删除记录再重新下载

**Comment by AriaLyy** [comment]
用3.3.10_dev测试看看，这个版本添加了一个`resetState()`来重置下载状态

**Comment by yangbiyao** [comment]
好的，谢谢，我需要调用resetstate吗？




发自网易邮箱大师
在2018年01月03日 09:55，laoyuyu 写道：

用3.3.10_dev测试看看，这个版本添加了一个resetState()来重置下载状态

**Comment by AriaLyy** [comment]
对，用这个试试吧

**Comment by yangbiyao** [comment]
因为项目紧张，一半会儿还没改好，还是替换了框架，其实还是很好用。重申下问题，相同的url文件被替换了，重新下载有问题，文件下不全，感谢作者用自己的空闲时间帮我修改，回答，谢谢




发自网易邮箱大师
在2018年01月03日 17:59，laoyuyu 写道：

对，用这个试试吧

**Comment by AriaLyy** [comment]
不客气，还是非常感谢你的反馈的^_^。

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:aria-core:3.3.10'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.10'
```
resetstate()现在已经可以实现你的需求了
