### ISSUE TITLE
getConvertSpeed方法没有返回

### ISSUE THREAD

**Issue by OuGaoJun** [AriaLyy/Aria#183]
如下，我写了3个`DownloadTask`的Convert方法。
![image](https://user-images.githubusercontent.com/31914181/34486152-4ad13ea4-f009-11e7-9a6a-ed04a7b72092.png)

下面是Log的输出：
![image](https://user-images.githubusercontent.com/31914181/34486185-8147868c-f009-11e7-80be-3807dcd60182.png)

`getConvertSpeed`方法没有任何返回。
一时半会找不到原因

**Comment by AriaLyy** [comment]
将配置文件中的`<convertSpeed value="true"/>`改为true就可以了

**Comment by OuGaoJun** [comment]
@AriaLyy 好的，非常感谢。
