### ISSUE TITLE
请教问题！

### ISSUE THREAD

**Issue by Born-alone** [AriaLyy/Aria#186]
1.如何在下载列表的Adapter中添加所需要的字段 
2.在点击下载的列表中判断是否下载过该资源与控制该资源的下载与暂停？

**Comment by AriaLyy** [comment]
1、通过[扩展字段](https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E7%94%A8api#%E4%BF%9D%E5%AD%98%E6%89%A9%E5%B1%95%E5%AD%97%E6%AE%B5)可以添加自定义数据
2、通过这个[api](https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E7%94%A8api#%E8%8E%B7%E5%8F%96%E4%BB%BB%E5%8A%A1%E5%88%97%E8%A1%A8)可以获取已下载的任务列表
3、暂停调用`Aria.download(context).load(url).stop()`、恢复下载或开始下载都是这个api`Aria.download(context).load(url).start()`
