### ISSUE TITLE
消息的频率问题

### ISSUE THREAD

**Issue by WalkerPen** [AriaLyy/Aria#190]
1.能不能提供消息发送频率的配置项，比如我希望300毫秒更新一次进度

2.取消下载会走两次回调

**Comment by AriaLyy** [comment]
1、现在还没有这个功能
2、取消下载走两次回调，请问你用的是那个版本？还有你是组任务下载还是单任务下载？

**Comment by AriaLyy** [comment]
`3.3.11`已经添加了相应的api接口，你现在可以再[配置文件](https://github.com/AriaLyy/Aria/blob/master/app/src/main/assets/aria_config.xml) 或使用代码`AriaManager.getInstance(AriaManager.APP).getDownloadConfig().setUpdateInterval(3000)`进行消息频率的控制
