### ISSUE TITLE
下载文件不全问题

### ISSUE THREAD

**Issue by 425540302** [AriaLyy/Aria#192]
当任务正在进行时，打开资源管理器，将此app进程给杀死，然后再重新进来继续下载，下载完成后文件不全，我下载的是apk,导致无法安装

**Comment by AriaLyy** [comment]
`3.3.11已经修复了这个问题`

**Comment by leadersm** [comment]
你好 我这边也遇到一个下载不全无法安装的问题。 3.3.13

**Comment by AriaLyy** [comment]
将线程数改为单线程
