### ISSUE TITLE
提两个bug

### ISSUE THREAD

**Issue by zhanglihow** [AriaLyy/Aria#193]
1.下载文件过多 使用单个url下载  没有打包下载  下载一部分后出现文件数打开过多的error 。
2.下载照片，完成后发现照片错位了   是被截掉一半然后错位拼接似的。

**Comment by AriaLyy** [comment]
1、文件数打开过多的error的log日志能提供下吗？
2、照片下载是多张图片同时下载吗？

**Comment by zhangli915952504** [comment]
日志暂时不能提供了，后面有空我补上吧，我查过资料，大概是资源打开的太多造成的，可能是因为我使用了太多单个下载的问题，如果换成打包下载，应该会避免。
照片是单张下载的，下完再下另一张这样，下载数张，偶尔会出现一两张。我觉得是因为分段下载后数据流拼接的问题。

**Comment by AriaLyy** [comment]
照片那个在配置文件中配置单线程试试看，这个版本已发现了一个失败重试可能导致下载文件错误的问题，明天你用新版本看下。

**Comment by AriaLyy** [comment]
方便的话，日志麻烦提供下哈

**Comment by zhangli915952504** [comment]
好的  。
对的，是有重试的现象出现。

**Comment by AriaLyy** [comment]
你用`3.3.11`试试，已经修复了这个问题

**Comment by zhangli915952504** [comment]
下载400多张照片，还是有错位的情况，错位比较频繁，是在下载正常的情况下。
在200多张的时候出现这个错（估计是请求太多的原因）：
`02-07 10:47:17.170 16380-19268/com.build.scan E/AbsThreadTask: 下载失败【http://flashair/DCIM/100MSDCF/DSC00305.JPG】
                                                               ExceptionDetailed:
                                                               ====================Exception Info====================
                                                               java.net.ConnectException: failed to connect to flashair/192.168.0.1 (port 80) after 5000ms: connect failed: EMFILE (Too many open files)
                                                               libcore.io.IoBridge.connect(IoBridge.java:124)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:502)
                                                               java.net.Socket.connect(Socket.java:884)
                                                               com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                               com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                               com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                                                               com.android.okhttp.Connection.connect(Connection.java:152)
                                                               com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                               com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                               com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
                                                               com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
                                                               com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:75)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               【Caused by】: android.system.ErrnoException: connect failed: EMFILE (Too many open files)
                                                               libcore.io.Posix.connect(Native Method)
                                                               libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                               libcore.io.IoBridge.connectErrno(IoBridge.java:154)
                                                               libcore.io.IoBridge.connect(IoBridge.java:122)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:502)
                                                               java.net.Socket.connect(Socket.java:884)
                                                               com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                               com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                               com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                                                               com.android.okhttp.Connection.connect(Connection.java:152)
                                                               com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                               com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                               com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
                                                               com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
                                                               com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:75)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               ===================================================
02-07 10:47:17.216 16380-19270/com.build.scan E/AbsThreadTask: 下载失败【http://flashair/DCIM/100MSDCF/DSC00305.JPG】
                                                               ExceptionDetailed:
                                                               ====================Exception Info====================
                                                               java.io.FileNotFoundException: /storage/emulated/0/ScanProject/测试11/cameras/DSC00305.JPG: open failed: EMFILE (Too many open files)
                                                               libcore.io.IoBridge.open(IoBridge.java:452)
                                                               java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                               com.arialyy.aria.util.BufferedRandomAccessFile.<init>(BufferedRandomAccessFile.java:123)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:77)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               【Caused by】: android.system.ErrnoException: open failed: EMFILE (Too many open files)
                                                               libcore.io.Posix.open(Native Method)
                                                               libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                               libcore.io.IoBridge.open(IoBridge.java:438)
                                                               java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                               com.arialyy.aria.util.BufferedRandomAccessFile.<init>(BufferedRandomAccessFile.java:123)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:77)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               ===================================================
02-07 10:47:17.223 16380-19270/com.build.scan E/art: ashmem_create_region failed for 'indirect ref table': Too many open files`

**Comment by zhangli915952504** [comment]
下载400多张照片，还是有错位的情况，错位比较频繁，是在下载正常的情况下。
在200多张的时候出现这个错（估计是请求太多的原因）：
02-07 10:47:17.170 16380-19268/com.build.scan E/AbsThreadTask: 下载失败【http://flashair/DCIM/100MSDCF/DSC00305.JPG】
                                                               ExceptionDetailed:
                                                               ====================Exception Info====================
                                                               java.net.ConnectException: failed to connect to flashair/192.168.0.1 (port 80) after 5000ms: connect failed: EMFILE (Too many open files)
                                                               libcore.io.IoBridge.connect(IoBridge.java:124)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:502)
                                                               java.net.Socket.connect(Socket.java:884)
                                                               com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                               com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                               com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                                                               com.android.okhttp.Connection.connect(Connection.java:152)
                                                               com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                               com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                               com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
                                                               com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
                                                               com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:75)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               【Caused by】: android.system.ErrnoException: connect failed: EMFILE (Too many open files)
                                                               libcore.io.Posix.connect(Native Method)
                                                               libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                               libcore.io.IoBridge.connectErrno(IoBridge.java:154)
                                                               libcore.io.IoBridge.connect(IoBridge.java:122)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
                                                               java.net.PlainSocketImpl.connect(PlainSocketImpl.java:502)
                                                               java.net.Socket.connect(Socket.java:884)
                                                               com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                               com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                               com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                                                               com.android.okhttp.Connection.connect(Connection.java:152)
                                                               com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                               com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                               com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
                                                               com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
                                                               com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                               com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:75)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               ===================================================
02-07 10:47:17.216 16380-19270/com.build.scan E/AbsThreadTask: 下载失败【http://flashair/DCIM/100MSDCF/DSC00305.JPG】
                                                               ExceptionDetailed:
                                                               ====================Exception Info====================
                                                               java.io.FileNotFoundException: /storage/emulated/0/ScanProject/测试11/cameras/DSC00305.JPG: open failed: EMFILE (Too many open files)
                                                               libcore.io.IoBridge.open(IoBridge.java:452)
                                                               java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                               com.arialyy.aria.util.BufferedRandomAccessFile.<init>(BufferedRandomAccessFile.java:123)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:77)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               【Caused by】: android.system.ErrnoException: open failed: EMFILE (Too many open files)
                                                               libcore.io.Posix.open(Native Method)
                                                               libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                               libcore.io.IoBridge.open(IoBridge.java:438)
                                                               java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                               com.arialyy.aria.util.BufferedRandomAccessFile.<init>(BufferedRandomAccessFile.java:123)
                                                               com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:77)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               java.lang.Thread.run(Thread.java:818)
                                                               ===================================================
02-07 10:47:17.223 16380-19270/com.build.scan E/art: ashmem_create_region failed for 'indirect ref table': Too many open files

**Comment by AriaLyy** [comment]
修改线程数量为单线程试试

**Comment by zhanglihow** [comment]
嗯，单线程就没有错位了

**Comment by AriaLyy** [comment]
估计是太多的线程请求写文件导致的问题

**Comment by zhanglihow** [comment]
400张快下完了  单线程下还没报错  看来是这个问题了
