### ISSUE TITLE
下载链接带符号‘会报错

### ISSUE THREAD

**Issue by LIBYER** [AriaLyy/Aria#194]
例如这个链接https://bogoe-res.mytbz.com/tbzengsong/If You're Happy.mp3  在You're中有个 ’ 符号，就会出现
near "re": syntax error (code 1): , while compiling: SELECT rowid, * FROM DownloadEntity WHERE url='https://bogoe-res.mytbz.com/tbzengsong/If You're Happy.mp3' and isGroupChild='false'

**Comment by AriaLyy** [comment]
`3.3.11已经修复了这个问题`
