### ISSUE TITLE
导入成功无法导入包

### ISSUE THREAD

**Issue by xiangou** [AriaLyy/Aria#195]
导入下面成功
    compile 'com.arialyy.aria:aria-core:3.3.15'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.15'

但是在项目中无法找到Aria 这个类
#

**Comment by AriaLyy** [comment]
clean 后再build一下看看

**Comment by xiangou** [comment]
可以了谢谢
程序行业是个玄学，昨天 clean 后再build  很多次
框架中用了 androidannotations
