### ISSUE TITLE
取消注册的方法似乎不好用

### ISSUE THREAD

**Issue by Reginer** [AriaLyy/Aria#197]
我在activity里写下了如下代码，activity继承的AppcompatActivity.

![qq 20180223140637](https://user-images.githubusercontent.com/12568257/36580354-da7a8472-18a2-11e8-8806-b249c8a961a4.jpg)

当我finish这个activity的时候，那个onTaskRunning回调依然执行。

**Comment by AriaLyy** [comment]
activity中不需要unregister，如果要使用，需要将该方法写在onDestory中

**Comment by Reginer** [comment]
试过了的，和在onStop里一样。在使用的过程中还遇到一个网址的文件下到一半退出来，然后更换服务器上这个文件，再点下载，提示文件被占用，就再无法下载这个文件了。

**Comment by Reginer** [comment]
这个需求是这样:在activity里注册下，然后通过这个注解获取下载进度这些信息设置控件，退出activity之后就不再设置控件了，也就是注解不再调用了。现在activity已经关闭了注解继续调用，就崩掉了

**Comment by AriaLyy** [comment]
在activity不调用unregister这个方法，有异常的话麻烦提供下日志

**Comment by AriaLyy** [comment]
更换服务器的文件，不改变url，需要调用resetState()方法

**Comment by Reginer** [comment]
![image](https://user-images.githubusercontent.com/12568257/36730620-0218d5b6-1c03-11e8-881b-6d087ecfb6b3.png)
像图中这样在activity里的，这时候activity已经退出了，那个控件已经没了。但是注解的回调却还在，再去设置控件的属性，就空指针啦。

还有就是不改变url改变了文件，apk也不会知道哦，要每次下载之前都先调用下resetState()方法，断点也没得用了

**Comment by AriaLyy** [comment]
你把Aria相关的方法全部注释下，然后用as的工具检查下当前页面有没有发生内存泄漏
如果你自己的页面没有发生内存泄漏。麻烦提供下内存断点文件和控制台日志
该问题一般是内存泄漏引起的

**Comment by Reginer** [comment]
谢谢，换其他的下载库了。这个问题你可以自己复现的。
