### ISSUE TITLE
任务下载后，马上去查看下载记录，有时候需要一段时间后才能获取到下载记录

### ISSUE THREAD

**Issue by chaopengTan** [AriaLyy/Aria#198]
并且  Aria.download(this).getTaskList()   和  Aria.download(this).getAllNotCompletTask()好像并没有什么区别

**Comment by AriaLyy** [comment]
getTaskList 是获取所有任务的，getAllNotCompletTask是获取未完成的任务，
一段时间指的的是多久？是点击下载，马上去都数据吗？

**Comment by chaopengTan** [comment]
@AriaLyy  是点击下载后，任务开始又回调了，这个时候立马去查看下载记录，获取不到下载的记录

**Comment by AriaLyy** [comment]
3.4 版本已经修复了这个问题
