### ISSUE TITLE
任务删除了 立马重新下载报错

### ISSUE THREAD

**Issue by zuoni1018** [AriaLyy/Aria#199]
下载完成之后 用自己的网络框架调接口 这时候偶尔出现 

java.net.ProtocolException: Unexpected status line: �<!DOCTYPE html>

**Comment by AriaLyy** [comment]
使用post请求试试

**Comment by zuoni1018** [comment]
都是使用的 post  是后台接口的原因还是我App的原因  下载完成之后过一会就恢复正常了

**Comment by AriaLyy** [comment]
能否提供下详细的日志

**Comment by zuoni1018** [comment]
服务器 原来用的内网 现在迁移到外网没有暂时没有这个问题了  谢谢！
