### ISSUE TITLE
多个界面同时监听下载进度 有问题

### ISSUE THREAD

**Issue by zuoni1018** [AriaLyy/Aria#200]
需求：

我的课程页面（嵌套 课程列表 和 课件下载列表）  ----点击课程列表的item 跳转课程详情界面（里面有个下载课件按钮）----点击下载课件 跳转到我的课程页面（显示课件下载列表的fragment）      这样就产生了循环  这时候只有栈底的fragment 能监听到下载进度  其余界面下载进度就静止了 （没有变化）

**Comment by AriaLyy** [comment]
也就是说这个过程中，会产生两个“我的课程”Activity？方便传一下gif的动图吗？这样比较好理解

**Comment by zuoni1018** [comment]
[S80302-09094564.zip](https://github.com/AriaLyy/Aria/files/1773347/S80302-09094564.zip)
解压了 里面有个 录屏MP4

**Comment by AriaLyy** [comment]
好的

**Comment by zuoni1018** [comment]
这个 bug 修复了吗 
我要怎么更新我的依赖才能引用到最新的

**Comment by AriaLyy** [comment]
3.3.16_dev 用这个测试下

**Comment by zuoni1018** [comment]
可以了
