### ISSUE TITLE
为什么浏览器能下载 在库里面总是返回下载失败，文件长度小于0

### ISSUE THREAD

**Issue by 617450941** [AriaLyy/Aria#202]
下载地址是这个 http://kf.lyfz.net/api/v1/we_chat/Business/getMaterial?company_id=51454009d703c86c91353f61011ecf2f&appid=wx88c6052d06eaaf7d&media_id=qpkQb72KqNkZhBNIUw7asF0LuJouXCTBd3A-rS2bYl7H4kvTZstEXD3F-pDVeqA-&type=3

**Comment by 617450941** [comment]
这是一个mp3文件 服务端输出的

**Comment by AriaLyy** [comment]
```
 Aria.download(this)
              .load(DOWNLOAD_URL)
              .setDownloadPath(DOWNLOAD_PATH)
              .addHeader("Accept-Encoding", "gzip, deflate")
              .start();
```
添加"gzip, deflate"头

**Comment by 617450941** [comment]
@AriaLyy 添加了 .addHeader("Accept-Encoding", "gzip, deflate") 还是一样返回下载失败，文件长度小于0

**Comment by AriaLyy** [comment]
抓包看下了网络，你的服务器貌似是启动了chunked模式，而我这边还没有实现chunked模式的请求，就导致我这边没能获取到正确的文件长度，以至于下载失败；
而百度的那个，貌似是https的原因，具体还要研究下。
你可以在你的服务器上尝试关闭chunked试试，看能不能正常下载

**Comment by AriaLyy** [comment]
3.4 版本已经支持chunked模式和gzip流的输入了
