### ISSUE TITLE
注解没有回调 apt换成annotationProcessor了 

### ISSUE THREAD

**Issue by junchenChow** [AriaLyy/Aria#204]
还是提示ProxyClassCounter没找到
然后又加上这个配置 还是不行
javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
log：Caused by: java.lang.ClassNotFoundException: Didn't find class "com.arialyy.aria.ProxyClassCounter" on path: DexPathList[[zip file "/data/app/me.donguo.android-1/base.apk"],nativeLibraryDirectories=[/data/app/me.donguo.android-1/lib/arm, /data/app/me.donguo.android-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
能帮忙看看吗

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by junchenChow** [comment]
我新建了个demo没问题 就是把下载集成进自己项目 就没反应了 都是按照你wiki上配置来的。
实在搞不懂 自己项目哪里出问题了。

**Comment by junchenChow** [comment]
看到依赖包都成功引入了 但是不起作用 晕￼
![wechatimg39](https://user-images.githubusercontent.com/13553319/37277593-1e749de0-2620-11e8-8593-be7ddcc86fea.jpeg)

**Comment by AriaLyy** [comment]
gradle日志和app.gradle文件能否给我看下呢？

**Comment by junchenChow** [comment]
[build.zip](https://github.com/AriaLyy/Aria/files/1805108/build.zip)
日志和gradle文件都在里面了 麻烦大佬看看～

**Comment by AriaLyy** [comment]
1、你的gradle文件配错了，没有导入kapt插件 [kapt 插件](https://www.kotlincn.net/docs/reference/kapt.html)
2、我的那个不应该使用`annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.14'` 而应该是`kapt 'com.arialyy.aria:aria-compiler:3.3.14'`

**Comment by junchenChow** [comment]
疏忽了没认真看到kotlin ，谢谢 兄弟 可以了 ！
