### ISSUE TITLE
java.io.FileNotFoundException: aria_config.xml

### ISSUE THREAD

**Issue by Anro-fei** [AriaLyy/Aria#205]
这是什么原因

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/Aria%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE

**Comment by Anro-fei** [comment]
华为手机上，下载进度，不能调用

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
