### ISSUE TITLE
组下载，有两个小问题请教

### ISSUE THREAD

**Issue by junchenChow** [AriaLyy/Aria#206]
1. aria_config.xml 里面的maxTaskNum设置的是1，然后开始下载之后 控制的是组的最大数而不是组里的subtask吗。

2. 我能控制Group里面的subtask最大下载数吗，如果不行 我只能for循环调用单任务的下载方式了么。

**Comment by AriaLyy** [comment]
1、maxTaskNum 是队列中人任务数，一个组的任务认为是一个队列中的任务
2、目前还不支持设置sub设置最大下载数，可以尝试下

**Comment by junchenChow** [comment]
那我列表下载 需求是最多只能有一个任务在下载 只能用单任务for循环添加了吗 有没有正确的方式～

**Comment by AriaLyy** [comment]
你的一个任务指的任务组中的子下载任务还是指一个任务组？
