### ISSUE TITLE
支持后台下载么？

### ISSUE THREAD

**Issue by ruhaly** [AriaLyy/Aria#21]
支持后台下载么？

**Comment by AriaLyy** [comment]
支持的，默认是后台下载，正常情况下，退出界面，再进入下载界面，默认会回调当前Activity在Aria中注册的事件，[在Activity等控件中获取下载任务状态](https://github.com/AriaLyy/Aria#下载状态获取)；如果你希望在Service获取下载状态，那么你可以在Service中注册广播接收器用来接收Aria的任务下载状态 [在Service中获取下载任务状态](https://github.com/AriaLyy/Aria#使用广播接收器接收aria的任务下载状态)
