### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by wang869755676** [AriaLyy/Aria#211]
static com.arialyy.artia.core.sheduler.downloadSchedulers
 references com.arialyy.artia.core.sheduler.downloadSchedulers.mObservers

 /**
   * 取消注册，如果是Activity或fragment，Aria会界面销毁时自动调用该方法。
   * 如果是Dialog或popupwindow，需要你在撤销界面时调用该方法
   */
  @Override public void unRegister() {
    if (needRmListener) {
      unRegisterListener();
    }
    AriaManager.getInstance(AriaManager.APP).removeReceiver(obj);
  }

**Comment by AriaLyy** [comment]
用3.3.16_dev2，dev1的bug

**Comment by wang869755676** [comment]
ok，使用过程中个人的一些感受 如果路径存在，就抛异常， url路径不合适就抛异常，个人觉得 可以把这些异常转为其他的，因为未知元素很多，如果都抛异常的，这些东西是很难把控的

**Comment by wang869755676** [comment]
ok
