### ISSUE TITLE
有时候设置了扩展字段再通过获取所有下载记录里面获取不到扩展字段数据

### ISSUE THREAD

**Issue by chaopengTan** [AriaLyy/Aria#212]
如题：
  Aria.download(mContext)
                .load(downApkUrl)   
                .setDownloadPath(filePath) 
                .addHeader("groupName", "value")
                .setExtendField(jsonObject.toJSONString())
                .start();   //启动下载

获取通过：absEntity.getStr()

**Comment by wjkqwer** [comment]
我也遇见这个问题了

**Comment by AriaLyy** [comment]
使用3.4_dev试一下呢

**Comment by AriaLyy** [comment]
3.4 版本已经修复了这个问题
http://aria.laoyuyu.me/aria_doc/api/extend_field.html
