### ISSUE TITLE
已经被其它任务占用，请设置其它保存路径

### ISSUE THREAD

**Issue by BayMikyou** [AriaLyy/Aria#215]
其实有时候我们不能再换路径的，因为可能会存在一种case就是服务端针对同一个视频每次返回的是url是不一样，后台服务端会根据过期的时间戳生成一个唯一auth_key拼接在URL后面，那么这样的同一个视频每次打开都要去下载。

**Comment by BayMikyou** [comment]
建议在内部 不要只默认把download url做为唯一download key. 可以尝试开放另外一个口子，给外部自定义download key,
如果外部没有设置download key才默认是download url作为key

**Comment by AriaLyy** [comment]
3.4已经处理了这个问题
