### ISSUE TITLE
多任务下载， 根据什么区获取进度

### ISSUE THREAD

**Issue by Anro-fei** [AriaLyy/Aria#216]

**Comment by Anro-fei** [comment]
app.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (url != null) {
                    appName = gameUrl.substring((gameUrl.lastIndexOf("/") + 1), (gameUrl.length()));
                    Log.i("Tag", "开始下载----------------" + appName);
//                    Aria.download(app)
//                            .load(gameUrl)     //读取下载地址
//                            .setDownloadPath(appPath + appName)    //设置文件保存的完整路径
//                            .start();   //启动下载
                    Aria.download(app)
                            .load(Arrays.asList(gameUrl))
                            .setSubFileName(Arrays.asList(appPath))
                            .setDownloadDirPath(appPath + appName)
                            .setGroupAlias(appName)
                            .start();
                  
                } else {
                    app.showAlertDialog("下载失败","下载地址不正确");
                }

**Comment by Anro-fei** [comment]
这是开始下载的调用，

**Comment by AriaLyy** [comment]
是的，前提是任务组要设置下总长度
正常来说不需要设置，某些情况下获取的总长度可能有偏差，因为任务组总长度是根据url获取到的子任务的长度相加的，但是获取文件信息的线程池是根据性能自动动态重建任务，可能会导致有些任务没来得急取到正确的长度

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/38291912-5040d9c8-3814-11e8-8099-b73c20a4130e.png)

**Comment by Anro-fei** [comment]
我这边没法获取任务的总长度

**Comment by AriaLyy** [comment]
那你子任务数是多少？

**Comment by Anro-fei** [comment]
一个条目对应一个apk,如何获取子任务数

**Comment by AriaLyy** [comment]
子任务数量就是你传进去的url的数量

**Comment by Anro-fei** [comment]
每次对应一个

**Comment by Anro-fei** [comment]
就是一个条目对应一个，点击几次条目，就会有几个

**Comment by AriaLyy** [comment]
你是多个普通的任务列表吧...，是不是相当于应用市场的下载列表？

**Comment by AriaLyy** [comment]
比如一个视频下载任务，它有视频截图、字幕、视频文件，这3个东西在一个文件夹中， 共享一个progressbar，这种情况才需要用到任务组

**Comment by Anro-fei** [comment]
对的，就是那样相当于应用市场

**Comment by Anro-fei** [comment]
那样不同任务之间，产生干扰吗

**Comment by Anro-fei** [comment]
所有的文件都是APK,但是可能同时下载，下载之间，会出现干扰

**Comment by AriaLyy** [comment]
这样的话，你使用单任务列表就行了，参考demo工程的[MultiDownloadActivity](https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/download/multi_download/MultiDownloadActivity.java)和[DownloadAdapter](https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/download/multi_download/DownloadAdapter.java)
可以实现你的需求，单任务走的是队列，Aria已经帮你管理了队列和任务将状态的调度了，你只需要在需要的时候调用start()，stop()，cancel()等方法就行了

**Comment by AriaLyy** [comment]
任务是相对独立的，在Aria中任务是不会相互干扰的，出现干扰一般是ListView刷新的问题导致，建议用recyclerview，就不会有那么多事

**Comment by Anro-fei** [comment]
我这边不是用的适配器组件，我用的JNI回调

**Comment by Anro-fei** [comment]
你那边用的队列，那么暂停，就是停止最后一个加入到队列里面的啊

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/Aria%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE#%E6%89%A7%E8%A1%8C%E9%98%9F%E5%88%97%E7%B1%BB%E5%9E%8B
