### ISSUE TITLE
translate yout fucking doc

### ISSUE THREAD

**Issue by dowan** [AriaLyy/Aria#22]
hi

**Comment by AriaLyy** [comment]
ok，i will translate this document soon

**Comment by czy1121** [comment]
翻译个毛线，爱用不用

**Comment by JasonZhu19910601** [comment]
提问者刚刚吃过shit吗？
Did the questioner just eat the shit?

**Comment by irufus** [comment]
If someone translates it to Korean I can translate it to English from there.

**Comment by lchben** [comment]
Why do not you eat feces?

**Comment by AriaLyy** [comment]
The document has been translated
