### ISSUE TITLE
无法设置下载进度监听器

### ISSUE THREAD

**Issue by guoleshou** [AriaLyy/Aria#221]
查看log，执行到：Aria.download(service).register();的时候，包如下警告：
04-09 22:09:19.124 2224-2285/com.lg.adserver E/AriaManager: java.io.FileNotFoundException: aria_config.xml
04-09 22:09:19.125 2224-2285/com.lg.adserver W/System.err: java.lang.ClassNotFoundException: com.arialyy.aria.ProxyClassCounter
04-09 22:09:19.125 2224-2285/com.lg.adserver W/System.err:     at java.lang.Class.classForName(Native Method)
04-09 22:09:19.125 2224-2285/com.lg.adserver W/System.err:     at java.lang.Class.forName(Class.java:309)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.Class.forName(Class.java:273)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at com.arialyy.aria.core.common.ProxyHelper.init(ProxyHelper.java:49)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at com.arialyy.aria.core.common.ProxyHelper.<init>(ProxyHelper.java:35)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at com.arialyy.aria.core.common.ProxyHelper.getInstance(ProxyHelper.java:41)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at com.arialyy.aria.core.download.DownloadReceiver.register(DownloadReceiver.java:195)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at lg.server.conn.LoadManager2.loadApk(LoadManager2.java:193)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at lg.server.release.ConnService.do4UP(ConnService.java:104)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at lg.server.conn.ParseProtocol.getTypeReturn(ParseProtocol.java:149)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at lg.server.conn.Connector$4.run(Connector.java:114)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.arialyy.aria.ProxyClassCounter" on path: DexPathList[[zip file "/data/app/com.lg.adserver-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lg.adserver-1/lib/arm, /vendor/lib, /system/lib]]
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err: 	... 12 more
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.arialyy.aria.ProxyClassCounter
04-09 22:09:19.126 2224-2224/com.lg.adserver I/LG: lg.lift.state.Connector$putRequest()@172 : putRequest ok!!!
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.Class.classForName(Native Method)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-09 22:09:19.126 2224-2285/com.lg.adserver W/System.err: 		... 13 more

实际上就是如下执行不成功，初始变量都为null，导致register失败：
Class clazz = Class.forName("com.arialyy.aria.ProxyClassCounter");
      Method download = clazz.getMethod("getDownloadCounter");
      Method downloadGroup = clazz.getMethod("getDownloadGroupCounter");
      Method downloadGroupSub = clazz.getMethod("getDownloadGroupSubCounter");
      Method upload = clazz.getMethod("getUploadCounter");
      Object object = clazz.newInstance();
      Object dc = download.invoke(object);

帮忙看看，多谢！

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
