### ISSUE TITLE
下载状态问题！

### ISSUE THREAD

**Issue by Born-alone** [AriaLyy/Aria#223]
文件开始下载以后  将程序切换至后台运行并杀死程序 进来 获取下载状态怎么还是
/**
   * 下载中
   */
  @Ignore int STATE_RUNNING = 4;
下载中状态？

**Comment by AriaLyy** [comment]
app 被kill前，任务是什么状态，从新进来任务便是什么状态，可以通过`Aria.download(this).getDownloadEntity()`获取状态信息

**Comment by Born-alone** [comment]
这样就会有问题呀！  
我如果正在下载中 杀死App后再进来 状态应该是暂停才对呀

**Comment by chaopengTan** [comment]
而且杀死程序再进来后，无法继续下载

**Comment by AriaLyy** [comment]
@chaopengTan  地址方便提供下吗？
kill app 的状态是无法获取的，应用自己的都无法做到，框架自然也无法做到..
