### ISSUE TITLE
注解问题

### ISSUE THREAD

**Issue by BayMikyou** [AriaLyy/Aria#224]
对于使用的注解必须在Activity或者fragment中，看似是解耦合，实际上局限性很大，对于使用这个库的人无法给你这个库和它的业务做隔离，回调触发在Activity中，并且把AbsEntity类实例回调，造成Activity与你的AbsEntity耦合在一起。无法真正做到把你这个库替换，不会影响业务代码运行。望做调整

**Comment by AriaLyy** [comment]
fragment 是可以使用注解的...

**Comment by BayMikyou** [comment]
嗯，我知道fragment中可以使用注解，但是关键是你的注解回调出来的DownloadTask已经和我的业务层产生耦合，无法做到很好隔离业务和你写的库

**Comment by BayMikyou** [comment]
如果能这样是最好的，或者甚至我可以不需要注解，你直接简单粗暴地给我回调都行。

2018-04-11 22:01 GMT+08:00 laoyuyu <notifications@github.com>:

**Comment by AriaLyy** [comment]
3.4版本已支持在任意类中使用
http://aria.laoyuyu.me/aria_doc/start/any_java.html

**Comment by BayMikyou** [comment]
谢谢 大佬
