### ISSUE TITLE
下载路径问题！

### ISSUE THREAD

**Issue by Born-alone** [AriaLyy/Aria#225]
现在有一个需求就是 需要根据用户的ID去下载文件 存储到用户ID对应的文件夹中  切换用户就得切换与之对应的缓存列表及缓存状态
请问下载列表是否支持读取指定文件夹中缓存列表  及 缓存状态
看库中都是以下载的Url为唯一标识！

**Comment by AriaLyy** [comment]
不支持动态切换文件夹..

**Comment by BayMikyou** [comment]
@AriaLyy @Born-alone 所以个人觉得以URL作为唯一标识是可以满足大部分需求场景，但是如果能把这个唯一标识开个口子给外面自定义的话 会更好。@Born-alone建议目前你可以使用extendFiled来达到需求

**Comment by Born-alone** [comment]
@BayMikyou extendFiled  这个是哪里的？

**Comment by Born-alone** [comment]
@BayMikyou 这个应该只能在缓存列表去筛选数据吧 
下载的状态怎么去判断呢 
不同用户 A下载了 B没下载 B就得从新开始下载

**Comment by BayMikyou** [comment]
其实你这个需求就是不同的用户的下载的目录不一样吧，这个只要拿用户ID命名下载目录不就可以了吗？

**Comment by Born-alone** [comment]
![Uploading [微信图片_20180412133908.jpg…]()](url)
问题是 这个缓存列表的数据倒好处理 根据 ID 去筛选一下数据就行 
但是我这还有一个页面 不同用户也根据ID去判断下载没下载过？

**Comment by Born-alone** [comment]
![_20180412134314](https://user-images.githubusercontent.com/25575326/38658353-59658c8a-3e57-11e8-98d1-b764063e3881.png)

**Comment by Born-alone** [comment]
![_20180412134352](https://user-images.githubusercontent.com/25575326/38658376-6f30edc0-3e57-11e8-94ad-46dafcca0948.png)

**Comment by Born-alone** [comment]
@BayMikyou 而且还有一个问题  
![_20180412150022](https://user-images.githubusercontent.com/25575326/38661117-53368930-3e62-11e8-890e-93bea50790b8.png)
我在这个方法里的json存了一个用户ID 作为标识  
我获取缓存列表 或者 缓存状态的时候也是根据这个ID 去筛选 List<AbsEntity> totleTaskList = Aria.download(this).getTotleTaskList(); 得到的数据
比如A用户下载了一个文件 存到了它ID所对应的文件夹中 
退出A用户登录B用户 再次下载同一文件时 该文件不会被再次下载 文件会继续存储在A用户对应的文件夹中  但是文件中我使用 setExtendField() 存储的json信息 中的ID 已经变成了B用户的ID  
所以再次登录A用户 根据ID去筛选数据的时候 该文件又是没有下载的

**Comment by BayMikyou** [comment]
问你个问题你的同一个视频，每次下载URL都是一样的吗

2018-04-12 15:07 GMT+08:00 Born-alone <notifications@github.com>:

**Comment by Born-alone** [comment]
是的  同一个视频 每次下载的URL都是相同的
