### ISSUE TITLE
注解中生成回调方法有时候不起作用

### ISSUE THREAD

**Issue by BayMikyou** [AriaLyy/Aria#226]
复现上述问题情况如下，就是在本地debug版本下，多run几次后就会出现状态回调的接口方法没有回调，打印日志也没有，虽然不是经常必现，但是几乎每隔几次都会出现一次这样情况，解决办法只能clean后，重新生成注解代码，才有用。

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/wiki/%E6%B3%A8%E8%A7%A3%E4%BD%BF%E7%94%A8

**Comment by BayMikyou** [comment]
还有一个问题，我在aria_config.xml中把最大任务数修改成3个，使它同时可以一起下载3个任务，当我扔入第四个任务的时候，处于等待状态。此时我把第一任务先暂停了，按道理第四个任务应该可以下载了。但是还是处于等待状态。如果我再暂停一个也就是暂停两个，第四个任务才开始下载。也就是我虽然把最大任务设置了3个，但是等待的时候，按道理也是3个，但是是两个。

**Comment by BayMikyou** [comment]
还是就是问下最新的依赖版本是多少，看你tag也看不出来，tag才3.2几的版本，可是你在issue中都给出了3.3.3和3.4

**Comment by hellocl** [comment]
这是我下载时的
Aria.download(getContext())
        .load(Arrays.asList(Constant.VIDEOURL + downloadUrl))
        .setSubFileName(Arrays.asList(title + sortNo))
        .setDownloadDirPath(file1.getAbsolutePath())
        .setGroupAlias(title + "##" + courseId + "##" + sortNo)
        .start();,
请教一下为什么个别视频下载完成后调用(DownloadGroupEntity) entity).getAlias()返回的为"",

**Comment by AriaLyy** [comment]
@hellocl 你的这个是任务组吧，不是单任务，单任务没有alias等东西https://github.com/AriaLyy/Aria/issues/216

**Comment by AriaLyy** [comment]
@BayMikyou 3.3.16

**Comment by hellocl** [comment]
@AriaLyy所有的都是加入任务组下载的,个别大小比较小的视频获取的Alisas都为空,长视频获取正常

**Comment by hellocl** [comment]
@AriaLyy谢谢,我版本升级了一下好了,之前是3.3.14,现在用最新的3.3.16
