### ISSUE TITLE
ftp下载链接已经包含用户名密码，下载不了

### ISSUE THREAD

**Issue by pinixiong** [AriaLyy/Aria#227]
demo提供的地址下载不了（Connection timed out）；自己找的ftp也下载不了，我用迅雷是可以下载的。

**Comment by AriaLyy** [comment]
地址方便提供下吗？邮箱511455842@qq.com

**Comment by pinixiong** [comment]
ftp://ygdy8:ygdy8@yg45.dydytt.net:7183/阳光电影www.ygdy8.com.快手枪手快枪手.BD.720p.国语中字.mkv

**Comment by AriaLyy** [comment]
这种公网地址，ftp资源是会经常被删除的，而迅雷是有自己的资源库的，对应的文件如果被删除，但是资源库中有其他地址，迅雷使用的将是可用地址
