### ISSUE TITLE
提个建议，版本升级问题

### ISSUE THREAD

**Issue by BayMikyou** [AriaLyy/Aria#228]
能否把maven中库的版本升级到V3.4，现在是V3.3.14版本有路径覆盖问题，然后我又升级到了V3.3.3,可是V3.3.3又有getUploadConfig的bug, 我看到了你V3.4分支修复了，可是我现在好像引入不了V3.4。我现在都很迷惑都不知道用哪个版本靠谱

**Comment by AriaLyy** [comment]
3.4 真正开发中
