### ISSUE TITLE
添加扩展字段时，会出现异常。无法获取任务列表。

### ISSUE THREAD

**Issue by for1gumer** [AriaLyy/Aria#229]
期初以为是注解监听不到下载更新的信息。后来查看数据库 DownloadEntity里面，fileName字段为空，其他字段蛮多都是空的。srt字段倒是有添加的扩展字段的值。用的是3.3.16_dev2版本。
    最后，感谢大佬的框架。应了大佬的标题：下载可以很简单

**Comment by AriaLyy** [comment]
是如何操作的？代码方便贴一下吗？

**Comment by AriaLyy** [comment]
3.4 版本已经优化了这个问题
http://aria.laoyuyu.me/aria_doc/api/extend_field.html
