### ISSUE TITLE
运行apk发现的一些问题

### ISSUE THREAD

**Issue by Liar1995** [AriaLyy/Aria#23]
1，运行项目后，在多任务下载的地方，出现过一次crash，具体操作就是正常流程点击的，截图上传不上来，就不传了

2，在多任务下载页面，开始多个任务，任务的暂停和恢复下载感觉并不是很及时，点了以后会等好久才有反应

3，断点下载在快速切换暂停和恢复的时候会重新下载，进度回到0%

4，还有就是有的任务一直处于下载状态却不一直没有进度，并没有开始下载

这些问题希望你能好好看一下，一些真正的用户场景都会存在这些问题。

**Comment by AriaLyy** [comment]
1、能把crash日志发我一下吗？
2、不及时是在恢复下载吗？还是全部都有？
3、我回头好好看下是哪个地方出的问题。
4、能把那个链接发我一下吗？我的邮箱 511455842@qq.com

非常感谢您提出的问题，我将会在最快的时间内解决这些问题。

**Comment by Liar1995** [comment]
nice ~ :thumbsup:
