### ISSUE TITLE
下载地址后面多出一个空格后下载异常

### ISSUE THREAD

**Issue by realicing** [AriaLyy/Aria#230]

**Comment by pinixiong** [comment]
你自己对url做去掉空格处理就好了，你那边ftp可以下载吗

**Comment by realicing** [comment]
没有试过，你给我一下地址试试

**Comment by pinixiong** [comment]
ftp://ygdy8:ygdy8@yg72.dydytt.net:8189/阳光电影www.ygdy8.com.深海狂鲨2.BD.720p.中英双字幕.mkv

**Comment by realicing** [comment]
java.lang.ClassCastException: libcore.net.url.FtpURLConnection cannot be cast to java.net.HttpURLConnection
        at com.arialyy.aria.core.download.downloader.ConnectionHelp.handleConnection(ConnectionHelp.java:57)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:54)
        at java.lang.Thread.run(Thread.java:818)

**Comment by realicing** [comment]
04-17 18:08:54.971 13171-13171/ D/BaseCachePool: 任务【阳光电影www.ygdy8.com.深海狂鲨2.BD.720p.中英双字幕.mkv】进入缓存队列成功
04-17 18:08:54.972 13171-13171/ D/BaseExecutePool: 任务【阳光电影www.ygdy8.com.深海狂鲨2.BD.720p.中英双字幕.mkv】进入执行队列成功
04-17 18:08:54.974 1529-12483/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@11dd2877 attribute=null, token = android.os.BinderProxy@1f47b0a2
04-17 18:08:55.706 2119-12746/com.netease.pnxbwysw.ylwl.hw:PushService E/NGPush_Network: receive exception:java.io.EOFException
04-17 18:08:55.706 2119-12746/com.netease.pnxbwysw.ylwl.hw:PushService W/System.err: java.io.EOFException
04-17 18:08:55.719 2119-12746/com.netease.pnxbwysw.ylwl.hw:PushService W/System.err:     at libcore.io.Streams.readFully(Streams.java:83)
        at java.io.DataInputStream.readShort(DataInputStream.java:152)
        at com.netease.pushservice.Network.run(Network.java)
        at java.lang.Thread.run(Thread.java:818)
04-17 18:08:56.122 13171-13309/ W/AbsFtpInfoThread: 遇到[ECONNREFUSED-连接被服务器拒绝]错误，已没有其他地址，链接失败
04-17 18:08:56.122 13171-13309/ E/AbsFtpInfoThread: 链接失败
04-17 18:08:56.137 13171-13171/ D/AbsTaskQueue: 从执行池删除任务【阳光电影www.ygdy8.com.深海狂鲨2.BD.720p.中英双字幕.mkv】成功
04-17 18:08:56.138 13171-13171/ I/AbsSchedulers: 没有下一任务
04-17 18:08:56.142 13171-13309/ E/AbsFtpInfoThread: 创建FTP客户端失败

**Comment by realicing** [comment]
Aria.download(activity).loadFtp("ftp://ygdy8:ygdy8@yg72.dydytt.net:8189/阳光电影www.ygdy8.com.深海狂鲨2.BD.720p.中英双字幕.mkv")
                                .setFilePath(DIR+ File.separator+"深海狂鲨.mkv").start();

**Comment by AriaLyy** [comment]
这种公网地址，经常会出现网站把资源删除的情况，下不了正常
