### ISSUE TITLE
提个异常情况下的bug

### ISSUE THREAD

**Issue by BayMikyou** [AriaLyy/Aria#234]
我正在下载的过程中，无意中直接杀掉了app了，下次再次进来下载，发现它不能接着上次的下载了，而且是重新下载了。

**Comment by AriaLyy** [comment]
kill app，如果没有保存到记录的话，会从0开始下

**Comment by BayMikyou** [comment]
现在情况就是从0开始下载的

**Comment by BayMikyou** [comment]
这个是你库的内部做了这样的处理吗

**Comment by AriaLyy** [comment]
那就不算bug，kill app 我是不知道的，app自己也无法获取自己被kill~

**Comment by BayMikyou** [comment]
好吧

**Comment by AriaLyy** [comment]
内部的机制是每隔5s保存一次进度

**Comment by BayMikyou** [comment]
OK 还有就是上次问你的 我这边可以直接引用3.3.3的库吗
