### ISSUE TITLE
支持注解的注解类型怎么增加

### ISSUE THREAD

**Issue by pinixiong** [AriaLyy/Aria#235]
目前有Activity、Service、Application、DialogFragment、Fragment、PopupWindow、Dialog。我要增加一个普通类，怎么加呢

**Comment by AriaLyy** [comment]
3.4版本会支持，现在暂时不支持普通类使用注解

**Comment by AriaLyy** [comment]
http://aria.laoyuyu.me/aria_doc/start/any_java.html

3.4版本已支持该功能
