### ISSUE TITLE
@Download.onTaskComplete 有时注解方法会回调多次

### ISSUE THREAD

**Issue by fxinxiu** [AriaLyy/Aria#238]
@Download.onTaskComplete 注解方法有时会回调多次 (v3.4)
但是 我想这个方法应该只回调一次吧！
尝试了很多次  解决不了啊

**Comment by AriaLyy** [comment]
做url验证没有？

**Comment by hallowsman** [comment]
在Service服务里面注解的
 @onTaskComplete
    void taskComplete(DownloadTask task) {
        Constant.log("zx","HeartBeatService Download.onTaskComplete:"+task.getPercent()+"--"+PublicTools.time()+"--"+System.currentTimeMillis());
        Constant.log("zx", "HeartBeatService Download.onTaskComplete BaseApplicationLike.isUploadAppList=" + BaseApplicationLike.isUploadAppList);
        if (BaseApplicationLike.isUploadAppList)
            PublicRequest.onTaskComplte(SampleApplicationContext.context, task);

    }
这个方法在下载单个任务的时候下载成功会多次回调taskComplete方法
