### ISSUE TITLE
3.4 版本报错无法下载 ：“获取流失败”  3.16 版本正常！

### ISSUE THREAD

**Issue by CordyHo** [AriaLyy/Aria#239]
报错：
E/AbsThreadTask: 获取流失败
    ExceptionDetailed:
    ====================Exception Info====================
    java.lang.IllegalStateException: Cannot access request header fields after connection is set
    com.android.okhttp.internal.huc.HttpURLConnectionImpl.getRequestProperties(HttpURLConnectionImpl.java:231)
    com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getRequestProperties(TrackedHttpURLConnection.java:204)
    com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackPreConnect(TrackedHttpURLConnection.java:63)
    com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:354)
    com.android.tools.profiler.support.network.httpurl.HttpURLConnection$.getInputStream(HttpURLConnection$.java:207)
    com.arialyy.aria.core.download.downloader.ConnectionHelp.convertInputStream(ConnectionHelp.java:49)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:77)
    com.arialyy.aria.core.common.AbsThreadTask$2.run(AbsThreadTask.java:249)
    java.util.TimerThread.mainLoop(Timer.java:555)
    java.util.TimerThread.run(Timer.java:505)

-------------------------------------------------------------------
顺便问下怎样禁止lotcat打印下载信息

**Comment by AriaLyy** [comment]
下载地址能提供一下吗？
关闭日志https://aria.laoyuyu.me/aria_doc/start/config.html

**Comment by CordyHo** [comment]
链接 https://dl.genymotion.com/releases/genymotion-2.12.1/genymotion-2.12.1-vbox.exe
试过几个链接了，3.16正常，3.4不行

**Comment by AriaLyy** [comment]
我这四可以下的啊~~
![image](https://user-images.githubusercontent.com/10437293/39953173-8db06e04-55d8-11e8-9599-c58a1d36a0f2.png)
按照异常提示，是获取输入流失败了
![image](https://user-images.githubusercontent.com/10437293/39953176-a4236d44-55d8-11e8-9dd8-d97155ae83a5.png)
检查下网络看看呢

**Comment by CordyHo** [comment]
我这边网络是正常的，我只修改了gradle里的版本，其他代码都没任何改动
implementation 'com.arialyy.aria:aria-core:3.3.16'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.16'
改为
implementation 'com.arialyy.aria:aria-core:3.4'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.4'
然后卸掉APP后重新跑就下载不了，改为3.3.16是正常的，我已经测试过几次了

还有就是 ：3.16版本的 Aria.download(this).getAllNotCompletTask().size() 这个方法判断是否还有没下载完的任务，但就算全部任务下载完了，size() 返回还是大于0的

**Comment by AriaLyy** [comment]
你有没有添加什么header，把启动下载的代码贴出来看看呢

**Comment by AriaLyy** [comment]
神奇啊，我这怎么弄都是可以下载的~~，你手机是啥型号的？

**Comment by AriaLyy** [comment]
3.4版本，你看下http://static.gaoshouyou.com/d/12/0d/7f120f50c80d2e7b8c4ba24ece4f9cdd.apk
这个能不能下

**Comment by CordyHo** [comment]
这个链接是可以下载的，为什么呢？

**Comment by AriaLyy** [comment]
不清楚，你把文件路径改下看看

**Comment by CordyHo** [comment]
这个链接 https://dl.genymotion.com/releases/genymotion-2.12.1/genymotion-2.12.1-vbox.exe 始终下载不了，只能继续用3.16了

**Comment by Chajian** [comment]
我更改了下载链接之后，运行之后就报错了
![a](https://user-images.githubusercontent.com/27548802/40647022-6b62a370-635d-11e8-9f2d-9f1a59fd5ee3.png)

**Comment by Chajian** [comment]
我的也下载不了，我试了很多个链接都无法下载

**Comment by AriaLyy** [comment]
@Chajian 能否提供下下载地址？
