### ISSUE TITLE
重复的ProxyClassCounter

### ISSUE THREAD

**Issue by hnbc8848** [AriaLyy/Aria#240]
## 什么问题
apt生成两个ProxyClassCounter

## 如何复现此问题
如果主App和另一个module都使用了，那么打成release包就会出现问题，提示java.util.zip.ZipException: duplicate entry。

以前只在主App中使用是没有问题，最近整理代码需要拆分出一个module，同时在两个地方使用就出问题了。

**Comment by AriaLyy** [comment]
gradle你是怎样配置的？我测试app和module中都同时导入了Aria，app和module的build中都生成了ProxyClassCounter，打正式包时，并没有出现你说的那个问题。
这问题一般是app和module使用相同的库，但是版本不一致导致的。
https://stackoverflow.com/questions/26966843/java-util-zip-zipexception-duplicate-entry-during-packagealldebugclassesformult

**Comment by hnbc8848** [comment]
# 错误信息
Warning: Exception while processing task java.io.IOException: Can't write 
[/code/demo/app/build/intermediates/transforms/proguard/samsung/release/0.jar] (Can't read [/code/demo/app/build/intermediates/transforms/desugar/samsung/release/12(;;;;;;**.class)] (Can't read [com] (Can't read [arialyy] (Can't read [aria] (Can't read [ProxyClassCounter.class] (Duplicate zip entry [com/arialyy/aria/ProxyClassCounter.class]))))))
:app:transformClassesAndResourcesWithProguardForSamsungRelease FAILED
:app:transformClassesAndResourcesWithProguardForSamsungRelease took 66073ms


# 版本信息
<img width="431" alt="2018-05-17 4 18 23" src="https://user-images.githubusercontent.com/7790233/40165472-a62a427e-59ee-11e8-9208-919cf0c78548.png">

# 配置信息
app配置
<img width="437" alt="2018-05-17 4 21 19" src="https://user-images.githubusercontent.com/7790233/40165515-ca83c410-59ee-11e8-82bc-9ef8e7446b63.png">
module配置
<img width="464" alt="2018-05-17 4 20 44" src="https://user-images.githubusercontent.com/7790233/40165576-eeff4404-59ee-11e8-88fb-e94e406a1933.png">

# 生产代码信息
<img width="419" alt="2018-05-17 4 28 37" src="https://user-images.githubusercontent.com/7790233/40165818-8b7dec72-59ef-11e8-970a-faa0b24bbfc6.png">

<img width="402" alt="2018-05-17 4 28 05" src="https://user-images.githubusercontent.com/7790233/40165808-8360721c-59ef-11e8-8220-645b67146f09.png">

**Comment by AriaLyy** [comment]
3.4.1已经修复了这个bug
