### ISSUE TITLE
上传问题

### ISSUE THREAD

**Issue by for1gumer** [AriaLyy/Aria#241]
## 版本号
~ 3.4

## 什么问题
~上传到局域网的apache服务器，手机提示上传成功。在服务器找不到文件

## 控制台日志
（github的issues支持图片直接粘贴复制）
~05-18 11:19:05.897 14327-14351/com.arialyy.simple D/OpenGLRenderer: DisplayEventReceiver 0x55aa5bd410 latestVsyncEvent 182375306315224
05-18 11:19:05.905 14327-14351/com.arialyy.simple D/OpenGLRenderer: DisplayEventReceiver 0x55aa5bd410 requestNextVsync
05-18 11:19:05.915 14327-14351/com.arialyy.simple D/OpenGLRenderer: DisplayEventReceiver 0x55aa5bd410 latestVsyncEvent 182375323235817
05-18 11:19:06.609 14327-14327/com.arialyy.simple D/HttpUploadActivity: P => 40
05-18 11:19:06.625 14327-14327/com.arialyy.simple D/ProgressBar: setProgress, old = 0, new = 40, max = 100, backtrace = android.widget.ProgressBar.setProgress:1337 com.arialyy.simple.databinding.ActivityUploadBinding.executeBindings:149 android.databinding.ViewDataBinding.executePendingBindings:355 android.databinding.ViewDataBinding$6.run:172 android.databinding.ViewDataBinding$7.doFrame:238 , this = com.arialyy.simple.widget.HorizontalProgressBarWithNumber{39399823 V.ED.... ........ 48,48-845,108 #7f0d008c app:id/pb}
05-18 11:19:06.629 14327-14327/com.arialyy.simple D/ColorDrawable: Color = -328966, canvas = android.view.GLES20RecordingCanvas@3e12f5c1, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@101b8436
05-18 11:19:07.610 14327-14327/com.arialyy.simple D/HttpUploadActivity: P => 79
05-18 11:19:07.621 14327-14327/com.arialyy.simple D/ProgressBar: setProgress, old = 40, new = 79, max = 100, backtrace = android.widget.ProgressBar.setProgress:1337 com.arialyy.simple.databinding.ActivityUploadBinding.executeBindings:149 android.databinding.ViewDataBinding.executePendingBindings:355 android.databinding.ViewDataBinding$6.run:172 android.databinding.ViewDataBinding$7.doFrame:238 , this = com.arialyy.simple.widget.HorizontalProgressBarWithNumber{39399823 V.ED.... ........ 48,48-845,108 #7f0d008c app:id/pb}
05-18 11:19:07.623 14327-14327/com.arialyy.simple D/ColorDrawable: Color = -328966, canvas = android.view.GLES20RecordingCanvas@3e12f5c1, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@101b8436
05-18 11:19:08.149 14327-14981/com.arialyy.simple I/System.out: [OkHttp] sendRequest<<
05-18 11:19:08.288 14327-14981/com.arialyy.simple E/HttpThreadTask: response msg: Not Found，code: 404
05-18 11:19:08.307 14327-14327/com.arialyy.simple D/AbsTaskQueue: 从执行池删除任务【mEELog】成功
05-18 11:19:08.309 14327-14327/com.arialyy.simple I/AbsSchedulers: 没有下一任务
05-18 11:19:08.309 14327-14327/com.arialyy.simple D/HttpUploadActivity: 上传完成
05-18 11:19:08.309 14327-14327/com.arialyy.simple D/HttpUploadActivity: 上传成功返回数据（如果有的话）：
05-18 11:19:08.313 14327-14327/com.arialyy.simple D/ProgressBar: setProgress, old = 79, new = 100, max = 100, backtrace = android.widget.ProgressBar.setProgress:1337 com.arialyy.simple.databinding.ActivityUploadBinding.executeBindings:149 android.databinding.ViewDataBinding.executePendingBindings:355 android.databinding.ViewDataBinding$6.run:172 android.databinding.ViewDataBinding$7.doFrame:238 , this = com.arialyy.simple.widget.HorizontalProgressBarWithNumber{39399823 V.ED.... ........ 48,48-845,108 #7f0d008c app:id/pb}
05-18 11:19:08.316 14327-14327/com.arialyy.simple D/ColorDrawable: Color = -328966, canvas = android.view.GLES20RecordingCanvas@3e12f5c1, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@101b8436
05-18 11:20:05.546 14327-14327/com.arialyy.simple D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{323d131 token=android.os.BinderProxy@3ce33016 {com.arialyy.simple/com.arialyy.simple.upload.HttpUploadActivity}}
05-18 11:20:05.623 14327-14327/com.arialyy.simple D/ActivityThread: ACT-PAUSE_ACTIVITY handled : 0 / android.os.BinderProxy@3ce33016
05-18 11:20:05.631 14327-14327/com.arialyy.simple V/ActivityThread: Finishing stop of ActivityRecord{323d131 token=android.os.BinderProxy@3ce33016 {com.arialyy.simple/com.arialyy.simple.upload.HttpUploadActivity}}: show=true win=com.android.internal.policy.impl.MiuiPhoneWindow@1112d07d
05-18 11:20:05.631 14327-14327/com.arialyy.simple D/ActivityThread: ACT-STOP_ACTIVITY_SHOW handled : 0 / android.os.BinderProxy@3ce33016
05-18 11:20:05.659 14327-14327/com.arialyy.simple V/InputMethodManager: START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{11e40b84 V.E..... R....... 0,0-1080,1920} ic=null tba=android.view.inputmethod.EditorInfo@684fc6c controlFlags=#100

**Comment by AriaLyy** [comment]
上传成功表示客户端流已经发送完成了，至于服务端如何处理流，是否将流写到文件，由服务器自行处理的
