### ISSUE TITLE
请问没有进下载回调大概是什么问题?

### ISSUE THREAD

**Issue by 15766736837** [AriaLyy/Aria#242]
## 版本号
3.4
~ 

## 什么问题
请问没有进下载回调大概是什么问题?
~

## 如何复现此问题
~ 

## 手机型号
荣耀8
~ 

## 控制台日志
（github的issues支持图片直接粘贴复制）
~

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html
