### ISSUE TITLE
版本跟新遇到问题

### ISSUE THREAD

**Issue by kangqin** [AriaLyy/Aria#243]
为什么进行版本跟新我下载的图片要重新下载

**Comment by AriaLyy** [comment]
老版本是哪个版本？

**Comment by kangqin** [comment]
假如我现在的版本是1.0.1,我升级到1.0.2以后，我以前下载的图片要重新下载

**Comment by kangqin** [comment]
帮我看一下

**Comment by AriaLyy** [comment]
什么意思，你用的是1.0.1的下载库，升级到1.0.2的下载库？

**Comment by kangqin** [comment]
我指的我的软件升级的时候，以前的图片要重新升级

**Comment by AriaLyy** [comment]
检查下数据库

**Comment by kangqin** [comment]
具体怎么操作，能给说一下吗

**Comment by kangqin** [comment]
怎么操作，图片才不会重新下载

**Comment by kangqin** [comment]
下载失败，保存路径【/storage/emulated/0/linkun.com.bluetoothscale/app-release-new.apk】已经被其它任务占用，请设置其它保存路径,我还想在这个路径下载，设置那一项
