### ISSUE TITLE
监听下载过程出现进度条停滞问题

### ISSUE THREAD

**Issue by wulileaf** [AriaLyy/Aria#244]
## 版本号
~ 3.4

## 什么问题
~
下载已经执行了，但是在监听下载状态的时候会出现停滞(ps:其实都已经下载完成了，就是进度条不动)

## 如何复现此问题
~ 
在A页面已经执行了下载操作(循环的单任务下载，只传了url和文件名称两个参数)，在B页面获取getTotalTaskList再用DownloadAdapter进行适配的时候会出现只有第一个会正常的现实进度，其余的会出现停滞(其实已经下载完成了)
## 手机型号
~ 
vivoY51A
## 控制台日志
（github的issues支持图片直接粘贴复制）
~

**Comment by AriaLyy** [comment]
3.4.2已经修复了这个问题
