### ISSUE TITLE
有的文件下载失败

### ISSUE THREAD

**Issue by GULIjing** [AriaLyy/Aria#245]
## 版本号
~ 3.4.1

## 什么问题
~下载时候进度超过200%了。而且经常提示下载路径被占用

## 如何复现此问题
~ 
直接下载就出现了
## 手机型号
~ 
三星S4
## 控制台日志
（github的issues支持图片直接粘贴复制）
~
 ExceptionDetailed:
                                                                     ====================Exception Info====================
                                                                     java.net.ProtocolException: unexpected end of stream
                                                                     com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:468)
                                                                     com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:174)
                                                                     java.io.BufferedInputStream.read(BufferedInputStream.java:290)
                                                                     java.io.InputStream.read(InputStream.java:162)
                                                                     com.arialyy.aria.core.download.downloader.HttpThreadTask.readNormal(HttpThreadTask.java:194)
                                                                     com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:100)
                                                                     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     java.lang.Thread.run(Thread.java:818)
                                                                     ===================================================
05-29 17:29:10.377 17801-17801/com.handsmap.mstouch I/文件下载:: [WelcomeActivity]  Line: 360 : 104%
05-29 17:29:11.378 17801-17801/com.handsmap.mstouch I/文件下载:: [WelcomeActivity]  Line: 360 : 104%
05-29 17:29:12.379 17801-17801/com.handsmap.mstouch I/文件下载:: [WelcomeActivity]  Line: 360 : 105%
05-29 17:29:13.380 17801-17801/com.handsmap.mstouch I/文件下载:: [WelcomeActivity]  Line: 360 : 105%
05-29 17:29:14.381 17801-17801/com.handsmap.mstouch I/文件下载:: [WelcomeActivity]  Line: 360 : 106%
05-29 17:29:14.891 17801-18962/com.handsmap.mstouch W/AbsThreadTask: 任务【41c33556-dc4a-4d78-bb76-b9f627f94448.mp4】thread__2__正在重试
05-29 17:29:14.891 17801-18962/com.handsmap.mstouch D/HttpThreadTask: 任务【41c33556-dc4a-4d78-bb76-b9f627f94448.mp4】线程__2__开始下载【开始位置 : 29308466，结束位置：29308466】
05-29 17:29:14.891 17801-18962/com.handsmap.mstouch I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-29 17:29:14.891 17801-18962/com.handsmap.mstouch I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false

**Comment by AriaLyy** [comment]
下载地址能否提供一下？

**Comment by GULIjing** [comment]
http://58.213.157.242:8081/sims_file/rest/v1/file/mshd_touchscreen_ms/guideFile/41c33556-dc4a-4d78-bb76-b9f627f94448.mp4/%E5%85%AB%E5%8D%A6%E6%B4%B2%E5%8D%97%E4%BA%AC%E5%86%9C%E4%B8%9A%E5%98%89%E5%B9%B4%E5%8D%8E0511.mp4

谢谢哈

**Comment by AriaLyy** [comment]
你用 3.4.2_dev1 增加了对进度修正的代码，你测试下看看呢
