### ISSUE TITLE
组下载时，文件不存在的时候如何判断？

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#246]
## 版本号
3.3.10

## 什么问题
在单文件下载时，假设文件url不存在，在@Download.onTaskFail void taskFail(DownloadTask task)事件中，通过task.getTaskEntity()获取到entity，entity中的code( entity.code)显示为404，由此来判定下载文件不存在。
但在组文件下载时，如何判断？
目前测试情况是：url不存在时，并没有触发@DownloadGroup.onTaskFail事件，只是在@DownloadGroup.onTaskRunning()事件中执行，在running中通过task.getTaskEntity()获取entity，entity中的code值为0

## 如何复现此问题
~ 

## 手机型号
~ 

## 控制台日志
（github的issues支持图片直接粘贴复制）
~

**Comment by lyxc** [comment]
@DownloadGroup.onSubTaskRunning void onSubTaskRunning(DownloadGroupTask groupTask, DownloadEntity subEntity) { }

    @DownloadGroup.onSubTaskFail void onSubTaskFail(DownloadGroupTask groupTask, DownloadEntity subEntity) { }

这个子任务的注解没有调用呢？

**Comment by AriaLyy** [comment]
只能查数据库了
```java
Aria.download(this).getDownloadEntity(url)
```
