### ISSUE TITLE
下载文件307重定向，导致文件下载失败

### ISSUE THREAD

**Issue by cutants** [AriaLyy/Aria#248]
## 版本号
~ 3.3.16

## 什么问题
~下载文件307重定向，导致文件下载失败

## 如何复现此问题
~ 
下载地址http://d1.showself.com/download/showself_android-s236279_release.apk
## 手机型号
~ HUAWEI RIO-AL00

## 控制台日志
（github的issues支持图片直接粘贴复制）
~E/HttpFileInfoThread: 任务【http://d1.showself.com/download/showself_android-s236279_release.apk】下载失败，错误码：307

**Comment by AriaLyy** [comment]
你用 3.4.2_dev1 已经修复了这个问题
