### ISSUE TITLE
@DownloadGroup.onTaskResume 不进该回调

### ISSUE THREAD

**Issue by 15766736837** [AriaLyy/Aria#250]
## 版本号
3.4.1

## 什么问题
问题1:@DownloadGroup.onTaskResume 不进该回调,暂停后再次下载不进回调,但是确实有点下载
问题2:最大下载数量设置为1,开启一个组任务下载,再点击下载另一个组任务进入等待,下载中的组任务下载
完成后,等待的组任务不自动下载
## 如何复现此问题
~ 

## 手机型号
~荣耀8

## 控制台日志
（github的issues支持图片直接粘贴复制）
~

**Comment by 15766736837** [comment]
任务组还是存在不进入@DownloadGroup.onTaskResume 回调的问题

**Comment by AriaLyy** [comment]
你用 3.4.2_dev1 测试看看，修复了几个任务组的问题

**Comment by 15766736837** [comment]
太感谢大兄弟,刚才测试了,两个问题都修复了

**Comment by AriaLyy** [comment]
3.4.2已经修复了这个问题
