### ISSUE TITLE
Ftp 下载文件出现崩溃

### ISSUE THREAD

**Issue by scofieldwenwen** [AriaLyy/Aria#251]
## 版本号
v3.4

## 什么问题
1.FtpDownloadActivity 冲突未解决
2.FtpDownloadActivity 下载文件闪退，原因是：端口号未填写导致 urlEntity.hostName 为空

## 如何复现此问题
 在 FtpDownloadActivity  点击下载

## 手机型号
与机型无关

## 控制台日志
06-04 16:53:18.107 23402-23439/com.arialyy.simple E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.arialyy.simple, PID: 23402
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:995)
        at java.util.regex.Matcher.<init>(Matcher.java:174)
        at java.util.regex.Pattern.matcher(Pattern.java:1006)
        at com.arialyy.aria.core.common.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:170)
        at com.arialyy.aria.core.common.AbsFtpInfoThread.run(AbsFtpInfoThread.java:73)
        at java.lang.Thread.run(Thread.java:761)

**Comment by AriaLyy** [comment]
1、冲突是什么冲突？如果是保留路径冲突，需要你自己判断路径
2、 urlEntity.hostName 为空，加上默认的21端口号临时处理吧，这个正则一直没时间弄

**Comment by scofieldwenwen** [comment]
**还有一个问题**：
FTP 下载时，设置文件保存文件夹路径，保存路径是文件夹路径，下载完成的文件名并非FTP服务器上的文件名。如：FTP 服务器的文件名为“debug.apk”，下载完成后文件名为“apk” 且没有后缀名。

看到代码中注释第2点和参数注释有矛盾，如果我想以FTP服务器的文件名来命名，如何获取FTP服务器的文件名。

/**
   * 设置文件保存文件夹路径
   * 关于文件名：
   * 1、如果保存路径是该文件的保存路径，如：/mnt/sdcard/file.zip，则使用路径中的文件名file.zip
   * 2、如果保存路径是文件夹路径，如：/mnt/sdcard/，则使用FTP服务器该文件的文件名
   *
   * @param filePath 路径必须为文件路径，不能为文件夹路径
   */
  public FtpDownloadTarget setFilePath(@NonNull String filePath) {
    mTempFilePath = filePath;
    return this;
  }

**Comment by AriaLyy** [comment]
你的ftp地址能否贴一下？

**Comment by scofieldwenwen** [comment]
tp://192.168.43.118:21/DNMC_v1.0_20180705-debug.apk

**Comment by AriaLyy** [comment]
3.4.2已经修复了这个问题
