### ISSUE TITLE
@DownloadGroup.onWait  不进该回调

### ISSUE THREAD

**Issue by 15766736837** [AriaLyy/Aria#253]
## 版本号
3.4.2_dev1

## 什么问题
1,在wifi断开的时候调用了该代码Aria.download(this).stopAllTask();无效,所以就遍历任务集合,
   调用该方法停止了所有下载中跟等待的任务 
   Aria.download(this).loadGroup(groupTaskList.get(i).getUrls()).stop();   
弹出提示框,咨询用户时候继续下载,用户点击继续下载的话就调用这句代码Aria.download(context).resumeAllTask();   出现了之前等待中的任务暂停掉后,再恢复现在不进等待回调

## 手机型号
荣耀8

## 控制台日志
（github的issues支持图片直接粘贴复制）
~

**Comment by 15766736837** [comment]
请问这个问题有修改好了吗?

**Comment by AriaLyy** [comment]
嗯，使用3.4.2_dev2

**Comment by 15766736837** [comment]
恩恩,刚刚我在测试,还是发现有一个任务下载完后MD5判断了完整性,是不一致的,重新下载后又是一致的了

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41186991-81a3a5ac-6bd3-11e8-8999-820c971c6bf9.png)
这是我的配置麻烦您看下

**Comment by AriaLyy** [comment]
3.4.2_dev2版本？控制台全部日志发我一下

**Comment by 15766736837** [comment]
是3.4.2_dev1的,日志稍等下,我在测试看看

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41187121-b888f8b8-6bd5-11e8-96b6-87fbf7e1c053.png)
刚刚还发现了这个问题,有一个任务回调回来的进度一直是0,可是在本地路径里面的文件大小一直有在增加

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41187164-4cecb756-6bd6-11e8-83e7-ee522d5be9db.png)

**Comment by AriaLyy** [comment]
3.4.2_dev2的？

**Comment by AriaLyy** [comment]
具体是怎么操作的？

**Comment by 15766736837** [comment]
3.4.2_dev2的,有点击过暂停下载,跟恢复下载,让任务直接下载完成倒是不会出现这种情况

**Comment by AriaLyy** [comment]
那下载完成后，进度和回调正确吗？

**Comment by 15766736837** [comment]
就是下载完的文件跟服务器上的文件大小不一致

**Comment by AriaLyy** [comment]
地址能提供下不？我用我的地址重现不出来~~~

**Comment by 15766736837** [comment]
http://120.79.135.3/oddvr/api/tgameinfo/list?page=1&limit=99   
GET 请求  地址的字段是gameUrl  是apk跟obb拼接成的

**Comment by AriaLyy** [comment]
3.4.3已经修复了改问题
