### ISSUE TITLE
防止抓包问题

### ISSUE THREAD

**Issue by 425540302** [AriaLyy/Aria#254]
求大神下次更新的时候，在Aria.download(context)
                        .setproxy(Proxy.NO_PROXY)
                        .start();
加个 .setproxy(Proxy.NO_PROXY)方法，为了防止代理抓包的，

HttpURLConnection上的体现：urlConnection = (HttpURLConnection) url.openConnection(Proxy.NO_PROXY);  

OkHttpClient上的体现：OkHttpClient client = new OkHttpClient().newBuilder().proxy(Proxy.NO_PROXY).build（）;

**Comment by AriaLyy** [comment]
3.4.2_dev2添加了`setUrlProxy`方法，支持设置proxy
```java

    Aria.download(this)
        .load(url)
        //.addHeader("Accept-Encoding", "gzip")
        .setRequestMode(RequestEnum.GET)
        .setUrlProxy(Proxy.NO_PROXY)
        .setFilePath(Environment.getExternalStorageDirectory().getPath() + "/abcds.exe")
        //.resetState()
        .start();
```
