### ISSUE TITLE
unregister 导致的问题

### ISSUE THREAD

**Issue by liudf731098327** [AriaLyy/Aria#257]
我在 Activity 中下载文件，退出的时候执行了 unregister，再次进入这个 Activity 点击下载，发现我在 @Download.onTaskRunning 和 @Download.onTaskComplete 的方法中已经初始化的控件会报 【 空指针异常 】
我把 unregister 去掉，倒不会报错，请问下是什么原因呢

**Comment by AriaLyy** [comment]
你是在onStop中 unregister的？

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/start/any_java.html?h=unregister
这个的？
这个的话是有歧义，应该是在module的java类中销毁

**Comment by liudf731098327** [comment]
噢噢，明白了~
