### ISSUE TITLE
任务一直在下载,可是回调回来的进度为0

### ISSUE THREAD

**Issue by 15766736837** [AriaLyy/Aria#258]
## 版本号
3.4.2
3.4.2_dev2

## 什么问题
![image](https://user-images.githubusercontent.com/23132489/41341031-49a93ba2-6f2b-11e8-8ce5-ded5d043c333.png)
任务一直在下载,可是回调回来的进度为0

## 如何复现此问题
偶显,下载34个任务出现4个

## 手机型号
荣耀8

## 控制台日志

~

**Comment by 15766736837** [comment]
其实有在下载,就是回调回来的进度为0,下载完成了也会进入成功回调,就是进度为0

**Comment by 15766736837** [comment]
版本是:3.4.2_dev4  跟 3.4.2 之前说错了

**Comment by 15766736837** [comment]
刚刚发现,这个问题在下载出现异常的时候会出现,比如4G切换成WiFi的时候,就会这样,回调回来的进度是0,实际上是有在下载的

**Comment by AriaLyy** [comment]
你是在哪打印的进度？代码贴一下看看呢

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41386389-ce42fc94-6fb3-11e8-95e3-8eaab0f083cf.png)

**Comment by 15766736837** [comment]
之前好像并你没有这个问题呢

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41386676-3f9b7b0e-6fb5-11e8-9646-04e0358dc564.png)
![image](https://user-images.githubusercontent.com/23132489/41386685-45986aa8-6fb5-11e8-97c4-936065fce77e.png)
出现异常后回调回来的进度就开始是0了,

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41386795-f69be64a-6fb5-11e8-9425-3559a5e10c1c.png)

**Comment by AriaLyy** [comment]
有没有“任务重试”一类的log打印？

**Comment by 15766736837** [comment]
有啊,看第二个图

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41387987-6d898af4-6fbc-11e8-8fe0-4224ad57412f.png)

**Comment by AriaLyy** [comment]
3.4.3_dev2 ，用这个，重试时把计数器重开了

**Comment by 15766736837** [comment]
好的,感谢,大神那个我有个需求是WiFi断开变成4g的时候要把所有任务暂停,然后弹出框提问是都使用移动流量下载,是的话就全部重启,我们这个框架的队列好像有点问题呢,您有时间可以帮忙看下吗?

**Comment by AriaLyy** [comment]
你可以自己监听网络变化的，
[停止所有任务](https://aria.laoyuyu.me/aria_doc/api/task_handle.html#%E5%81%9C%E6%AD%A2%E6%89%80%E6%9C%89%E6%AD%A3%E5%9C%A8%E4%B8%8B%E8%BD%BD%E7%9A%84%E4%BB%BB%E5%8A%A1)

[恢复所有任务](https://aria.laoyuyu.me/aria_doc/api/task_handle.html#%E6%81%A2%E5%A4%8D%E6%89%80%E6%9C%89%E5%81%9C%E6%AD%A2%E7%9A%84%E4%BB%BB%E5%8A%A1)

**Comment by 15766736837** [comment]
对,就是停止所有任务跟恢复所有任务 这个两个方法,你可以试试看,好像逻辑有点问题,您开多几个任务,然后观察下等待的任务全部暂停后跟全部恢复下载的效果

**Comment by AriaLyy** [comment]
恢复的顺序？

**Comment by 15766736837** [comment]
是呢,还有就是看下等待的任务还能否继续下载

**Comment by 15766736837** [comment]
![image](https://user-images.githubusercontent.com/23132489/41390297-99afe366-6fc7-11e8-95d5-184c37252c39.png)

3.4.3_dev2用您这个版本的,所有下载任务都不进入回调了

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/start/any_java.html

调用下init

**Comment by 15766736837** [comment]
有调用呢

**Comment by AriaLyy** [comment]
用 3.4.3_dev3

**Comment by 15766736837** [comment]
好的,我试下
