### ISSUE TITLE
fragment 任务组回调 

### ISSUE THREAD

**Issue by Carlxx** [AriaLyy/Aria#260]
## 版本号
~ 3.4.2

## 什么问题
~回调不没有响应  demo 里的下载回调也不可用

## 如何复现此问题
~ 

## 手机型号
~ 

## 控制台日志
（github的issues支持图片直接粘贴复制）
~

**Comment by AriaLyy** [comment]
使用`3.4.3`版本
在fragment中将`download(getContext())`改为`downloa(this)`
