### ISSUE TITLE
错误码453

### ISSUE THREAD

**Issue by Average77** [AriaLyy/Aria#263]
## 版本号
3.4.4

## 什么问题

需要添加header的视频下载，下载失败，错误码453
## 如何复现此问题
 .addHeader("headers", "Referer: http://www.bilibili.com/")
                                                                        .addHeader("user-agent", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36")

## 控制台日志（越完整越好）
 任务【http://cn-hbsjz-cmcc-v-03.acgvideo.com/upgcxcode/63/82/5108263/5108263-1-80.flv?expires=1530087000&platform=pc&ssig=lRD5B1-58jBAGuyUf6VLwA&oi=3746029570&nfa=BpfiWF+i4mNW8KzjZFHzBQ==&dynamic=1&hfa=2030045662&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=a576dbff07d54c1dab7d490247812f2c&nfc=1】下载失败，错误码：453

**Comment by Average77** [comment]
链接失效很快的

**Comment by AriaLyy** [comment]
这是你们服务器自己返回的错误码吧~~
我用浏览器打开也是453错误...

**Comment by Average77** [comment]
可是可以播放诶。 @AriaLyy

**Comment by Average77** [comment]
话说视频任务多一点的时候，打开下载列表我这边应用就超级卡，是需要在什么地方回收的吗

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/41961870-2e567954-7a26-11e8-9cf1-1e5527801ec3.png)
将队列大小调成2，减少同一时间IO的使用

**Comment by Average77** [comment]
失效了，我再给您弄一个链接 [图片]http://cn-hbsjz-cmcc-v-03.acgvideo.com/upgcxcode/63/82/5108263/5108263-1-80.flv?expires=1530095400&platform=pc&ssig=DuhaM81zdkyiMyeArhj4Mg&oi=3746029570&nfa=BpfiWF+i4mNW8KzjZFHzBQ==&dynamic=1&hfa=2030071308&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=e51ea199320f41dd9422578ffbc6fdb8&nfc=1    失效很快的

**Comment by Average77** [comment]
![tim 20180627163341](https://user-images.githubusercontent.com/28084588/41962553-eb70b01c-7a27-11e8-87a5-854b4f3b4bfb.png)

**Comment by Average77** [comment]
![tim 20180627163715](https://user-images.githubusercontent.com/28084588/41962752-6da29082-7a28-11e8-85bd-4b7162cf61fc.png)
不加header的时候就是453 
![tim 20180627163912](https://user-images.githubusercontent.com/28084588/41962841-a616d0a4-7a28-11e8-8233-d60138b2bd32.png)
可这个是已经加了

**Comment by Average77** [comment]
http://cn-hbsjz-cmcc-v-03.acgvideo.com/upgcxcode/63/82/5108263/5108263-1-80.flv?expires=1530096000&platform=pc&ssig=CpEShAQ5m-sREy_1-eZFrg&oi=3746029570&nfa=BpfiWF+i4mNW8KzjZFHzBQ==&dynamic=1&hfa=2030070935&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=b0bdc2c7d4c140a1bc89bc7537e618a2&nfc=1  @AriaLyy

**Comment by AriaLyy** [comment]
看你发的那几张图，加不加header都是453啊~~~
[http标准协议状态码](https://zh.wikipedia.org/wiki/HTTP%E7%8A%B6%E6%80%81%E7%A0%81)也没有453的状态码，这个错误码你们后台服务器的定义是什么？

**Comment by Average77** [comment]
啊，难受，没注意到。 视频不是我们后台的，公司用的b站的源_(:з」∠)_我也没有办法啊，我只是个小职员啊QAQ，现在又非要让下载TAT

**Comment by AriaLyy** [comment]
你那边浏览器能不能下载？我postman模拟器请求，都是453错误~~

**Comment by Average77** [comment]
我用浏览器没法加header，但是用ijk播放器加了header可以播放

**Comment by AriaLyy** [comment]
你地址是怎么来的？

**Comment by Average77** [comment]
第三方解析出来的，方便加一下QQ什么的吗，我给您发个解析的demo

**Comment by AriaLyy** [comment]
加群吧：524329160

**Comment by AriaLyy** [comment]
添加的头错误
bilibili视频流下载需要添加的头是
```
.addHeader("Referer", "http://www.bilibili.com/")
```
而不是
```
.addHeader("headers", "Referer: http://www.bilibili.com/")
```
