### ISSUE TITLE
下载 apk 后偶尔会出现解析包错误

### ISSUE THREAD

**Issue by liudf731098327** [AriaLyy/Aria#265]
如题，部分手机偶尔出现这个问题，一直找不到原因。希望给个建议。。

**Comment by AriaLyy** [comment]
使用3.4.4版本，使用单线程下载或打开分块下载
如果还是有问题的话，在完成回调中检查下文件md5和服务器端的md5是否一致，不一致的话重新下载

**Comment by liudf731098327** [comment]
最后改成 3.2.0 版本才解决。。刚好以前的 app 用的这个版本。。。

**Comment by AriaLyy** [comment]
嗯，昨天发现分块那有点问题，最新的代码已经修复了分块的问题。
建议使用单线程
