### ISSUE TITLE
 停止命令执行失败，【调度器中没有该任务】

### ISSUE THREAD

**Issue by dodan200** [AriaLyy/Aria#266]
## 版本号  

3.4.3

## 什么问题    

点击暂停或则继续下载时报如下错误：
    “   停止命令执行失败，【调度器中没有该任务】”

## 如何复现此问题

任务池中总共有3个下载任务，切换网络，其中第二个下载任务是暂停。再次点击恢复下载时报错。

## 手机型号
华为小米机都有这个问题。

**Comment by AriaLyy** [comment]
用3.4.4版本，这个是以前版本连接失败的一个错误

**Comment by dodan200** [comment]
好的，谢谢

**Comment by AriaLyy** [comment]
我重新上传一个版本，这个是我调试的时候，把一行关键代码屏蔽了~~~

**Comment by AriaLyy** [comment]
或者你用3.4.4_dev4
