### ISSUE TITLE
下载进度会重置为0。

### ISSUE THREAD

**Issue by dodan200** [AriaLyy/Aria#269]
## 版本号  
3.4.5  

## 什么问题
下载进度会重置为0。

## 如何复现此问题
在下载中的任务（下载了一部分时），重复点击暂停，多次后，点击为下载状态时。下载进度会重置为0。重新开始下载。（生产包，或者测试包都存在）

## 手机型号
小米，华为。

## 控制台日志（越完整越好）
  /HttpThreadTask: 该下载不支持断点

**Comment by AriaLyy** [comment]
不支持断点续传的下载地址，是没有暂停功能的

**Comment by dodan200** [comment]
支持HTTP\FTP断点续传、多任务自动调度  ，标题上有，我就用这个库了。看来要临时去切库了。.....

**Comment by dodan200** [comment]
有什么其他下载库支持断点续传的嘛？推荐个

**Comment by AriaLyy** [comment]
支不支持断点是服务端说的算的
