### ISSUE TITLE
1，没有加入内存的判断，当内存不够时会继续下载，导致程序崩溃 2，当我在A界面开始下载，B这界面这时候是关闭的状态，但是回调了注解方法(下载进度等状态)，这样是对的么？

### ISSUE THREAD

**Issue by woshiyizhijiao** [AriaLyy/Aria#272]
## 版本号
3.4.7

1，没有加入内存的判断，当内存不够时会继续下载，导致程序崩溃

2，当我在A界面开始下载，B这界面这时候是关闭的状态，但是回调了注解方法(下载进度等状态)，这样是对的么？

3，能否加入对wifi的判断

**Comment by AriaLyy** [comment]
1、内存判断下个版本会增加
2、这个不对，确定进度日志是在B界面打印的吗？控制台他有什么日志吗？
3、这个可执行判断，然后使用`stopAll`和`resumeAll`来控制所有任务的暂停和启动

**Comment by woshiyizhijiao** [comment]
第二个问题，B界面确实是关闭状态，但是回调了下载中的方法。我在B界面使用了Aria.download(this).register();
