### ISSUE TITLE
组合任务,有时候下载失败后就不会重试再下载了

### ISSUE THREAD

**Issue by 15766736837** [AriaLyy/Aria#277]
## 版本号
3.4.6_dev3

## 什么问题
![image](https://user-images.githubusercontent.com/23132489/43034137-25b3199c-8d09-11e8-9d1f-5b9111cf0990.png)

组合任务,有时候下载失败后就不会重试再下载了

**Comment by 15766736837** [comment]
设置了重试次数为60,间隔3s,

**Comment by AriaLyy** [comment]
感谢反馈，`3.5`版本修复了这个问题
