### ISSUE TITLE
HTTP链接，下载失败，下载长度超出文件大小

### ISSUE THREAD

**Issue by pinixiong** [AriaLyy/Aria#278]
## 版本号
3.4.8

## 什么问题
单任务下载：HTTP链接，下载失败，下载长度超出文件大小

## 如何复现此问题
链接：http://58.213.157.242:8081/sims_file/rest/v1/file/mshd_touchscreen_ms/guideFile/41c33556-dc4a-4d78-bb76-b9f627f94448.mp4/%E5%85%AB%E5%8D%A6%E6%B4%B2%E5%8D%97%E4%BA%AC%E5%86%9C%E4%B8%9A%E5%98%89%E5%B9%B4%E5%8D%8E0511.mp4
此链接每次调用单任务的HTTP下载，都会出现此问题。

## 控制台日志（越完整越好）
07-23 15:00:01.435 4998-12479/ D/AbsThreadTask: currentLocation=29310845, fileSize=29308466
07-23 15:00:01.435 4998-12479/ E/AbsThreadTask: 下载失败，下载长度超出文件大小
07-23 15:00:01.447 4998-12479/ D/StateConstance: fail_num=1; start_thread_num=3; complete_num=0
07-23 15:00:01.469 4998-12478/ D/AbsThreadTask: currentLocation=29310845, fileSize=29308466
07-23 15:00:01.469 4998-12478/ E/AbsThreadTask: 下载失败，下载长度超出文件大小
07-23 15:00:01.490 4998-12478/ D/StateConstance: fail_num=2; start_thread_num=3; complete_num=0
07-23 15:00:01.490 4998-12480/ D/AbsThreadTask: currentLocation=29310845, fileSize=29308466
07-23 15:00:01.490 4998-12480/ E/AbsThreadTask: 下载失败，下载长度超出文件大小
07-23 15:00:01.500 4998-12480/ D/StateConstance: fail_num=3; start_thread_num=3; complete_num=0
07-23 15:00:01.500 4998-12480/ E/AbsThreadTask: 任务【%E5%85%AB%E5%8D%A6%E6%B4%B2%E5%8D%97%E4%BA%AC%E5%86%9C%E4%B8%9A%E5%98%89%E5%B9%B4%E5%8D%8E0511.mp4】执行失败
07-23 15:00:01.525 4998-4998/ D/AbsTaskQueue: 从执行池删除任务【%E5%85%AB%E5%8D%A6%E6%B4%B2%E5%8D%97%E4%BA%AC%E5%86%9C%E4%B8%9A%E5%98%89%E5%B9%B4%E5%8D%8E0511.mp4】成功
07-23 15:00:01.525 4998-4998/ D/AbsSchedulers: fail_next
07-23 15:00:01.527 4998-4998/ I/AbsSchedulers: 没有下一任务

**Comment by AriaLyy** [comment]
使用`3.4.11`版本
