### ISSUE TITLE
ftp下载失败没有走onTaskFail回调

### ISSUE THREAD

**Issue by pinixiong** [AriaLyy/Aria#280]
## 版本号
3.4.8

## 什么问题
ftp下载：
1：ftp连不上服务器，任务失败，没有抛出onTaskFail
2：ftp连上服务器，但文件不存在，任务失败，没有抛出onTaskFail
任务创建初期失败，感觉也应该有个失败回调通知，这样应该比较好吧。
## 如何复现此问题
1：连不上服务器链接：ftp://ygdy8:ygdy8@yg72.dydytt.net:7046/阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4
2：文件不存在链接：ftp://d:d@a.dygodj8.com:12311/[电影天堂www.dy2018.com]女黑手党BD中英双字.mkv

## 控制台日志（越完整越好）
D/BaseCachePool: 任务【[电影天堂www.dy2018.com]女黑手党BD中英双字.mkv】进入缓存队列成功
D/BaseExecutePool: 任务【[电影天堂www.dy2018.com]女黑手党BD中英双字.mkv】进入执行队列成功
D/AriaDownTaskManager: [main(1): AriaDownTaskManager.java:206] - onPre ==> [电影天堂www.dy2018.com]女黑手党BD中英双字.mkv
I/AbsFtpInfoThread: FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码
E/AbsFtpInfoThread: 文件不存在，任务链接【ftp://d:d@a.dygodj8.com:12311/[电影天堂www.dy2018.com]女黑手党BD中英双字.mkv】，remotePath：/[µçÓ°ÌìÌÃwww.dy2018.com]Å®ºÚÊÖµ³BDÖÐÓ¢Ë«×Ö.mkv
D/AbsTaskQueue: 从执行池删除任务【[电影天堂www.dy2018.com]女黑手党BD中英双字.mkv】成功
D/AbsSchedulers: fail_next
I/AbsSchedulers: 没有下一任务
I/AbsFtpInfoThread: 路径【/[电影天堂www.dy2018.com]女黑手党BD中英双字.mkv】下的文件列表 ===================================
D/AbsFtpInfoThread: -rw-rw-rw-   1 user     group      126958 Jul 26 16:33 123.rar
D/AbsFtpInfoThread: d---------   1 user     group           0 Jul 19 00:38 Recycled
D/AbsFtpInfoThread: drw-rw-rw-   1 user     group           0 Jan  1  2003 TEMP
D/AbsFtpInfoThread: -rw-rw-rw-   1 user     group    1652573885 Jul 25 16:17 [电影天堂www.dy2018.com]女黑手党BD中英双字.mp4
D/AbsFtpInfoThread: -rw-rw-rw-   1 user     group    1077688251 Jul 26 16:21 [电影天堂www.dy2018.com]烟花BD日语中字.mp4
I/AbsFtpInfoThread: ================================= --end-- ===================================
D/rabbitMqReceiver: [main(1): RemoteDownService.java:296] - operation_code: download_management_new_pre_download_file
D/rabbitMqReceiver: [main(1): RemoteDownService.java:297] - content: {"operation_code":"download_management_new_pre_download_file","op_params":{"source_url":"ftp:\/\/ygdy8:ygdy8@yg72.dydytt.net:7046\/\u9633\u5149\u7535\u5f71www.ygdy8.com.\u5c0f\u516c\u4e3b\u827e\u8587\u62c9\u4e0e\u795e\u79d8\u738b\u56fd.HD.1080p.\u56fd\u8bed\u4e2d\u5b57.mp4","task_id":"bbe99723b380817503995b7ba787ae6c","user_name":"Blackwing"}}
D/startDownTask: [main(1): AriaDownTaskManager.java:92] - UserName:ygdy8
D/startDownTask: [main(1): AriaDownTaskManager.java:93] - Password:ygdy8
D/CommonUtil: scheme = ftp, user = ygdy8:ygdy8, host = yg72.dydytt.net, port = 7046, path = /阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4
D/BaseCachePool: 任务【阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4】进入缓存队列成功
D/BaseExecutePool: 任务【阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4】进入执行队列成功
D/AriaDownTaskManager: [main(1): AriaDownTaskManager.java:206] - onPre ==> 阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4
W/AbsFtpInfoThread: 遇到[ECONNREFUSED-连接被服务器拒绝]错误，已没有其他地址，链接失败
E/AbsFtpInfoThread: 链接失败
D/AbsTaskQueue: 从执行池删除任务【阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4】成功
D/AbsSchedulers: fail_next
I/AbsSchedulers: 没有下一任务
E/AbsFtpInfoThread: 任务【ftp://ygdy8:ygdy8@yg72.dydytt.net:7046/阳光电影www.ygdy8.com.小公主艾薇拉与神秘王国.HD.1080p.国语中字.mp4】失败

**Comment by yy1300326388** [comment]
没有网络启动下载任务，也不走 onTaskFail ，相同的问题怎处理呢？
<img width="853" alt="image" src="https://user-images.githubusercontent.com/8764899/158117438-5a29c810-75a2-4827-91a8-bfdf1b285b3a.png">
