### ISSUE TITLE
@Download.onTaskComplete 有时注解方法会回调多次

### ISSUE THREAD

**Issue by 506967734** [AriaLyy/Aria#283]
compile 'com.arialyy.aria:aria-core:3.4.8'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.4.8'

MainApplication中增加Aria.init(this);
BaseActivity中onCreate()增加 Aria.download(this).register();onDestroy()增加Aria.download(this).unRegister();
同时还有一个下载方法
/**
     * 下载
     * @param url  资源路径
     * @param path 本地路径
     */
    public void ariaDownload(String url, String path) {
        DebugLog.d("ariaDownload------>");
        Aria.download(this)
                .load(url)     //读取下载地址
                .setFilePath(path)    //设置文件保存的完整路径
                .start();   //启动下载
    }

AActivity集成BaseActivity
AActivity中的方法如下：
 @Download.onPre
  void onPre(DownloadTask task) {
  }
 @Download.onTaskFail
    void taskFail(DownloadTask task) {
  }
  @Download.onTaskComplete
   void taskComplete(DownloadTask task) {
      DebugLog.d("taskComplete----->" + task.getDownloadPath());
}

流程：
启动AActivity，点击下载，调用ariaDownload(),下载成功打印taskComplete----->"一次
关闭AActivity后，再次启动AActivity，点击下载，调用ariaDownload()，下载成功打印taskComplete----->"有时候会有两次

08-01 09:21:45.365 25722-25722/com.geely.GassistantSubDlr D/BeforeNonTerritoryCreateActivity.java: [taskComplete:785]taskComplete----->/storage/emulated/0/gassistantSubDlr/picture_1533086504651.jpg
08-01 09:21:45.366 25722-25722/com.geely.GassistantSubDlr D/BeforeNonTerritoryCreateActivity.java: [taskComplete:785]taskComplete----->/storage/emulated/0/gassistantSubDlr/picture_1533086504651.jpg
    [taskComplete:785]taskComplete----->/storage/emulated/0/gassistantSubDlr/picture_1533086504651.jpg
08-01 09:21:45.367 25722-25722/com.geely.GassistantSubDlr D/BeforeNonTerritoryCreateActivity.java: [taskComplete:785]taskComplete----->/storage/emulated/0/gassistantSubDlr/picture_1533086504651.jpg

**Comment by AriaLyy** [comment]
感谢反馈，`3.5`版本修复了这个问题
