### ISSUE TITLE
Cannot Configuration for Aria Core 

### ISSUE THREAD

**Issue by DeevD** [AriaLyy/Aria#286]
Aria.get(fragmentActivity).downloadConfig.setMaxTaskNum(2)

when i wrote the above code i got these error  in Kotlin Code
' Cannot access 'Configuration' : it is a public/*package*/ com.arialyy.aria.core' bro .. Can you explain me thank

**Comment by DeevD** [comment]
it not work bro appear error like  above

**Comment by AriaLyy** [comment]
`3.4.12` already fix the bug

**Comment by DeevD** [comment]
thank bro !! great library
