### ISSUE TITLE
 调用Aria.download(this).unRegister()，还是会回调onTaskRunning等状态更新方法

### ISSUE THREAD

**Issue by wuxusheng** [AriaLyy/Aria#288]
## 版本号
compile 'com.arialyy.aria:aria-core:3.4.9'
 annotationProcessor 'com.arialyy.aria:aria-compiler:3.4.9'
## 什么问题
首先打开一个activity调用Aria.download(this).register();注册，并添加onTaskRunning等状态更新方法，然后启动一个新的activity，在activity又调用了 Aria.download(this).register()，并添加onTaskRunning等状态更新方法，然后在此activity启动单任务下载，结果发现任务回调不光走了第二个activity中的onTaskRunning回调方法，还走了上一个activity中的onTaskRunning方法。

结论：多个界面（activity或fragment）调用Aria.download(this).register()，其中一个地方启动下载，则所有注册的界面的回调方法都会走。调用Aria.download(this).unRegister();也不管用

解决办法：调试代码发现，源码中DownloadReceiver类中的unRegisterListener()方法中的
    Set<String> dCounter = ProxyHelper.getInstance().downloadCounter;
                Set<String> dgCounter = ProxyHelper.getInstance().downloadGroupCounter;
                Set<String> dgsCounter = ProxyHelper.getInstance().downloadGroupSubCounter;
                if (dCounter != null && dCounter.contains(this.targetName)) {
                    DownloadSchedulers.getInstance().unRegister(obj);
                }
 DownloadSchedulers.getInstance().unRegister(obj);此行代码没有执行导致没有注销掉回调。

目前处理注销我需要调用Aria.download(this).unRegister();和 DownloadSchedulers.getInstance().unRegister(obj);两个方法才行

希望作者可以修复这个问题

## 手机型号
智能设备

**Comment by AriaLyy** [comment]
感谢反馈，3.4.11 已经修复了这个bug

**Comment by wuxusheng** [comment]
好的，建议作者不要再往框架加功能了，如果功能太多，api不断增多，后期维护很麻烦，怕力不从心，小建议哈

**Comment by AriaLyy** [comment]
→_→
