### ISSUE TITLE
下载链接问题

### ISSUE THREAD

**Issue by mansemn6** [AriaLyy/Aria#291]
3.4.13 下载图片的时候链接地址加了1导致下载失败
Aria/Aria/src/main/java/com/arialyy/aria/core/download/downloader/HttpThreadTask.java
URL url = new URL(CommonUtil.convertUrl(mConfig.URL + 1));

**Comment by AriaLyy** [comment]
感谢反馈，打包时忘记去掉这个测试代码了，3,4,14已经上传

**Comment by pinixiong** [comment]
你好，为什么我这边看到的最新版本是3.412，找不到3.414呢
