### ISSUE TITLE
downloadActivity LeakCanary leaked

### ISSUE THREAD

**Issue by tmxd09887** [AriaLyy/Aria#293]
## 版本号
3.4.9

## 什么问题
downloadActivity LeakCanary leaked内测泄露

## 如何复现此问题
每次进入这个activity LeakCanary 都报leaked，抱歉错误日志，看不懂。谢谢帮忙看看。

## 手机型号
google pixel2 XL 8.0

## 控制台日志（越完整越好）
* com.yesModule.downPackage.module.download.downloadActivity has leaked:
* static DownloadSchedulers.!(INSTANCE)!
* ↳ DownloadSchedulers.!(mObservers)!
* ↳ ConcurrentHashMap.!(table)!
* ↳ array ConcurrentHashMap$Node[].!([2])!
* ↳ ConcurrentHashMap$Node.!(next)!
* ↳ ConcurrentHashMap$Node.!(val)!
* ↳ downloadActivity$$DownloadListenerProxy.!(obj)!
* ↳ downloadActivity

**Comment by AriaLyy** [comment]
使用
```
3.4.12
```
最新版本

**Comment by tmxd09887** [comment]
抱歉，前面版本号写错了，应该是3.4.9，现在重新编辑了

我用了3.4.12，再试试
