### ISSUE TITLE
HTTP上传  URL 应该传什么？

### ISSUE THREAD

**Issue by ljk761626336** [AriaLyy/Aria#294]
## 控制台日志（越完整越好）
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isShipBuild true
I/System.out: (HTTPLog)-Thread-24791-364151967: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
D/UploadDialog: upload start，md5：9d9e67d947c251b924fbd05692ba8af8
D/UploadDialog: P => 1
D/UploadDialog: P => 1
D/UploadDialog: P => 4
I/art: Background sticky concurrent mark sweep GC freed 236(7KB) AllocSpace objects, 40(2MB) LOS objects, 15% free, 12MB/15MB, paused 15.719ms total 47.627ms
D/UploadDialog: P => 11
D/UploadDialog: P => 18
D/UploadDialog: P => 23
D/UploadDialog: P => 29
D/UploadDialog: P => 31
D/UploadDialog: P => 34
D/UploadDialog: P => 40
D/UploadDialog: P => 45
I/art: Background sticky concurrent mark sweep GC freed 365(9KB) AllocSpace objects, 138(8MB) LOS objects, 39% free, 12MB/20MB, paused 5.655ms total 39.286ms
D/UploadDialog: P => 51
D/UploadDialog: P => 55
D/UploadDialog: P => 61
D/UploadDialog: P => 67
I/art: Background sticky concurrent mark sweep GC freed 348(9KB) AllocSpace objects, 140(8MB) LOS objects, 39% free, 12MB/20MB, paused 5.680ms total 43.797ms
D/UploadDialog: P => 71
D/UploadDialog: P => 76
D/UploadDialog: P => 79
D/UploadDialog: P => 82
D/UploadDialog: P => 86
D/UploadDialog: P => 90
I/art: Background sticky concurrent mark sweep GC freed 373(10KB) AllocSpace objects, 134(8MB) LOS objects, 38% free, 12MB/20MB, paused 5.352ms total 39.998ms
D/UploadDialog: P => 96
E/HttpThreadTask: response msg: Not Found，code: 404
D/AbsTaskQueue: 从执行池删除任务【广东省-始兴县180816104245498.db】成功
D/AbsSchedulers: complete_next
I/AbsSchedulers: 没有下一任务
D/UploadDialog: 上传完成
D/UploadDialog: 上传成功返回数据（如果有的话）：

**Comment by ljk761626336** [comment]
到目标服务器查看没有文件

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/upload/http_normal.html

服务器读取文件的key

**Comment by ljk761626336** [comment]
第一次使用 这个key 怎么来  个人随便设置吗？

**Comment by ljk761626336** [comment]
有demo 吗？

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/tree/master/app/src/main/java/com/arialyy/simple/upload

**Comment by ljk761626336** [comment]
这个demo 里面也没有设置key
