### ISSUE TITLE
切换静态ip地址引起ontaskrunning回调部分进度

### ISSUE THREAD

**Issue by wuxusheng** [AriaLyy/Aria#295]
## 版本号
3.4.9

## 什么问题
大神，我又来问问题了哈哈，问题是我这边有个android设备，非手机，我在多次切换静态ip地址之后，启动一个单线程下载，然后发现，进度条回调了一部分不走了，即ontaskrunning方法回调了部分（可能是百分之70也可能是30 等等），但是其实还在下载，等下完之后会走onTaskComplete方法，完成下载。

## 如何复现此问题
我现在怀疑是切换ip的时候，导致没有马上连上外网，然后走的是http缓存的文件（我在浏览器试了一下，如果连上网在浏览器输入下载地址可以拿到文件，然后断开网以后再次访问还能拿到那个文件，这是什么原理，跟这个问题有关联吗，请指教），还是说ontaskrunning的处理回调时有限制，因为毕竟onTaskComplete最后回调了，下载也还在继续。还有，我这边的设备比较特殊，插的是一条网线，既不是wifi类型网络，又不是mobile网络类型。

作者方便把回调ontaskrunning 的具体类和代码贴一下吗？我一时找不到，我这边也瞧一下咋回事
## 控制台日志（越完整越好）
这是我自己打的日志方法，方便理解
   @Download.onTaskRunning
    protected void onTaskRunning(DownloadTask task) {
        Log.e("LoginActivity","----ontaskrunning"+task.getPercent());
}

**Comment by AriaLyy** [comment]
AbsFileer，running是由定时器触发的
```
 /**
   * 启动进度获取定时器
   */
  private void startTimer() {
    mTimer = new Timer(true);
    mTimer.schedule(new TimerTask() {
      @Override public void run() {
        if (mConstance.isComplete()
            || mConstance.isStop()
            || mConstance.isCancel()
            || !mConstance.isRunning) {
          closeTimer();
        } else if (mConstance.CURRENT_LOCATION >= 0) {
          mListener.onProgress(mConstance.CURRENT_LOCATION);
        }
      }
    }, 0, mUpdateInterval);
  }
```
可能是频繁切换ip后，导致线程读取流失败，导致线程重启，可能出现了状态判断失败的情况，控制台有没有错误日志

**Comment by wuxusheng** [comment]
没有错误日志，切换ip是我在下载前做的，切换了一个新的ip然后开启下载，而且进度可以走一小段，然后就不走了，但是最后oncomplete还是走了，并且下载完成， 这是我要表达的意思，还是ontaskrunning，有时候不回调的问题

**Comment by wuxusheng** [comment]
if (mConstance.isComplete()
            || mConstance.isStop()
            || mConstance.isCancel()
            || !mConstance.isRunning) {
          closeTimer();
        }
是不是这里某一个条件符合了就关闭定时器了，但是其实下载还在继续，有没有对应的获取这四种条件的方法，我打个日志先

**Comment by wuxusheng** [comment]
if (mConstance.isComplete()
            || mConstance.isStop()
            || mConstance.isCancel()
            || !mConstance.isRunning) {
          closeTimer();
        }
是不是这里某一个条件符合了就关闭定时器了，但是其实下载还在继续，有没有对应的获取这四种条件的方法，我打个日志先

**Comment by AriaLyy** [comment]
不一定，也有可能是fail播线程重启出现的，这几个状态是线程任务的，建议用3.4.15测试下，3.4.15版本我修改了线程的重启方式

**Comment by AriaLyy** [comment]
AbsThreadTask中retryThis这个方法

**Comment by wuxusheng** [comment]
用了3.4.16 试过了还是下载进行一半不回调了，但是最终会下载完，我感觉跟有线网有关系，连接无线网下载就没关系，日志只有threadtask 返回的下载完成，有其他解决办法吗

**Comment by wuxusheng** [comment]
我跑了一下你的demo ，就是SingleTaskActivity 这个例子，怎么下载都没问题，我的程序现在只要下载就会停进度完成下载，都不用切换网络，对比了一下，两者不同，我就是加了解注册而已
