### ISSUE TITLE
下载开始后，马上取消，再次开始，任务没有开始

### ISSUE THREAD

**Issue by wuxusheng** [AriaLyy/Aria#297]
## 版本号
3.4.15

## 什么问题
点击开始下载  Aria.download(this).setMaxSpeed(512)
                .load(download_url)    //读取下载地址
                .setFilePath(download_save_path) //设置文件保存的完整路径
                .start();   //启动下载
开始下载后，下载过程当中点击取消Aria.download(this).load(download_url).cancel(true);，再次点击开始，任务没有开始，并且点击取消也没有删除本地未下载完成的文件

## 如何复现此问题
我发现第一次点击开始下载，然后点击取消，文件没有删除，然后再次点击开始，任务没有开始，但是点击取消，文件就删除了，然后再点击开始下载，任务就启动了，是不是跟文件没有删除有关系

**Comment by AriaLyy** [comment]
用3.4.16

**Comment by wuxusheng** [comment]
好的
