### ISSUE TITLE
有3.4.16的文档吗

### ISSUE THREAD

**Issue by lql7993259lql** [AriaLyy/Aria#298]

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/

**Comment by lql7993259lql** [comment]
本文档适用于3.4.8版本

**Comment by lql7993259lql** [comment]
文档不够完善，有些状态都没列出来。比如，是否下载过，或者正在下载之类的。

**Comment by AriaLyy** [comment]
判断是否下载过：https://aria.laoyuyu.me/aria_doc/api/task_list.html
获取任务状态：https://aria.laoyuyu.me/aria_doc/api/task_handle.html#%E8%8E%B7%E5%8F%96%E4%BB%BB%E5%8A%A1%E5%BD%93%E5%89%8D%E7%8A%B6%E6%80%81

任务是否正在下载
```
Aria.download(this).load(url).isRunning();
```
