### ISSUE TITLE
文件大小不一致

### ISSUE THREAD

**Issue by CaptainJno** [AriaLyy/Aria#3]
你好。我用您的项目测试后，出现以下情况，如果方便的话，麻烦大神帮忙分析一下：
1、分别用浏览器和您的项目（多线程断点），下载项目中自带的链接apk，两种方式文件大小一致。
2、分别用浏览器和您的项目（多线程断点），下载我自己的链接apk，两种方式文件大小不一致。 多线程比浏览器下载的大（分别是4.98M和2.98M）。源文件大小2.98M，浏览器下载的大小正确。
根据上述情况，我猜测问题可能出现在服务器端，会不会是服务器不支持断点下载？但是，我不确定。
希望您根据您的经验，帮我再分析分析问题所在。

**Comment by AriaLyy** [comment]
能不能把你的下载链接给我，我去验证下，看看是什么地方出问题了

**Comment by CaptainJno** [comment]
我们外网环境下是https, https://trust.pdx.life/selfservice/daap/plugin/download/apk/daap3d3b4d271cb0488da692aa2e2541fa78/pdx_abendorse_V1.0.0.apk

**Comment by CaptainJno** [comment]
@AriaLyy 
如果您方便的话，能否加我的QQ：787068730

**Comment by CaptainJno** [comment]
你好，我和后台测试通过了。
后台增加了nginx配置及项目代码对断点下载的支持后，就不会出现文件大小不一致的问题了。
谢谢您的帮助！

**Comment by AriaLyy** [comment]
解决问题就好，同时谢谢您的反馈，我会在以后的版本中添加断点续传判断^_^

**Comment by xiaoguiYY** [comment]
最近集成你的这个项目到工程中，发现下载图片的话会出现图片不完整，下完后打开有一部分显示是模糊的，是不是断点哪里出问题了

**Comment by AriaLyy** [comment]
有可能，能把你的图片下载链接给我吗？我测试看看。

**Comment by xiaoguiYY** [comment]
我这边是测试链接，你可以随便找个图片链接试试，看是不是有那个问题

**Comment by AriaLyy** [comment]
你好，我在百度上找了多张图片下载，都没有出现你所说的问题。没有具体链接实在无法判断问题出在哪里，如果方便的话，能否提供下你出问题的链接？

**Comment by AmbitChen** [comment]
我有两个Activity，一个Activity里查询下载列表，一个Activity下载文件，为什么在下载列表里还是未开始状态？但是文件已经下载好了，好像是因为context不是一个的原因

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/5
