### ISSUE TITLE
扩张字段son value中"转义问题

### ISSUE THREAD

**Issue by androiddy** [AriaLyy/Aria#301]
## 版本号
全部

## 什么问题
扩张字段son value中如果包含 " 就会出现问题

## 如何复现此问题
扩张字段son value中"转义问题

## 手机型号
荣耀v10

**Comment by lql7993259lql** [comment]
<  >   这个  转义也有问题

**Comment by AriaLyy** [comment]
@lql7993259lql 本否提供下字符串？我测试`<>`是没有问题的..
