### ISSUE TITLE
修改系统时间后会停止下载进度条，但是还是会继续下载

### ISSUE THREAD

**Issue by wuxusheng** [AriaLyy/Aria#303]
## 版本号
3.4.16

## 什么问题
作者思密达，我找到问题了。我在你的singletaskactivity 这个demo中也复现了，我这边有个需求是修改

android 系统时间的，如果在下载过程当中，调用了修改系统时间，进度条则会停止。可以复现的代码如下：
1.进入singletaskactivity  oncreate调用如下代码，然后点击开始下载，这里睡眠不能去掉，去掉了进度
条不会停止不知道为什么。

在线程里调用下边代码
   try {
          Thread.sleep(10000);
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
        String strTime = "1970-01-01/08:00:00";//最好用这个时间可以很好复现，如果用正确的当前时间就没问题，不知道为什么，可能是当前时间之前的时间就不行吧。
  modifySystemTime(Integer.parseInt(ymd[0]), Integer.parseInt(ymd[1]), Integer.parseInt(ymd

[2]), Integer.parseInt(hms[0]), Integer.parseInt(hms[1]), Integer.parseInt(hms[2]));

public static void modifySystemTime(int year, int month, int day, int hourOfDay, int minute, 

int second) {
        Calendar c = Calendar.getInstance();
        c.set(c.YEAR, year);
        c.set(c.MONTH, month - 1);
        c.set(c.DATE, day);
        c.set(c.HOUR_OF_DAY, hourOfDay);
        c.set(c.MINUTE, minute);
        c.set(c.SECOND, second);
        long when = c.getTimeInMillis();
        SystemClock.setCurrentTimeMillis(when);
    }

2.等下载了某一时刻，即睡眠时间刚好到，调用更改系统时间后就会停止。

3.这里有个问题是修改系统时间是厂商专门为我们定制的api，其他设备调用可能不会起到修改时间的作用

，所以作者注意一下看怎么能复现，或者看代码进度条这块有没有依赖时间这块儿，希望作者能够修复

**Comment by AriaLyy** [comment]
感觉像是修改了系统时间导致了定时器异常

**Comment by wuxusheng** [comment]
if (System.currentTimeMillis() - mLastSaveTime > 5000
          && mChildCurrentLocation < mConfig.END_LOCATION) {
        mLastSaveTime = System.currentTimeMillis();
        if (!mConfigThreadPool.isShutdown()) {
          mConfigThreadPool.execute(mConfigThread);
        }
      }
不知道是不是这里影响的

**Comment by AriaLyy** [comment]
不是，这个地方不影响的，这个线程只是定时保存下进度

**Comment by AriaLyy** [comment]
时间这个是只会影响running的回调吗？

**Comment by AriaLyy** [comment]
其它的回调有没有影响？

**Comment by wuxusheng** [comment]
是的，文件下载完成后就走oncompelete 了，界面上看就是下载一部分停下来，然后就突然完成了

**Comment by AriaLyy** [comment]
你时间是往以前调整的？
谷歌到一个信息：
    1.当将时钟向未来调整，timer会继续从新时间开始定时执行任务.
    2.当将时钟向过去调整，timer会暂停执行，暂停的时间=现在的时间-新设置的时间

**Comment by wuxusheng** [comment]
是的，设置的String strTime = "1970-01-01/08:00:00";错误时间，那难怪了确实跟这个信息相符合，我设置正确就没问题，没试过设置未来很远的时间

**Comment by AriaLyy** [comment]
你用3.5_dev这个版本测试下看看呢，我用ScheduledThreadPoolExecutor替换掉了Timer

**Comment by wuxusheng** [comment]
有没有改好的源码我直接在github上下载一下，我想直接在你的singletaskactivity试一下，我自己的程序东西有点多了怕有干扰改坏了

**Comment by AriaLyy** [comment]
代码上传了

**Comment by wuxusheng** [comment]
试过了，没问题了，关了我

**Comment by AriaLyy** [comment]
:smirk:
