### ISSUE TITLE
注解在第二次回调时失效

### ISSUE THREAD

**Issue by nbcallum** [AriaLyy/Aria#306]
## 版本号
Aria版本：3.4.16

## 什么问题
注解在第二次回调时失效

## 如何复现此问题
1.打开app，进入下载页，下载一个文件，注解回调正常
2.调用Aria.download(context).load(downloadEntity).cancel(true)删除刚才下载的记录和文件
3.再次进入下载页，下载同一个文件，注解回调失效，但是文件下载成功（SD卡确实有此文件）
4.后台杀掉app进程，重启，进入下载页，下载文件，回调正常，重复第2步骤，结果依旧（第二次不回调）

ps:在3.4.1版本下无此问题。

## 手机型号
华为P10  EMUI版本：8.0.0   Anroid版本：8.0.0

## 控制台日志（越完整越好）
无错误日志打印

**Comment by AriaLyy** [comment]
是在两个不同的页面操作吗？
回调是下载页页面中的吗？

**Comment by nbcallum** [comment]
操作都是同一个界面，回调是在下载页面中的，下载页是一个fragment

**Comment by nbcallum** [comment]
@AriaLyy 小米8  android 8.0.1系统，测试了一下，无此问题..... 目前就华为p10这样，我再排查看看

**Comment by AriaLyy** [comment]
感谢:smile:

**Comment by nbcallum** [comment]
@AriaLyy 很奇怪...在子线程执行Aria.download(context).load(downloadEntity).cancel(true); 第二次注解就会失败，但是如果new handler在post里执行，就可以解决，不知道为什么会这样，目前还是只有华为p10这样，大佬有啥思路没

**Comment by AriaLyy** [comment]
你用这个版本试下看看：`3.5_dev1`

**Comment by nbcallum** [comment]
@AriaLyy 大佬牛逼...可以了
