### ISSUE TITLE
关于下载最大速度设置的问题

### ISSUE THREAD

**Issue by wuxusheng** [AriaLyy/Aria#307]
## 版本号
3.4.16

## 什么问题
 首先项目中没用到配置文件，直接在代码里写的，如下
  Aria.download(LoginActivity.this).setMaxSpeed(512)
                        .load(versionUrl)     //读取下载地址
                        .setFilePath(apkPath) //设置文件保存的完整路径
                        .start(); 
下载完成后直接安装新程序（新程序把.setMaxSpeed(512)去掉了，即不限制速度），安装完之后再次点击下载，应该按照最大速度下，结果还是按照512的速度下载了

**Comment by AriaLyy** [comment]
```
setMaxSpeed
```
是针对全局任务的，如果希望不限制速度，将参数改为0就可以了

**Comment by wuxusheng** [comment]
好我试试
