### ISSUE TITLE
源码注解问题

### ISSUE THREAD

**Issue by wuxusheng** [AriaLyy/Aria#308]
## 版本号
3.4.16

## 什么问题
@Retention(RetentionPolicy.CLASS) @Target(ElementType.METHOD) public @interface Download 

ElementType.METHOD 这个应该是修饰方法用的吧，不是应该用ElementType.Type吗？是不是没啥影响，对注解这块不是很了解，请教下，另外下载进度监听怎么和注解关联起来的，代码在哪块儿

**Comment by AriaLyy** [comment]
METHOD 只是限制条件，核心的是RetentionPolicy.CLASS注解，通过这个注解可以在编译的时候动态生成java文件，具体可以自行谷歌搜索java apt技术
连接各个模块的是AbsSchedulers这个调度类
1、AbsSchedulers接受任务模块传递来的进度数据
2、在AbsSchedulers类的createListener方法中，根据编译时生成的java文件创建观察者，然后宿主Activity设置观察者
3、观察者将AbsSchedulers通过回调的方式告诉宿主
大体上是上面的逻辑
自动生成java的代码是在AriaCompiler模块中

**Comment by wuxusheng** [comment]
createListener 中的Class clazz = Class.forName(targetName + getProxySuffix());
      listener = (AbsSchedulerListener<TASK, AbsNormalEntity>) clazz.newInstance(); 中activity怎么能强转成(AbsSchedulerListener<TASK, AbsNormalEntity>) 类型呢？

callback() 方法中的listener.onTaskRunning(task); 等方法怎么跟activity的注解关联的，是apt吗

**Comment by AriaLyy** [comment]
本质上一致的，代理类中持有activity的引用，AbsSchedulers调用代理类中的方法相当于调用activity中的方法。
至于为什么这么做，是因为每个activity都有自己的代理类，而AbsSchedulers却需要动态调度不同的代理类，如果直接调用activity中的方法，那么activity就需要使用者手动`implements AbsSchedulerListener`接口，这样就太耦合太麻烦了
而代理类是自动生成的，相当于自动替开发者实现了AbsSchedulerListener接口，这样省去了很多步骤

**Comment by wuxusheng** [comment]
嗯看了apt以后，再结合你的解释，明白了，谢谢。
