### ISSUE TITLE
UploadUtil看到了new Thread(this).start()

### ISSUE THREAD

**Issue by liuzhanta** [AriaLyy/Aria#31]

**Comment by AriaLyy** [comment]
UploadUtil 实现了Runnable接口，new Thread(this).start()相当于启动了自己...

**Comment by liuzhanta** [comment]
那真正在上传的时候，是调用这个方法吗？

**Comment by AriaLyy** [comment]
对，代码从run开始

**Comment by liuzhanta** [comment]
那你怎么管理你的线程呢？

**Comment by AriaLyy** [comment]
上传部分比较简单，没有涉及到多线程，所以通过command中的命令就可以直接管理

**Comment by liuzhanta** [comment]
哦，如果能用线程池来管理就更好了，那样能根据手机核数以及其他因素控制最大并发数，否则，可能会有OOM的风险

**Comment by AriaLyy** [comment]
下载部分是用线程池管理的，但是上传部分比较简单，每一任务都只是单线程，所以用线程池意义不是很大。
