### ISSUE TITLE
***已被其他任务占用

### ISSUE THREAD

**Issue by Reginer** [AriaLyy/Aria#311]
3.5

****.zip(设置的下载路径)已被其他任务占用

设置一个固定的下载路径，下载中退出。下次下载还是那个路径，网址更换，不知道旧地址。

通用机型都可以

有没有api设置一下？出现这种错误提示直接开始重新下载的。

**Comment by Reginer** [comment]
不好意思，没解释清楚。旧的下载地址没存呢，也不检测下载地址是不是有变化。是想问一下，有没有想法取消掉updateUrl这个api。改为这种loadOrReload("url"),出现那种错误直接在sdk里处理updateUrl。

**Comment by AriaLyy** [comment]
没有这个api，框架里面是根据下载地址检索记录和下载文件都，后面版本可以添加一个强制下载的api

**Comment by Reginer** [comment]
嗯，是的。强制下载的api  。

**Comment by AriaLyy** [comment]
`3.5.1`增加了一个强制狭窄的 api
```
Aria.download(SingleTaskActivity.this)
                     .load(DOWNLOAD_URL)
                     .setFilePath(path, true) // true表示忽略路径是否被占用
                     .start();
```

**Comment by Reginer** [comment]
棒
