### ISSUE TITLE
使用Aria下载框架 监听完成事件后，如何回到主线

### ISSUE THREAD

**Issue by ILoveChina1994** [AriaLyy/Aria#313]
在下载完成以后的监听事件中，使用线程，线程要在下载完成以后，该怎么处理

**Comment by ILoveChina1994** [comment]
我仔细找了一下，发现并不是Aria 的问题，不过我刚刚发现，在线程中我曾经加过一个路径判断，结果下载的操作就不执行了，代码如下：
//将对象注册到Aria
        Aria.download(this).register();
 ariaDownLoad = Aria.download(this);
 Runnable runnable2 = new Runnable() {
        @Override
        public void run() {
            try {
                Message msg = new Message();
                Bundle data = new Bundle();
                data.putString("value", getRemoteInfo2());
                msg.setData(data);
                handler2.sendMessage(msg);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    };

    Handler handler2 = new Handler() {
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            Bundle data = msg.getData();
            String val = data.getString("value");
            String[] string = val.split(",");
            for (int i =0 ;i < string.length; i++){
                String str = string[i];
                if (str.contains("http://")){
                    downloadUrl = str.substring(7,str.length() - 1);
                    break;
                }
            }
            if (downloadUrl != null){
                String[] strings =downloadUrl.split("/");
                String path = downloadPath + strings[strings.length -1];
                ariaDownLoad.load(downloadUrl)     //读取下载地址
                        .setFilePath(path)
                        .start();
//                popuWindowTextView.setText("989");
                popupWindow.showAtLocation(popView,Gravity.CENTER, 0 , -100);
            }

        }
    };
只是把popWindows显示出来了，但是下载的回调监听不到。
我添加的判断如下：
在  String path = downloadPath + strings[strings.length -1];下面添加：
if (isFolderExists(path)) {
                    Log.i("123-----------","存在" + path);
                }else {
                    Log.i("123-----------","不存在" + path);
                }
其中isFolderExists 是如下的写法：
 boolean isFolderExists(String strFolder) {
        File file = new File(strFolder);
        if (!file.exists()) {
            if (file.mkdirs()) {
                return true;
            } else {
                return false;

            }
        }
        return true;
    }

**Comment by AriaLyy** [comment]
加这种判断是不会影响下载的，能否提供下控制台太输出的日志？还有你说的回调是宿主的回调还是popupwindow的回调？

**Comment by ILoveChina1994** [comment]
能不能加一下你 QQ 或者其他聊天方式，我给你看一下

**Comment by ILoveChina1994** [comment]
是Aria的监听，不执行  @Download.onTaskRunning
    protected void running(DownloadTask task) {
        isLoading = true;
        isLoading2 = false;
        int p = task.getPercent();  //任务进度百分比
//        String speed = task.getConvertSpeed();  //转换单位后的下载速度，单位转换需要在配置文件中打开
//        long dataLong = task.getSpeed(); //原始byte长度速度
//        if (modelList.size() ==0 ){
//            for (int i =0; i< pathArr.size();i++){
//                ModelList model = new ModelList();
//                if (index == i){
//                    model = new ModelList(pathArr.get(i), urlArr.get(i), versionArr.get(i), false, "", -1);
//                }else {
//                    model = new ModelList(pathArr.get(i), urlArr.get(i), versionArr.get(i), true, "正在下载", -1);
//                }
//                modelList.add(model);
//            }
//        }
//        modelList.get(index).setPropress(p);
        long dataSize = task.getFileSize();
        String mb = CommonUtil.formatFileSize(dataSize);
        //字符替换 将单位mb 替换成 MB
        String mb2 = mb.substring(0,mb.length()- 3);
        size = mb2;
        mb2 = mb2 + "MB";
        popuWindowTextView.setText(mb2 +"       已下载..."+ p+ "%");
    }

**Comment by ILoveChina1994** [comment]
我把手机Aria下载所在的项目删除，手机重启以后又可以下载了

**Comment by ILoveChina1994** [comment]
我手机测试的版本最低的都是Android 5.0的，android4.3和android 4.4.2的这么操作是不行的

**Comment by AriaLyy** [comment]
1、请提供控制台日志
2、你只需要设置路径，文件夹目录会自动创建

**Comment by ILoveChina1994** [comment]
11-12 00:20:05.899 2200-2875/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:07.984 2200-2919/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:10.049 2200-2954/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:12.129 2200-3031/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:14.194 2200-3104/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:16.259 2200-3141/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:18.384 2200-3179/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:20.509 2200-3260/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
11-12 00:20:22.699 2200-3329/com.zjdx.admin.wyplaningapp_ipad E/HttpFileInfoThread: 任务【http://120.55.95.61:8811/ghcg/zg/武义总规纲要成果.zip】下载失败，错误码：403
使用高板本是可以下载的，但是Android 4.3和Android4.4.2 一直再报这个错误，请问有什么解决方案吗，急求

**Comment by AriaLyy** [comment]
中文导致的问题，高版本的android系统使用Httpurlconnection 会自动URLEncoder

**Comment by ILoveChina1994** [comment]
那我要怎么处理

**Comment by ILoveChina1994** [comment]
错误 码 是404 是什么错误

**Comment by ILoveChina1994** [comment]
我把url 中的中文转码了，出现有的时候可以下载，有的时候就不能下载，不能下载的时候报错是任务下载失败，报错404 ，是不是中文里面出现的（）也要转码呀，中文的（）要怎么转码

**Comment by ILoveChina1994** [comment]
错误码400是不是特殊符号（）和()报的错

**Comment by ILoveChina1994** [comment]
这个怎么转啊
