### ISSUE TITLE
是否支持网速限制？

### ISSUE THREAD

**Issue by Likarl** [AriaLyy/Aria#32]

**Comment by AriaLyy** [comment]
这个功能3.1.6版本已经实现，奈何，3.1.6增加了apt的注解方法，重新上传jcenter，bintray迟迟不给审核通过，如果着急使用功能话，可以下载v_3.0分支的代码到本地使用：
使用方式：
```java
Aria.download(this).setMaxSpeed(speed);
```

**Comment by Likarl** [comment]
好的。可以简单说一下是如何实现网速限制的吗？

**Comment by AriaLyy** [comment]
通过限制流的读取速度来实现，下面是Aria的速度公式。
```java
speed = (bufSize / 1024) * threadNum / sleepTime
```
speed 为下载速度，bufSize 为 缓冲byte长度，threadNum 为下载线程数，sleepTime为单条线程等待时间
通过上面的公式可以算出sleepTime，然后通过Thread.sleep(sleepTime)来控制每秒钟写入文件的byte字节

**Comment by AriaLyy** [comment]
3.1.9版本已经支持了
