### ISSUE TITLE
建议：希望IEntity可以继承Serializable接口

### ISSUE THREAD

**Issue by nbcallum** [AriaLyy/Aria#320]
## 如何复现此问题
项目里有个对象的字段是IEntity的实现类，当使用putSerializable传递该对象时会报错crash，虽然可以使用putParcelable来解决...但是项目人多，不好控制，希望大佬可以实现Serializable接口，通用性更强^_^

**Comment by AriaLyy** [comment]
感谢反馈，下个版本会增加Serializable接口支持
