### ISSUE TITLE
下载失败了！这是为啥？

### ISSUE THREAD

**Issue by hghAndroid** [AriaLyy/Aria#323]
E/Downloader: 下载失败【downloadUrl:http://mh.gdown.baidu.com/f2efd4b9558d969afff67b1b8bbbfee26bb152c400a1d2efaed459fd54bdeb54f7d1e3e996219b098ace912120c13b41bbb9ab4623d34a8bc98c48c3be560b6abae6bac1c688ddd96245122e7213c54e7ef8efa5ce3604da63bc363331230f1bba65a961f5ce9d11321829b5fa4afe54f9a17c4550b02db820bbe8917e82572a61e4233b8970a63ee045588579ba802e5c1715a391f3442e3c01c522d62643639e6248d56f46880eee92f21f923aa374569b9654f7bf7e41abd3128a84b03aebd3f8d31e3b50a9f8c7903a9873d925e5414e9094fda93efb7da8a01772aabb3acb86189901fb4c47bbe099e07972ad60315aa362a3914f17f9c7dc3c2b878b24df2f4711618ddcb205df8a87d9f78135509e1390f53c64ac】；【filePath:/storage/emulated/0/zhixing/"百度手机助手(大众看点).apk"】
                                                            EXCEPTIONDETAILED:
                                                           ====================EXCEPTION INFO====================
                                                           JAVA.IO.FILENOTFOUNDEXCEPTION: /STORAGE/EMULATED/0/ZHIXING/F2EFD4B9558D969AFFF67B1B8BBBFEE26BB152C400A1D2EFAED459FD54BDEB54F7D1E3E996219B098ACE912120C13B41BBB9AB4623D34A8BC98C48C3BE560B6ABAE6BAC1C688DDD96245122E7213C54E7EF8EFA5CE3604DA63BC363331230F1BBA65A961F5CE9D11321829B5FA4AFE54F9A17C4550B02DB820BBE8917E82572A61E4233B8970A63EE045588579BA802E5C1715A391F3442E3C01C522D62643639E6248D56F46880EEE92F21F923AA374569B9654F7BF7E41ABD3128A84B03AEBD3F8D31E3B50A9F8C7903A9873D925E5414E9094FDA93EFB7DA8A01772AABB3ACB86189901FB4C47BBE099E07972AD60315AA362A3914F17F9C7DC3C2B878B24DF2F4711618DDCB205DF8A87D9F78135509E1390F53C64AC: OPEN FAILED: ENAMETOOLONG (FILE NAME TOO LONG)
                                                           LIBCORE.IO.IOBRIDGE.OPEN(IOBRIDGE.JAVA:512)
                                                           JAVA.IO.RANDOMACCESSFILE.<INIT>(RANDOMACCESSFILE.JAVA:255)
                                                           COM.ARIALYY.ARIA.UTIL.BUFFEREDRANDOMACCESSFILE.<INIT>(BUFFEREDRANDOMACCESSFILE.JAVA:123)
                                                           COM.ARIALYY.ARIA.CORE.DOWNLOAD.DOWNLOADER.DOWNLOADER.HANDLENEWTASK(DOWNLOADER.JAVA:69)
                                                           COM.ARIALYY.ARIA.CORE.COMMON.ABSFILEER.HANDLEBREAKPOINT(ABSFILEER.JAVA:558)
                                                           COM.ARIALYY.ARIA.CORE.COMMON.ABSFILEER.STARTFLOW(ABSFILEER.JAVA:165)
                                                           COM.ARIALYY.ARIA.CORE.COMMON.ABSFILEER.RUN(ABSFILEER.JAVA:174)
                                                           JAVA.LANG.THREAD.RUN(THREAD.JAVA:784)
                                                           【CAUSED BY】: ANDROID.SYSTEM.ERRNOEXCEPTION: OPEN FAILED: ENAMETOOLONG (FILE NAME TOO LONG)
                                                           LIBCORE.IO.LINUX.OPEN(NATIVE METHOD)
                                                           LIBCORE.IO.BLOCKGUARDOS.OPEN(BLOCKGUARDOS.JAVA:207)
                                                           LIBCORE.IO.IOBRIDGE.OPEN(IOBRIDGE.JAVA:498)
                                                           JAVA.IO.RANDOMACCESSFILE.<INIT>(RANDOMACCESSFILE.JAVA:255)
                                                           COM.ARIALYY.ARIA.UTIL.BUFFEREDRANDOMACCESSFILE.<INIT>(BUFFEREDRANDOMACCESSFILE.JAVA:123)
                                                           COM.ARIALYY.ARIA.CORE.DOWNLOAD.DOWNLOADER.DOWNLOADER.HANDLENEWTASK(DOWNLOADER.JAVA:69)
                                                           COM.ARIALYY.ARIA.CORE.COMMON.ABSFILEER.HANDLEBREAKPOINT(ABSFILEER.JAVA:558)
                                                           COM.ARIALYY.ARIA.CORE.COMMON.ABSFILEER.STARTFLOW(ABSFILEER.JAVA:165)
                                                           COM.ARIALYY.ARIA.CORE.COMMON.ABSFILEER.RUN(ABSFILEER.JAVA:174)
                                                           JAVA.LANG.THREAD.RUN(THREAD.JAVA:784)
                                                           ===================================================
11-03 18:00:13.208 27165-27165/com.zxbrowser D/AbsTaskQueue: 从执行池删除任务【"百度手机助手(大众看点).apk"】成功

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/48454032-b59e0700-e7f0-11e8-9fe5-51c82bef1129.png)

文件名太长
