### ISSUE TITLE
compile换成api

### ISSUE THREAD

**Issue by Reginer** [AriaLyy/Aria#324]
## 版本号
3.5.1

## 什么问题
compile可不可以换成api引用

## 如何复现此问题
使用gradle5

gradle5已经移除了compile引用，我引用一个core导致注解那个引用引不到了。

**Comment by AriaLyy** [comment]
compile 改为implementation
annotationProcessor 不变
https://developer.android.com/studio/build/dependencies

**Comment by Reginer** [comment]
是这样的。
文档中是这样引用的compile 'com.arialyy.aria:aria-core:3.5.1'。
我用implementation或者api引用他只能引用到core自己，它依赖的另外一些库就依赖不到了。
所以希望在https://github.com/AriaLyy/Aria/blob/master/Aria/build.gradle  里的compile可以改成api，
注意不是implementation。
不然只能
> api("com.arialyy.aria:aria-core:$download") {
        exclude group: 'com.android.support'
    }
    api"com.arialyy.aria:aria-annotations:$download"

**Comment by Reginer** [comment]
我在Android Studio Canary3上测试的。里面是gradle5。所以会有这样的问题 。

**Comment by AriaLyy** [comment]
com.arialyy.aria:aria-annotations:$download 不能使用 api 只能使用  annotationProcesso

**Comment by Reginer** [comment]
这个库可以的。这是注解类。不是注解器呢。
其实我的意思就是把 https://github.com/AriaLyy/Aria/blob/master/Aria/build.gradle  里的compile改成api。
这是我现在的引用方式，没引用那个ftp，你参考下。
因为我是用的kotlin，所以用的kapt 。
```
api("com.arialyy.aria:aria-core:$download") {
        exclude group: 'com.android.support'
    }
api"com.arialyy.aria:aria-annotations:$download"
kapt "com.arialyy.aria:aria-compiler:$download"
```

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/blob/master/Aria/build.gradle 在这个文件将依赖改为：
```
api("com.arialyy.aria:aria-core:$download") {
        exclude group: 'com.android.support'
    }
api"com.arialyy.aria:aria-annotations:$download"
kapt "com.arialyy.aria:aria-compiler:$download"
```
这个？
