### ISSUE TITLE
APK下载完成后打开就闪退。

### ISSUE THREAD

**Issue by PiterPeng** [AriaLyy/Aria#327]
## 版本号
implementation 'com.arialyy.aria:aria-core:3.5'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.5'

## 什么问题
下载APK，有进度提示100%，但下载完成后打开就闪退。

## 如何复现此问题
地址：http://111.47.14.136:10002/app-release.apk，每次下载都是这个固定地址

## 手机型号
SUPOIN Android 5.1.1 API 22 

## 控制台日志（越完整越好）
控制台没有报错

麻烦看到回复一下，有点急。 Q 294841204

**Comment by AriaLyy** [comment]
下载完成后安装应用崩溃？

**Comment by PiterPeng** [comment]
下载完成，但是安装闪退。但是通过IE能下载安装

**Comment by AriaLyy** [comment]
你在系统的文件管理器安装呢？

**Comment by AriaLyy** [comment]
调用安装的代码贴下看看

**Comment by PiterPeng** [comment]
``    // 安装apk
    protected void installApk(File file) {
        Intent intent = new Intent(Intent.ACTION_VIEW);
        //判断是否是AndroidN以及更高的版本
        if (Build.VERSION.SDK_INT >= 24) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(mActivity,
                    BuildConfig.APPLICATION_ID + ".provider", file);
            intent.setDataAndType(contentUri, "application/vnd.android.package-archive");
        } else {
            intent.setDataAndType(Uri.fromFile(file), "application/vnd.android.package-archive");
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        }
        startActivity(intent);
    }

**Comment by PiterPeng** [comment]
系统文件管理器安装不了，闪退

**Comment by AriaLyy** [comment]
应该是解析包出错导致的，增加一个头`.addHeader("Accept-Encoding", "gzip, deflate")`
```
Aria.download(SingleTaskActivity.this)
        .load(DOWNLOAD_URL)
        .addHeader("Accept-Encoding", "gzip, deflate")
        .useServerFileName(true)
        .setFilePath(path, true)
        .start();
```
