### ISSUE TITLE
11-20 14:06:05.825 9182-9284/com.ledvance.smart W/System.err: com.arialyy.aria.exception.AriaIOException: Aria Net Exception:任务下载失败，文件长度小于0， url: https://firmwareapi.azurewebsites.net/firmware-overview?name=A19_Filament_W_IMG0038_00102411-encrypted.ota 11-20 14:06:05.826 9182-9284/com.ledvance.smart W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.checkLen(HttpFileInfoThread.java:271)         at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:181)         at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:71)         at java.lang.Thread.run(Thread.java:764) 11-20 14:06:05.947 9182-9289/com.ledvance.smart W/HttpThreadTask: 该下载不支持断点

### ISSUE THREAD

**Issue by zhoutianling** [AriaLyy/Aria#328]
## 版本号
最新版本

## 什么问题
下载失败，文件长度小于0

## 如何复现此问题
使用该下载地址：https://firmwareapi.azurewebsites.net/firmware-overview?name=A19_Filament_W_IMG0038_00102411-encrypted.ota    必现！  
浏览器可以正常下载

## 手机型号
小米6x

## 控制台日志（越完整越好）
11-20 14:06:05.825 9182-9284/com.ledvance.smart W/System.err: com.arialyy.aria.exception.AriaIOException: Aria Net Exception:任务下载失败，文件长度小于0， url: https://firmwareapi.azurewebsites.net/firmware-overview?name=A19_Filament_W_IMG0038_00102411-encrypted.ota
11-20 14:06:05.826 9182-9284/com.ledvance.smart W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.checkLen(HttpFileInfoThread.java:271)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:181)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:71)
        at java.lang.Thread.run(Thread.java:764)
11-20 14:06:05.947 9182-9289/com.ledvance.smart W/HttpThreadTask: 该下载不支持断点

**Comment by AriaLyy** [comment]
应该是cookie导致的问题

**Comment by zhoutianling** [comment]
哈哈，是服务端传递的Header 信息里面没有Content-Legth 字段导致

**Comment by AriaLyy** [comment]
我抓包看chrome的貌似需要第二次请求传送cookie，服务器端才会返回头部长度😂
