### ISSUE TITLE
如何设置下载的文件名为下载链接对应的真实文件名

### ISSUE THREAD

**Issue by zhoutianling** [AriaLyy/Aria#329]
## 版本号
3.2.9

## 什么问题
如何设置下载的文件名为下载链接对应的真实文件名

使用文档中有提到 设置 serverName属性 ,服务端也有传递Content-Disposition ，源码中也有看到rename  但是怎么设置到下载的文件名中呢？请指教

## 如何复现此问题
下载地址为：https://firmwareapi.azurewebsites.net/api/v1/zigbee/firmwares/download/4489/25/latest
对应的文件名为：A19_RGBW_IMG0019_00102411-encrypted.ota

**Comment by zhoutianling** [comment]
看了一下源码，解决了问题：
原因是： 头部信息Content-Disposition里面有空格，导致该条件不成立，if (info.trim().startsWith("filename") && info.contains("=")) {  }
所有不会重命名，加上去空格即可解决问题

**Comment by AriaLyy** [comment]
感谢反馈😊

**Comment by zhoutianling** [comment]
大神，我很喜欢这套下载框架，这套设计思想和风格，我 愿意一起为这套框架无偿贡献自己的力量（修改Bug），让这套框架更完美，分享使人快乐！

**Comment by zhoutianling** [comment]
刚才提交了一个设置下载文件名为服务端文件名的小问题，多次测试没问题（提交了代码），大致思路为可以在文件下载完成后再重命名，可以防止重命名不成功，不知道对不对，请大神指点

**Comment by AriaLyy** [comment]
欢迎欢迎

**Comment by AriaLyy** [comment]
github贡献代码的步骤如下：
1、你fork 工程
2、git remote set-url origin URL 
­ 2018/11/20 17:37:26
url修改为你fork后的项目clone的url
3、push到你的fork的项目
4、进入这个 
![image](https://user-images.githubusercontent.com/10437293/48816752-615dce80-ed7e-11e8-8391-a91e6d818f27.png)
页面就可以提交代码了
