### ISSUE TITLE
取消任务时onTaskCancel回调两次

### ISSUE THREAD

**Issue by AllenMeex** [AriaLyy/Aria#33]
hi, 
当取消一个正在进行的任务时onTaskCancel回调两次，取消已经stop的任务onTaskCancel回调一次。。

**Comment by AriaLyy** [comment]
非常感谢您的反馈，
compile 'com.arialyy.aria:Aria:3.1.6' 已经解决这个bug

**Comment by AllenMeex** [comment]
确实正常了~
