### ISSUE TITLE
提示该下载不支持断点，running方法一直运行下载进度为0

### ISSUE THREAD

**Issue by xiangbinduan** [AriaLyy/Aria#331]
## 什么问题
下载文件提示，该下载不支持断点，然后一直执行running回调方法，到是下载速度一直是0，也没有回调onNoSupportBreakPoint方法。我用okhttp测试是可以下载成功的。请问是什么问题呢？

## 如何复现此问题
http://10.8.1.10:8800/download/1e3d88c7e2d24c33a931598e7443d532   这是一个内网地址。

## 控制台日志（越完整越好）
11-22 20:16:05.813 13654-13654/com.arialyy.simple D/BaseCachePool: 任务【ggsg9.apk】进入缓存队列成功
11-22 20:16:05.816 13654-13654/com.arialyy.simple D/BaseExecutePool: 任务【ggsg9.apk】进入执行队列成功
11-22 20:16:05.991 13654-14031/com.arialyy.simple I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
11-22 20:16:06.012 13654-14031/com.arialyy.simple D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-22 20:16:07.432 13654-14031/com.arialyy.simple W/System.err: java.io.IOException: Permission denied
11-22 20:16:07.433 13654-14031/com.arialyy.simple W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
11-22 20:16:07.434 13654-14031/com.arialyy.simple W/System.err:     at java.io.File.createNewFile(File.java:948)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
11-22 20:16:07.435 13654-14031/com.arialyy.simple W/System.err:     at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
11-22 20:16:07.436 13654-14031/com.arialyy.simple W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:83)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:118)
11-22 20:16:07.437 13654-14031/com.arialyy.simple W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:68)
        at java.lang.Thread.run(Thread.java:761)
11-22 20:16:07.634 13654-14047/com.arialyy.simple W/HttpThreadTask: 该下载不支持断点
11-22 20:16:11.797 13654-13659/com.arialyy.simple I/art: Do partial code cache collection, code=122KB, data=98KB
11-22 20:16:11.798 13654-13659/com.arialyy.simple I/art: After code cache collection, code=122KB, data=98KB
    Increasing code cache capacity to 512KB
11-22 20:16:34.884 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:16:36.227 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:16:34.884 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:16:36.227 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:16:38.724 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:52.323 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:53.121 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:53.726 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:54.360 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:55.054 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:55.544 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:55.808 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:56.044 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734
11-22 20:17:56.253 13654-13654/com.arialyy.simple D/SingleTaskActivity: com.arialyy.simple.download.SingleTaskActivity_running_6497734

**Comment by AriaLyy** [comment]
这是之前版本的一个bug，3.5.2_dev_3已经修复了这个问题

**Comment by AriaLyy** [comment]
保存路径是啥？

**Comment by xiangbinduan** [comment]
加上了还是同样的问题啊

**Comment by AriaLyy** [comment]
3.5.2_dev_4 用这个版本试试呢

**Comment by xiangbinduan** [comment]
3.5.2_dev_4 版本测试下来 回调了onNoSupportBreakPoint方法，但是下载依然不成功 runing方法还是一直在回调
下载链接 返回的header 只加了Content-Disposition   没有加Content-Length和Content-Range

log日志如下：
1-23 19:04:44.643 18099-18114/com.zqautomotive.orislink.testdemo I/OpenGLRenderer: Initialized EGL, version 1.4
11-23 19:04:44.643 18099-18114/com.zqautomotive.orislink.testdemo D/OpenGLRenderer: Swap behavior 1
11-23 19:04:44.646 18099-18114/com.zqautomotive.orislink.testdemo W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
11-23 19:04:58.821 18099-18106/com.zqautomotive.orislink.testdemo I/art: Debugger is active
11-23 19:04:59.061 18099-18106/com.zqautomotive.orislink.testdemo I/art: Starting a blocking GC Instrumentation
11-23 19:05:01.447 18099-18099/com.zqautomotive.orislink.testdemo V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@871b87d
11-23 19:05:01.953 18099-18099/com.zqautomotive.orislink.testdemo D/BaseCachePool: 任务【z.zip】进入缓存队列成功
11-23 19:05:01.956 18099-18099/com.zqautomotive.orislink.testdemo D/BaseExecutePool: 任务【z.zip】进入执行队列成功
11-23 19:05:02.221 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:03.226 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:04.231 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:05.236 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:06.241 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:07.246 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:07.270 18099-18104/com.zqautomotive.orislink.testdemo I/art: Do partial code cache collection, code=25KB, data=30KB
    After code cache collection, code=25KB, data=30KB
11-23 19:05:07.271 18099-18104/com.zqautomotive.orislink.testdemo I/art: Increasing code cache capacity to 128KB
11-23 19:05:08.331 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:09.336 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:10.340 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:11.345 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:12.350 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:13.425 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:14.430 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:15.435 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:16.442 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:17.450 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:18.515 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:19.520 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:20.524 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:21.529 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:22.534 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:23.641 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:23.842 18099-18130/com.zqautomotive.orislink.testdemo I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
11-23 19:05:23.866 18099-18130/com.zqautomotive.orislink.testdemo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-23 19:05:23.871 18099-18130/com.zqautomotive.orislink.testdemo W/HttpThreadTask: 该下载不支持断点
11-23 19:05:24.647 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:25.651 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:26.657 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:27.664 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:28.731 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:29.736 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:30.741 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:31.745 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:32.749 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:33.815 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:34.820 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:35.825 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:36.830 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:37.835 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:38.907 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:39.911 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:40.916 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:41.920 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:42.924 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:44.016 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:45.021 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:46.025 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:47.030 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:48.036 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:49.103 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:50.107 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:51.113 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:52.117 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:53.122 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:54.223 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:55.227 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:56.232 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:57.236 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:58.241 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:05:59.335 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:00.342 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:01.347 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:02.352 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:03.357 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:04.444 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:05.450 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:06.463 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:07.413 18099-18130/com.zqautomotive.orislink.testdemo E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.TaskException: 任务【z.zip】下载失败，filePath: /mnt/sdcard/z.zip, url: http://10.8.1.170:8080/download
    timeout
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:131)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:50)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    java.lang.Thread.run(Thread.java:761)
    ===================================================
11-23 19:06:07.415 18099-18130/com.zqautomotive.orislink.testdemo E/AbsThreadTask: 任务【z.zip】执行失败
11-23 19:06:07.467 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=0; start_thread_num=1; complete_num=0
11-23 19:06:07.497 18099-18130/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=1; start_thread_num=1; complete_num=0
11-23 19:06:07.567 18099-18130/com.zqautomotive.orislink.testdemo W/System.err: com.arialyy.aria.exception.TaskException: Aria Task Exception:, 任务【z.zip】执行失败
        at com.arialyy.aria.core.common.AbsThreadTask.handleFailState(AbsThreadTask.java:481)
11-23 19:06:07.568 18099-18130/com.zqautomotive.orislink.testdemo W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:382)
11-23 19:06:07.569 18099-18130/com.zqautomotive.orislink.testdemo W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:363)
11-23 19:06:07.570 18099-18130/com.zqautomotive.orislink.testdemo W/System.err:     at com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:130)
        at com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:50)
11-23 19:06:07.571 18099-18130/com.zqautomotive.orislink.testdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-23 19:06:07.572 18099-18130/com.zqautomotive.orislink.testdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-23 19:06:07.573 18099-18130/com.zqautomotive.orislink.testdemo W/System.err:     at java.lang.Thread.run(Thread.java:761)
11-23 19:06:08.471 18099-18131/com.zqautomotive.orislink.testdemo D/StateConstance: fail_num=1; start_thread_num=1; complete_num=0
