### ISSUE TITLE
FTP上传中间手动断网，有taskFail返回，taskComplete也返回

### ISSUE THREAD

**Issue by TianXuanL** [AriaLyy/Aria#335]
## 版本号
3.5.2

## 什么问题
ftp上传时断开网络，taskFail回调任务失败，taskComplete回调任务上传成功，

## 如何复现此问题
ftp上传时断开网络

## 手机型号
summi P1

## 控制台日志（越完整越好）
12-06 12:06:40.273 6886-10032/com.xxh.ftpdemo E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaIOException: 上传失败，filePath: /storage/emulated/0/DCIM/123.zip
    IOException caught while copying.
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.upload(FtpThreadTask.java:163)
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:88)
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:38)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    java.lang.Thread.run(Thread.java:818)
    ===================================================
12-06 12:06:40.419 6886-10032/com.xxh.ftpdemo W/AbsThreadTask: 任务【123.zip】thread__0__重试失败，网络未连接
12-06 12:06:40.419 6886-10032/com.xxh.ftpdemo D/StateConstance: fail_num=1; start_thread_num=1; complete_num=0
12-06 12:06:40.616 6886-10032/com.xxh.ftpdemo W/System.err: com.arialyy.aria.exception.TaskException: Aria Task Exception:, 任务【123.zip】执行失败
        at com.arialyy.aria.core.common.AbsThreadTask.handleFailState(AbsThreadTask.java:481)
        at com.arialyy.aria.core.common.AbsThreadTask.retryThis(AbsThreadTask.java:405)
        at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:378)
        at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:363)
        at com.arialyy.aria.core.upload.uploader.FtpThreadTask.upload(FtpThreadTask.java:162)
        at com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:88)
12-06 12:06:40.617 6886-10032/com.xxh.ftpdemo W/System.err:     at com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
12-06 12:06:40.666 6886-10032/com.xxh.ftpdemo E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaIOException: Aria Net Exception:文件上传错误，错误码为：150, msg：150 Opening data channel for file upload to server of "/123.zip", restarting at offset 136336991
    , filePath: /storage/emulated/0/DCIM/123.zip
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.upload(FtpThreadTask.java:172)
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:88)
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:38)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    java.lang.Thread.run(Thread.java:818)
    ===================================================
12-06 12:06:40.695 6886-10033/com.xxh.ftpdemo D/StateConstance: fail_num=1; start_thread_num=1; complete_num=0
12-06 12:06:40.749 6886-10032/com.xxh.ftpdemo W/AbsThreadTask: 任务【123.zip】thread__0__重试失败，网络未连接
12-06 12:06:40.749 6886-10032/com.xxh.ftpdemo D/StateConstance: fail_num=2; start_thread_num=1; complete_num=0
12-06 12:06:40.749 6886-10032/com.xxh.ftpdemo I/System.out: close [socket][/192.168.0.82:39767]
12-06 12:06:40.749 6886-10032/com.xxh.ftpdemo I/FtpUploadThreadTask: 任务【123.zip】线程__0__上传完毕
12-06 12:06:40.775 6886-6886/com.xxh.ftpdemo D/AbsTaskQueue: 从执行池删除任务【123.zip】成功
12-06 12:06:40.777 6886-6886/com.xxh.ftpdemo I/AbsSchedulers: 没有等待中的任务
12-06 12:06:40.778 6886-6886/com.xxh.ftpdemo D/qwe: 文件：123.zip，onTaskFailAria Task Exception:, 任务【123.zip】执行失败
12-06 12:06:40.820 6886-10032/com.xxh.ftpdemo D/StateConstance: fail_num=2; start_thread_num=1; complete_num=1
12-06 12:06:40.820 6886-6886/com.xxh.ftpdemo D/AbsSchedulers: complete_next
12-06 12:06:40.822 6886-6886/com.xxh.ftpdemo I/AbsSchedulers: 没有等待中的任务
12-06 12:06:40.823 6886-6886/com.xxh.ftpdemo D/qwe: 文件：123.zip，上传完成true

**Comment by TianXuanL** [comment]
断网后和ftp的连接没有中断，导致联网后再次上传直接回调taskComplete，显示任务完成，如果断网后我在ftp服务端手动断开连接，联网后再次上传是正常上传的

**Comment by AriaLyy** [comment]
感谢反馈，我检查下看看

**Comment by TianXuanL** [comment]
大神，有时间能更新个版本把这问题改下吗，打算在项目中用你的上传框架

**Comment by AriaLyy** [comment]
使用`3.5.3_dev` 版本

**Comment by TianXuanL** [comment]
大神，最新版3.5.3_dev依赖后，少了aria-ftp-plug-1.0.4.jar这个，导致报错
![default](https://user-images.githubusercontent.com/38403108/49779325-6cd06400-fd44-11e8-9715-af758729fae6.png)

**Comment by AriaLyy** [comment]
用`3.5.3_dev_1`这个版本吧，忘记添加依赖了
