### ISSUE TITLE
上传成功后，获取所有普通下载任务Aria.upload(this).getTaskList()，之前上传成功的任务getPercent=0

### ISSUE THREAD

**Issue by TianXuanL** [AriaLyy/Aria#336]
## 版本号
3.5.3

## 什么问题
上传成功后，获取所有普通下载任务Aria.upload(this).getTaskList()，之前上传成功的任务getPercent=0

## 如何复现此问题
上传成功后，获取之前成功任务的实例，getPercent=0

## 手机型号
sunmi P1

## 控制台日志（越完整越好）
12-06 12:10:01.304 12257-12257/com.xxh.ftpdemo D/qwe: PP = 70
    PP = 5.20mb/s
12-06 12:10:03.305 12257-12257/com.xxh.ftpdemo D/qwe: PP = 100
    PP = 4.00mb/s
12-06 12:10:03.503 12257-12257/com.xxh.ftpdemo D/qwe: 文件：123.mp4，上传完成true
12-06 12:10:09.915 12257-12257/com.xxh.ftpdemo D/qwe: getFilePath------/storage/emulated/0/DCIM/123.mp4
    getKey------/storage/emulated/0/DCIM/123.mp4
    getResponseStr------
    getConvertFileSize------null
    getConvertSpeed------null
    getFileName------123.mp4
    getRedirectUrl------null
    getStr------asd
    getUrl------ftp://192.168.0.91:21
    getTaskType------19
    getCompleteTime------1544069403460
    getCurrentProgress------28171262
    getPercent------0
    getState------1
    getStopTime------1544001582897
    getFailNum------0
    getSpeed------0
    getFileSize------28171262

**Comment by AriaLyy** [comment]
之前版本没有保存进度百分比，后面会考虑增加这个保存，百分比可根据上传进度和文件长度计算，是否完成使用`isComplete()`这个方法进行判断
