### ISSUE TITLE
怎么传递我的数据model

### ISSUE THREAD

**Issue by zhengxuming** [AriaLyy/Aria#34]
比如我在"播放列表"页面一个个的点击下载，然后在"下载列表"页面查看下载状态，怎么把数据model传递过去，因为model里面不止包含文件名，下载地址，还有音频的id，封面url，以及收藏状态等。

我大致研究了下demo，也没看出来哪里有传递的方法，很想问问题主，谢谢，等待您的回答。

**Comment by AriaLyy** [comment]
downloadentity中有一个str的扩展字段，你可以把你的数据转换为json字符串，存到str里面

**Comment by AriaLyy** [comment]
在多任务下载那个页面，有关于使用downloadentity下载的方法，在下一个版本我会在ariamanaher增加一个设置str的方法

**Comment by zhengxuming** [comment]
好的，十分感谢！！！支持您的项目！！！

**Comment by AriaLyy** [comment]
谢谢😄😄

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:Aria:3.1.7'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.1.7'
```
3.1.7版本已经提供了一个快速设置扩展字段的api.
`Aria.download(this).load(DOWNLOAD_URL).setExtendField(str)`
