### ISSUE TITLE
注解回调方法无效

### ISSUE THREAD

**Issue by zzjian** [AriaLyy/Aria#340]
## 版本号
v_3.5.2

## 什么问题
当把下载相关代码写在父Activity中时，注解方法不执行

**Comment by AriaLyy** [comment]
哪个类使用注解就需要在哪个类中注册

**Comment by zzjian** [comment]
是在MainActivity中注册及使用注解。`startAcvity(MainActivity.class)` 注解有效
然后用A类继承MainActivity，不写任何代码。`startAcvity(a.class)` 注解无效
```
public class a extends MainActivity{
}

```

**Comment by AriaLyy** [comment]
如果希望再a类中使用注解，那么a类中同样需要注册
