### ISSUE TITLE
Aria 的组下载问题

### ISSUE THREAD

**Issue by ILoveChina1994** [AriaLyy/Aria#341]
## 什么问题
组下载的时候要实现你在github上面的类似的组下载，看了一下你的代码，感觉好麻烦，有没有简单一点的demo，我试着去复现一下，发现特别困难，所以想问问有没有简单一些的。

**Comment by AriaLyy** [comment]
什么意思？

**Comment by ILoveChina1994** [comment]
我想做多任务下载，用的是ListView,   DownLoadAdapter.java

public class DownLoadAdapter extends BaseAdapter {

    private ArrayList<ModelList> mModeList;
    private Context mContext;
    private LayoutInflater inflater = null;
    private DownLoadButtonClick mButtonClick;
    private int mWidth, mHeight;
    private DownLoadAdapter.ViewHolder viewHolder;
    public DownLoadAdapter(Context context, ArrayList<ModelList> modeList, List<DownloadEntity> downloadList, int width, int height){
        mContext = context;
        inflater = LayoutInflater.from(context);
        mWidth = width;
        mHeight = height;
        mModeList = modeList;
    }
    @Override
    public int getCount() {
        return mModeList.size();
    }

    @Override
    public Object getItem(int i) {
        return i;
    }

    @Override
    public long getItemId(int i) {
        return i;
    }

    @Override
    public View getView(final int i, View contentView, ViewGroup viewGroup) {
        ViewHolder viewHolder = null;
        if (viewHolder == null){
            viewHolder = new ViewHolder();
            contentView = inflater.inflate(R.layout.download_adapter_list,null);
            viewHolder.downLoadBtn = (Button) contentView.findViewById(R.id.download_list_Btn);
            ConstraintLayout.LayoutParams  downLoadBtnParams = (ConstraintLayout.LayoutParams) viewHolder.downLoadBtn.getLayoutParams();
            downLoadBtnParams.rightMargin = 20;
            downLoadBtnParams.width = 60 * 2;
            downLoadBtnParams.height = mHeight - 40;
            downLoadBtnParams.topMargin = 20;
            downLoadBtnParams.bottomMargin = 20;
            viewHolder.downLoadBtn.setLayoutParams(downLoadBtnParams);
            viewHolder.downLoadBtn.setTag(i);
            viewHolder.downLoadTextView = (TextView) contentView.findViewById(R.id.download_list_text);
            viewHolder.propressTextView = (TextView) contentView.findViewById(R.id.download_list_propress);
            viewHolder.propressTextView.setTextColor(Color.parseColor("#b036c4"));
        }

        viewHolder.downLoadTextView.setText(mModeList.get(i).getName());
        if (mModeList.get(i).getPropress()==-1){
            viewHolder.propressTextView.setText(mModeList.get(i).getMb());
        }else {
            viewHolder.propressTextView.setTextColor(Color.parseColor("#3c3c3c"));
            viewHolder.propressTextView.setText(mModeList.get(i).getMb() + "     正在下载..." + mModeList.get(i).getPropress() + "%");
        }

        if (mModeList.get(i).isHiddren() ){
                //此处显示下载的内容
                ConstraintLayout.LayoutParams  downLoadTextViewParams = (ConstraintLayout.LayoutParams) viewHolder.downLoadTextView.getLayoutParams();
                downLoadTextViewParams.rightMargin = 20;
                downLoadTextViewParams.leftMargin = 20;
                downLoadTextViewParams.height = mHeight - 40;
                downLoadTextViewParams.topMargin = 10;
                downLoadTextViewParams.bottomMargin = 30;
                downLoadTextViewParams.width = mWidth - 60 * 2 - 40;
                viewHolder.downLoadTextView.setLayoutParams(downLoadTextViewParams);
                viewHolder.downLoadTextView.setGravity(Gravity.CENTER_VERTICAL|Gravity.TOP);

                viewHolder.propressTextView.setVisibility(View.VISIBLE);
                ConstraintLayout.LayoutParams  propressTextViewParams = (ConstraintLayout.LayoutParams) viewHolder.propressTextView.getLayoutParams();
                propressTextViewParams.rightMargin = 20;
                propressTextViewParams.leftMargin = 20;
                propressTextViewParams.topMargin = 30;
                propressTextViewParams.bottomMargin = 10;
                propressTextViewParams.height = mHeight - 40;
                propressTextViewParams.width = mWidth - 60 * 2 - 40;
                viewHolder.propressTextView.setLayoutParams(propressTextViewParams);
                viewHolder.propressTextView.setGravity(Gravity.CENTER_VERTICAL|Gravity.BOTTOM);
                viewHolder.downLoadBtn.setVisibility(View.GONE);
            }else {
                //隐藏下面下载的信息
                viewHolder.propressTextView.setVisibility(View.GONE);
                ConstraintLayout.LayoutParams  downLoadTextViewParams = (ConstraintLayout.LayoutParams) viewHolder.downLoadTextView.getLayoutParams();
                downLoadTextViewParams.rightMargin = 20;
                downLoadTextViewParams.leftMargin = 20;
                downLoadTextViewParams.height = mHeight - 40;
                downLoadTextViewParams.topMargin = 20;
                downLoadTextViewParams.bottomMargin = 20;
                downLoadTextViewParams.width = mWidth - 60 * 2 - 40;
                viewHolder.downLoadTextView.setLayoutParams(downLoadTextViewParams);
                viewHolder.downLoadBtn.setVisibility(View.VISIBLE);
                viewHolder.downLoadTextView.setGravity(Gravity.CENTER_VERTICAL|Gravity.LEFT);
        }
        final ViewHolder finalViewHolder = viewHolder;
        viewHolder.downLoadBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //点击了下载
                int m = (int) finalViewHolder.downLoadBtn.getTag();
                mButtonClick.DownLoadButtonClick(m);
            }
        });
        return contentView;
    }
    class ViewHolder{
        TextView downLoadTextView;
        Button downLoadBtn;
        TextView propressTextView;
    }


    //adapter 里面的按钮回调
    public interface DownLoadButtonClick{
        public void DownLoadButtonClick(int i);
    }
    public void setDownLoadButtonClick(DownLoadButtonClick buttonClick){
        mButtonClick = buttonClick;
    }

    public synchronized void updateState(ModelList modelList) {
        if (viewHolder!= null){
            for (ModelList modelList1 : mModeList) {
                if (modelList.getUrl().equals(modelList1.getUrl())){
                    viewHolder.propressTextView.setText(modelList.getMb() + "     正在下载..." + modelList.getPropress() + "%");
                }
            }
            notifyDataSetChanged();
        }

    }

}

ModelList.java
public class ModelList implements Serializable {
    private String  name;
    private String url;
    private boolean isHiddren;
    private String mb;
    private int propress;
    private String version;
    public ModelList(String name, String url, String version, Boolean isHiddren, String mb, int propress){
        super();
        this.mb = mb;
        this.name = name;
        this.url =url;
        this.isHiddren = isHiddren;
        this.propress= propress;
        this.version = version;
    }
    public ModelList(){

    }
    //将对象属性反序列化然后读取出来，注意属性的顺序必须按照序列化属性的顺序
    protected ModelList(Parcel parcel){
        name = parcel.readString();
        url = parcel.readString();
        isHiddren= parcel.hasFileDescriptors();
        mb = parcel.readString();
        propress= parcel.readInt();
        version = parcel.readString();
    }
    public static  final Parcelable.Creator<ModelList> CREATOR =new Parcelable.Creator<ModelList>() {
        @Override
        public ModelList createFromParcel(Parcel parcel) {
            return new ModelList(parcel);
        }

        @Override
        public ModelList[] newArray(int i) {
            return new ModelList[i];
        }
    };

    //将对象属性进行序列化
    private void writToParcel(Parcel dest,int flag){
        dest.writeInt(propress);
        dest.writeString(name);
        dest.writeString(url);
        dest.writeString(mb);
        dest.writeString(version);
    }

    @Override
    public String toString(){
        return "ModelList{" +
                "name="+name+"url="+ url+"version ="+ version + "isHiddren="+
                isHiddren + "mb=" + mb + "propress=" + propress+'}';

    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrl() {
        return url;
    }

    public void setHiddren(boolean hiddren) {
        isHiddren = hiddren;
    }

    public boolean isHiddren() {
        return isHiddren;
    }

    public void setMb(String mb) {
        this.mb = mb;
    }

    public String getMb() {
        return mb;
    }

    public void setPropress(int propress) {
        this.propress = propress;
    }

    public int getPropress() {
        return propress;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getVersion() {
        return version;
    }
}
在Activity 中下载的使用
if (modelList.size()> 0){
    int width = getResources().getDisplayMetrics().widthPixels;
    int height = getResources().getDisplayMetrics().heightPixels / 14;
    adapter = new DownLoadAdapter(DownLoadActivity.this, modelList, downloadList, width, height);
    listView.setAdapter(adapter);
}

adapter.setDownLoadButtonClick(new DownLoadAdapter.DownLoadButtonClick() {
    @Override
    public void DownLoadButtonClick(int i) {
        index = i;
        modelList.get(i).setHiddren(true);
        modelList.get(i).setMb("正在下载");
        adapter.notifyDataSetChanged();
        String urlName = modelList.get(i).getUrl();
        String[] ns = urlName.split("/");
        File file1 = new File(downloadPath + ns[ns.length - 1]);
        if (!file1.exists()) {
            try {
                file1.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        //标记下下载状态
        isLoading = true;
        currentLoadUrl = modelList.get(i).getUrl();
        currentLoadPath = file1.getPath();
        currentLoadPath = currentLoadPath.substring(0,currentLoadPath.indexOf(".zip"));
         //启动下载
        Aria.download(this)
                .loadGroup(urlList)
                .setDirPath(currentLoadPath)
                .start();

    }

});
下载：
@DownloadGroup.onTaskComplete void taskComplete(DownloadGroupTask task) {
//        mAdapter.updateBtState(task.getKey(), true);
        Intent media = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
        Uri contentUri = Uri.fromFile(new File(downloadPath));
        media.setData(contentUri);
        this.sendBroadcast(media);
        if (index2 != -1){
            index = index2;
        }
        modelList.get(index).setMb("下载完成，正在解压");
        modelList.get(index).setPropress(-1);
        
        adapter.notifyDataSetChanged();
        String urlName = modelList.get(index).getUrl();
        String[] ns = urlName.split("/");

        //解压完成，将下载的.zip 文件删除
        File file = new File(downloadPath + ns[ns.length - 1]);
        if (file.exists()) {
            upZipFile(downloadPath + ns[ns.length - 1], downloadPath );
        }else {
            modelList.get(index).setMb("解压失败，请重新下载");
            modelList.get(index).setPropress(-1);
            modelList.get(index).setHiddren(false);
            adapter.notifyDataSetChanged();
        }
    }
download_adapter_list
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal"
    tools:context="com.zjdx.admin.hyplaningapp.Main_PlaningDisplay.display_download.DownLoadActivity"
    android:descendantFocusability="blocksDescendants">

    <Button
        android:layout_width="30dp"
        android:layout_height="34dp"
        android:text="下 载"
        app:layout_constraintRight_toRightOf="parent"
        android:id="@+id/download_list_Btn"
        android:layout_marginRight="10dp"
        android:textColor="#fff"
        android:background="#5eabf8"
        android:layout_marginTop="0dp"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_marginBottom="5dp"
        app:layout_constraintBottom_toBottomOf="parent"/>
    <TextView
        android:layout_width="300dp"
        android:layout_height="34dp"
        android:textSize="14dp"
        android:id="@+id/download_list_text"
        android:layout_marginLeft="10dp"
        android:lines="1"
        android:gravity="center_vertical"
        app:layout_constraintLeft_toLeftOf="parent"
        android:layout_marginTop="5dp"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_marginBottom="10dp"
        app:layout_constraintBottom_toBottomOf="parent"/>
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="20dp"
        android:id="@+id/download_list_propress"
        android:textSize="12dp"
        android:text="下载的情况"
        android:layout_marginLeft="10dp"
        android:layout_marginBottom="5dp"
        android:layout_marginTop="10dp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"/>

</android.support.constraint.ConstraintLayout>
index是一个全局 的变量，当点击下载按钮时，会给index赋值，但是会发现下载的大小是一样的，这要怎么办，下载的url是从网络上获取的，每一个名称对应一个下载链接，还有就是当点击了下载以后，在下载完成之前，点击返回按钮，再次进入下载页面，应该和离开的时候一样（下载进度不同），除非下载完成以后，数据移除。这个要怎么改合适 。

**Comment by ILoveChina1994** [comment]
在下载页面的Activity中，  
Aria.download(this).register();
Aria.get(this).getDownloadConfig().setMaxTaskNum(4);

**Comment by AriaLyy** [comment]
DownloadGroupEntity 中可以获取任务总长度和任务已下载的进度，自己换算成百分比进度就是了；还有如果是自己的业务逻辑需要你自己处理
