### ISSUE TITLE
支持功能

### ISSUE THREAD

**Issue by NerdAnonymous** [AriaLyy/Aria#346]
大佬，不持之M3U8的切片下载啊

**Comment by AriaLyy** [comment]
能否提供一个下载地址？

**Comment by NerdAnonymous** [comment]
@AriaLyy 明天发你

**Comment by NerdAnonymous** [comment]
@AriaLyy 明天发你

**Comment by NerdAnonymous** [comment]
@AriaLyy m3u8地址http://v2.qingdian1.com/m_20180730_991/2/2B9FB34A4BCD8CE61481D1C8418EFE36_1080P.m3u8 希望下载出来是个完整的视频 这个是斗罗大陆第二集的地址

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/50746306-577a2700-1269-11e9-866c-10ca7d3700db.png)
文件时可以下的，估计是服务器做了防盗限制
