### ISSUE TITLE
Failed to resolve: Aria:AriaFtpPlug:unspecified

### ISSUE THREAD

**Issue by yuhaoz** [AriaLyy/Aria#347]
添加依赖
    implementation 'com.arialyy.aria:aria-core:3.5.3'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.5.3'

报错：
Failed to resolve: Aria:AriaFtpPlug:unspecified

**Comment by AriaLyy** [comment]
清空下缓存，添加这个依赖看下，我这新工程测试没有出现这个问题
```
compile 'com.arialyy.aria:aria-ftp-plug:1.0.4'
```

**Comment by AriaLyy** [comment]
使用`3.5.4`
