### ISSUE TITLE
android.database.sqlite.SQLiteException not an error (code 0): Could not open the database in read/write mode.

### ISSUE THREAD

**Issue by hkp3162858** [AriaLyy/Aria#351]
## 控制台日志（越完整越好）

1 java.lang.RuntimeException:Unable to start activity ComponentInfo{com.cloudminds.pepper.hari/com.cloudminds.airobot.app.AiRobot}: android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
3 ......
4 Caused by:
5 android.database.sqlite.SQLiteException:not an error (code 0): Could not open the database in read/write mode.
6 android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
7 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
8 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
9 android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
10 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
11 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
12 android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
13 android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
14 android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
15 android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
16 android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
17 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
18 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
19 com.arialyy.aria.orm.SqlHelper.init(SqlHelper.java:53)
20 com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:39)
21 com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:47)
22 com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:114)
23 com.arialyy.aria.core.AriaManager.<init>(AriaManager.java:81)
24 com.arialyy.aria.core.AriaManager.getInstance(AriaManager.java:90)
25 com.arialyy.aria.core.Aria.get(Aria.java:118)
26 com.arialyy.aria.core.Aria.download(Aria.java:92)
27 com.cloudminds.airobot.app.AiRobot.onCreate(AiRobot.java:108)
28 android.app.Activity.performCreate(Activity.java:6720)
29 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
30 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
31 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
32 android.app.ActivityThread.-wrap12(ActivityThread.java)
33 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
34 android.os.Handler.dispatchMessage(Handler.java:102)
35 android.os.Looper.loop(Looper.java:154)
36 android.app.ActivityThread.main(ActivityThread.java:6119)
37 java.lang.reflect.Method.invoke(Native Method)
38 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
39 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by AriaLyy** [comment]
升级到`3.5.4`版本看下
