### ISSUE TITLE
在 atlas阿里组件开发的环境中，注解无效

### ISSUE THREAD

**Issue by fengyerq** [AriaLyy/Aria#353]
## 版本号

3.5.4
## 什么问题
提示信息：    【没有Aria的注解方法】
没有下载回调信息，但是 可以下载
## 如何复现此问题
使用atlas框架进行组件开发，在bundle下 使用这个下载框架进行下载。

## 手机型号
华为P9 Android8.0系统

## 控制台日志（越完整越好）
只有一个提示信息：【没有Aria的注解方法】
再提供其他信息，1、如果在app下使用，不在bundle下使用功能都正常。可以进行回调。
2.clean下工程 在rebuild下工程，bundle下可以生成代理文件，但是 还是不能回调，依然提示 没有Aria的注解方法
3.如果这个注解方法 跟butterknife 是一样的思路，这个bundle下 是可以正常使用butterknife注解，是当成在library中使用

希望大佬出马 帮忙看下原因，谢谢

**Comment by AriaLyy** [comment]
看下这个：https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html
