### ISSUE TITLE
文件下载总是404

### ISSUE THREAD

**Issue by MonkeyEatBanana** [AriaLyy/Aria#36]
文件地址是有文件的，复制到浏览器中好用，试了几个xlsx格式的文件下载都不好用，其中一个地址是
http://oqcpqqvuf.bkt.clouddn.com/可用.xlsx

`W/DownloadUtil: 任务【http://oqcpqqvuf.bkt.clouddn.com/可用.xlsx】下载失败，错误码：404
 D/DownloadTaskQueue: 从执行池删除任务，删除成功`

求解答

**Comment by AriaLyy** [comment]
我这边测试的正常的
![123.png](http://upload-images.jianshu.io/upload_images/1824042-687c0f51ec5c02c3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![222.png](http://upload-images.jianshu.io/upload_images/1824042-b66c5b1c8a38b066.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
请检查一下你的网络

**Comment by MonkeyEatBanana** [comment]
网络没有问题
是用的我发的地址吗？有中文的，我试了好几遍，好像是有中文的都不行，然后我把中文编码，有的还是不好用
`http://oqcpqqvuf.bkt.clouddn.com/文本.txt`
编码之后下载的时候报
`E/DownloadUtil: 任务【http://oqcpqqvuf.bkt.clouddn.com/%E6%96%87%E6%9C%AC.txt】下载失败，文件长度小于0`

**Comment by AriaLyy** [comment]
是用你的地址，如果文件名改成英文可以下载吗？

**Comment by MonkeyEatBanana** [comment]
我把名字改成英文的上传之后，下载还是
`E/DownloadUtil: 任务【http://oqcpqqvuf.bkt.clouddn.com/ceshi.txt】下载失败，文件长度小于0`
是我哪里写的不对吗？其他下载，都好用了

**Comment by MonkeyEatBanana** [comment]
目前发现所有的txt的下载链接都不好用

**Comment by AriaLyy** [comment]
非txt的呢？

**Comment by MonkeyEatBanana** [comment]
都好用，有中文的编码一下就好用了。
现在发现就是txt的不好用，无论是有没有中文

**Comment by AriaLyy** [comment]
我找到问题，你的返回码是206，表示该链接支持断点，但是服务器却告诉文件长度是-1

**Comment by MonkeyEatBanana** [comment]
文件长度返回-1是服务器的问题吗？

**Comment by AriaLyy** [comment]
不确定，我debug，`conn.getContentLength();`长度返回的是-1，我加编码尝试下看看

**Comment by MonkeyEatBanana** [comment]
嗯嗯，好，我也看看，辛苦啦

**Comment by AriaLyy** [comment]
解决了，这个你需要添加一个head`addHeader("Accept-Encoding", "gzip, deflate")`
```java
 Aria.download(this)
              .load(DOWNLOAD_URL)
              .setDownloadPath(DOWNLOAD_PATH)
              .addHeader("Accept-Encoding", "gzip, deflate")
              .start();
```

**Comment by MonkeyEatBanana** [comment]
我这不知道怎么回事，添加addHeader("Accept-Encoding", "gzip, deflate")还是不好用
`E/DownloadUtil: 任务【http://oqcpqqvuf.bkt.clouddn.com/ceshi.txt】下载失败，文件长度小于0`

然后我试了一下addHeader("Accept-Encoding", "identity")是好用的，谢谢啦

**Comment by AriaLyy** [comment]
可以的了话，就麻烦把issues关了哈
