### ISSUE TITLE
关于atlas组件开发，注解失效问题，我已经找到原因了。希望大佬下个版本改正下

### ISSUE THREAD

**Issue by fengyerq** [AriaLyy/Aria#361]
## 版本号
3.5.4版本

## 什么问题
bundle下注解失效

注解不成的原因是，中间代理类 是通过反射查找，但 未能找到该类。
查看了源码反射的代码如下：Class.forName(className.concat("$$DownloadListenerProxy"))方法查询
请把所有的Class.forName反射修改为:obj.getClass().getClassLoader().loadClass(className.concat("$$DownloadListenerProxy"))
方法查询。
这样atlas组件开发就能使用，期待大佬下个版本更新。谢谢

## 手机型号
华为P9

## 控制台日志（越完整越好）
无

**Comment by AriaLyy** [comment]
好的
