### ISSUE TITLE
关于断点续传

### ISSUE THREAD

**Issue by spd-heshuip** [AriaLyy/Aria#363]
## 版本号
最新版本

## 什么问题
关于断点续传，由于每次下载的地址都会变（下载同一个文件），是否会影响断点续传的功能？

**Comment by AriaLyy** [comment]
如果只是参数改变，如七牛的下载地址，建议使用：https://aria.laoyuyu.me/aria_doc/api/get_params_support.html
如果是整个地址都发生改变，请使用：https://aria.laoyuyu.me/aria_doc/api/update_url.html

**Comment by spd-heshuip** [comment]
好的，试试先，感谢！
