### ISSUE TITLE
安卓5.0以下设备如何支持https下载

### ISSUE THREAD

**Issue by whenair** [AriaLyy/Aria#366]
## 版本号
Aria 3.5.4

## 什么问题
我用Android 4.3.1模拟器无法下载https文件，http文件可以直接下载。应该是5.0以下证书问题，
glide可以通过okhttp设置信任任意证书处理，Aria不知道如何设置信任所有证书。

非常感谢你，这个开源库很棒
## 如何复现此问题
Android 5.0以下设备下载https文件

## 手机型号
Android 5.0以下设备

## 控制台日志（越完整越好）
E/xxxxx Aria: Aria onPre
D/AbsTaskQueue: 从执行池删除任务【dialog_use.gif】成功
W/System.err: com.arialyy.aria.exception.AriaIOException: Aria Net Exception:下载失败，filePath: /storage/sdcard/yourApp/dialog_use.gif, url: https://github.com/AriaLyy/Aria/raw/master/img/dialog_use.gif
W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:82)
I/AbsSchedulers: 没有等待中的任务
E/xxxxx Aria: Aria taskFail

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/53384287-4a4dfe80-39b5-11e9-804b-f9b01ee8b617.png)
可以在配置文件那指定ca证书

**Comment by whenair** [comment]
谢谢回复 我最后发现是https下载链接跳转的问题，已经处理
