### ISSUE TITLE
监听器可以针对单个任务设置就好了

### ISSUE THREAD

**Issue by Joky-SSS** [AriaLyy/Aria#37]
比如addListenner(taskId, listenner)

**Comment by AriaLyy** [comment]
这个可以有，你是希望只获取单个任务的下载状态吗？如果这样的话，目前你可以使用task.getKey()来判断是不是想要的任务，后续版本我将会采用注解的方式处理这个问题

**Comment by AriaLyy** [comment]
[3.1.9已实现对单个任务设置监听器](https://github.com/AriaLyy/Aria#下载状态获取)
