### ISSUE TITLE
导入这个依赖的时候直接导入的libs没有按照说明导入

### ISSUE THREAD

**Issue by wenxueyangx** [AriaLyy/Aria#370]
## Aria版本
3.4.9

## 什么问题
我们在工程中直接依赖的libs包，也就是
compile files('libs/aria-annotations-3.4.9.jar')
    compile files('libs/aria-core-3.4.9.jar')
我发现这样虽然下载成功了，但是onPre,onTaskRunning,onTaskComplete等方法并没有回调到，这是为什么？

## 如何复现此问题
更改导如依赖的方式如上所示

**Comment by AriaLyy** [comment]
需要导入`AriaCompiler`支持
![image](https://user-images.githubusercontent.com/10437293/54247891-9da77b80-4575-11e9-83a2-8ff3e48685ec.png)

**Comment by wenxueyangx** [comment]
可以了，感谢！
