### ISSUE TITLE
3.5.4版本使用save方法，会重新下载任务

### ISSUE THREAD

**Issue by woshiyizhijiao** [AriaLyy/Aria#373]
## Aria版本
3.5和3.5.4

## 什么问题
之前项目用的是3.5版本，问题是：我暂停所有的任务,重新进入到我的下载列表，percent 拿到是0

切换到3.5.4之后，我调用，我是想要更新str这个字段的数据，但是会把之前的下载任务全部清空

`Aria.download(context).load(downloadUrl).setExtendField(str).save();`

PS:为什么我更新3.6的时候，会提示说没有这个依赖库呢

**Comment by AriaLyy** [comment]
3.6.2_debug_6
