### ISSUE TITLE
数据库表结构更改

### ISSUE THREAD

**Issue by Reginer** [AriaLyy/Aria#374]
## Aria版本
3.6.2debug

## 什么问题
数据库表是不是变动过 ？从以前3.4升级上来之后，再使用下载就提示数据库报错。
组下载

## 如何复现此问题
使用旧版本，打开一次apk。之后使用现在版本，打开apk使用组下载功能

## 控制台日志
android.database.sqlite.SQLiteException: foreign key mismatch - "DownloadGroupTaskEntity" referencing "DownloadGroupEntity" (code 1): , while compiling: UPDATE DownloadGroupEntity SET currentProgress=?,urls=?,fileSize=?,convertFileSize=?,groupHash=?,completeTime=?,stopTime=?,dirPath=?,state=?,percent=?,isComplete=? WHERE rowid=?

**Comment by AriaLyy** [comment]
是的，3.6.2版本去掉了一些没有的外键

**Comment by Reginer** [comment]
那要是想流畅的升级到最新版而不至于让功能异常，Aria有没有提供什么api可以清理下数据下载数据库的数据，或者有其他什么办法  ？

**Comment by AriaLyy** [comment]
暂时还在研究怎么处理，你可以自己清除数据库的数据，数据库名：AndroidAria.db

**Comment by Reginer** [comment]
https://github.com/yuweiguocn/GreenDaoUpgradeHelper    这个估计可以帮上你

**Comment by AriaLyy** [comment]
3q

**Comment by cyw026** [comment]
@AriaLyy 你好，升级到3.6.4也碰到了这个问题
