### ISSUE TITLE
简单使用下载一个服务器文件，提示权限问题

### ISSUE THREAD

**Issue by aellenlei** [AriaLyy/Aria#375]
## Aria版本
3.6.2

## 什么问题
添加了读写权限，但是简单的下载一个文件就出现权限问题，调试代码是内部创建文件出错，位置为FileUtil.java文件，240行，该行代码”testWriteFile.createNewFile();“执行提示权限问题。
![1D4A807C-1E8C-4F99-AA14-901656EE32D0](https://user-images.githubusercontent.com/15522058/55327766-687bb280-54bd-11e9-8b12-b0ca0e0f2660.png)

## 如何复现此问题
调用方式:
Aria.download(this).register();
        Aria.download(this)
                .load("http://192.168.50.155/index_.php")
                .setFilePath(Environment.getExternalStorageDirectory().getAbsolutePath() + "/hello.php",true)
                .start();

## 控制台日志

> 04-01 20:34:11.885 19666-19666/? I/art: Not late-enabling -Xcheck:jni (already on)
04-01 20:34:12.134 19666-19666/yuanqi.android.terminalservice.app W/System: ClassLoader referenced unknown path: /data/app/yuanqi.android.terminalservice.app-2/lib/x86_64
04-01 20:34:12.383 19666-19666/yuanqi.android.terminalservice.app W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
04-01 20:34:12.423 19666-19666/yuanqi.android.terminalservice.app I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
04-01 20:34:12.427 19666-19666/yuanqi.android.terminalservice.app I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
04-01 20:34:12.548 19666-19666/yuanqi.android.terminalservice.app D/CommonUtil: 创建文件成功:/data/user/0/yuanqi.android.terminalservice.app/files/Aria/AriaApp.cfg
04-01 20:34:12.598 19666-19666/yuanqi.android.terminalservice.app W/DownloadTarget: 保存路径【/storage/emulated/0/hello.php】已经被其它任务占用，当前任务将覆盖该路径的文件
04-01 20:34:12.599 19666-19666/yuanqi.android.terminalservice.app W/CommonUtil: 记录为空
04-01 20:34:12.674 19666-19666/yuanqi.android.terminalservice.app D/BaseCachePool: 任务【hello.php】进入缓存队列成功
04-01 20:34:12.674 19666-19666/yuanqi.android.terminalservice.app D/BaseExecutePool: 任务【hello.php】进入执行队列成功
04-01 20:34:12.730 19666-19682/yuanqi.android.terminalservice.app D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-01 20:34:12.811 19666-19676/yuanqi.android.terminalservice.app I/art: WaitForGcToComplete blocked for 6.267ms for cause Background
04-01 20:34:12.840 19666-19681/yuanqi.android.terminalservice.app W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
04-01 20:34:12.841 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at java.io.File.createNewFile(File.java:939)
04-01 20:34:12.843 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
04-01 20:34:12.843 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
04-01 20:34:12.843 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
04-01 20:34:12.843 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:196)
04-01 20:34:12.843 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:129)
04-01 20:34:12.843 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:82)
04-01 20:34:12.844 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-01 20:34:12.844 19666-19681/yuanqi.android.terminalservice.app W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
04-01 20:34:12.844 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at libcore.io.Posix.open(Native Method)
04-01 20:34:12.844 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-01 20:34:12.844 19666-19681/yuanqi.android.terminalservice.app W/System.err:     at java.io.File.createNewFile(File.java:932)
04-01 20:34:12.844 19666-19681/yuanqi.android.terminalservice.app W/System.err: 	... 7 more
04-01 20:34:12.949 19666-19683/yuanqi.android.terminalservice.app I/AbsFileer: 文件【/storage/emulated/0/hello.php】错误，任务重新开始
04-01 20:34:12.996 19666-19666/yuanqi.android.terminalservice.app D/tag: onPre,null
04-01 20:34:13.118 19666-19684/yuanqi.android.terminalservice.app I/AndServer: VM with version 2.1.0 has Multidex support.
04-01 20:34:13.141 19666-19684/yuanqi.android.terminalservice.app I/AndServer: InstantRun support was not found.
04-01 20:34:13.195 19666-19676/yuanqi.android.terminalservice.app W/art: Suspending all threads took: 8.454ms
04-01 20:34:13.205 19666-19682/yuanqi.android.terminalservice.app I/OpenGLRenderer: Initialized EGL, version 1.4
04-01 20:34:13.206 19666-19682/yuanqi.android.terminalservice.app W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-01 20:34:13.226 19666-19682/yuanqi.android.terminalservice.app D/EGL_emulation: eglCreateContext: 0x7f3bb7849500: maj 3 min 0 rcv 3
04-01 20:34:13.229 19666-19682/yuanqi.android.terminalservice.app D/EGL_emulation: eglMakeCurrent: 0x7f3bb7849500: ver 3 0 (tinfo 0x7f3bb55b7e00)
04-01 20:34:13.242 19666-19682/yuanqi.android.terminalservice.app E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
04-01 20:34:13.242 19666-19682/yuanqi.android.terminalservice.app E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
04-01 20:34:13.269 19666-19684/yuanqi.android.terminalservice.app I/AndServer: Loading com.yanzhenjie.andserver.register.AdapterRegister.
04-01 20:34:13.270 19666-19684/yuanqi.android.terminalservice.app I/AndServer: Loading com.yanzhenjie.andserver.register.WebsiteRegister.
04-01 20:34:13.342 19666-19682/yuanqi.android.terminalservice.app D/EGL_emulation: eglMakeCurrent: 0x7f3bb7849500: ver 3 0 (tinfo 0x7f3bb55b7e00)
04-01 20:34:13.348 19666-19676/yuanqi.android.terminalservice.app I/art: Background sticky concurrent mark sweep GC freed 4394(251KB) AllocSpace objects, 0(0B) LOS objects, 9% free, 2027KB/2MB, paused 31.166ms total 102.581ms
04-01 20:34:13.514 19666-19676/yuanqi.android.terminalservice.app I/art: Background partial concurrent mark sweep GC freed 4997(495KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 1713KB/2MB, paused 6.308ms total 42.109ms
04-01 20:34:13.624 19666-19666/yuanqi.android.terminalservice.app I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
04-01 20:34:13.675 19666-19688/yuanqi.android.terminalservice.app W/HttpThreadTask: 该下载不支持断点
04-01 20:34:13.716 19666-19688/yuanqi.android.terminalservice.app E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.TaskException: 任务【hello.php】下载失败，filePath: /storage/emulated/0/hello.php, url: http://192.168.50.155/index_.php
    length=8192; regionStart=0; regionLength=-1
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:134)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:51)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    java.lang.Thread.run(Thread.java:818)
    ===================================================
04-01 20:34:13.716 19666-19688/yuanqi.android.terminalservice.app E/AbsThreadTask: 任务【hello.php】执行失败
04-01 20:34:13.773 19666-19688/yuanqi.android.terminalservice.app W/System.err: com.arialyy.aria.exception.TaskException: Aria Task Exception:, 任务【hello.php】执行失败
04-01 20:34:13.782 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.handleFailState(AbsThreadTask.java:490)
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: │ Thread: main
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: │ ServerService$1.onStarted  (ServerService.java:30)
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: │    LogUtil.d  (LogUtil.java:64)
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
04-01 20:34:13.802 19666-19666/yuanqi.android.terminalservice.app D/TSA: │ Http Server已启动,ip:::
04-01 20:34:13.803 19666-19666/yuanqi.android.terminalservice.app D/TSA: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:391)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:372)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:133)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:51)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-01 20:34:13.813 19666-19688/yuanqi.android.terminalservice.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-01 20:34:13.866 19666-19666/yuanqi.android.terminalservice.app D/tag: onTaskStart,-1
04-01 20:34:13.866 19666-19666/yuanqi.android.terminalservice.app D/tag: onTaskRunning,0
04-01 20:34:18.867 19666-19692/yuanqi.android.terminalservice.app D/AbsSchedulers: 任务【hello.php】开始重试
04-01 20:34:18.880 19666-19666/yuanqi.android.terminalservice.app D/tag: onPre,/storage/emulated/0/hello.php
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at java.io.File.createNewFile(File.java:939)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:196)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:129)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:82)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at libcore.io.Posix.open(Native Method)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err:     at java.io.File.createNewFile(File.java:932)
04-01 20:34:18.889 19666-19694/yuanqi.android.terminalservice.app W/System.err: 	... 7 more
04-01 20:34:18.891 19666-19695/yuanqi.android.terminalservice.app I/AbsThreadTask: 任务【hello.php】已中断
04-01 20:34:18.893 19666-19695/yuanqi.android.terminalservice.app I/AbsFileer: 文件【/storage/emulated/0/hello.php】错误，任务重新开始
04-01 20:34:19.000 19666-19696/yuanqi.android.terminalservice.app W/HttpThreadTask: 该下载不支持断点
04-01 20:34:19.010 19666-19696/yuanqi.android.terminalservice.app E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.TaskException: 任务【hello.php】下载失败，filePath: /storage/emulated/0/hello.php, url: http://192.168.50.155/index_.php
    length=8192; regionStart=0; regionLength=-1
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:134)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:51)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    java.lang.Thread.run(Thread.java:818)
    ===================================================
04-01 20:34:19.010 19666-19696/yuanqi.android.terminalservice.app E/AbsThreadTask: 任务【hello.php】执行失败
04-01 20:34:19.011 19666-19666/yuanqi.android.terminalservice.app D/tag: onTaskStart,-1
04-01 20:34:19.011 19666-19666/yuanqi.android.terminalservice.app D/tag: onTaskRunning,0
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err: com.arialyy.aria.exception.TaskException: Aria Task Exception:, 任务【hello.php】执行失败
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.handleFailState(AbsThreadTask.java:490)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:391)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:372)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:133)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:51)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-01 20:34:19.030 19666-19696/yuanqi.android.terminalservice.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-01 20:34:19.034 19666-19666/yuanqi.android.terminalservice.app D/AbsTaskQueue: 从执行池删除任务【hello.php】成功
04-01 20:34:19.036 19666-19666/yuanqi.android.terminalservice.app I/AbsSchedulers: 没有等待中的任务
04-01 20:34:19.037 19666-19666/yuanqi.android.terminalservice.app D/tag: onTaskFail,

**Comment by AriaLyy** [comment]
你的保存路径问题导致的，`/storage/emulated/0/hello.php`, android根路径没有`/storage/`

**Comment by aellenlei** [comment]
首先我用的是模拟器，然后我是使用

> Environment.getExternalStorageDirectory().getAbsolutePath() + "/hello.php"

来指定路径的，不是我随手写的一个路径。

**Comment by aellenlei** [comment]
@AriaLyy 这个应该不是路径的问题，同时我查看模拟器内部存储，可以看到该文件创建了，但是文件大小为0，无法写入。

**Comment by AriaLyy** [comment]
1、你申请文件读写权限没有？
2、使用`/mnt/sdcard/`这个目录测试下

**Comment by AriaLyy** [comment]
还有一点，如果是android自带的模拟器，检查下你分配的内存
