### ISSUE TITLE
e: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/kapt3/base/util/KaptLogger

### ISSUE THREAD

**Issue by h93910** [AriaLyy/Aria#376]
## Aria版本
3.6.2

## 什么问题
kotlin用kapt,加了
apply plugin: 'kotlin-kapt'

    implementation 'com.arialyy.aria:aria-core:3.6.2'
    kapt 'com.arialyy.aria:aria-compiler:3.6.2'

出现
e: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/kapt3/base/util/KaptLogger

**Comment by h93910** [comment]
ext.kotlin_version = '1.3.21'

**Comment by AriaLyy** [comment]
感觉像是kapt没有下载下来，翻墙同步试试

**Comment by h93910** [comment]
的确是,按例子的project build.gradle 改了一下,再把.gradle\caches 删了再重新下过一次就行了
谢谢作者回复 :D
