### ISSUE TITLE
下载任务无法删除

### ISSUE THREAD

**Issue by nwhhades** [AriaLyy/Aria#377]
## Aria版本
3.6.2

## 什么问题
任务下载完成后，手动将文件删除。此时无法正常删除任务、重新下载任务。

## 如何复现此问题
下载完成后，手动将文件删除

## 控制台日志
删除任务log:
04-02 12:31:25.992 1755-1755/cn.whiner.orange9 E/DownloadTarget: 下载失败，文件保存路径【f8ec9bde731147879de8b3540e0fc8d9】错误

重新下载任务log:这里确认是同一个任务
04-02 12:24:50.362 32141-32141/cn.whiner.orange9 E/DownloadTarget: 下载失败，保存路径【/storage/emulated/0/Android/data/cn.whiner.orange9/files/Download/叹云兮.mp3】已经被其它任务占用，请设置其它保存路径

**Comment by AriaLyy** [comment]
你是如何调用删除的？
看你日志的时间，第二个是路径冲突了

**Comment by nwhhades** [comment]
这是代码
Aria.download(HifiActivity.this).load(mUrl).cancel(false);
                
Aria.download(HifiActivity.this)
                        .load(mUrl)//读取下载地址
                        .resetState()
                        .setFilePath(path)//设置文件保存的完整路径
                        .start();

**Comment by AriaLyy** [comment]
找到问题了，是这个版本数据库优化后，搜索参数没有解码导致的

**Comment by AriaLyy** [comment]
`3.6.3`版本已经修复了这个问题
