### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by h93910** [AriaLyy/Aria#378]
## Aria版本
3.6.3

## 什么问题
下载文件时程序崩溃,不知是不是多线程的问题还是别的什么,我把线程改为1,useBlock value="false"  也还是会出现

## 如何复现此问题
从日志上看到有个Could not read input channel file descriptors from parcel.这样的问题
我下载的文件使用的名称和真实下载的名字不一样,我把它改为无后缀的文件,不知是不是这出了问题

## 控制台日志
2019-04-06 16:12:25    AbsThreadTask    
msg【】
Exception：ExceptionDetailed:
====================Exception Info====================
com.arialyy.aria.exception.TaskException: Aria Task Exception:, 任务【20190301】执行失败
com.arialyy.aria.core.common.AbsThreadTask.handleFailState(AbsThreadTask.java:490)
com.arialyy.aria.core.common.AbsThreadTask.retryThis(AbsThreadTask.java:414)
com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:387)
com.arialyy.aria.core.common.AbsThreadTask.fail(AbsThreadTask.java:372)
com.arialyy.aria.core.download.downloader.HttpThreadTask.readDynamicFile(HttpThreadTask.java:192)
com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:110)
com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:51)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:764)
===================================================

2019-04-06 23:55:22    main    
msg【】
Exception：ExceptionDetailed:
====================Exception Info====================
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
android.view.InputChannel.nativeReadFromParcel(Native Method)
android.view.InputChannel.readFromParcel(InputChannel.java:148)
android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:804)
android.view.ViewRootImpl.setView(ViewRootImpl.java:726)
android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
android.widget.Toast$TN.handleShow(Toast.java:496)
android.widget.Toast$TN$1.handleMessage(Toast.java:400)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6494)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
===================================================

**Comment by h93910** [comment]
加了后缀也不行,用的模拟器
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
E/EGL_emulation: tid 4847: init(382): error 0x3003 (EGL_BAD_ALLOC)
E/EGL_emulation: tid 4847: eglCreateWindowSurface(922): error 0x3003 (EGL_BAD_ALLOC)
A/OpenGLRenderer: Failed to create EGLSurface for window 0x7b12e008, eglErr = EGL_BAD_ALLOC
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4847 (RenderThread), pid 4792 (ban.adultcomics)

**Comment by AriaLyy** [comment]
https://blog.csdn.net/xunmeng_93/article/details/78484640

**Comment by h93910** [comment]
> https://blog.csdn.net/xunmeng_93/article/details/78484640

谢谢回复,昨天已经找到问题点了,是我自己的问题,在   @com.arialyy.annotations.Download.onTaskRunning 里做太多事了,就崩了

**Comment by AriaLyy** [comment]
taskrunning 默认是1s执行一次的，建议不要在这个回调中做繁重的操作..

**Comment by h93910** [comment]
> taskrunning 默认是1s执行一次的，建议不要在这个回调中做繁重的操作..

是的呢,改掉了下载就很顺利了
