### ISSUE TITLE
android.database.sqlite.SQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by fadedHYC** [AriaLyy/Aria#379]
android.database.sqlite.SQLiteDatabaseLockedException
database is locked (code 5): , while compiling: PRAGMA journal_mode
com.arialyy.aria.orm.SqlHelper.init(SqlHelper.java:53)

![image](https://user-images.githubusercontent.com/22925521/55769079-f6edc680-5ab1-11e9-8984-11e6f0a63d0d.png)

![image](https://user-images.githubusercontent.com/22925521/55769091-0836d300-5ab2-11e9-8f24-fa6982e071a5.png)

**Comment by AriaLyy** [comment]
哪一个版本的下载库？
用最新版本的下载库看看

**Comment by fadedHYC** [comment]
使用最新版本最新版本

**Comment by fadedHYC** [comment]
报错机型很多

**Comment by AriaLyy** [comment]
使用`3.6.4_dev_1`这个版本看看

**Comment by fadedHYC** [comment]
在bugly日志统计中发现两个bug


1.




2.

**Comment by AriaLyy** [comment]
什么bug？？？

**Comment by fadedHYC** [comment]
![image](https://user-images.githubusercontent.com/22925521/56479628-0248e500-64e9-11e9-91e4-253386bd343b.png)
![image](https://user-images.githubusercontent.com/22925521/56479638-0f65d400-64e9-11e9-8ff1-f1da241c3ba8.png)

**Comment by fadedHYC** [comment]
![image](https://user-images.githubusercontent.com/22925521/56479657-1db3f000-64e9-11e9-91c7-615730936310.png)
![image](https://user-images.githubusercontent.com/22925521/56479662-21477700-64e9-11e9-8964-c07fef541b2c.png)

**Comment by fadedHYC** [comment]
在bugly上看到的bug统计日志

**Comment by AriaLyy** [comment]
使用`3.6.4`观察看看呢，地区切换做了下处理
![image](https://user-images.githubusercontent.com/10437293/57991711-3660f700-7ae3-11e9-9356-b2003cb94433.png)

**Comment by fadedHYC** [comment]
手机：小米mxa2
------------------ 原始邮件 ------------------
发件人: "lyy"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 下午3:31
收件人: "AriaLyy/Aria"<Aria@noreply.github.com>;
抄送: "恢恢黑夜"<1339868776@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AriaLyy/Aria]android.database.sqlite.SQLiteDatabaseLockedException (#379)




Closed #379.
