### ISSUE TITLE
组下载时，可否不设置组文件的大小

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#380]
## Aria版本
3.6.3

## 什么问题
在组下载时，要使用setFileSize方法设置总任务文件的大小，但是这里有的时候并获取不到，只是有下载的地址，这里如何不设置文件大小，也能正确显示下载百分比？目前随便写文件大小导致下载百分比显示不准

**Comment by AriaLyy** [comment]
老版本支持，新版本不支持了，如果组合任务的文件多的话，会卡住很久

**Comment by lyxc** [comment]
可是如果随便写个文件大小的话，那个百分比显示不准确，经常回出现300%之类的数字，有什么好的方式可以解决？

**Comment by AriaLyy** [comment]
3.6.4_dev_3 新增了`unknownSize()`，用于处理组合任务大小未知的情况
