### ISSUE TITLE
下载logo有时候失败

### ISSUE THREAD

**Issue by wenxueyangx** [AriaLyy/Aria#381]
## Aria版本
3.4.9

## 什么问题
我下载logo有时候会下载不成功

## 控制台日志
04-03 16:17:59.175688  4658  4658 I AbsSchedulers: 没有下一任务
04-03 16:17:59.194542  4658  5392 W DownloadTask: ExceptionDetailed:
04-03 16:17:59.194542  4658  5392 W DownloadTask: ====================Exception Info====================
04-03 16:17:59.194542  4658  5392 W DownloadTask: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
04-03 16:17:59.194542  4658  5392 W DownloadTask: android.os.Handler.<init>(Handler.java:200)
04-03 16:17:59.194542  4658  5392 W DownloadTask: android.os.Handler.<init>(Handler.java:128)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.download.DownloadTask$Builder.setOutHandler(DownloadTask.java:160)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:108)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:66)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:113)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:36)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.command.normal.AbsNormalCmd.createTask(AbsNormalCmd.java:184)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.command.normal.StartCmd.executeCmd(StartCmd.java:70)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.AriaManager.exe(AriaManager.java:218)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:221)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.cloudminds.airobot.f.d.a(DownloadManagerUtils.java:49)
04-03 16:17:59.194542  4658  5392 W DownloadTask: com.cloudminds.airobot.service.a$31.run(AiManager.java:4809)
04-03 16:17:59.194542  4658  5392 W DownloadTask: java.lang.Thread.run(Thread.java:761)
04-03 16:17:59.194542  4658  5392 W DownloadTask: ===================================================
04-03 16:17:59.194846  4658  5392 D BaseCachePool: 任务【logo.png】进入缓存队列成功
04-03 16:17:59.195117  4658  5392 D BaseExecutePool: 任务【logo.png】进入执行队列成功
04-03 16:17:59.213955  4658  4658 D AiRobot : download pre:
04-03 16:17:59.278677  4658  5399 D CommonUtil: 创建文件成功:/storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-03 16:17:59.331341  4658  4658 D AiRobot : download start
04-03 16:17:59.333362  4658  4658 D AiRobot : download app running 0
04-03 16:17:59.333996  4658  5400 D HttpThreadTask: 任务【logo.png】线程__0__开始下载【开始位置 : 0，结束位置：118076】
04-03 16:17:59.366841  2230  2261 I QtiTetherService: limitReached Alert received limitName: globalAlert on Interface: lo
04-03 16:17:59.370800  4795  4795 D OVPN:   : PID_ERR replay-window backtrack occurred [5] [SSL-0] [0_0_0_0000000000000000000000000000000000000000000000000000000000] 0:1128 0:1123 t=1554279479[0] r=[-1,64,15,5,1] sl=[24,64,64,528]
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting: getTetherStats() called NetworkStats: elapsedRealtime=259878
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [0] iface=tun0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=117519 rxPackets=752 txBytes=18453 txPackets=256 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [1] iface=tun0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [2] iface=tun0 uid=1000 set=DEFAULT tag=0x0 roaming=NO rxBytes=76 rxPackets=1 txBytes=41404 txPackets=493 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [3] iface=tun0 uid=1000 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [4] iface=tun0 uid=10007 set=DEFAULT tag=0x0 roaming=NO rxBytes=386 rxPackets=3 txBytes=726 txPackets=5 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [5] iface=tun0 uid=10007 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [6] iface=tun0 uid=10024 set=DEFAULT tag=0x0 roaming=NO rxBytes=10223 rxPackets=21 txBytes=2788 txPackets=22 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [7] iface=tun0 uid=10024 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [8] iface=tun0 uid=10085 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=352 txPackets=7 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [9] iface=tun0 uid=10085 set=FOREGROUND tag=0x0 roaming=NO rxBytes=148466 rxPackets=635 txBytes=663614 txPackets=691 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [10] iface=wlan0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=47232 rxPackets=420 txBytes=17058 txPackets=144 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [11] iface=wlan0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [12] iface=wlan0 uid=1000 set=DEFAULT tag=0x0 roaming=NO rxBytes=37447 rxPackets=29 txBytes=15283 txPackets=207 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [13] iface=wlan0 uid=1000 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [14] iface=wlan0 uid=10007 set=DEFAULT tag=0x0 roaming=NO rxBytes=386 rxPackets=3 txBytes=726 txPackets=5 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [15] iface=wlan0 uid=10007 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [16] iface=wlan0 uid=10024 set=DEFAULT tag=0x0 roaming=NO rxBytes=10510 rxPackets=20 txBytes=1523 txPackets=20 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [17] iface=wlan0 uid=10024 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [18] iface=wlan0 uid=10085 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=1038 txPackets=10 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [19] iface=wlan0 uid=10085 set=FOREGROUND tag=0x0 roaming=NO rxBytes=2363 rxPackets=38 txBytes=13996 txPackets=115 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [20] iface=wlan0 uid=10086 set=DEFAULT tag=0x0 roaming=NO rxBytes=35107 rxPackets=169 txBytes=68526 txPackets=491 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [21] iface=wlan0 uid=10086 set=FOREGROUND tag=0x0 roaming=NO rxBytes=891336 rxPackets=4120 txBytes=1611774 txPackets=5496 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [22] iface=rndis0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=576 txPackets=6 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [23] iface=rndis0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [24] iface=rndis0 uid=10085 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=360 txPackets=6 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [25] iface=rndis0 uid=10085 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=3660 txPackets=61 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [26] iface=dummy0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=168 txPackets=3 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [27] iface=dummy0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [28] iface=rmnet_data7 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=216 rxPackets=3 txBytes=724 txPackets=10 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [29] iface=rmnet_data7 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [30] iface=lo uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=4953 rxPackets=51 txBytes=8217 txPackets=83 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [31] iface=lo uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-03 16:17:59.404629  1568  1955 I TetherStatsReporting:   [32] iface=lo uid=10085 set=DEFAULT tag=0x0 roaming=NO rxBytes=264 rxPackets=3 txBytes=0 txPackets=
04-03 16:17:59.404674  1568  1955 I TetherStatsReporting: combining tether stats
04-03 16:17:59.405551  2230  2257 D QtiTetherService/IpaWrapper: getStats(false)
--------- switch to events
04-03 16:17:59.407322  1568  1955 I netstats_mobile_sample: [0,0,0,0,0,0,0,0,0,0,0,0,1554279479411]
04-03 16:17:59.407464  1568  1955 I netstats_wifi_sample: [1073535,5078,1828172,6535,1070895,5030,1736486,6528,1023681,4797,1729764,6486,1554279479411]
--------- switch to main
04-03 16:17:59.408794  4658  4658 D AiRobot : download start
04-03 16:17:59.410176  4658  5405 D HttpThreadTask: 任务【logo.png】线程__0__开始下载【开始位置 : 0，结束位置：118076】
04-03 16:17:59.410548  4658  4658 D AiRobot : download app running 0
04-03 16:17:59.516324  4658  5400 I HttpThreadTask: 任务【logo.png】线程__0__下载完毕
04-03 16:17:59.584734  4658  5400 D StateConstance: fail_num=0; start_thread_num=1; complete_num=1
04-03 16:17:59.585597  4658  4658 D AbsTaskQueue: 从执行池删除任务【logo.png】成功
04-03 16:17:59.586215  4658  4658 D AbsSchedulers: complete_next
04-03 16:17:59.588325  4658  4658 I AbsSchedulers: 没有下一任务
04-03 16:17:59.589122  4658  4658 D AiRobot : download done http://10.155.0.135:30536/data/apn_wifi_test/image/1173048e-f47e-44e3-9ab5-63df3d36a575.jpg
04-03 16:17:59.601521  4658  5405 I HttpThreadTask: 任务【logo.png】线程__0__下载完毕
04-03 16:17:59.636452  4658  5405 D StateConstance: fail_num=0; start_thread_num=1; complete_num=1
04-03 16:17:59.659556  4658  4658 D BaseCachePool: 任务【logo.png】进入缓存队列成功
04-03 16:17:59.692099  4658  4658 D skia    : libjpeg error 117 <Corrupt JPEG data: premature end of data segment> from output_message
04-03 16:17:59.692508  4658  4658 D skia    : libjpeg error 61 <Invalid JPEG file structure: two SOI markers> from output_message
04-03 16:17:59.692565  4658  4658 D skia    : libjpeg error 61 <Invalid JPEG file structure: two SOI markers> from setjmp
04-03 16:17:59.692606  4658  4658 D skia    : --- codec->getAndroidPixels() failed.
04-03 16:17:59.693938  4658  4658 D AbsTaskQueue: 从缓存池删除任务【logo.png】成功
04-03 16:17:59.694009  4658  4658 D AbsSchedulers: complete_next
04-03 16:17:59.695311  4658  4658 I AbsSchedulers: 没有下一任务
04-03 16:17:59.695694  4658  4658 D AiRobot : download done http://10.155.0.135:30536/data/apn_wifi_test/image/1173048e-f47e-44e3-9ab5-63df3d36a575.jpg
04-03 16:17:59.702620  4658  4658 E DownloadTarget: 下载失败，文件保存路径【966a5379208145238d30e1987447f1b8】错误
04-03 16:17:59.729271  4658  4658 D skia    : libjpeg error 117 <Corrupt JPEG data: premature end of data segment> from output_message
04-03 16:17:59.729711  4658  4658 D skia    : libjpeg error 61 <Invalid JPEG file structure: two SOI markers> from output_message
04-03 16:17:59.729775  4658  4658 D skia    : libjpeg error 61 <Invalid JPEG file structure: two SOI markers> from setjmp
04-03 16:17:59.729804  4658  4658 D skia    : --- codec->getAndroidPixels() failed.

**Comment by AriaLyy** [comment]
升级到新版本
