### ISSUE TITLE
这个是什么原因

### ISSUE THREAD

**Issue by kangqin** [AriaLyy/Aria#382]
Error inserting stopTime=0 fileName=57836banner1293975bf54d676553e.png isComplete=false isGroupChild=true downloadPath=%2Fstorage%2Femulated%2F0%2Flinkun.com.newbluetoothscale%2F57836banner1293975bf54d676553e.png url=http%3A%2F%2Fimg.linkunst.com%2F53%2F20181121%2F57836banner1293975bf54d676553e.png fileSize=1 groupName=cdade598ba40180b2addc5b12fc017a0 state=3 percent=0 currentProgress=0 isRedirect=false completeTime=0

**Comment by AriaLyy** [comment]
哪个版本，如何重现？
