### ISSUE TITLE
组下载文件手机端删除后，再次下载，不重命名

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#383]
## Aria版本
3.6.2

## 什么问题
在组下载文件成功之后，删除手机端本地文件，然后再次执行下载操作，文件在下载过程中不重新命名了，下载后的文件是下载地址中原文件的名字。将设置--应用中，将APP的数据清除后，再次下载，可重命名正常下载。

## 如何复现此问题
下载代码：
        JSONObject extentJson = new JSONObject();
        extentJson.put("materalid",materialid);
        extentJson.put("materialname",materialname);
        if (Aria.download(this).taskExists(mUrls)){
            Aria.download(this).loadGroup(mUrls).removeRecord();
        }
        Aria.download(this)
                .loadGroup(mUrls)
                .setDirPath(filePath)
                .setGroupAlias("主任会议材料下载")
                .setSubFileName(nameUrls)
                .setExtendField(extentJson.toString())
                .setFileSize(2000)
                .start();

**Comment by lyxc** [comment]
另外，还有一个问题，APP之前使用过的是3.3.10版本，现在升级至3.6.2版本之后，APP自动更新也会出现上面的问题。该框架升级之后只能讲APP卸载重装或清除数据吗？不能自动更新升级？

**Comment by AriaLyy** [comment]
使用`3.6.4_dev_1`

**Comment by iurgnid** [comment]
> 使用`3.6.4_dev_1`

也遇到了组下载文件，手机端删除后，再次下载，不重命名的问题
                Aria.download(getActivity())
                        .loadGroup(urls)  
                        .setDirPath(FileDir.getVideoName()) 
                        .setGroupAlias("advert")
                        .setSubFileName(names)
                        .unknownSize()
                        .start(); 
看日志然后断点，发现会进入 HttpGroupDelegatelei的 updateSingleSubFileName()方法
          if (DbEntity.checkDataExist(DownloadEntity.class, "downloadPath=? or isComplete='true'",
              newPath)) {
            ALog.w(TAG, String.format("更新文件名失败，路径【%s】已存在或文件已下载", newPath));
            return;
          }
现在本地已经删了，重新下载就变成下载地址的名字，不重新命名了，求解决方案
