### ISSUE TITLE
华为手机：SendBroadcastPermission: action:ARIA_TASK_INFO_ACTION, mPermissionType:0

### ISSUE THREAD

**Issue by keyoumi** [AriaLyy/Aria#387]
## Aria版本
最新版本

## 什么问题
SendBroadcastPermission: action:ARIA_TASK_INFO_ACTION, mPermissionType:0

## 如何复现此问题
使用华为手机调用api

## 控制台日志
SendBroadcastPermission: action:ARIA_TASK_INFO_ACTION, mPermissionType:0

**Comment by AriaLyy** [comment]
调用的是哪个api？
