### ISSUE TITLE
有的地址 用pc浏览器或手机浏览器可以下载  用aria提示下载失败   

### ISSUE THREAD

**Issue by Mr-PolarBear** [AriaLyy/Aria#389]
## Aria版本
3.6.3

## 什么问题
有的地址 用pc浏览器或手机浏览器可以下载  用aria提示下载失败 

## 如何复现此问题

              chuned 适配的问题

**Comment by AriaLyy** [comment]
使用`3.6.4_dev_2`版本

**Comment by Mr-PolarBear** [comment]
thanks
