### ISSUE TITLE
Gradle升级到3.4.0后 @Download注解报错

### ISSUE THREAD

**Issue by kokobebekoko** [AriaLyy/Aria#391]
## Aria版本

3.5.4
## 什么问题
Gradle升级到3.4.0后 @Download注解报错

## 控制台日志

![image](https://user-images.githubusercontent.com/5987097/57190284-1f4ed080-6f4b-11e9-8838-e5c5a631cfa4.png)

**Comment by AriaLyy** [comment]
清空gradle的缓存，重新引入看看

**Comment by liuguangbanzang** [comment]
现在能行了吗？我也遇到这个问题

**Comment by kokobebekoko** [comment]
aria也要升级下




 
---原始邮件---
发件人: "liuguangbanzang"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 下午4:56
收件人: "AriaLyy/Aria"<Aria@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"kokobebekoko"<617347215@qq.com>;
主题: Re: [AriaLyy/Aria] Gradle升级到3.4.0后 @Download注解报错 (#391)



现在能行了吗？我也遇到这个问题

**Comment by kokobebekoko** [comment]
aria也要升级下


 
---原始邮件---
发件人: "liuguangbanzang"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 下午4:56
收件人: "AriaLyy/Aria"<Aria@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"kokobebekoko"<617347215@qq.com>;
主题: Re: [AriaLyy/Aria] Gradle升级到3.4.0后 @Download注解报错 (#391)



现在能行了吗？我也遇到这个问题

**Comment by liuguangbanzang** [comment]
> aria也要升级下
> […](#)
> ---原始邮件--- 发件人: "liuguangbanzang"<notifications@github.com> 发送时间: 2019年6月25日(星期二) 下午4:56 收件人: "AriaLyy/Aria"<Aria@noreply.github.com>; 抄送: "Author"<author@noreply.github.com>;"kokobebekoko"<617347215@qq.com>; 主题: Re: [AriaLyy/Aria] Gradle升级到3.4.0后 @Download注解报错 (#391) 现在能行了吗？我也遇到这个问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

升级到3.6.4 也是一样的

**Comment by kokobebekoko** [comment]
as什么版本的？------------------ 原始邮件 ------------------
发件人: "liuguangbanzang"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 晚上6:49
收件人: "AriaLyy/Aria"<Aria@noreply.github.com>;
抄送: "kokobebekoko"<617347215@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AriaLyy/Aria] Gradle升级到3.4.0后 @Download注解报错 (#391)


 
aria也要升级下
 …
 ---原始邮&#x4EF6;--- 发&#x4EF6;人: "liuguangbanzang"notifications@github.com 发送时间: 2019年6月25日(星期&#x4E8C;) 下午4:56 收&#x4EF6;人: "AriaLyy/Aria"Aria@noreply.github.com; 抄送: "Author"author@noreply.github.com;"kokobebekoko"617347215@qq.com; 主题: Re: [AriaLyy/Aria] Gradle升级到3.4.0后 @Download注解报错 (#391) 现在能行了吗？我也遇到这个问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
升级到3.6.4 也是一样的
 
&mdash;
