### ISSUE TITLE
不同下载资源地址指向同一个下载的路径

### ISSUE THREAD

**Issue by wenxueyangx** [AriaLyy/Aria#392]
## Aria版本
3.4.9

## 什么问题

如果第一个下载的url不可用，但紧接着又提供了一个可用的url地址，但是他们指向的下载保存路径是一个，这样导致了可用的下载地址也下载不成功
## 控制台日志
04-29 17:08:15.555615 11117 11238 D AppConfigSetting: to load logo http://10.155.0.110:31154/data/
04-29 17:08:15.558141 11117 11238 D DownloadMgrUtils: delete filePath is /storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-29 17:08:15.561042 11117 11238 D DownloadMgrUtils: delete filePath success 
04-29 17:08:15.561161 11117 11238 D DownloadMgrUtils: download file url ishttp://10.155.0.110:31154/data/ *** storage file is /storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-29 17:08:15.615234 11117 11238 D BaseCachePool: 任务【logo.png】进入缓存队列成功
04-29 17:08:15.615482 11117 11238 D BaseExecutePool: 任务【logo.png】进入执行队列成功
04-29 17:08:15.616433 11117 11238 D AppConfigSetting: getAppConfigSetting{"data":{"gasket":{"closing":["不好意思，请换个问题把"],"consultingDelay":2,"endDelay":3,"gasketEnable":true,"language":"CH","openDelay":1,"opening":["让我想想"]},"greeting":{"offLineModeHintEN":["I am offline and cannot provide service"],"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"]},"logo":{"url":"http://10.155.0.110:31154/data/","version":7},"version":34},"type":"appConfig"}
04-29 17:08:15.644359 11117 11238 D AiRobot : download pre:
04-29 17:08:15.677264   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:15.785445 11117 13844 D HttpFileInfoThread: 30x跳转，新url为【null】
04-29 17:08:15.820287 11117 11238 D AbsTaskQueue: 从执行池删除任务【logo.png】成功
04-29 17:08:15.820605 11117 11238 D AbsSchedulers: fail_next
04-29 17:08:15.822156 11117 11238 I AbsSchedulers: 没有下一任务
04-29 17:08:15.909613  2348  2382 I QtiTetherService: limitReached Alert received limitName: globalAlert on Interface: lo
04-29 17:08:15.926975 11117 11117 E TEST    : getHariServiceConnector: 
04-29 17:08:15.935909  4103 13820 I RobotStateMonitor: PingStats{id=55, lost=0, pings=20, aver=93.67354, min=89.915, max=108.824, ia=/47.105.146.7, port=30295, useTcp=false}
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting: getTetherStats() called NetworkStats: elapsedRealtime=3175109
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [0] iface=tun0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=14370710 rxPackets=26819 txBytes=224338 txPackets=2813 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [1] iface=tun0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [2] iface=tun0 uid=1000 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=392028 txPackets=4667 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [3] iface=tun0 uid=1000 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [4] iface=tun0 uid=10006 set=DEFAULT tag=0x0 roaming=NO rxBytes=6176 rxPackets=48 txBytes=11696 txPackets=80 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [5] iface=tun0 uid=10006 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [6] iface=tun0 uid=10023 set=DEFAULT tag=0x0 roaming=NO rxBytes=4936 rxPackets=12 txBytes=2132 txPackets=15 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [7] iface=tun0 uid=10023 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [8] iface=tun0 uid=10081 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=40 txPackets=1 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [9] iface=tun0 uid=10081 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [10] iface=tun0 uid=10116 set=DEFAULT tag=0x0 roaming=NO rxBytes=6774 rxPackets=68 txBytes=925523 txPackets=1606 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [11] iface=tun0 uid=10116 set=FOREGROUND tag=0x0 roaming=NO rxBytes=5384376 rxPackets=11298 txBytes=44936202 txPackets=123841 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [12] iface=tun0 uid=10117 set=DEFAULT tag=0x0 roaming=NO rxBytes=331 rxPackets=4 txBytes=82646 txPackets=64 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [13] iface=tun0 uid=10117 set=FOREGROUND tag=0x0 roaming=NO rxBytes=6201 rxPackets=74 txBytes=8927026 txPackets=6772 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [14] iface=wlan0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=133836 rxPackets=913 txBytes=32440 txPackets=264 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [15] iface=wlan0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [16] iface=wlan0 uid=1000 set=DEFAULT tag=0x0 roaming=NO rxBytes=34142 rxPackets=31 txBytes=19696 txPackets=246 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [17] iface=wlan0 uid=1000 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [18] iface=wlan0 uid=9999 set=DEFAULT tag=0x0 roaming=NO rxBytes=122 rxPackets=1 txBytes=58 txPackets=1 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [19] iface=wlan0 uid=9999 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [20] iface=wlan0 uid=10006 set=DEFAULT tag=0x0 roaming=NO rxBytes=772 rxPackets=6 txBytes=1462 txPackets=10 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [21] iface=wlan0 uid=10006 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [22] iface=wlan0 uid=10023 set=DEFAULT tag=0x0 roaming=NO rxBytes=19309 rxPackets=34 txBytes=2678 txPackets=32 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [23] iface=wlan0 uid=10023 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [24] iface=wlan0 uid=10081 set=DEFAULT tag=0x0 roaming=NO rxBytes=623 rxPackets=4 txBytes=667 txPackets=5 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [25] iface=wlan0 uid=10081 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [26] iface=wlan0 uid=10116 set=DEFAULT tag=0x0 roaming=NO rxBytes=14990 rxPackets=118 txBytes=64569 txPackets=305 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [27] iface=wlan0 uid=10116 set=FOREGROUND tag=0x0 roaming=NO rxBytes=27945 rxPackets=82 txBytes=45246 txPackets=346 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [28] iface=wlan0 uid=10117 set=DEFAULT tag=0x0 roaming=NO rxBytes=18735 rxPackets=127 txBytes=21158 txPackets=149 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [29] iface=wlan0 uid=10117 set=FOREGROUND tag=0x0 roaming=NO rxBytes=7703833 rxPackets=22391 txBytes=5071490 txPackets=19372 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [30] iface=rndis0 uid=0 set=DEFAULT tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=480 txPackets=5 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [31] iface=rndis0 uid=0 set=FOREGROUND tag=0x0 roaming=NO rxBytes=0 rxPackets=0 txBytes=0 txPackets=0 operations=0
04-29 17:08:15.977112  1398  2068 I TetherStatsReporting:   [32] iface=rndis0 uid=10116 set=DEFAULT
04-29 17:08:15.977272  1398  2068 I TetherStatsReporting: combining tether stats
04-29 17:08:15.978763  2348  3853 D QtiTetherService/IpaWrapper: getStats(false)
--------- switch to events
04-29 17:08:16.006442  1398  2068 I netstats_mobile_sample: [0,0,0,0,0,0,0,0,0,0,0,0,1556528896008]
04-29 17:08:16.006681  1398  2068 I netstats_wifi_sample: [12533433,66730,77376291,174271,12171017,54572,74937479,174152,15810339,75777,120102098,298652,1556528896008]
--------- switch to main
04-29 17:08:16.009353 11306 11306 D OVPN:   : >BYTECOUNT:6085775,3517073
--------- switch to system
04-29 17:08:16.024524  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:16.033842  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:16.394884   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:16.599284   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:17.213714   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:17.418662   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:17.419240   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:17.725965   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:18.005667  2721  2721 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-29 17:08:18.006057 11306 11306 D OVPN:   : >BYTECOUNT:6087427,3539540
04-29 17:08:18.011738  2721  2721 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=62
--------- switch to system
04-29 17:08:18.030134  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:18.043987  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:18.341170   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:19.363976   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:19.446095 11117 11117 D AlarmPingSender: Sending Ping at:1556528899445
04-29 17:08:19.451941 11117 11117 D AlarmPingSender: Schedule next alarm at 1556528905917
04-29 17:08:19.452304 11117 11117 D AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 6466
04-29 17:08:20.002056 11306 11306 D OVPN:   : >BYTECOUNT:6089119,3561926
--------- switch to system
04-29 17:08:20.044760  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:20.073079  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:20.798386   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:20.900440   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:21.029382  2721  2721 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-29 17:08:21.035129  2721  2721 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=62
04-29 17:08:22.005408 11306 11306 D OVPN:   : >BYTECOUNT:6090811,3584312
--------- switch to system
04-29 17:08:22.037140  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:22.046965  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:22.538903   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:23.461251   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:23.461822   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:24.008354 11306 11306 D OVPN:   : >BYTECOUNT:6092503,3606698
04-29 17:08:24.045563  2721  2721 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-29 17:08:24.048789  2721  2721 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=62
--------- switch to system
04-29 17:08:24.050993  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:24.063974  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:24.382569   898   898 I cnss-daemon: RTM_NEWROUTE Indication
04-29 17:08:24.946541 11117 11367 D HS/WSChannelClient: WSS->C: {"id":"heartbeatResponse","sid":"2d7e7af0-6a5c-11e9-af28-4136301fe5a5","from":"hariSwitch","to":"cqtest","seq":358857,"ver":"1.5.0"}
04-29 17:08:25.922978 11117 11117 D AlarmPingSender: Sending Ping at:1556528905922
04-29 17:08:25.927186 11117 11117 D AlarmPingSender: Schedule next alarm at 1556528915927
04-29 17:08:25.927444 11117 11117 D AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 10000
04-29 17:08:25.932625 11117 11117 E TEST    : getHariServiceConnector: 
04-29 17:08:26.014189 11306 11306 D OVPN:   : >BYTECOUNT:6094734,3630079
04-29 17:08:26.019508 11117 11375 D AlarmPingSender: Success. Release lock(MqttService.client.0f98c22dcec5404aa9a5c4da0752a297):1556528906019
--------- switch to system
04-29 17:08:26.043646  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:26.060823  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:27.043148   898   898 I cnss-daemon: RTM_NEWNEIGH message received: 28
04-29 17:08:27.043346   898   898 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
04-29 17:08:27.059610  2721  2721 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-29 17:08:27.065162  2721  2721 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=62
04-29 17:08:28.003480 11306 11306 D OVPN:   : >BYTECOUNT:6097164,3653224
--------- switch to system
04-29 17:08:28.044629  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:28.053244  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:30.008238 11306 11306 D OVPN:   : >BYTECOUNT:6099516,3676288
--------- switch to system
04-29 17:08:30.026546  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:30.036314  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:30.074761  2721  2721 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-29 17:08:30.076797  2721  2721 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=62
04-29 17:08:31.023806 11117 11327 D CMTI/AiRobotApplication: mCurrentSpeechType:LOCAL  mSpeechType:LOCAL
04-29 17:08:31.024734 11117 11327 D CMTI/AiRobotApplication: a()
04-29 17:08:31.025072 11117 11327 D IFlyTekNativeService: startRecognizing(16000) isInitialized is true
04-29 17:08:31.025281 11117 11327 D IFlyTekNativeService: iflytek asr:
04-29 17:08:31.027315 11117 11327 D IFlyTekNativeService: session begin param: sub = iat, domain = iat, sample_rate = 16000, engine_type = local, mixed_threshold = 80, grm_build_path = /storage/emulated/0/msc/grammar, local_grammar = action, asr_res_path = fo|/data/app/com.cloudminds.pepper.hari-2/base.apk|98644|9781778, result_type = json, result_encoding = utf-8, vad_eos = 800, language = , accent = mandarin, asr_dwa = 1, dwa = 1, asr_ptt = 0, ptt = 1
04-29 17:08:31.925737  4103 13849 I RobotStateMonitor: PingStats{id=56, lost=0, pings=20, aver=95.634254, min=89.608, max=162.772, ia=/47.105.146.7, port=30295, useTcp=false}
04-29 17:08:32.009802 11306 11306 D OVPN:   : >BYTECOUNT:6101868,3699352
--------- switch to system
04-29 17:08:32.019081  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:32.026291  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:32.058223 11117 11327 D CMTI/AiRobotApplication: b()
04-29 17:08:32.058397 11117 11327 D IFlyTekNativeService: finishRecognizing(). current state:RUNNING
04-29 17:08:32.060413 11117 11327 D CMTI/AiRobotApplication: onEventSpeechRecognized()event =SPEECH_RECOGNIZED_RESULT
04-29 17:08:32.061782 11117 11327 D CMTI/AiRobotApplication: onEventSpeechRecognized()isFinal=false, text=hello Confidence is 12
04-29 17:08:32.062631 11117 11327 D CMTI/AiRobotApplication: b(): asrState=1isASREnable:true
04-29 17:08:32.063260 11117 11327 D CMTI/VoiceRecorder: Pipeline has stopped.
04-29 17:08:32.063594 11117 11327 D CMTI/AiRobotApplication: onEventSpeechRecognized()event =SPEECH_RECOGNIZED_RESULT
04-29 17:08:32.063738 11117 11327 D CMTI/AiRobotApplication: onEventSpeechRecognized()isFinal=true, text=hello Confidence is 12
04-29 17:08:32.064037 11117 11327 D CMTI/AiRobotApplication: onEventSpeechRecognized()resumeVoice.
04-29 17:08:32.064215 11117 11327 D CMTI/AiRobotApplication: d(): asrState=2IsASREnable:true
04-29 17:08:32.064716 11117 11327 D CMTI/VoiceRecorder: Pipeline has started.
04-29 17:08:32.071088 11117 11327 D CMTI/AiRobotApplication: c()
04-29 17:08:32.071191 11117 11327 D IFlyTekNativeService: finishRecognizing(). current state:DONE
04-29 17:08:32.071344   898   898 I cnss-daemon: RTM_NEWNEIGH message received: 28
04-29 17:08:32.071372   898   898 E cnss-daemon: Stale or unreachable neighbors, ndm state: 16
04-29 17:08:32.072029   898   898 I cnss-daemon: RTM_NEWNEIGH message received: 28
04-29 17:08:32.072099   898   898 I cnss-daemon: NDA_DST received: 192.168.31.1 ul: 562992921946304
04-29 17:08:32.072125   898   898 I cnss-daemon: NDA_LLADDR received
04-29 17:08:32.072159   898   898 E cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
04-29 17:08:32.072159   898   898 E cnss-daemon: : 00:00:00:00:00:00
04-29 17:08:32.072307   898   898 E cnss-daemon: Invalid mac address: 0x555555f110M
04-29 17:08:33.088489  2721  2721 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-29 17:08:33.093668  2721  2721 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=62
04-29 17:08:34.004323 11306 11306 D OVPN:   : >BYTECOUNT:6104009,3723449
--------- switch to system
04-29 17:08:34.043329  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
04-29 17:08:34.073469  1398  1398 D ZenLog  : disable_effects: 0|de.blinkt.openvpn|1346787898|null|10117,booleanState
--------- switch to main
04-29 17:08:34.725292 11117 11117 D AiManager: rcu received info is:{"data":{"greeting":{"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"],"offLineModeHintEN":["I am offline and cannot provide service"]},"logo":{"version":7,"url":"http:\\/\\/10.155.0.110:31154\\/data\\/cqtest105\\/image\\/778e012f-e485-4fff-bee4-db93471cc2da.jpg"},"version":35,"gasket":{"openDelay":1,"consultingDelay":2,"closing":["不好意思，请换个问题把"],"gasketEnable":true,"language":"CH","opening":["让我想想"],"endDelay":3}},"type":"appConfig"}
04-29 17:08:34.728000 11117 11238 D AiManager: run()appConfig:{"data":{"greeting":{"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"],"offLineModeHintEN":["I am offline and cannot provide service"]},"logo":{"version":7,"url":"http:\\/\\/10.155.0.110:31154\\/data\\/cqtest105\\/image\\/778e012f-e485-4fff-bee4-db93471cc2da.jpg"},"version":35,"gasket":{"openDelay":1,"consultingDelay":2,"closing":["不好意思，请换个问题把"],"gasketEnable":true,"language":"CH","opening":["让我想想"],"endDelay":3}},"type":"appConfig"}
04-29 17:08:34.728911 11117 11238 D AppConfigSetting: setAppConfigSetting the newAppConfigMsg is {"data":{"greeting":{"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"],"offLineModeHintEN":["I am offline and cannot provide service"]},"logo":{"version":7,"url":"http:\\/\\/10.155.0.110:31154\\/data\\/cqtest105\\/image\\/778e012f-e485-4fff-bee4-db93471cc2da.jpg"},"version":35,"gasket":{"openDelay":1,"consultingDelay":2,"closing":["不好意思，请换个问题把"],"gasketEnable":true,"language":"CH","opening":["让我想想"],"endDelay":3}},"type":"appConfig"} and replace is false
04-29 17:08:34.738693 11117 11238 D AppConfigSetting: combine appconfig
04-29 17:08:34.745129 11117 11238 D AppConfigSetting: oldJson{"data":{"gasket":{"closing":["不好意思，请换个问题把"],"consultingDelay":2,"endDelay":3,"gasketEnable":true,"language":"CH","openDelay":1,"opening":["让我想想"]},"greeting":{"offLineModeHintEN":["I am offline and cannot provide service"],"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"]},"logo":{"url":"http://10.155.0.110:31154/data/","version":7},"version":34},"type":"appConfig"}
04-29 17:08:34.746297 11117 11238 D AppConfigSetting: newJson{"data":{"gasket":{"closing":["不好意思，请换个问题把"],"consultingDelay":2,"endDelay":3,"gasketEnable":true,"language":"CH","openDelay":1,"opening":["让我想想"]},"greeting":{"offLineModeHintEN":["I am offline and cannot provide service"],"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"]},"logo":{"url":"http://10.155.0.110:31154/data/cqtest105/image/778e012f-e485-4fff-bee4-db93471cc2da.jpg","version":7},"version":35},"type":"appConfig"}
04-29 17:08:34.747698 11117 11238 D AppConfigSetting: combine{"data":{"gasket":{"closing":["不好意思，请换个问题把"],"consultingDelay":2,"endDelay":3,"gasketEnable":true,"language":"CH","openDelay":1,"opening":["让我想想"]},"greeting":{"offLineModeHintEN":["I am offline and cannot provide service"],"offLineModeHintZH":["我处于断网状态，这是断网测试，断网测试，测试。"]},"logo":{"url":"http://10.155.0.110:31154/data/cqtest105/image/778e012f-e485-4fff-bee4-db93471cc2da.jpg","version":7},"version":35},"type":"appConfig"}
04-29 17:08:34.755129 11117 11238 D AppConfigSetting: to load logo http://10.155.0.110:31154/data/cqtest105/image/778e012f-e485-4fff-bee4-db93471cc2da.jpg
04-29 17:08:34.759993 11117 11238 D DownloadMgrUtils: delete filePath is /storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-29 17:08:34.762707 11117 11238 D DownloadMgrUtils: delete filePath failed File does not exist: /storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-29 17:08:34.762881 11117 11238 W System.err: java.io.FileNotFoundException: File does not exist: /storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-29 17:08:34.763077 11117 11238 W System.err: 	at org.apache.commons.b.a.c(FileUtils.java:1386)
04-29 17:08:34.763152 11117 11238 W System.err: 	at com.cloudminds.airobot.f.d.a(DownloadManagerUtils.java:1060)
04-29 17:08:34.763195 11117 11238 W System.err: 	at com.cloudminds.airobot.b.a.a(AppConfigSetting.java:1107)
04-29 17:08:34.763242 11117 11238 W System.err: 	at com.cloudminds.airobot.service.a$26.run(AiManager.java:3655)
04-29 17:08:34.763294 11117 11238 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
04-29 17:08:34.763334 11117 11238 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-29 17:08:34.763373 11117 11238 W System.err: 	at android.os.Looper.loop(Looper.java:154)
04-29 17:08:34.763436 11117 11238 W System.err: 	at com.cloudminds.hc.hariservice.webrtc.f.run(LooperExecutor.java:40)
04-29 17:08:34.763533 11117 11238 D DownloadMgrUtils: download file url ishttp://10.155.0.110:31154/data/cqtest105/image/778e012f-e485-4fff-bee4-db93471cc2da.jpg *** storage file is /storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png
04-29 17:08:34.775688 11117 11238 E DownloadTarget: 下载失败，保存路径【/storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/Logo/logo.png】已经被其它任务占用，请设置其它保存路径

**Comment by AriaLyy** [comment]
升级到最新版本，设置保存路径的时候使用另外一个重载方法
```
setFilePath(path, true)
```
