### ISSUE TITLE
用法上@Download.onTaskFail被调用的时候我想要知道失败的原因应该如何方便的查看哈？

### ISSUE THREAD

**Issue by halohoop** [AriaLyy/Aria#393]
## Aria版本
"com.arialyy.aria:aria-core:3.6.3",
"com.arialyy.aria:aria-compiler:3.6.3"

## 什么问题
用法上@Download.onTaskFail被调用的时候我想要知道失败的原因应该如何方便的查看哈？

## 如何复现此问题
突然遇到了这个错误。

## 控制台日志
![image](https://user-images.githubusercontent.com/16235096/57432990-de67fc00-7269-11e9-9275-b20c60e61be4.png)
![image](https://user-images.githubusercontent.com/16235096/57428180-c38d8b80-7259-11e9-9522-a701977fd3f4.png)
2019-05-09 13:01:46.665 4037-4261/a.b.c E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.TaskException: 任务【c_prd_20190401_2019_1.1_5.apk】下载失败，filePath: /data/user/0/a.b.c/files/upgrade/aaaaa.apk, url: http://a.b.c/resource/im/d9bf2ca22f071100a651c18b443e226fe4f6afb1a2edab41039a96c9bb1b3208.apk
    length=8192; regionStart=0; regionLength=-1
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:134)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:51)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    java.lang.Thread.run(Thread.java:784)
    ===================================================

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/57430265-b7a5c780-7261-11e9-91eb-0ad501e12ad1.png)
用这个

**Comment by halohoop** [comment]
可能文档需要更新一下咯。
![image](https://user-images.githubusercontent.com/16235096/57431089-3f8cd100-7264-11e9-899d-36d771ab8d75.png)

**Comment by halohoop** [comment]
我这边定义到我的问题是解析响应头部的文件长度的时候失败，因为我们的下载地址经过了一层转发，然后又不归我们后台维护，所以响应头部不能够自己定义，所以提出一个如下图的需求，谢谢。
![image](https://user-images.githubusercontent.com/16235096/57431225-b5913800-7264-11e9-9116-7814602d37cf.png)

**Comment by AriaLyy** [comment]
可以

**Comment by halohoop** [comment]
哈哈，谢谢，焦急等待中……

**Comment by halohoop** [comment]
优秀~！请问大佬方便加个微信不，有机会在网上面个基一下什么的。😄

**Comment by AriaLyy** [comment]
使用3.6.4_dev_3     
 
```java
      .setFileLenAdapter(new IHttpFileLenAdapter() {
        @Override public long handleFileLen(Map<String, List<String>> headers) {
          ...
          // 处理header中的文件长度

          return fileLen;
        }
       })
 ```
