### ISSUE TITLE
在Fragment中注册时，没有Aria的注解方法

### ISSUE THREAD

**Issue by ZhangBingbin** [AriaLyy/Aria#394]
没有Aria的注解方法

**Comment by ZhangBingbin** [comment]
![image](https://user-images.githubusercontent.com/16457177/57518549-d3859800-734b-11e9-8231-0a308f9bc2a5.png)

**Comment by ZhangBingbin** [comment]
![image](https://user-images.githubusercontent.com/16457177/57518573-e8fac200-734b-11e9-9db2-a9e7fb746361.png)

**Comment by ZhangBingbin** [comment]
是因为AndroidX的原因嘛

**Comment by AriaLyy** [comment]
尝试设置这个标志为看看，https://blog.csdn.net/ShareUs/article/details/88085362

**Comment by EchoYuQ** [comment]
先将Aria整个工程迁移androidx，然后将每个module打包成aar或者jar，上传到你的依赖库中就可以了。
我的工程也是androidx的，收不到回调，按照上面我说的做法就OK，亲测可用。

**Comment by AriaLyy** [comment]
3.7.2 已经适配了androix
