### ISSUE TITLE
问个问题3.6.3kotlin版本中使用注解不起作用

### ISSUE THREAD

**Issue by lhj1079947827** [AriaLyy/Aria#398]
注解不起作用我也添加了
`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'org.greenrobot.greendao'`

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by lhj1079947827** [comment]
W/DownloadReceiver: 没有Aria的注解方法
I/zygote: Do partial code cache collection, code=494KB, data=280KB
I/zygote: After code cache collection, code=494KB, data=280KB
    Increasing code cache capacity to 2MB
Disconnected from the target VM, address: 'localhost:8607', transport: 'socket'
这个是什么意思？
 我都引入了两个版本啊
implementation rootProject.ext.other.aria_core
    annotationProcessor rootProject.ext.other.aria_compiler  
"aria_core":"com.arialyy.aria:aria-core:3.6.3",
            "aria_compiler":"com.arialyy.aria:aria-compiler:3.6.3"

**Comment by lhj1079947827** [comment]
这些配置我都已经配置了的

**Comment by AriaLyy** [comment]
代理文件生成失败，有可能是和其它插件冲突了，请提供下build日志

**Comment by lhj1079947827** [comment]
看了半天不知道那段日志是和你的包有问题

**Comment by lhj1079947827** [comment]
有没有什么关键字搜索吗

**Comment by AriaLyy** [comment]
搜索下`$$DownloadListenerProxy`这个后缀的类有没有生成

**Comment by lhj1079947827** [comment]
沒有生成 搜索不到

**Comment by lhj1079947827** [comment]
按shift两次来搜索这个 没有找到这代理类

**Comment by lhj1079947827** [comment]
是不是和我没有配置aria_config 这个有关系吗？我没有配置这个

**Comment by AriaLyy** [comment]
没有关系，注解是写在`app`里面还是`lib`里面？

**Comment by lhj1079947827** [comment]
app 里面

**Comment by lhj1079947827** [comment]
我没有用模块化写项目就一个主工程 app 模块

**Comment by lhj1079947827** [comment]
您的这个注解是不是这样子就可以了
`@Download.onWait
    internal fun taskWait(task: DownloadTask) {
        Log.e("tag",task.downloadEntity.fileName)
    }
`

**Comment by lhj1079947827** [comment]
还是需要在什么地方也要使用注解

**Comment by lhj1079947827** [comment]
您的库我是这么使用的
`        mAdapter.setOnItemChildClickListener { adapter, view, position ->
            var item = adapter.getItem(position) as AccessoryListEntity.ListBean
            var file=File(item.fileUrl)
            var downEntity=DownloadEntity()
            downEntity.url=item.fileUrl
            Aria.download(this)
                    .load(downEntity)
                    .setFilePath(downPathFile.path+"/"+file.name,true)
                    .start()
        }`
然后下面是使用注解获取状态但是就是 注解不起作用
`@Download.onWait
    internal fun taskWait(task: DownloadTask) {
        Log.e("tag",task.downloadEntity.fileName)
    }

    @Download.onTaskStart
    internal fun taskStart(task: DownloadTask) {
        Log.e("tag",task.downloadEntity.fileName)
    }

    @Download.onTaskResume
    internal fun taskResume(task: DownloadTask) {
    }

    @Download.onTaskStop
    internal fun taskStop(task: DownloadTask) {
    }

    @Download.onTaskCancel
    internal fun taskCancel(task: DownloadTask) {
    }

    @Download.onTaskFail
    internal fun taskFail(task: DownloadTask) {

    }

    @Download.onTaskComplete
    internal fun taskComplete(task: DownloadTask) {
        Log.e("tag","---------"+task.key)
    }

    @Download.onTaskRunning
    internal fun taskRunning(task: DownloadTask) {
        Log.e("tag","进度"+task.entity.currentProgress)
    }


    @DownloadGroup.onTaskComplete
    internal fun groupTaskComplete(task: DownloadGroupTask) {

    }

    @DownloadGroup.onTaskStart
    internal fun groupTaskStart(task: DownloadGroupTask) {

    }

    @DownloadGroup.onTaskResume
    internal fun groupTaskResume(task: DownloadGroupTask) {

    }

    @DownloadGroup.onWait
    internal fun groupTaskWait(task: DownloadGroupTask) {
        ALog.e("tag", String.format("group【%s】wait---", task.taskName))

    }

    @DownloadGroup.onTaskStop
    internal fun groupTaskStop(task: DownloadGroupTask) {
        Log.e("tag", String.format("group【%s】stop", task.taskName))
    }

    @DownloadGroup.onTaskCancel
    internal fun groupTaskCancel(task: DownloadGroupTask) {

    }

    @DownloadGroup.onTaskFail
    internal fun groupTaskFail(task: DownloadGroupTask) {
        Log.e("tag", String.format("group【%s】fail", task.taskName))
    }

    @DownloadGroup.onTaskComplete
    internal fun taskComplete(task: DownloadGroupTask) {

    }`

**Comment by AriaLyy** [comment]
看起来没什么问题，提供下完整的build日志、kotlin版本

**Comment by lhj1079947827** [comment]
你是要logCat里面的日志还是build的这个？

**Comment by lhj1079947827** [comment]
`apply from :"config.gradle"
buildscript {
    ext.kotlin_version = '1.3.20'

    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

**Comment by AriaLyy** [comment]
build日志

**Comment by lhj1079947827** [comment]
build日志里没哟报错啊 主要是

**Comment by lhj1079947827** [comment]
`16:53	Gradle build finished in 7 s 117 ms

16:55	Executing tasks: [:app:assembleDebug]

16:55	Gradle build finished in 6 s 493 ms

16:56	Executing tasks: [:app:assembleDebug]

16:56	Gradle build finished in 7 s 290 ms

17:03	Executing tasks: [:app:assembleDebug]

17:03	Gradle build finished in 7 s 779 ms

17:08	Executing tasks: [:app:assembleDebug]

17:09	Gradle build finished in 25 s 18 ms

17:09	IDE and Plugin Updates: Android Studio is ready to update.

17:32	Executing tasks: [:app:assembleDebug]

17:32	Gradle build finished in 1 s 634 ms

17:32	Executing tasks: [:app:assembleDebug]

17:33	Gradle build finished in 29 s 453 ms

17:45	Executing tasks: [:app:assembleDebug]

17:46	Gradle build finished in 28 s 28 ms`

**Comment by lhj1079947827** [comment]
`2019/5/16
17:55	Executing tasks: [:app:assembleDebug]

17:55	Gradle build finished in 22 s 5 ms
`

**Comment by AriaLyy** [comment]
我用你的kotlin配置可以正常回调，😂
![image](https://user-images.githubusercontent.com/10437293/57993657-8abca480-7aec-11e9-8be9-f791e7b6d9d5.png)

**Comment by lhj1079947827** [comment]
....，我的配置也没有问题啊，为什么调用不到呢。。。

**Comment by lhj1079947827** [comment]
能发你的demo我看下吗

**Comment by lhj1079947827** [comment]
1079947827@QQ.com 发到这个邮箱下

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/57994301-1cc5ac80-7aef-11e9-8f1a-e6564b6a372a.png)
将所有注解方法的internal 去掉，demo我晚下上传

**Comment by lhj1079947827** [comment]
主要是我连这个DownLoadLinsenerProxy代理类都没有生成成功。。。

**Comment by lhj1079947827** [comment]
哪天我用的是按下两次Shift查找 这个代理都没有

**Comment by lhj1079947827** [comment]
等下我创建一个demo来测试

**Comment by AriaLyy** [comment]
我刚才测试，加了internal编译都不通过，出现`e: [kapt] An exception occurred: java.lang.IllegalArgumentException: index 1 for '$a' not in range (received 0 arguments)
`
估计是你哪些地方配置了忽略错误😂

**Comment by lhj1079947827** [comment]
对的，我的有些地方写的代码在升级后kotlin后有些不符合升级后的 规范，所以我必须使用` lintOptions {
        abortOnError false
    }`来忽略警告 不然每个地方都去改有点痛苦

**Comment by AriaLyy** [comment]
将`internal`去掉看看，只需要去掉aria的注解方法的就行了

**Comment by lhj1079947827** [comment]
等会儿我在重新写个代码测试一下
