### ISSUE TITLE
多任务下载的时候,下载同一个URL,但是保存的本地路径都不同, 却立马报错

### ISSUE THREAD

**Issue by 983045775** [AriaLyy/Aria#399]
多任务下载的时候,下载同一个URL,但是保存的本地路径都不同, 却立马报错

![D3098FA5-23FA-40B1-8FBF-3EA210CC0D69](https://user-images.githubusercontent.com/13258336/57896666-75454180-7884-11e9-9758-899c2335b248.png)

**Comment by 983045775** [comment]
开始下载第二个的时候立马报错了...都是同一个URL,但是保存的路径不同....

**Comment by AriaLyy** [comment]
框架里是通过url查找对应信息的，不支持一个url对应多个保存路径
