### ISSUE TITLE
为什么getFileSize会比实际下载下来的文件小

### ISSUE THREAD

**Issue by zhengxuming** [AriaLyy/Aria#40]
我这里有个音频的链接http://tinghuaapp.oss-cn-shanghai.aliyuncs.com/20170612152014756680，下载时，读取到的总大小为5.4M，但是实际下载后，文件大小为9M多，这是怎么回事？

**Comment by AriaLyy** [comment]
这个连接都连不通啊...
```html
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>593E85E3462A363D772B8094</RequestId>
<HostId>tinghuaapp.oss-cn-shanghai.aliyuncs.com</HostId>
<Key>20170612152014756680</Key>
</Error>
```

**Comment by zhengxuming** [comment]
不好意思，刚才以为是服务器问题，清空数据了，用这个可以http://tinghuaapp.oss-cn-shanghai.aliyuncs.com/20170612201739607815

**Comment by zhengxuming** [comment]
大神，要不然建个群嘛，这样大家以后有问题可以及时沟通

**Comment by AriaLyy** [comment]
找到问题了，当我设置
```java
conn.setRequestProperty("Range", "bytes=" + START_LOCATION + "-" + END_LOCATION);
```
后，我请求完成了`START_LOCATION + "-" + END_LOCATION`的数据流后，你的服务器socket没有断开...
现在，我已经重新对完成条件做了处理

**Comment by zhengxuming** [comment]
好的，谢谢，等你上传。

**Comment by AriaLyy** [comment]
能把文件m5码发我一下吗？我需要验证下我的截取是否正常，麻烦了

**Comment by zhengxuming** [comment]
我只有源文件，没弄过m5码😔

**Comment by zhengxuming** [comment]
或者你加我QQ，644185216

**Comment by AriaLyy** [comment]
不用了哈，已经使用迅雷成功下载了

**Comment by AriaLyy** [comment]
compile 'com.arialyy.aria:Aria:3.1.7'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.1.7'

已经修复该bug
