### ISSUE TITLE
能下载.m3u8文件么？

### ISSUE THREAD

**Issue by tenda2014** [AriaLyy/Aria#400]
## Aria版本
3.6.3

## 什么问题
.m3u8的文件，可以播放，但是下载下来是一个几十KB的文件，能直接把视频下载下来保存成.mp4格式的文件么？
下载地址:
https://www.gaoya123.cn/2019/1557993797897.m3u8

**Comment by AriaLyy** [comment]
只支持下载单个文件，不支持持续的视频流下载

**Comment by tenda2014** [comment]
大佬后续会加.m3u8视频流的下载么？

**Comment by AriaLyy** [comment]
看情况，对视频流服务器搭建这块不熟。。

**Comment by Piscen** [comment]
试过用这个框架下载m3u8视频，思路是需要先解析m3u8得到所有的ts文件链接，然后通过框架中的任务组去下载所有得到的ts文件到本地，同时在本地构建一个新的m3u8索引文件，里面的ts地址都指向本地。播放的时候调用本地的m3u8就可以了

**Comment by Piscen** [comment]
如果需要转成mp4那就得合并本地所有的ts文件，这个网上应该也有例子

**Comment by tenda2014** [comment]
> 看情况，对视频流服务器搭建这块不熟。。

这个不用搭建服务器，我找了个别人写的下载m3u8的demo，感觉可以集成到这个框架里，流程就跟楼上大哥说的一样。
这个是地址：
https://github.com/huangdali/M3U8Manger
希望楼主采纳。

**Comment by AriaLyy** [comment]
好的，后面我看下源码看他怎么实现的，可以的话后面会增加一个m3u8的下载功能

**Comment by AriaLyy** [comment]
3.6.5_beta_1已支持m3u8文件，文档见：https://aria.laoyuyu.me/aria_doc/download/m3u8.html
