### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by NerdAnonymous** [AriaLyy/Aria#404]
库里最好加一个tag的标签作为下载的唯一标识，方便扩展，有时候并不是让url作为标识的

**Comment by AriaLyy** [comment]
其实，框架里面保存路径才是唯一标识，只不过因为历史遗留问题，一直没有找到好的兼容方法，后面考虑下使用url+保存路径处理这个问题

**Comment by w13159584927** [comment]
建议+1
有同样的需求：
就是在下载的时候需要传tag，暂停或者删除时传tag去处理，
保存路径也是根据tag来的。

**Comment by AriaLyy** [comment]
3.7.2已修改了这个问题，改id为唯一标志了
