### ISSUE TITLE
请问googlevideo视频怎么下载？

### ISSUE THREAD

**Issue by tmxd09887** [AriaLyy/Aria#405]
## Aria版本
版本 3.4.12

## 什么问题
下载googlevideo失败
这个视频有时效性，过期就不能下载。但是我测试的时候，这个下载链接在浏览器CHROME里能正常播放，放到下载软件里也能下载。

## 控制台日志

D/skia: --- Failed to create image decoder with message 'unimplemented'

E/AbsThreadTask: 下载失败【https://r4---sn-qxo7rn7s.googlevideo.com/videoplayback?id=2781c26c352fec4e&itag=18&source=picasa&begin=0&requiressl=yes&pl=24&sc=yes&ei=R1fqXK2eB8WH8gOc7LjoCA&susc=ph&app=fife&mime=video/mp4&dur=5095.851&lmt=1557999740146787&ipbits=0&keepalive=yes&ratebypass=yes&ip=91.232.105.62&expire=1558868839&sparams=app,dur,ei,expire,id,ip,ipbits,itag,lmt,mime,mip,mm,mn,ms,mv,pl,requiressl,sc,source,susc&signature=5143B66DC493653BC1F0CF8B4573A800BC88A1EB.53909D793C60A0D773D8A2661C39F50D34C34C65&key=cms1&cms_redirect=yes&mip=172.96.13.239&mm=30&mn=sn-qxo7rn7s&ms=nxu&mt=1558867576&mv=u】
    ExceptionDetailed:
    ====================Exception Info====================
    java.io.FileNotFoundException: https://r4---sn-qxo7rn7s.googlevideo.com/videoplayback?id=2781c26c352fec4e&itag=18&source=picasa&begin=0&requiressl=yes&pl=24&sc=yes&ei=R1fqXK2eB8WH8gOc7LjoCA&susc=ph&app=fife&mime=video/mp4&dur=5095.851&lmt=1557999740146787&ipbits=0&keepalive=yes&ratebypass=yes&ip=91.232.105.62&expire=1558868839&sparams=app,dur,ei,expire,id,ip,ipbits,itag,lmt,mime,mip,mm,mn,ms,mv,pl,requiressl,sc,source,susc&signature=5143B66DC493653BC1F0CF8B4573A800BC88A1EB.53909D793C60A0D773D8A2661C39F50D34C34C65&key=cms1&cms_redirect=yes&mip=172.96.13.239&mm=30&mn=sn-qxo7rn7s&ms=nxu&mt=1558867576&mv=u1
    com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
    com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
    com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
    com.arialyy.aria.core.download.downloader.ConnectionHelp.convertInputStream(ConnectionHelp.java:53)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:85)
    com.arialyy.aria.core.download.downloader.HttpThreadTask.call(HttpThreadTask.java:43)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    java.lang.Thread.run(Thread.java:784)

**Comment by AriaLyy** [comment]
提供的日志无法定位问题，请升级到最新版本或提供更加完整到日志
