### ISSUE TITLE
组下载中某个文件的下载状态

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#406]
## Aria版本
3.6.4_dev_3
## 什么问题
使用组下载下载A、B、C、D四个文件，在下载过程中中断，此时A、B已下载完。然后在调用Aria.download(this).getGroupTaskList()获取到组下载列表，通过downloadGroupEntity.getSubEntities()获取子任务实体列表时，为什么A、B的子任务实体的complete属性依旧是false？
此种情况下，如何过滤出已经下载完成的文件？

**Comment by AriaLyy** [comment]
`3.6.5`已经修复来这个问题
