### ISSUE TITLE
3.4.7升级到3.6.4数据库升级问题

### ISSUE THREAD

**Issue by cyw026** [AriaLyy/Aria#407]
## Aria版本
3.6.4

## 什么问题
3.4.7版本更新到3.6.4版本数据库迁移

## 如何复现此问题
3.4.7版本添加下载再更新到3.6.x处理数据库升级时可复现

## 控制台日志
![WX20190603-162539](https://user-images.githubusercontent.com/1871567/58787453-6ac4cf00-861c-11e9-9677-51be31cb645c.png)

**Comment by OneGreenHand** [comment]
捕获到一个异常
#2402 android.database.sqlite.SQLiteConstraintException
UNIQUE constraint failed: TaskRecord.filePath (code 1555)
com.arialyy.aria.orm.DelegateUpdate.updateData(DelegateUpdate.java:62)

**Comment by AriaLyy** [comment]
`3.6.5`已经修复来这个问题
