### ISSUE TITLE
m3u8下载后无法播放

### ISSUE THREAD

**Issue by shuncaigao** [AriaLyy/Aria#408]
## Aria版本
3.6.5_beta_1

## 什么问题
m3u8下载自动合并后无法播放

## 如何复现此问题

https://youku.xlabzjx.com/20181206/TlplsOkr/index.m3u8

**Comment by AriaLyy** [comment]
如果合并的文件不能播放，请自行处理ts文件的合并,https://aria.laoyuyu.me/aria_doc/download/m3u8.html#%E5%90%88%E5%B9%B6ts%E6%96%87%E4%BB%B6
