### ISSUE TITLE
缺少一个总任务恢复方法

### ISSUE THREAD

**Issue by zhengxuming** [AriaLyy/Aria#41]
我发现框架中有Aria.download(this).stopAllTask();但是却没法恢复下载

**Comment by AriaLyy** [comment]
个人觉得这个api不是很常用，后续版本可以考虑，如果现在需要使用带恢复所有下载任务的需求，你可以
使用`Aria.download(this).getTaskList();`获取数据的所有信息，然后遍历把状态为停止状态的数据取出来，然后使用这些数据恢复任务。

**Comment by zhengxuming** [comment]
我根据你的停止方法，加了一个恢复的方法，经测试，可以使用，`/**
   * 停止所有正在下载的任务
   */
  @Override public void stopAllTask() {
    final AriaManager ariaManager = AriaManager.getInstance(AriaManager.APP);
    List<DownloadEntity> allEntity = DbEntity.findAllData(DownloadEntity.class);
    List<AbsCmd> stopCmds = new ArrayList<>();
    for (DownloadEntity entity : allEntity) {
      int state=entity.getState();
      if ( (state== DownloadEntity.STATE_RUNNING)||(state==DownloadEntity.STATE_WAIT)) {
        stopCmds.add(
            CommonUtil.createCmd(targetName, new DownloadTaskEntity(entity), CmdFactory.TASK_STOP));
      }
    }
    ariaManager.setCmds(stopCmds).exe();
  }

  /**
   * 恢复所有正在下载的任务
   */
   public void resumeAllTask() {
    final AriaManager ariaManager = AriaManager.getInstance(AriaManager.APP);
    List<DownloadEntity> allEntity = DbEntity.findAllData(DownloadEntity.class);
    List<AbsCmd> stopCmds = new ArrayList<>();
    for (DownloadEntity entity : allEntity) {
      if (entity.getState() == DownloadEntity.STATE_STOP) {
        stopCmds.add(
                CommonUtil.createCmd(targetName, new DownloadTaskEntity(entity), CmdFactory.TASK_RESUME));
      }
    }
    ariaManager.setCmds(stopCmds).exe();
  }`

**Comment by zhengxuming** [comment]
另外，我发现停止方法有个问题，就是可以停调并行任务，不能停止串行任务，当执行stopAllTask()时，只能停掉串行队列的第一个任务，队列后面的任务会接着执行。

**Comment by AriaLyy** [comment]
非常感谢你，提出了这么多问题，有没有兴趣一起维护这个项目？:blush:

**Comment by zhengxuming** [comment]
可以啊，非常感谢有这个机会。

**Comment by AriaLyy** [comment]
直接把代码提交到Aria项目里就行了哈 :smile:

**Comment by 1206010214** [comment]
resumeAllTask()容易产生java.lang.ClassCastException，如果此时既有任务组，又存在但任务，此时调用会导致类型转换异常java.lang.ClassCastException: com.arialyy.aria.core.download.DownloadTaskEntity cannot be cast to com.arialyy.aria.core.download.DownloadGroupTaskEntity

**Comment by lql7993259lql** [comment]
Aria.download(this).stopAllTask(); 停止的时候DownloadTaskEntity里面的state状态没有改变。
