### ISSUE TITLE
没有单独操作某个任务的方法吗？

### ISSUE THREAD

**Issue by huangyuan0pplabs** [AriaLyy/Aria#411]
## Aria版本
3.6.4

## 什么问题
没有单独操作某任务的方法

## 如何复现此问题
必现

**Comment by huangyuan0pplabs** [comment]
今天自己翻源码找到了，可以用Aria.download(context).load(url)直接操作这个URL对应的task，DownloadTaskQueue.getInstance()可以直接控制，不过这个没有试过。

谢谢大佬提供这么强大方便的下载框架。

**Comment by AriaLyy** [comment]
不要使用`DownloadTaskQueue.getInstance()`，这个是最终调用的api，如果没有之前的条件判断，将会出现重复下载的风险
