### ISSUE TITLE
id问题

### ISSUE THREAD

**Issue by NerdAnonymous** [AriaLyy/Aria#412]
目前直接down下来的代码会不会有问题，想直接把你的代码弄下来，然后改一波主键

**Comment by AriaLyy** [comment]
可以

**Comment by NerdAnonymous** [comment]
但是你目前的demo队列任务跑不起来

**Comment by NerdAnonymous** [comment]
还有 我想把以url为主键改为新增一个id为主键的，需要修改哪些代码呢

**Comment by AriaLyy** [comment]
不清楚你是如何导入的，我只能保证我的代码是完整的😂，最新代码已经没有主键了，只有保存路径的唯一约束

**Comment by AriaLyy** [comment]
3.7.2已增加这个功能
