### ISSUE TITLE
警告: 以下选项未被任何处理程序识别

### ISSUE THREAD

**Issue by pioneerz** [AriaLyy/Aria#413]
w: 警告: 以下选项未被任何处理程序识别: '[android.databinding.artifactType, android.databinding.printEncodedErrors, android.databinding.minApi, android.databinding.isTestVariant, android.databinding.enableDebugLogs, android.databinding.sdkDir, android.databinding.bindingBuildFolder, android.databinding.enableForTests, android.databinding.modulePackage, kapt.kotlin.generated, android.databinding.generationalFileOutDir, android.databinding.xmlOutDir]'

**Comment by pioneerz** [comment]
一直不能运行

**Comment by AriaLyy** [comment]
databinding的问题，请自行谷歌
