### ISSUE TITLE
不支持断点下载的文件下载完毕，下载进度一直回调

### ISSUE THREAD

**Issue by nwhhades** [AriaLyy/Aria#416]
## Aria版本
3.6.4

## 什么问题

onTaskRunning方法一直回调
## 如何复现此问题
下载这个某个不支持断点的文件
Aria.download(this)
                .load(task.getUrl())
                .setFilePath(path + task.getName(), true)
                .resetState()
                .start();
## 控制台日志
1-21 14:24:26.588 9026-9116/cn.whiner.show D/BaseCachePool: 任务【newApp.apk】进入缓存队列成功
01-21 14:24:26.590 9026-9116/cn.whiner.show D/StartCmd: 开始新任务, 任务状态：3
01-21 14:24:26.591 9026-9116/cn.whiner.show D/BaseExecutePool: 任务【newApp.apk】进入执行队列成功
01-21 14:24:27.014 9026-9120/cn.whiner.show D/AbsFileer: path: /data/user/0/cn.whiner.show/cache/download/newApp.apk
01-21 14:24:27.058 9026-9026/cn.whiner.show D/DownLoadService:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, cn.whiner.show.download.DownLoadService.onNoSupportBreakPoint(DownLoadService.java:88)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ newApp.apk该下载链接不支持断点
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
01-21 14:24:27.103 9026-9120/cn.whiner.show D/AbsFileer: 保存记录，线程记录数：4
01-21 14:24:27.135 9026-9121/cn.whiner.show W/HttpThreadTask: 该下载不支持断点
01-21 14:24:27.149 9026-9120/cn.whiner.show D/AbsFileer: 启动定时器
01-21 14:24:27.150 9026-9026/cn.whiner.show D/DownLoadService:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, cn.whiner.show.download.DownLoadService.onTaskStart(DownLoadService.java:93)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ newApp.apk，开始下载
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
01-21 14:24:27.153 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小0b - - - 文件进度0
01-21 14:24:28.155 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小880.62kb - - - 文件进度24
01-21 14:24:28.787 346-813/system_process I/ActivityManager: Killing 8922:com.android.defcontainer/u0a3 (adj 9): empty #1
01-21 14:24:29.155 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小1.84mb - - - 文件进度53
01-21 14:24:30.157 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小2.45mb - - - 文件进度71
01-21 14:24:31.158 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.02mb - - - 文件进度87
01-21 14:24:31.716 9026-9121/cn.whiner.show I/AbsThreadTask: 任务【newApp.apk】完成
01-21 14:24:31.737 9026-9121/cn.whiner.show W/CommonUtil: 记录为空
01-21 14:24:31.789 9026-9026/cn.whiner.show D/AbsTaskQueue: 从执行池删除任务【newApp.apk】成功
01-21 14:24:31.790 9026-9026/cn.whiner.show D/AbsSchedulers: complete_next
01-21 14:24:31.792 9026-9026/cn.whiner.show I/AbsSchedulers: 没有等待中的任务
01-21 14:24:31.793 9026-9026/cn.whiner.show D/DownLoadService:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, cn.whiner.show.download.DownLoadService.onTaskComplete(DownLoadService.java:113)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ newApp.apk，下载完成
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
01-21 14:24:31.923 9026-9116/cn.whiner.show D/UpService:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ pool-2-thread-1, cn.whiner.show.up.UpService.getDownLoad(UpService.java:97)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ /data/user/0/cn.whiner.show/cache/download/newApp.apk
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
01-21 14:24:32.160 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:33.190 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:34.192 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:35.194 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:36.196 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:37.198 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:38.223 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:39.225 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:40.227 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:41.229 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:42.231 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:43.261 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:44.263 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:45.264 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:46.265 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:47.266 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:48.287 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:49.289 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:50.291 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:51.292 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:51.924 346-562/system_process D/WifiStateMachine: starting scan for "NIE"WPA_PSK with 2412
01-21 14:24:52.294 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:53.324 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:54.326 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:55.327 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:56.329 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:57.332 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:58.360 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:24:59.362 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:00.364 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:01.365 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:02.367 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:03.393 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:04.395 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:05.397 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100
01-21 14:25:06.399 9026-9026/cn.whiner.show E/DownLoadService: newApp.apk- - 文件大小3.45mb - - - 文件进度100

**Comment by AriaLyy** [comment]
`3.6.5`已经修复来这个问题
