### ISSUE TITLE
m3u8视频地址转换问题？

### ISSUE THREAD

**Issue by colaly** [AriaLyy/Aria#418]
## m3u8视频地址转换问题？
视频地址：https://youku.kuyun-leshi.com/20190625/esujXTMm/index.m3u8
响应的内容为：
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000,RESOLUTION=1080x608
/ppvod/928DCDC2D8A6080ACF04ADCC6DFF60AF.m3u8
这种类型的url无法通过setTsUrlConvert()进行转换

**Comment by AriaLyy** [comment]
这是多码率的m3u8文件，请设置码率的m3u8地址转换器
