### ISSUE TITLE
组下载时获取文件大小失败

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#419]
## Aria版本
3.6.4_dev_3
## 什么问题
在使用组下载时，使用的unknownSize来设置组合任务的总长度，在文件数量较少（大约20个文件，总文件长度约15G），文件总大小是可以获取到的（convertFileSize这个参数是有值的）。但是在文件数量较多（约77个文件，总文件约20G），此时总文件大小获取到的是0（convertFileSize这个参数值为零），导致在使用task.getPercent()获取下载进度时始终为0

**Comment by AriaLyy** [comment]
有没有错误日志，感觉像是崩了，文件数太多，建议自行设置文件大小，并设置同时执行的子任务数量

**Comment by lyxc** [comment]
没有看到错误日志，下载是一直进行的，很正常，就是总文件大小没有获取到

**Comment by AriaLyy** [comment]
我这重现了，因为unknownSize()机制的问题以及组合任务的特性，文件多多时，很大概率不能及时获取组合任务总长度，最好的方法还是自行设置组合任务长度

**Comment by AriaLyy** [comment]
`3.6.5`已经修复来这个问题，但是文件过多时会出现长时间的等待，才能进入下载流程
