### ISSUE TITLE
发现一个小bug

### ISSUE THREAD

**Issue by 710224800** [AriaLyy/Aria#42]
![image](https://user-images.githubusercontent.com/17699223/27077011-5964d8ce-5061-11e7-967a-91a35a4b2611.png)

这个地方永远进不来，cancle的时候没有设置状态吧，大神

**Comment by AriaLyy** [comment]
额，我下班回去看下，demo是很久之前写的了，现在代码改了很多，可能这句话没啥用了

**Comment by 710224800** [comment]
![image](https://user-images.githubusercontent.com/17699223/27078234-7aca7d4e-5065-11e7-8638-90a5a4c9536b.png)
这个是做什么用的呀，不引用行吗

**Comment by AriaLyy** [comment]
这是apt注解扫描器，不引用就不能使用下载注解方法了

**Comment by 710224800** [comment]
不使用注解方式也没问题吧大神

**Comment by 710224800** [comment]
因为我后续要切换到eclipse，会有问题吗

**Comment by AriaLyy** [comment]
没影响，只是不能使用apt注解方法了而已。使用以前的api获取下载事件就可以了

**Comment by 710224800** [comment]
OK

**Comment by 710224800** [comment]
eclipse下能引用apt注解吗，把那几个类拷贝过去就行吗

**Comment by AriaLyy** [comment]
eclipse 我没尝试过使用apt，你可以参考下鸿洋的[这篇文章](http://blog.csdn.net/lmj623565791/article/details/43452969)

**Comment by 710224800** [comment]
点fragment 下载会报错

**Comment by AriaLyy** [comment]
修改`activity_fragment.xml`文件为
```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

  <LinearLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:orientation="vertical"
      >
    <include layout="@layout/layout_bar"/>
    <fragment
        android:id="@+id/fragment1"
        android:name="com.arialyy.simple.download.fragment_download.DownloadFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

  </LinearLayout>
</layout>
```
