### ISSUE TITLE
组下载文件时部分文件下载出错时不会有任何回调

### ISSUE THREAD

**Issue by xiaxiayang** [AriaLyy/Aria#422]
## Aria版本
3.6.4

## 什么问题
1.当组文件中某个文件地址其实不存在的时候（服务器返回数据有问题），后面不会走任何回调，导致流程终端，模拟了一下，会有警告信息，见控制台输出【1】
2.对于服务器返回的同一图片下载地址，部分机型会一直下载中断，线上日志只记录到下载开始的回调，其他回调也不会走，情况同1，具体报错信息无法获取

## 如何复现此问题
对于问题1，必现，比如下载地址为：https://img-dev.xiniunet.com/658896334535139328/photo/791521213481881600.jpg
对于问题2，不好复现，固定机器

## 控制台日志
[1]
![79FD2A83-A615-4EC4-AD36-C3DB9A319874](https://user-images.githubusercontent.com/25956745/61202924-83e09580-a71b-11e9-8962-49422e89f05b.png)

**Comment by AriaLyy** [comment]
`3.6.5`已经修复来这个问题
