### ISSUE TITLE
下载m3u8文件时 merge false和setMergeHandler有问题

### ISSUE THREAD

**Issue by w13159584927** [AriaLyy/Aria#423]
## Aria版本
3.6.5

## 什么问题

用3.6.5的demo手动替换为自己的m3u8下载的url出现以下问题：

1.setMergeHandler方法进不去，
2..merge(false)后看不到下载的文件，文件夹为空。

## 如何复现此问题
设置的url有三个码率，且存在key。所以代码如下。

Aria.download(M3U8VodDLoadActivity.this)
.load("https://www.ilingdai.com/hls/5277/playlist/41bc2b88a93211e9aca5d32802ef90bd.m3u8?rnad=0")
        .useServerFileName(true)
        .setFilePath("/sdcard/111/m3u8Downloader/index.ts", true)
        .asM3U8()
        .setBandWidthUrlConverter(new IBandWidthUrlConverter() {
          @Override public String convert(String bandWidthUrl) {
            return bandWidthUrl;
          }
        })
        .setTsUrlConvert(new IVodTsUrlConverter() {
          @Override public List<String> convert(String m3u8Url, List<String> tsUrls) {
            return tsUrls;
          }
        })
        .setMergeHandler(new ITsMergeHandler() {
          @Override public boolean merge(@Nullable M3U8KeyInfo keyInfo, List<String> tsPath) {
            return false;
          }
        })
        .merge(false)
        .start();

**Comment by AriaLyy** [comment]
有无控制台日志？我这测试merge(false)是正常的，如果你merge设置为fasle，将不会执行`ITsMergeHandler`
ts文件保存路径为: `"/sdcard/111/m3u8Downloader/.index.ts" `
![image](https://user-images.githubusercontent.com/10437293/61604655-01088f00-ac75-11e9-8b79-6c46acfde492.png)

**Comment by w13159584927** [comment]
1.用我的url的时候，merge(false)文件夹还是空的，如果不加merge(false)会生成一完整的ts文件。
2. ITsMergeHandler方法两种情况都不进。
3.merge(false)加不加都是输出一样的，解析的m3u8和下载部分都打印了。
4.提供个新的url： https://www.ilingdai.com/hls/5277/playlist/c8075578ac3911e9803780fc789088f2.m3u8?rnad=0 ps:时间长可能会过期，无法解析。
5.截图上传不上来。。。

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
