### ISSUE TITLE
后续任务一直是wait状态

### ISSUE THREAD

**Issue by gaosiling** [AriaLyy/Aria#424]
## Aria版本
implementation 'com.arialyy.aria:aria-core:3.6.5'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.5'

## 什么问题
a Fragment 添加2个普通任务，跳到b Fragment中回调进度，完成后删除，再在a Fragment重新添加这2个普通任务，跳到b Fragment下载完任务1后，任务2一直是等待状态，没有继续。

## 控制台日志
![image](https://user-images.githubusercontent.com/22977565/61540555-66d7f980-aa70-11e9-9dee-cf7eecd71e37.png)
![image](https://user-images.githubusercontent.com/22977565/61540590-7a836000-aa70-11e9-9fa5-93dac3f7dbf4.png)
![image](https://user-images.githubusercontent.com/22977565/61540666-a6064a80-aa70-11e9-91ad-fae5757ed521.png)
![image](https://user-images.githubusercontent.com/22977565/61540692-b0c0df80-aa70-11e9-94e7-ff4f3b0c87ff.png)
![image](https://user-images.githubusercontent.com/22977565/61540748-d221cb80-aa70-11e9-99c7-7b65fefb9651.png)

**Comment by gaosiling** [comment]
在b Fragment中的初始化中有调用resumeAllTask()，删除时调的cancel(true)和removeAllTask(true)

**Comment by gaosiling** [comment]
在assets目录下aria_config配置文件中设置了<maxTaskNum value="3"/>，下载时没有三个一个任务去下载，而是一个一个去下载的。
![image](https://user-images.githubusercontent.com/22977565/61578844-81bd7300-ab2f-11e9-8bf6-5925f1ef1f2f.png)
在a Fragment中通过代码设置最大任务数后Aria.init(getContext()).getDownloadConfig().setMaxTaskNum(3);也是同样的情况。

**Comment by AriaLyy** [comment]
我这测试是正常的。。。

![image](https://user-images.githubusercontent.com/10437293/61601028-3d80be80-ac66-11e9-947c-6127b18a7546.png)

![image](https://user-images.githubusercontent.com/10437293/61601048-4ffaf800-ac66-11e9-80dd-06c1d4e13e95.png)

**Comment by gaosiling** [comment]
好的  我再看一下什么原因导致的
