### ISSUE TITLE
并发修改

### ISSUE THREAD

**Issue by gaosiling** [AriaLyy/Aria#425]
## Aria版本
implementation 'com.arialyy.aria:aria-core:3.6.5'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.5'

## 什么问题
并发修改

## 如何复现此问题
删除多个普通任务，进行遍历，调用cancel(true)，然后会调用.setExtendField(s).save()修改保存扩展字段，会并发修改的错误。

## 控制台日志
![截图](https://user-images.githubusercontent.com/22977565/61581105-7d538300-ab4c-11e9-852d-fb6ecf2e5878.png)

**Comment by AriaLyy** [comment]
看控制台日志，并不是我这出的问题。。
