### ISSUE TITLE
3.4.7升级到3.6.5之后在7.0的机器上会出现崩溃

### ISSUE THREAD

**Issue by cyw026** [AriaLyy/Aria#426]
## Aria版本
3.6.5

## 什么问题
3.4.7升级到3.6.5之后在7.0的机器上会出现崩溃

## 控制台日志
![image](https://user-images.githubusercontent.com/1871567/61581221-28187100-ab4e-11e9-9d2d-c0af956e6b64.png)

**Comment by AriaLyy** [comment]
你机器上面的sqlite 版本是多少？

**Comment by AriaLyy** [comment]
`3.6.6_beta_1`已经修复了这个问题

**Comment by xiaxiayang** [comment]
android  5.1.1 系统上从3.6.4升级到3.6.5也出现这个问题。在原apk不卸载的情况下，3.6.6_beta_1也还会报同样的错误

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/430

**Comment by AriaLyy** [comment]
@xiaxiayang 麻烦提供下日志，个人测试3.6.4升级到3.6.6_beta_1是正常的

**Comment by AriaLyy** [comment]
使用3.6.6_beta_2，修复了某些机型sqlite3 `where(x,x,x) in xxx `语法不兼容的问题

**Comment by xiaxiayang** [comment]
升级到 3.6.6_beta_2 后没有这个报错了
