### ISSUE TITLE
遍历删除多个状态的普通任务没有全部删除

### ISSUE THREAD

**Issue by gaosiling** [AriaLyy/Aria#427]
## Aria版本
implementation 'com.arialyy.aria:aria-core:3.6.5'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.5'

## 什么问题
Q1: 配置maxTaskNum没有生效。
Q2: 遍历删除多个状态的普通任务，并没有全部删除掉。

## 如何复现此问题
Q1: aria_config.xml中 <maxTaskNum value="3"/>没有生效。
Q2: 添加2个任务后，任务1状态running，任务2状态wait，选择这2个任务通过遍历调用cancel(true)删除；通过getTaskList();获取已完成和未完成的普通任务，任务2仍存在，并没有删除掉。

## 控制台日志
![image](https://user-images.githubusercontent.com/22977565/61589990-5ba5da80-abe4-11e9-88f7-6984deb492e9.png)

**Comment by gaosiling** [comment]
什么时候可以修复呢？或者您建议我怎么处理？

**Comment by AriaLyy** [comment]
```
        List<DownloadEntity> entities = Aria.download(this).getTaskList();
        for (DownloadEntity entity: entities){
          Aria.download(this).load(entity.getUrl()).cancel(true);
          ALog.d(TAG, "exist ==" + Aria.download(this).load(entity.getUrl()).taskExists());
        }
```
这种删除方式有问题，原因待排查，如果需要删除全部任务，可以使用以下的删除方式
```
        Aria.download(this).removeAllTask(true);
```

**Comment by gaosiling** [comment]
我这删除全部是没有问题的， 但是删除其中的几个会出现这个问题，这个要怎么处理可以实现，我没有找到别的方法

**Comment by gaosiling** [comment]
或者可以加一个删除多个任务的方法

**Comment by AriaLyy** [comment]
原因是3.6.5版本后添加了一个调用命令间隔的限制，后面考虑将停止和删除的间隔限制去掉
![image](https://user-images.githubusercontent.com/10437293/61602432-0d3c1e80-ac6c-11e9-83a0-323f1c5a80c8.png)
![image](https://user-images.githubusercontent.com/10437293/61602445-1927e080-ac6c-11e9-8abb-6f4927f60bc4.png)

**Comment by gaosiling** [comment]
好的  那我通过removeRecord()来实现吧

**Comment by AriaLyy** [comment]
`3.6.6_beta_1`已经修复了这个问题
