### ISSUE TITLE
添加依赖报错是怎么回事啊？

### ISSUE THREAD

**Issue by matbird** [AriaLyy/Aria#43]
大神，添加依赖的时候说找不到啊？
`Error:(36, 13) Failed to resolve: com.arialyy.aria:Aria:3.1.8`

3.1.5就没问题

**Comment by AriaLyy** [comment]
compile 'com.arialyy.aria:aria-core:3.1.8'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.1.8'

抱歉，readme在合并的时候貌似被覆盖了

**Comment by matbird** [comment]
我说呢，昨天添加也一直报错，然后升级了gradle版本也还是一样的问题。
谢谢大神啊

**Comment by AriaLyy** [comment]
不客气，这是我的疏忽，感觉您的反馈
