### ISSUE TITLE
小米max2 在Application初始化的时候报错。

### ISSUE THREAD

**Issue by fadedHYC** [AriaLyy/Aria#430]
## Aria版本

![image](https://user-images.githubusercontent.com/22925521/61811668-92921f80-ae74-11e9-9ba7-6a5b6cb0c3ad.png)

## 什么问题
![image](https://user-images.githubusercontent.com/22925521/61811683-98880080-ae74-11e9-85bb-e2c201a3a797.png)

![image](https://user-images.githubusercontent.com/22925521/61811696-9f167800-ae74-11e9-91d2-4ec3b4c904ce.png)

## 如何复现此问题
手机 小米max2 在Application初始化的时候报错。

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/426

**Comment by fadedHYC** [comment]
3.6.6 版本什么时候上呢

**Comment by AriaLyy** [comment]
使用这个版本：3.6.6_beta_2
