### ISSUE TITLE
使用SFTP功能异常,设置asFTPS没有生效.

### ISSUE THREAD

**Issue by bigfacejava** [AriaLyy/Aria#434]
## Aria版本
3.6.4

## 什么问题
按照文档上使用SFTP的上传下载功能,异常. 设置sftp会先走asFtp,然后到asFtps的时候直接retuen了.请问一下sftp的功能完善吗?文档里也比较简洁

## 如何复现此问题
直接依赖,然后根据文档使用sftp功能,

**Comment by AriaLyy** [comment]
将sftp前缀修改为ftps看看

**Comment by AriaLyy** [comment]
3.8.5 已支持 sftp https://aria.laoyuyu.me/aria_doc/download/sftp_normal.html
