### ISSUE TITLE
M3U8支持多任务吗 

### ISSUE THREAD

**Issue by z876335662** [AriaLyy/Aria#436]

**Comment by AriaLyy** [comment]
支持

**Comment by cblsyp** [comment]
DownloadGroupTarget中没有asM3U8之类方法，如何实现多任务下载呢大神能否给一个实例代码。（version： 3.6.6）

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/core/download/m3u8/M3U8VodDLoadActivity.java

**Comment by cblsyp** [comment]
也就是多次调用   Aria.download(M3U8VodDLoadActivity.this)...start()   传入不同的url  然后根据key得到DownloadTarget对象   进行任务的控制吗？
