### ISSUE TITLE
批量操作的问题

### ISSUE THREAD

**Issue by huangyuan0pplabs** [AriaLyy/Aria#443]
## Aria版本
3.6.4， 3.6.5， 3.6.6-beta1，3.3.6-beta2， 3.6.6-beta3

## 什么问题
项目需求需要可以对下载任务进行全部停止全部继续任务，全部重试。但是遇到一些问题：
1.当创建多个下载任务后，使用stopAllTask()方法，经常有部分任务状态不是IEntity.STATE_STOP，依旧是IEntity.STATE_WAIT。如果杀死应用进程，再次进入应用，则所有任务状态都是IEntity.STATE_STOP。此现象这几个版本都存在。

2.使用rsumeAllTask()方法后，也经常有部分任务状态仍然是IEntity.STATE_STOP，此现象这几个版本都存在；

3.使用resumeAllTask()方法后，一般情况下各个任务都会一个接一个的继续完成，但是有时会遇到在stopAllTask()新创建任务后再resumeAllTask()，那些仍然为IEntity.STATE_STOP状态的任务，不会在其他任务下载完成后自动下载的情况。当杀死进城后再次进入应用，resumeAllTask()所有任务，基本不会出现这种部分任务不会自动下载的情况。但是有时经过各种反复操作后，resumeAllTask()方法只会启动一个任务下载，其他任务都没有反应。
这些resumeAllTask()失效的现象出现情况比较复杂，这几个版本上具体出现情况还没有做详细统计分析。

## 如何复现此问题
使用stopAllTask()和resumeAllTask()方法操作大量任务，比如20多个任务，甚至100个任务。其中因为恢复任务需要设置任务的headers，所以是先单个resumes()和reTry()后再调用resumeAllTask()，不过测试过，即使直接调用resumeAllTask()也是差不多的现象。

## 控制台日志
控制台日志没有看到什么异常位置

**Comment by AriaLyy** [comment]
第一个问题：
是特地这样处理的，进入app，Aria初始化时，首先会将所有状态为执行中的任务全部设置为停止；因为用户kill app，我是不知道的，系统也没有这种api接口。并且当你kill app后，所有状态为执行中的都应该是stop

第二个问题：
确认下stop的任务能否继续执行，因为恢复任务，只是把所有非完成状态的任务添加到队列中，如果队列已经满，会回调等待接口，否则任务进入下载流程。
在将任务加入队列的时候，是不会修改任务的状态的。

第三个问题：
有待观察，有可能是异步导致的，因为所有的操作是异步的..

**Comment by huangyuan0pplabs** [comment]
> 第一个问题：
> 是特地这样处理的，进入app，Aria初始化时，首先会将所有状态为执行中的任务全部设置为停止；因为用户kill app，我是不知道的，系统也没有这种api接口。并且当你kill app后，所有状态为执行中的都应该是stop
> 
> 第二个问题：
> 确认下stop的任务能否继续执行，因为恢复任务，只是把所有非完成状态的任务添加到队列中，如果队列已经满，会回调等待接口，否则任务进入下载流程。
> 在将任务加入队列的时候，是不会修改任务的状态的。
> 
> 第三个问题：
> 有待观察，有可能是异步导致的，因为所有的操作是异步的..



> 第一个问题：
> 是特地这样处理的，进入app，Aria初始化时，首先会将所有状态为执行中的任务全部设置为停止；因为用户kill app，我是不知道的，系统也没有这种api接口。并且当你kill app后，所有状态为执行中的都应该是stop
> 
> 第二个问题：
> 确认下stop的任务能否继续执行，因为恢复任务，只是把所有非完成状态的任务添加到队列中，如果队列已经满，会回调等待接口，否则任务进入下载流程。
> 在将任务加入队列的时候，是不会修改任务的状态的。
> 
> 第三个问题：
> 有待观察，有可能是异步导致的，因为所有的操作是异步的..



> 第一个问题：
> 是特地这样处理的，进入app，Aria初始化时，首先会将所有状态为执行中的任务全部设置为停止；因为用户kill app，我是不知道的，系统也没有这种api接口。并且当你kill app后，所有状态为执行中的都应该是stop
> 
> 第二个问题：
> 确认下stop的任务能否继续执行，因为恢复任务，只是把所有非完成状态的任务添加到队列中，如果队列已经满，会回调等待接口，否则任务进入下载流程。
> 在将任务加入队列的时候，是不会修改任务的状态的。
> 
> 第三个问题：
> 有待观察，有可能是异步导致的，因为所有的操作是异步的..

有个相关的问题，比如下载任务数为2，同时创建20个任务，在3.6.4版本上，是最先创建的两个任务最新下载，而其后的任务等待。后续版本上变成了第一个任务和隔着数个任务之后的第N个任务最新开始下载，其他的任务处于等待状态。

感觉任务进入下载流程的机制有了变化，原来是直接添加到下载队列中，现在似乎变成了一个任务走完了部分下载流程后才会将一个此时刚刚创建的任务再放入下载队列。

这个现象感觉对用户体验不友好，不知道产生原因是什么，后续是否会修改。

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/start/config.html

队列模式选择wait。

**Comment by AriaLyy** [comment]
使用3.6.6版本看看，停止全部操作后，做了移除所有线程任务任务的操作

**Comment by huangyuan0pplabs** [comment]
> 使用3.6.6版本看看，停止全部操作后，做了移除所有线程任务任务的操作

好的

**Comment by huangyuan0pplabs** [comment]
> https://aria.laoyuyu.me/aria_doc/start/config.html
> 
> 队列模式选择wait。

还是不行，不管是使用wiki里的配置文件，还是在代码使用Aria.get(this).getDownloadConfig().setQueueMod("wait");方法设置，都没有效果，3.6.6和3.6.6-beta3都是一样的，甚至设置Aria.get(this).getDownloadConfig().setQueueMod("now");也是一样的。

下载几十个apk，第一个任务进入下载，后续多个任务都是等待，再才有一个任务是下载，后续多个任务又是等待状态。

**Comment by huangyuan0pplabs** [comment]
> > 使用3.6.6版本看看，停止全部操作后，做了移除所有线程任务任务的操作
> 
> 好的

resumeAllTask()后部分任务不会自动继续下载的问题仍然存在，与之前版本相比基本没有什么变化。

**Comment by AriaLyy** [comment]
检查下你到代码，我这边测试队列是正常的

**Comment by huangyuan0pplabs** [comment]
> 检查下你到代码，我这边测试队列是正常的

好的，我再看看
