### ISSUE TITLE
下载的时候有时候报错闪退..

### ISSUE THREAD

**Issue by chenmingdu** [AriaLyy/Aria#444]
## Aria版本
3.6.5

## 什么问题
java.lang.ClassCastException
com.arialyy.aria.core.download.downloader.HttpThreadTask cannot be cast to java.lang.Long
com.arialyy.aria.core.common.ThreadStateManager.handleMessage(ThreadStateManager.java:105)

**Comment by AriaLyy** [comment]
已知问题 https://github.com/AriaLyy/Aria/issues/437，请使用`3.6.6_beta_3`版本
