### ISSUE TITLE
任务组下载空指针 3.6.6

### ISSUE THREAD

**Issue by kroben-ha** [AriaLyy/Aria#445]
@DownloadGroup.onTaskFail
    void groupTaskFail(DownloadGroupTask task) {
        // ALog.d(TAG, String.format("group【%s】fail", task.getTaskName()));
        adapter.updateState(task.getEntity());
    }

task.getEntity()空指针
如何引发异常：
任务组下载时，显示 下载大小4b和0切换，然后失败，点击恢复下载，
private void start(DownloadGroupEntity entity) {
        Aria.download(mContext).loadGroup(entity.getUrls()).start();
    }

**Comment by AriaLyy** [comment]
如果检查参数失败，就不会进入下载流程，也就不会创建DownloadGroupTask这个任务，这个地方需要你自己进行判空处理

**Comment by kroben-ha** [comment]
我尝试任务组，拿每个单独的任务，好像拿不到，如果说是多任务下载是没问题的。可以给个QQ号吗？我很多不懂的地方想要问下大佬。

**Comment by AriaLyy** [comment]
首先，你要清楚组合任务、普通任务、多任务的区别；
* 组合任务类似于打包下载，如：视频 + 字幕，两个文件的下载组合成一个任务，而视频、字幕被称为组合任务的子任务，他们共享同一进度。
* 普通任务类似单个文件下载，如：单独下载一个apk
* 多任务：__无论普通任务还是组合任务在aria中都叫做任务__。多任务意思是，多个任务同时下载.

如果你要获取任务列表，见[获取任务列表](https://aria.laoyuyu.me/aria_doc/api/task_list.html)
如果你是要获取组合任务中的子任务列表，请使用`groupEntity.getSubEntities()`。

**Comment by kroben-ha** [comment]
我都理解，组合任务我可能没太理解，我是想用组合任务下载视频，下载三个，让他们共享一个进度，然后拆分成一个列表，每个子任务配个单独的进度。或者我用多任务下载，用什么参数区分它们，然后根据参数筛选来实现。我对api不太熟，刚才看到你发的api。

**Comment by AriaLyy** [comment]
参考这个类：https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/core/download/group/DownloadGroupActivity.java

通过`groupEntity.getSubEntities()`可以获取到子任务信息
```java
 @DownloadGroup.onTaskRunning() protected void running(DownloadGroupTask task) {
    getBinding().setProgress(task.getPercent());
    getBinding().setSpeed(task.getConvertSpeed());
    mChildList.updateChildProgress(task.getEntity().getSubEntities());
  }
```
![image](https://user-images.githubusercontent.com/10437293/62602905-60c69180-b927-11e9-9d81-3449c2ab3203.png)

**Comment by kroben-ha** [comment]
好的，谢谢您
