### ISSUE TITLE
有时候开始任务的时候，直接就返回下载完成状态了

### ISSUE THREAD

**Issue by 710224800** [AriaLyy/Aria#45]
是怎么回事，大神

**Comment by 710224800** [comment]
貌似是没开始就完成了，因为进度一直是0，等了约1-2秒左右就直接提示完成，然而包是不完整的

**Comment by 710224800** [comment]
下载失败的时候，进度能否不显示-1

**Comment by AriaLyy** [comment]
能把失败的链接提供一下吗？

**Comment by AriaLyy** [comment]
失败的话，有一个失败的回掉，你可以在失败的回掉中处理你的UI

**Comment by 710224800** [comment]
没有回调失败，回调的完成，但是并没有下载完成，连接就是demo里的连接，偶现

**Comment by 710224800** [comment]
还有个问题大神，有时候下载的时候，突然就不动了，没有速度，点暂停再开始才行，
还有的时候下载大小出现负数如：-1234E3/239m   这种形式

**Comment by AriaLyy** [comment]
负数可能是我文件大小转换那导致的，回头我看下代码，看是是啥问题

**Comment by 710224800** [comment]
没有速度问题呢？，点暂停再开始才行

**Comment by AriaLyy** [comment]
速度可能是队列任务暂停了，晚上有空我看下代码

**Comment by 710224800** [comment]
负数问题能解决大神，我看了好几天没找到原因

**Comment by 710224800** [comment]
如果任务下载中，断开网络一会，并不提示暂停和失败，然后重新联通网络，暂停任务重新开始，就有机会出现负数

**Comment by AriaLyy** [comment]
负数的，新版本已经处理了，或者你自行处理，当获取当前进度时，如果长度小于0，你可以自行在UI界面上处理

**Comment by 710224800** [comment]
我今天看了一下，有任务下载中时，我断开网络
并没有回调到失败
DownloadUtil.java
第209行

**Comment by AriaLyy** [comment]
我这是可以的，下载中突然断网的失败要达到超时时间达到了才会回调的，我默认时间是10秒，测试的话，你可以把它改短点
