### ISSUE TITLE
插入多个多个单独任务时， 实际执行的任务数和插入的数量不相符

### ISSUE THREAD

**Issue by sufish** [AriaLyy/Aria#453]
## Aria版本

3.6.6
## 什么问题
插入多个单独任务时， 实际执行的任务数和插入的数量不相符

## 如何复现此问题
类似于如下的代码
```java
for(String url: urls){
Aria.download(this).load(url).setFilePath(filepath).start();
}
```
urls的长度为10的情况下，实际执行的数量为2，3，6等，随机出现。 当再次执行这样的代码，有时候又会实际执行10个任务，感觉有时序问题，任务没有被正确放入队列。 

## 控制台日志
D/BaseCachePool: 任务【face_c9a29d8fd2b74e068911f3ee8ba96b43.download】进入缓存队列成功
D/BaseCachePool: 任务【face_cb62152737074168aa5651bb41dbf1b4.download】进入缓存队列成功
D/HttpFileInfoThread: 长度不一致，任务为新任务
D/RecordHandler: 保存记录，线程记录数：1
D/Downloader: 任务【face_6d501b803afa45f0b1eb278eb11818aa.download】线程__0__恢复任务

这个取决于这次执行有多少任务被放入队列，没有任何错误日志

检查所有task的状态，发现大部分的task一直是在waiting的状态

**Comment by sufish** [comment]
如果每隔500毫秒插入一次任务，基本可以解决这个问题

**Comment by sufish** [comment]
已确定是3.6.5引入的问题，回滚到3.6.4，功能可以正常使用

**Comment by AriaLyy** [comment]
3.6.5以上版本做了间隔处理 https://github.com/AriaLyy/Aria/issues/427#issuecomment-513618323
