### ISSUE TITLE
java.lang.OutOfMemoryError pthread_create (1040KB stack) failed: Out of memory  com.arialyy.aria.core.scheduler.AbsSchedulers.handleFailTask(AbsSchedulers.java:497)

### ISSUE THREAD

**Issue by huangyuan0pplabs** [AriaLyy/Aria#454]
## Aria版本
3.6.6.-beta3

## 什么问题
框架OOM崩溃问题

## 如何复现此问题
bugly捕获发布版本的日志，复现路径不明,发现概率较低
设备机型：荣耀 NEM AL10，系统版本：Android 7.0,level 24， ROM：HuaWei/EMOTION， 
CPU架构：arm64-v8a

## 控制台日志
java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Out of memory

1 java.lang.Thread.nativeCreate(Native Method)
--
2 java.lang.Thread.start(Thread.java:745)
3 java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
4 java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1582)
5 java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:313)
6 java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
7 com.arialyy.aria.core.scheduler.AbsSchedulers.void handleFailTask(com.arialyy.aria.core.inf.ITask)(AbsSchedulers.java:497)
8 com.arialyy.aria.core.scheduler.AbsSchedulers.void handleNormalEvent(com.arialyy.aria.core.inf.ITask,int,int)(AbsSchedulers.java:292)
9 com.arialyy.aria.core.scheduler.AbsSchedulers.boolean handleMessage(android.os.Message)(AbsSchedulers.java:155)
10 com.arialyy.aria.core.scheduler.DownloadSchedulers.boolean handleMessage(android.os.Message)(DownloadSchedulers.java:27)
11 android.os.Handler.dispatchMessage(Handler.java:101)
12 android.os.Looper.loop(Looper.java:156)
13 android.app.ActivityThread.main(ActivityThread.java:6523)
14 java.lang.reflect.Method.invoke(Native Method)
15 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
16 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
