### ISSUE TITLE
3.6.5版本，使用sftp下载上传文件必须配置密钥？

### ISSUE THREAD

**Issue by 340022268** [AriaLyy/Aria#455]
## Aria版本
3.6.5

## 什么问题
使用sftp下载文件提示 “证书路径为空”。3.5.3不是可以无需配置证书了吗？
用FileZilla客户端访问同一个sftp服务器可以正常传输无需配置证书。

**Comment by AriaLyy** [comment]
没做默认证书处理，后续版本会考虑

**Comment by 340022268** [comment]
期待哟

**Comment by 340022268** [comment]
> 没做默认证书处理，后续版本会考虑

期待哟

**Comment by AriaLyy** [comment]
3.8.5版本已增加sftp功能，详情见[sftp下载](https://aria.laoyuyu.me/aria_doc/download/sftp_normal.html)，[sftp上传](https://aria.laoyuyu.me/aria_doc/upload/sftp_normal.html)
