### ISSUE TITLE
兼容SDK28 hide api的问题

### ISSUE THREAD

**Issue by BayMikyou** [AriaLyy/Aria#456]
## Aria版本
com.arialyy.aria:aria-core:3.5
com.arialyy.aria:aria-compiler:3.5

## 什么问题
为了兼容SDK28 FileUtil类中存在反射hide api
## 如何复现此问题
![image](https://user-images.githubusercontent.com/31265255/63247773-6e213b80-c298-11e9-9a69-46e6b3c7c03a.png)

**Comment by AriaLyy** [comment]
这个有什么影响妈？

**Comment by BayMikyou** [comment]
有的 OPPO应用商店检测到了，如果不及时处理会影响APP上架问题

**Comment by AriaLyy** [comment]
了解了，后续版本会处理这个问题

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
