### ISSUE TITLE
多线程下载的问题

### ISSUE THREAD

**Issue by lucky-you** [AriaLyy/Aria#457]
## Aria版本
版本：3.6.6

## 什么问题
1.AbsEntity 类中只包含了下载速度和状态等，视频的封面和名称我该怎么记录到数据库中去呢？
2.在当前页面点击下载，开始启动下载，我离开这个页面就停止下载了，怎么能让它在后台持续下载呢？

## 控制台日志
这是我的设计稿：
![下载缓存](https://user-images.githubusercontent.com/22268878/63263589-a1c18d00-c2bb-11e9-8ecf-6548d8bc9ce8.png)

**Comment by AriaLyy** [comment]
1、使用扩展字段
2、下载任务是在线程中的，和activity的生命周期没有关系，请检查你的代码

**Comment by lucky-you** [comment]
再请教一个问题，我需要一边下载一边更新进度条（也就是刷新界面）。
我获取到下载中的视频信息，那不就是需要一直去向数据库插入同一个对象，然后再从数据库查询这个视频，获取到之后再更新界面，这样就会出现下载中，界面一直在刷新的问题，请问改如何优化一下？

**Comment by AriaLyy** [comment]
不清楚你的需求，界面刷新和优化需要你自己处理
