### ISSUE TITLE
22702 android.system.ErrnoException statvfs failed: ENOTCONN (Transport endpoint is not connected)  com.arialyy.aria.util.CommonUtil.long getAvailableExternalMemorySize(java.lang.String)(CommonUtil.java:227)

### ISSUE THREAD

**Issue by huangyuan0pplabs** [AriaLyy/Aria#458]
## Aria版本
3,6,6-beta3

## 什么问题
bugly捕获发布版本崩溃日志

## 如何复现此问题
如上，目前仅捕获一例，复现路径不明。
设备机型: 金立 S9
系统版本: Android 6.0,level 23
ROM: amigo/GiONEE+ROM5.0.17
CPU架构: arm64-v8a

## 控制台日志
Thread-2818(2818)
android.system.ErrnoException
statvfs failed: ENOTCONN (Transport endpoint is not connected)
java.lang.IllegalArgumentException:Invalid path: /storage/emulated/0
--
2 android.os.StatFs.doStat(StatFs.java:46)
3 ......
4 android.system.ErrnoException:statvfs failed: ENOTCONN (Transport endpoint is not connected)
5 libcore.io.Posix.statvfs(Native Method)
6 libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:298)
7 android.system.Os.statvfs(Os.java:500)
8 android.os.StatFs.doStat(StatFs.java:44)
9 android.os.StatFs.<init>(StatFs.java:39)
10 com.arialyy.aria.util.CommonUtil.long getAvailableExternalMemorySize(java.lang.String)(CommonUtil.java:227)
11 com.arialyy.aria.util.CommonUtil.boolean checkSDMemorySpace(java.lang.String,long)(CommonUtil.java:212)
12 com.arialyy.aria.core.download.downloader.HttpFileInfoThread.void handleConnect(java.net.HttpURLConnection)(HttpFileInfoThread.java:123)
13 com.arialyy.aria.core.download.downloader.HttpFileInfoThread.void handleUrlReTurn(java.net.HttpURLConnection,java.lang.String)(HttpFileInfoThread.java:315)
14 com.arialyy.aria.core.download.downloader.HttpFileInfoThread.void handleConnect(java.net.HttpURLConnection)(HttpFileInfoThread.java:213)
15 com.arialyy.aria.core.download.downloader.HttpFileInfoThread.void handleUrlReTurn(java.net.HttpURLConnection,java.lang.String)(HttpFileInfoThread.java:315)
16 com.arialyy.aria.core.download.downloader.HttpFileInfoThread.void handleConnect(java.net.HttpURLConnection)(HttpFileInfoThread.java:213)
17 com.arialyy.aria.core.download.downloader.HttpFileInfoThread.void run()(HttpFileInfoThread.java:85)
18 java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
