### ISSUE TITLE
等待中状态保存的问题

### ISSUE THREAD

**Issue by wojiaoyanxin** [AriaLyy/Aria#459]
## Aria版本
3.6.6

## 什么问题
等待状态变成暂停

## 如何复现此问题
在下载列表中,存在多个下载任务,首次进入,如果最大允许3个任务进行,会显示3个正在下载,其余显示等待中,此时执行全部暂停,任务全部变成暂停状态,再执行全部开始,则个正在下载,其余显示等待中,退出当前activity再次进入,此时之前的等待中任务全部变成已暂停状态

**Comment by OJZen** [comment]
我也出现了此问题。

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
