### ISSUE TITLE
在下载图片列表的时候，出现了部分图片出错的问题

### ISSUE THREAD

**Issue by matbird** [AriaLyy/Aria#46]
`String baseUrl = "http://file.bmob.cn/";
        String[] urlArray = {"M02/3B/A4/oYYBAFaOeUSAc1QiAAFTbmA7AHs052.jpg","M02/3B/A4/oYYBAFaOeUaAfYC-AAFD8zf9NXc879.jpg","M02/3B/A4/oYYBAFaOeUuAOxhnAACSdmbqSac702.jpg","M02/3B/A4/oYYBAFaOeU2AFAIGAAFICximvXc924.jpg","M02/3B/A4/oYYBAFaOeVCAPWMQAAFm2KWCq_E721.jpg","M02/3B/A4/oYYBAFaOeVOAbiv9AAFfCTTgr94948.jpg","M02/3B/A4/oYYBAFaOeVaAMR3tAAFf3yTuuCM577.jpg","M02/3B/A4/oYYBAFaOeVmACEWhAAEt72ecbpg468.jpg","M02/3B/A4/oYYBAFaOeVyAHHt4AAFg9e9bRio507.jpg","M02/3B/A4/oYYBAFaOeV-AClYXAAESLGY0gag424.jpg","M02/3B/A4/oYYBAFaOeWKAA7N0AAF3omYOJUI703.jpg","M02/3B/A4/oYYBAFaOeWWAD2lrAAFN7eRFxBs575.jpg","M02/3B/A4/oYYBAFaOeWiAdCVEAAFg4273Dus313.jpg","M02/3B/A4/oYYBAFaOeWyAJDm5AAF8JVoGVb0705.jpg","M02/3B/A4/oYYBAFaOeW-AUoA8AAGjKiHkXUo181.jpg","M02/3B/A4/oYYBAFaOeXKABIamAAFU7J7vraE265.jpg","M02/3B/A5/oYYBAFaOeXaAW09jAAFf37qdwDA457.jpg","M02/3B/A5/oYYBAFaOeXmAWmS7AAFtLNpWjgo967.jpg","M02/3B/A5/oYYBAFaOeX2AQf9cAAF2fhwS2UE145.jpg","M02/3B/A5/oYYBAFaOeYCAKGnLAAFVAzks-qU937.jpg","M02/3B/A5/oYYBAFaOeYOAMODNAAF6HjTTMq4819.jpg","M02/3B/A5/oYYBAFaOeYeAbn8uAAFLSQLw48Q042.jpg","M02/3B/A5/oYYBAFaOeYqAMJThAAFtrNe4UNM047.jpg","M02/3B/A5/oYYBAFaOeY2AbnQvAAFNSXWn0Dc026.jpg","M02/3B/A5/oYYBAFaOeZCAIsr0AAFHZFEVhPc682.jpg","M02/3B/A5/oYYBAFaOeZOAGvITAAFqPmfcc9c471.jpg","M02/3B/A5/oYYBAFaOeZaATvjbAAFHDmALnhE003.jpg","M02/3B/A5/oYYBAFaOeZmAJPuVAAFfPJC2wsE319.jpg","M02/3B/A5/oYYBAFaOeZyAXtAmAAFfArJNwtM371.jpg","M02/3B/A5/oYYBAFaOeZ-AGZN0AAFgqwYYCS8004.jpg","M02/3B/A5/oYYBAFaOeaOAbbrGAAFcq59JjUo205.jpg","M02/3B/A5/oYYBAFaOeaSAdFyoAACaxVxgUJA092.jpg"};
        for(int i=0;i<urlArray.length;i++){
            Aria.download(this)
                    .load(baseUrl+urlArray[i])
                    .setDownloadPath(saveDir + "test" + i + ".jpg")
                    .start();
        }`

### 出现的问题：
32张图片只有两张在相册中是可以打开的，其他的全都是黑屏，图片大小是对的。
打开错误图片的信息，发现分辨率信息是：-1x-1
### 疑问？
是否aria在存储的时候丢失了部分信息？抑或是我的调用方式不对？

![](http://of2squwm4.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720170615155744.jpg)

**Comment by AriaLyy** [comment]
下载队列的大小是多大？

**Comment by AriaLyy** [comment]
我这看到的情况是，有些文件超时了，然后在浏览器打开某些链接，如http://file.bmob.cn/M02/3B/A4/oYYBAFaOeW-AUoA8AAGjKiHkXUo181.jpg，大概需要5到6秒时间，
建议把下面两个超时时间改才一点.
 <connectTimeOut value="5000"/>
    <iOTimeOut value="20000"/>

**Comment by AriaLyy** [comment]
如果你是多任务同时下载的话，Aria的Start机制是，如果你的队列大小是3，你连续下载30个文件，Aria会，自动停止最先开始的任务，正确的做法是：
```java
int maxNum = Aria.get(this).getDownloadConfig().getMaxTaskNum();
    for (int i = 0; i < urlArray.length; i++) {
      if (i < maxNum) {
        Aria.download(this)
            .load(baseUrl + urlArray[i])
            .setDownloadPath(Environment.getExternalStorageDirectory() + "/test/" + i + ".jpg")
            .start();
      } else {
        Aria.download(this)
            .load(baseUrl + urlArray[i])
            .setDownloadPath(Environment.getExternalStorageDirectory() + "/test/" + i + ".jpg")
            .add();
      }
    }
```
add的任务为自动开始任务，当队列中的任务下载完成后，会自动下载add的任务

**Comment by matbird** [comment]
好的，我去试一下，应该就是这个队列的问题了，谢谢

**Comment by AriaLyy** [comment]
中午空闲时，我重新研究了一下，对于你这种情况，可能的原因为：
你的服务器处于高并发状态，开启多线程下载时候，服务器不能及时处理你的任务，导致图片下载不完成。
解决方案：
1. 增加链接超时时间`<connectTimeOut value="10000"/>`
2. 减少同时下载的任务数` <maxTaskNum value="2"/>`
3. 不使用多线程下载`<threadNum value="1"/>`（多线程下载，每一个线程都是一个请求）
4. 用md5码判断文件是否完整，不完整的话，重新下载

我使用了前面1、2、3三个设置，在链接不超时的情况下，基本都能成功下载

**Comment by AriaLyy** [comment]
32张图片，除了一张连接超时外，其余的都下载成功
![1.png](http://upload-images.jianshu.io/upload_images/1824042-a1577042cc3c10ff.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


![2.png](http://upload-images.jianshu.io/upload_images/1824042-70da45a97d771921.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
