### ISSUE TITLE
for循环中添加大量下载链接   Aria.download(this).load（） ，会有很多数据无法进入等待队列

### ISSUE THREAD

**Issue by Mr-YangCheng** [AriaLyy/Aria#461]
## Aria版本
3.6.6

## 什么问题

for循环中添加大量下载链接   Aria.download(this).load（） ，会有很多数据无法进入等待队列

**Comment by AriaLyy** [comment]
做了500ms处理 https://github.com/AriaLyy/Aria/issues/427#issuecomment-513618323

**Comment by xyUp** [comment]
您好，请问这个问题解决了吗，关于for循环中添加大量下载链接 Aria.download(this).load().start() ，会有很多数据无法进入等待队列

**Comment by xyUp** [comment]
您好，请问这个问题解决了吗，关于for循环中添加大量下载链接 Aria.download(this).load().start() ，会有很多数据无法进入等待队列，看3.6.6版本，把cancel方法里的isFastDoubleClick判断给删除了，其他方法这个判断还在
