### ISSUE TITLE
正式版本第一次下载不显示

### ISSUE THREAD

**Issue by lucky-you** [AriaLyy/Aria#462]
## Aria版本
版本：3.6.6

## 什么问题
打包正式版本，安装成功，第一次点击缓存下载，在缓存列表中没有显示，第二次就正常了。

**Comment by AriaLyy** [comment]
add() 还是 start() ?

**Comment by lucky-you** [comment]
Aria.download(mContext)
                .load(downLoadVideo.getVideo_url())
                .setFilePath(PATH_CHALLENGE_VIDEO)
                .setExtendField(JsonUtils.toJson(downLoadVideo))
                .start();

**Comment by AriaLyy** [comment]
请查看下日志，查看是否有“任务开始”等信息

**Comment by lucky-you** [comment]
在Debuge模式下，点击下载之后，走了onPre（），taskRunning（）方法，也就是说，实际是在下载，就是在下载列表中没有展示出来。

**Comment by AriaLyy** [comment]
列表界面需要你自己处理，请打印log查看每一个item的状态

**Comment by lucky-you** [comment]
我是把下载的数据存到数据库里面，也就是说在taskRunning（）我需要不断的存入已经下载的数据，只这样吗？

**Comment by lucky-you** [comment]
> 列表界面需要你自己处理，请打印log查看每一个item的状态

点击下载之后，还会出现一种情况，预处理状态onPre（），没有日志输出，直接到了taskRunning（）状态。
![企业微信截图_15664605568763](https://user-images.githubusercontent.com/22268878/63497014-8a6de400-c4f5-11e9-8617-d84d305dcdb8.png)

**Comment by AriaLyy** [comment]
onPre 必定会调用，除非任务进入缓存

**Comment by lucky-you** [comment]
正式版第一次有时候不下载，这个该怎么处理一下呢？

**Comment by AriaLyy** [comment]
请参考demo例子，我测试多少次都是正常的https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/core/download/SingleTaskActivity.java

**Comment by lucky-you** [comment]
是我自己这边的问题，已经解决了，谢谢
