### ISSUE TITLE
你好,使用FTPS登陆问题

### ISSUE THREAD

**Issue by wuxinlingluan** [AriaLyy/Aria#467]
## Aria版本
3.6.6

## 什么问题
使用示例代码进行FTPS上传时候,提示登陆失败,请问如何解决

## 控制台日志
登录失败，错误码为：530， msg：530 This server does not allow plain FTP. You have to use FTP over TLS.

**Comment by AriaLyy** [comment]
是如何写的？麻烦提供下上传部分的代码

**Comment by wuxinlingluan** [comment]
> 是如何写的？麻烦提供下上传部分的代码

     Aria.upload(this)
                .loadFtp(picturePath)
                .setUploadUrl("ftp://**.***.***.***:**")
                .login("***", "******")
                .asFtps()
                .setProtocol(ProtocolType.SSL) 
                .start();

**Comment by AriaLyy** [comment]
将ftp://xxxx，修改为ftps://xxxx

**Comment by AriaLyy** [comment]
3.8.5版本已增加sftp功能，详情见[sftp下载](https://aria.laoyuyu.me/aria_doc/download/sftp_normal.html)，[sftp上传](https://aria.laoyuyu.me/aria_doc/upload/sftp_normal.html)
