### ISSUE TITLE
cancel 删除任务实体会出现一点延迟

### ISSUE THREAD

**Issue by OJZen** [AriaLyy/Aria#468]
## aria 版本
3.6.6

## 详细的问题过程
执行下面这段代码，并没有马上将url对应的实体删除，也就是说entityList里面还存在着url对应的实体。
```
Aria.download(mContext).load(url).cancel(true);
entityList = Aria.download(mContext).getAllCompleteTask();
```

如果在这中间插一个50ms的延迟则没有问题。

所以，`cancel`删除一个任务实体会出现一点延迟。

**Comment by AriaLyy** [comment]
在aria中，所有对任务的操作都是异步的，包括删除

**Comment by OJZen** [comment]
@AriaLyy 好的，我明白了。
