### ISSUE TITLE
README.md里面的两个错别字

### ISSUE THREAD

**Issue by OJZen** [AriaLyy/Aria#469]
## 1
`Aria项目源于工作中遇到的一个文件下载管理的需求，当时被下载折磨的痛不欲生，从那时起便萌生了编写一个简单易用，稳当高效的下载框架，aria经历了1.0到3.0的开发，算是越来越接近当初所制定的目标了。`

这里`折磨`为动词，所以后面应该接`得`。应改为：`当时被下载折磨得痛不欲生`。

## 2
`注解回掉采用Apt的方式实现，所以，你不需要担心这会影响你机器的性能`

这里`回掉`按照原文意思应该改为：`回调`。

##
以上。

**Comment by AriaLyy** [comment]
我后面改下，😂
