### ISSUE TITLE
第一次下载会一直停留在预加载状态，不开始下载

### ISSUE THREAD

**Issue by lucky-you** [AriaLyy/Aria#470]
## Aria版本
3.6.6

## 什么问题
安装程序，第一次下载状态一直停留在预处理，就是不开始下载，退出页面重新进来也依然不下载。
我在fragment中的各个状态打了日志，第一次都没有日志输出，我怀疑是第一次在fragment中的注解没有生效的原因。
![QQ图片20190831164741](https://user-images.githubusercontent.com/22268878/64061557-12976c00-cc0f-11e9-9ad5-42d0727d4412.jpg)

**Comment by AriaLyy** [comment]
请提供详细的日志

**Comment by Richard0403** [comment]
我也遇见了，组合任务下载，第一次运行不开始，咋回事？
