### ISSUE TITLE
组下载初次下载成功退出界面再进入界面下载出现问题

### ISSUE THREAD

**Issue by brivelee** [AriaLyy/Aria#471]
## Aria版本

3.6.6
## 什么问题

组下载初次下载成功后，退出下载界面，再进入下载界面下载，出现进入缓存队列，并提示正在下载，但未执行下载操作
## 控制台日志
09-10 19:09:04.462 14076-14726/ D/BaseCachePool: 任务【任务组->a6fdee46881890b14d0af5b32e48e5df】进入缓存队列成功
09-10 19:09:04.462 14076-14726/W/StartCmd: 任务【任务组->a6fdee46881890b14d0af5b32e48e5df】已经在运行

**Comment by AriaLyy** [comment]
你设置组合任务大小没有？没有设置的话需要更长的时间才能进入下载流程
