### ISSUE TITLE
3.6.3升级到3.6.6之后项目编译报错

### ISSUE THREAD

**Issue by 13871124816** [AriaLyy/Aria#472]
## Aria版本
3.6.6

## 什么问题
3.6.3升级到3.6.6之后项目编译报错

## 如何复现此问题
之前使用3.6.3正常，刚才升级到3.6.6之后编译报错。

## 控制台日志
D:\Program Files\myAsProjects\electronic_class_v3\branches\zhanghui\haikang_V31\app\build\generated\source\apt\RELEASE\debug\com\tyjy\electronicclass\home\HomeActivity$$DownloadGroupListenerProxy.java:5: 错误: 找不到符号
import com.arialyy.aria.core.scheduler.AbsSchedulerListener;
                                      ^
  符号:   类 AbsSchedulerListener
  位置: 程序包 com.arialyy.aria.core.scheduler
D:\Program Files\myAsProjects\electronic_class_v3\branches\zhanghui\haikang_V31\app\build\generated\source\apt\RELEASE\debug\com\tyjy\electronicclass\home\HomeActivity$$DownloadGroupListenerProxy.java:13: 错误: 找不到符号
public final class HomeActivity$$DownloadGroupListenerProxy extends AbsSchedulerListener<DownloadGroupTask, DownloadEntity> {
                                                                    ^
  符号: 类 AbsSchedulerListener
2 个错误

**Comment by 13871124816** [comment]
我进到com.arialyy.aria.core.scheduler路径下看了，确实没有这个类AbsSchedulerListener。

**Comment by AriaLyy** [comment]
clean 工程，重新build，3.6.6中这个类改名字了

**Comment by 13871124816** [comment]
3.6.3发现了一个bug，不知道3.6.6改了没有，就是子任务完成时监听到的url错误，跟其它子任务重复了，具体代码为：void onSubTaskComplete(DownloadGroupTask groupTask, DownloadEntity subEntity){
    String picurl = subEntity.getUrl();
}
打log以及断点发现有两个子任务获取到的这个picurl 一样，场景是下载6张不同的小图片，第一次下载picurl 都不相同，第二次重复下载这6张小图片时就发现其中两个子任务的picurl相同，重复测试多次每次都有相同的情况出现

**Comment by 13871124816** [comment]
> clean 工程，重新build，3.6.6中这个类改名字了

大神，我从昨天到今天已经clean了无数次，包括手动删除build文件夹，还重启了AS和电脑，都没用，依然报错找不到类，求指教！
