### ISSUE TITLE
3.6.6版本多次下载的文件不能放在同一目录下

### ISSUE THREAD

**Issue by 13871124816** [AriaLyy/Aria#474]
## Aria版本
3.6.6

## 什么问题
3.6.6版本多次下载的文件不能放在同一目录下

## 如何复现此问题
设置照片下载之后放在/sdcard/facePics/目录，第一次下载6张全部成功，第二次下载7张到同一个目录，下载失败，log显示文件夹路径【/sdcard/facePics/】已被其它任务占用，第一次下载完成之后推出app重新进入再次下载，依然会提示占用，3.6.3不存在该问题。

## 控制台日志

09-11 09:52:50.471 4218-4218/com.tyjy.electronicclass E/HttpGroupConfigHandler: 文件夹路径【/sdcard/facePics/】已被其它任务占用，请重新设置文件夹路径

**Comment by AriaLyy** [comment]
参考 https://github.com/AriaLyy/Aria/issues/311#issuecomment-427727900

**Comment by 13871124816** [comment]
setFilePath(path, true)，这个方法是单文件下载吧？组下载里面没有找到强制下载的方法，请大神指教！

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/476
