### ISSUE TITLE
任务组没有强制下载的方法

### ISSUE THREAD

**Issue by 13871124816** [AriaLyy/Aria#476]
## Aria版本
3.6.6

## 什么问题
任务组下载提示文件夹被占用，setFilePath(path, true)这个方法应该只适合单个任务下载，任务组下载里面没有找到强制下载的api！

## 如何复现此问题
建任务组下载必现。

## 控制台日志
09-11 09:52:50.471 4218-4218/com.tyjy.electronicclass E/HttpGroupConfigHandler: 文件夹路径【/sdcard/facePics/】已被其它任务占用，请重新设置文件夹路径

**Comment by AriaLyy** [comment]
后面考虑增加

**Comment by 13871124816** [comment]
好的，谢谢大神的回复，还有昨天提的那个监听子任务的url有bug的问题，麻烦有时间看下！
就是子任务完成时监听到的url错误，跟其它子任务重复了，具体代码为：void onSubTaskComplete(DownloadGroupTask groupTask, DownloadEntity subEntity){
String picurl = subEntity.getUrl();
}
打log以及断点发现有两个子任务获取到的这个picurl 一样，场景是下载6张不同的小图片，第一次下载picurl 都不相同，第二次重复下载这6张小图片时就发现其中两个子任务的picurl相同，重复测试多次很大概率会出现其中两个子任务的url相同的情况，通过观察发现出现重复url时两张小图片下载完成的时间很接近，一秒钟以内。

**Comment by AriaLyy** [comment]
后面我抽空看下

**Comment by Reginer** [comment]
文件夹路径     已被其它任务占用，请重新设置文件夹路径,我这也是

**Comment by AriaLyy** [comment]
3.7.10 增加了强制下载的方法

**Comment by Reginer** [comment]
是哪个api ？setDirPath(dirPath)还是一个参数
