### ISSUE TITLE
【非bug】请教注解初始化的问题

### ISSUE THREAD

**Issue by guxun12** [AriaLyy/Aria#48]
你好，我clone项目后发现并没有apt插件的引用，比如类似以下代码片段
`apply plugin: 'com.neenbedankt.android-apt'`
`dependencies {
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
}`
但是demo项目可以正常创建辅助代码，比如：UploadActivity$$UploadListenerProxy.java
请问APT初始化的逻辑是在哪里呢？非常感谢😝

**Comment by AriaLyy** [comment]
`apply plugin: 'com.neenbedankt.android-apt'`作者已经停止维护了，现在一般使用谷歌各方插件`annotationProcessor` ,`annotationProcessor`和`compile`的使用一样方便，并且不需要在gradle增加额外的插件

**Comment by guxun12** [comment]
@AriaLyy 
我发现Aria项目中并没有直接使用annotationProcessor，对注解处理器工程使用以下形式依赖
`dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')
  testCompile 'junit:junit:4.12'
  compile 'com.android.support:appcompat-v7:23.1.1'
  compile project(':AriaCompiler')
  //  compile project(':AriaAnnotations')
}`
是否表示对于注解处理器Module使用`annotationProcessor `和`compile `是一样的效果？
谢谢！

**Comment by AriaLyy** [comment]
是的，效果是一样的，直接依赖module方便本地测试......
正式打包出去，不依赖module的时候需要使用annotationProcessor

**Comment by guxun12** [comment]
@AriaLyy 谢谢大牛回复，学习了！
