### ISSUE TITLE
FTP上传中切换网络会出现崩溃

### ISSUE THREAD

**Issue by cc1314** [AriaLyy/Aria#482]
## Aria版本
3.6.6

## 什么问题
FTP上传中切换网络会出现崩溃

## 如何复现此问题
开始上传时使用wifi，在上传过程中关闭wifi使用4g会出现崩溃

## 控制台日志
# Thread-614(50127)
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

com.arialyy.aria.core.common.ftp.FtpTaskConfig.getUploadInterceptor(FtpTaskConfig.java:59)
com.arialyy.aria.core.upload.uploader.FtpFileInfoThread.onInterceptor(FtpFileInfoThread.java:66)
com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:135)
java.lang.Thread.run(Thread.java:784)

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
