### ISSUE TITLE
旧版本升到3.6.6获取下载进度超100了

### ISSUE THREAD

**Issue by Reginer** [AriaLyy/Aria#483]
## Aria版本
3.6.6

## 什么问题
旧版本升到3.6.6获取下载进度超100了

## 如何复现此问题
旧版本下载应用之后切换到3.6.6，新版本下载几次进度都超，清除数据之后再下载数据正常，猜测是没更新文件大小

**Comment by AriaLyy** [comment]
哪个版本升级的？能否提供下日志

**Comment by Reginer** [comment]
3.6.5，我给本地数据清除复现不了了，复现之后发给你。不过我估计就算不升级也会有这种情况。
开始下载之后文件大小不更新。

**Comment by AriaLyy** [comment]
好的

**Comment by Reginer** [comment]
复现了，下载过程中断网，之后再开网。断网的时候下载就中断了，开网之后自己就下载了。
下载之后的文件是错的，本地文件删除之后重新下载，下载进度就超了。

**Comment by AriaLyy** [comment]
开网之后自己就下载，是你那边处理的还是配置了断网继续重试？

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
