### ISSUE TITLE
普通模式设置了多线程下载之后，还是只会下载一个，其他的都处于等待状态

### ISSUE THREAD

**Issue by xicong** [AriaLyy/Aria#485]
## Aria版本
3.6.6

## 什么问题
普通模式设置了多线程下载之后，还是只会下载一个，其他的都处于等待状态

## 如何复现此问题
普通模式下，修改下载线程为非默认值的数字
![image](https://user-images.githubusercontent.com/11675597/67141067-95918600-f292-11e9-8818-e4d38ecb086b.png)

**Comment by AriaLyy** [comment]
需要修改的是任务数
