### ISSUE TITLE
你好，怎么感觉IBandWidthUrlConverter有时候不被执行呢

### ISSUE THREAD

**Issue by deepdream88** [AriaLyy/Aria#486]
## Aria版本
最新版，3.6.6

## 什么问题
有时候下载M3U8文件，IBandWidthUrlConverter的convert好像没有执行，然后任务下载失败，报错信息是M3U8 Exception:no protocol: 1000k/hls/index.m3u8
有时候就可以正常调用，任务正常执行。

## 如何复现此问题
m3u8地址：https://youku.com-iqiyi.net/20191008/22581_3ae03efd/index.m3u8

## 控制台日志
    ====================Exception Info====================
    com.arialyy.aria.exception.M3U8Exception: M3U8 Exception:no protocol: 1000k/hls/index.m3u8
    com.arialyy.aria.core.download.m3u8.M3U8InfoThread.failDownload(M3U8InfoThread.java:278)
    com.arialyy.aria.core.download.m3u8.M3U8InfoThread.run(M3U8InfoThread.java:94)
    java.lang.Thread.run(Thread.java:761)
    ===================================================

**Comment by deepdream88** [comment]
仔细调试原来是我退出的太快了

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/473#issuecomment-543573008 已知问题，后面版本会改

**Comment by deepdream88** [comment]
> [#473 (comment)](https://github.com/AriaLyy/Aria/issues/473#issuecomment-543573008) 已知问题，后面版本会改

顺便请问一下，m3u8跳片，跳到指定位置后是同时下载多个分片还是顺序下载分片？因为高峰期播放m3u8会频繁卡顿，所以想着同时下载多个分片能缓解此问题。

最后非常感谢你的作品，我不能对你要求什么。

**Comment by AriaLyy** [comment]
默认是4个，可以调用的`setMaxTsQueueNum()`设置

**Comment by deepdream88** [comment]
> 默认是4个，可以调用的`setMaxTsQueueNum()`设置

哦哦，再烦请问一下，暂停m3u8下载任务后，好像就无法再继续下载了（尤其是重启APP后）。

有时，我再测试期间，多次删除并重新下载一个链接，刚开始还能下载，后来只显示下载中，却不见进度。我不太清楚原因，这和我删除时没有调用service.aria.load(url).removeRecord();有关系么？
我删除任务只用了service.aria.load(url).cancel(removeFile);
删除全部任务也只用了service.aria.removeAllTask(removeFile);
说完这番话后，我在删除方法中加入了：service.aria.load(url).removeRecord();

**Comment by AriaLyy** [comment]
删除记录，相当于把任务删除了。
`cancel()`是删除方法，`stop()`才是停止
