### ISSUE TITLE
Aria 3.6.6 空指针问题

### ISSUE THREAD

**Issue by zjloong** [AriaLyy/Aria#487]
## Aria版本
3.6.6

## 什么问题
Downloader -> onPostPre -> file.getParentFile() 为 null

## 如何复现此问题
bug统计到出现几率较高, 自测未能复现

## 控制台日志
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at com.arialyy.aria.core.download.downloader.Downloader.onPostPre(SourceFile)
	at com.arialyy.aria.core.common.AbsFileer.startFlow(SourceFile)
	at com.arialyy.aria.core.common.AbsFileer.run(SourceFile)
	at java.lang.Thread.run(Thread.java:776)

**Comment by zjloong** [comment]
这里的代码这样改一下是不是更加安全点?  

原代码:
```java
@Override protected void onPostPre() {
    super.onPostPre();
    ((IDownloadListener) mListener).onPostPre(mEntity.getFileSize());
    File file = new File(mEntity.getDownloadPath());
    if (!file.getParentFile().exists()) {
      file.getParentFile().mkdirs();
    }
  }
```

修改后:
```java
protected void onPostPre() {
        super.onPostPre();
        ((IDownloadListener) mListener).onPostPre(mEntity.getFileSize());
        File file = new File(mEntity.getDownloadPath());
        File parentFile = new File(file.getParent());
        // System.out.println("aria parentFile: " + parentFile.getAbsolutePath());
        if (!parentFile.exists()) {
            parentFile.mkdirs();
        }
    }
```

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题

**Comment by zjloong** [comment]
3.7 只支持 androidx 版的吗

**Comment by AriaLyy** [comment]
是的，毕竟androidx是趋势了
