### ISSUE TITLE
你好，多次取消并重新下载同一个链接会下载失败的问题

### ISSUE THREAD

**Issue by deepdream88** [AriaLyy/Aria#489]
## Aria版本
3.6.6和3.6.5

## 什么问题
多次取消并重新下载同一个链接会下载失败，原因是码率转换器未被调用，提示了错误的下载地址，当我对对应用清除数据后即可解决该问题，在我调用aria.removeAllTask(true);之后发现数据库中有一个表还存在数据，或许是因为缓存信息影响了任务下载，所以我想在调用aria.removeAllTask(true);之后并清空或删除数据库。不知道aira有没有相关api可用，如果没有，我只能直接删除数据库文件了。

**Comment by AriaLyy** [comment]
这个是已知问题 https://github.com/AriaLyy/Aria/issues/473#issuecomment-543573008
