### ISSUE TITLE
你好，jumPeerIndex()方法只能向后跳？不能像前跳么？

### ISSUE THREAD

**Issue by deepdream88** [AriaLyy/Aria#490]
## Aria版本
3.6.6

## 什么问题
我很想知道jumpeerindex的工作机制，因为我在使用过程中遇到了一些小问题，比如，跳到索引1000，他可能会从1006分片开始下载，我目前可以通过减去一个值，来缓解该问题。
在我跳到1000之后，再调用jumpeerindex(300)，将没有任何回应，我看到分片还在1000处继续下载，直到下载至最后一个分片，然后从头开始下载未下载的分片。

## 总的来说
我想知道能不能回过头来下载前面的分片？
如果已经下载了300-305的分片，我跳跃到300开始下载，应该可以检测到分片存在，然后从306分片下载吧？

###最后感谢你能从百忙之中抽空查看我的问题

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/67645502-1839d580-f964-11e9-8532-5be0d22cb130.png)

**Comment by deepdream88** [comment]
刚开始可以正确运行，但是多次跳转分片后，好像就不管用了。

**Comment by AriaLyy** [comment]
麻烦提供下日志，我这测试是正常的

**Comment by deepdream88** [comment]
我这边看日志是
当我跳转到分片1000时，日志输出【将优先下载1000之后的任务】，随后显示【已停止123等分片】
等待一会后，继续从123之后开始下载。
有时候可以正确运行，我不知道这和什么因素有关系。
每次跳转分片，必定会输出 将优先下载... 以及  已停止当前正在下载的分片。
