### ISSUE TITLE
您好，上传文件时回调进不去是否和androidX有关系

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#491]
## Aria版本
 implementation 'com.arialyy.aria:aria-core:3.6.3'

## 什么问题
上传文件时回调进不去

**Comment by AriaLyy** [comment]
用的是哪个版本的gradle，如果是最新版本，建议将gradle降低到gradle 5.4

**Comment by gjk666** [comment]
您好，这是我的/gradle-4.10.1-all.zip  不是最新版本的是不是还有别的原因呢





------------------ 原始邮件 ------------------
发件人: "lyy"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 上午10:05
收件人: "AriaLyy/Aria"<Aria@noreply.github.com>;
抄送: "高江奎"<2426224101@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AriaLyy/Aria] 您好，上传文件时回调进不去是否和androidX有关系 (#491)




用的是哪个版本的gradle，如果是最新版本，建议将gradle降低到gradle 5.4

**Comment by AriaLyy** [comment]
看下这个：https://aria.laoyuyu.me/aria_doc/3.6/other/annotaion_invalid.html

**Comment by gjk666** [comment]
那几个方法都试过啦有这个错误不知道是不是  W/DownloadReceiver: 没有Aria的注解方法
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/com.hdtd.ibuilder/databases/AndroidAria.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
W/art: Attempt to remove non-JNI local reference, dumping thread
 




------------------ 原始邮件 ------------------
发件人: "lyy"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 上午10:12
收件人: "AriaLyy/Aria"<Aria@noreply.github.com>;
抄送: "高江奎"<2426224101@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AriaLyy/Aria] 您好，上传文件时回调进不去是否和androidX有关系 (#491)




看下这个：https://aria.laoyuyu.me/aria_doc/3.6/other/annotaion_invalid.html

**Comment by AriaLyy** [comment]
这应该不影响的，你清空下数据看看

**Comment by gjk666** [comment]
这个不是找不到注解吗？但是就有这一个错，就是进不去回调

**Comment by gjk666** [comment]
方便加一下qq吗2426224101

**Comment by AriaLyy** [comment]
没有注解是编译时构建代理文件的时候失败了，和那个警告没有关系的，估计是gradle的问题。
使用：distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
和：classpath 'com.android.tools.build:gradle:3.4.0'
这两个gradle配置看看

**Comment by gjk666** [comment]
implementation 'com.arialyy.aria:aria-core:3.6.3'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.3'

是不是这个版本的问题啊





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午5:52
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"高江奎"<2426224101@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 您好，上传文件时回调进不去是否和androidX有关系 (#491)




没有注解是编译时构建代理文件的时候失败了，和那个警告没有关系的，估计是gradle的问题。
 使用：distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip
 和：classpath 'com.android.tools.build:gradle:3.4.0'
 这两个gradle配置看看

**Comment by gjk666** [comment]
您好，为什么第一次下载没问题之后下载的话会报错但是数据也确实下载下来啦？E/SQLiteDatabase: Error inserting isGroupChild=true downloadPath=%2Fdata%2Fuser%2F0%2Fcom.example.ariademo%2Ffiles%2Ftest%2F%2F%2Fhome%2Fftpuser%2Fvideopic%2Fhistorymonitor%2Fgroup%2F145%2F%2F%E4%B8%9C%E5%9B%BA%E5%9F%8E%E8%87%B3.jpg url=ftp%3A%2F%2F101.132.33.64%3A21%2F%2Fhome%2Fftpuser%2Fvideopic%2Fhistorymonitor%2Fgroup%2F145%2F%2F%E4%B8%9C%E5%9B%BA%E5%9F%8E%E8%87%B3.jpg state=3 convertFileSize=11.92kb isRedirect=false stopTime=0 fileName=%E4%B8%9C%E5%9B%BA%E5%9F%8E%E8%87%B3.jpg isComplete=false groupHash=ftp%3A%2F%2F101.132.33.64%3A21%2Fhome%2Fftpuser%2Fvideopic%2Fhistorymonitor%2Fgroup%2F145%2F fileSize=12208 percent=0 currentProgress=0 completeTime=0     android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadEntity.downloadPath (code 2067)         at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)         at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)         at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)         at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)         at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)         at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)         at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:136)         at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:182)         at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:293)         at com.arialyy.aria.ftp.FtpDirInfoThread.addEntity(FtpDirInfoThread.java:75)         at com.arialyy.aria.ftp.FtpDirInfoThread.handleFile(FtpDirInfoThread.java:48)         at com.arialyy.aria.ftp.AbsFtpInfoThread.getFileSize(AbsFtpInfoThread.java:372)         at com.arialyy.aria.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:134)         at java.lang.Thread.run(Thread.java:761)

**Comment by AriaLyy** [comment]
3.7.6已经修复了这个问题。并且增加了一个强制上传的api`forceUpload()`

**Comment by gjk666** [comment]
大佬可以啦麻烦您啦，方便加您微信吗给您点个外卖

**Comment by gjk666** [comment]
刚刚看到那个码有一丝尴尬

**Comment by AriaLyy** [comment]
这个不需要哈😄

**Comment by gjk666** [comment]
这有啥的这是我微信gjkkjg666您方便的话可以加一下，麻烦您这么长时间

**Comment by gjk666** [comment]
大佬，现在这个最新版本下载完成不走下载的完成的回调啦，但是走下载中的回调ftp的那个，上传的没问题啦

**Comment by AriaLyy** [comment]
使用`3.7.7`这个版本，3.7重构带来的一个问题

**Comment by gjk666** [comment]
好的

**Comment by gjk666** [comment]
大佬，还是不走这个完成回调ftp文件夹下载这个

**Comment by AriaLyy** [comment]
使用`3.7.8-pre`这个版本

**Comment by gjk666** [comment]
大佬现在是没发布吗依赖不了啊

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/69213783-10a2d080-0ba0-11ea-81af-b7dda0023d04.png)

**Comment by gjk666** [comment]
大佬，您这个ftp上传文件现在不是单文件上传，如果我循环调用上传多个文件的话，现在这个是等到所有文件都上传完成后然后在统一进上传完成的回调，而不是上传完成一个进一次上传完成的回调有什么地方可以修改这个配置吗

**Comment by AriaLyy** [comment]
不是，每个任务回调一次，这个不是组合任务

**Comment by gjk666** [comment]
您的意思是只有一个任务的所有回调走完才会走另外一个，我下午打log的时候发现回调不是这么走的

**Comment by AriaLyy** [comment]
不是，每个任务都会回调所有状态

**Comment by gjk666** [comment]
嗯，这个明白啦，大佬如果用ftp的断点续传您的那个文档里只是简单介绍啦一下需要后台开启什么权限，您方便和我说一下怎么写吗

**Comment by AriaLyy** [comment]
打开append权限

**Comment by gjk666** [comment]
那前端这里呢android端我在您的那个文档里面没有找到这一块的有点尴尬

**Comment by gjk666** [comment]
大佬，现在有一个小问题就是我在A和B页面都用ftp上传功能，我在A页面上传文件然后进入B页面然后再次回到A页面再次使用上传功能就会出现问题W/ResumeThread: 任务已存在
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
&nbsp; &nbsp; &nbsp; &nbsp; at java.util.regex.Matcher.reset(Matcher.java:995)
&nbsp; &nbsp; &nbsp; &nbsp; at java.util.regex.Matcher.<init&gt;(Matcher.java:174)
&nbsp; &nbsp; &nbsp; &nbsp; at java.util.regex.Pattern.matcher(Pattern.java:1006)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:199)
W/System.err:&nbsp; &nbsp; &nbsp;at com.arialyy.aria.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:90)

**Comment by AriaLyy** [comment]
检查下url是否发生改变
有新问题的话，新开一个issues吧，我好处理下

**Comment by gjk666** [comment]
我的上传地址都是一个啊，新的session已经发过去啦
