### ISSUE TITLE
多次下载同名文件。下载一半就显示下载成功

### ISSUE THREAD

**Issue by yaoZhao0323** [AriaLyy/Aria#493]
## Aria版本
3.7.2

## 什么问题
下载成功一遍文件，在手机设置里清空了一遍应用数据。重新下载一遍文件，相同下载地址，相同文件存储地址。有一个线程会直接显示成功。

## 如何复现此问题
下载一个文件，去设置界面，清空应用数据。
long taskId = Aria.download(this)
                        .load(url)     //读取下载地址
                        .setFilePath(file.getPath(),true) //设置文件保存的完整路径
                        .create();   //启动下载
使用这个方法强制下载。
## 控制台日志
![image](https://user-images.githubusercontent.com/20471919/67846005-7240c380-fb3b-11e9-9e76-c47eb1d5e676.png)
![image](https://user-images.githubusercontent.com/20471919/67846042-808edf80-fb3b-11e9-82f3-f7fddc738d14.png)
线程2几十ms就成功，线程0、线程1都是正常的16s成功。

**Comment by AriaLyy** [comment]
检查下下载文件的md5 码是否正确

**Comment by yaoZhao0323** [comment]
测试了一下，服务器那边没有设置md5码。需要设置为随机字符串的MD5码吗？

**Comment by AriaLyy** [comment]
md5是需要你自己验证的

**Comment by yaoZhao0323** [comment]
校验下载文件的MD5值不对，是需要重新执行一遍下载么。

**Comment by AriaLyy** [comment]
是的，文件不对删除任务重新开始

**Comment by yaoZhao0323** [comment]
有别的办法么，下完之后再验证然后回滚，显得有些奇怪。我试过用Aria.download(this).removeAllTask(true)清空下载记录也不行。是什么地方的缓存导致这个问题的么？

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/start/config.html 这个配置

**Comment by yaoZhao0323** [comment]
我没有配置过这些参数，应该走的都是默认值吧

**Comment by AriaLyy** [comment]
我这测试了好几次都正常。。。。

**Comment by yaoZhao0323** [comment]
好啊，我再想想别的办法吧。谢谢。库写的很棒，加油！

**Comment by AriaLyy** [comment]
谢谢 ☺️

**Comment by yaoZhao0323** [comment]
我发现了一点别的情况。我重装App，把目标路径的文件删除也有可能出现这样的问题（有这样的log：HttpFileInfoThread: 长度不一致，任务为新任务。如图）。我换了2个手机都存在这种情况。
![image](https://user-images.githubusercontent.com/20471919/68012960-8bc24680-fcc6-11e9-9cbd-bbcc067c9147.png)

**Comment by AriaLyy** [comment]
这个不影响，只是用来判断是否有同名文件的。

**Comment by yaoZhao0323** [comment]
我改成1个线程了，也是不到50ms就显示成功了。实际文件是0b，但是task返回的长度是正确的

**Comment by AriaLyy** [comment]
步骤是哪些？

**Comment by yaoZhao0323** [comment]
下载成功一遍、删除App、删除本地下载的文件、重新下载一边文件。
Aria.get(this).getDownloadConfig().setThreadNum(1);
我用的是单线程
 long taskId = Aria.download(this)
                        .load(url)     //读取下载地址
                        .setFilePath(file.getPath(),true) //设置文件保存的完整路径
                        .create();   //启动下载
下载还是这种方式。
PS：我试过不删除本地包是没有问题的。
我用华为手机和vivo手机都试过，都会出现。应该跟手机无关

**Comment by AriaLyy** [comment]
删除下载成的包就出问题？还是删除app?

**Comment by yaoZhao0323** [comment]
同时删除下载成功的包和App。然后重新安装App

**Comment by AriaLyy** [comment]
将 useBlock 改为 true看看

**Comment by yaoZhao0323** [comment]
![image](https://user-images.githubusercontent.com/20471919/68016767-34c16f00-fcd0-11e9-896c-7a46fa808b30.png)
还是不行。。。

**Comment by yaoZhao0323** [comment]
试了你的demo，确实不会复现。然后我按照你的demo加了option。
HttpOption option = new HttpOption();
    option.addHeader("1", "@")
        .useServerFileName(true)
        .setFileLenAdapter(new FileLenAdapter());
![image](https://user-images.githubusercontent.com/20471919/68018693-be733b80-fcd4-11e9-8592-ac8d8d14dfab.png)

**Comment by AriaLyy** [comment]
使用`3.7.4`看看
