### ISSUE TITLE
3.7 Androidx

### ISSUE THREAD

**Issue by zjloong** [AriaLyy/Aria#494]
## Aria版本
3.7.2

## 什么问题
根据说明添加了
```java
implementation ('com.arialyy.aria:core:3.7.2'){
        exclude group: 'androidx.appcompat.app'
}
```
还是无法通过编译, 错误提示如下:
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:154:5-1963:19 to override.

3.7只支持 androidx, 不支持 support了吗

**Comment by AriaLyy** [comment]
是的，androidx不兼容support

**Comment by zjloong** [comment]
我用3.6.6的有bug, 现在又不能迁移到androidx , 那这个库就不能用了, 是这个意思吧

**Comment by AriaLyy** [comment]
是的，androidx不兼容support是谷歌决定的，谁也没办法

**Comment by zjloong** [comment]
好的,  明白了

**Comment by OneGreenHand** [comment]
为啥不能搞两个版本，就像别的库，他会弄android x和support两个版本的
我现在没升android x，因为还有很多三方库没适配android x,但是适配了android x也会提供两个版本
虽然这样维护比较麻烦，但是对于那些还是维护老项目的来说比较友好

**Comment by OneGreenHand** [comment]
只是一个建议，虽然这样会增加维护成本，哈哈

**Comment by AriaLyy** [comment]
@OneGreenHand 主要是没这么多精力，互联网人，你懂的😂

**Comment by zjloong** [comment]
我拉了个分支, 自己修复了.  感谢作者的贡献.  这个issue可以关了

**Comment by AriaLyy** [comment]
@zjloong 欢迎贡献代码😂

**Comment by OneGreenHand** [comment]
@zjloong 贡献一波把
