### ISSUE TITLE
只有DownloadTask能获取到下载速度，其他方法都获取不到

### ISSUE THREAD

**Issue by xicong** [AriaLyy/Aria#495]
## Aria版本
3.7.2

## 什么问题
不知道为什么只能在注解的DownloadTask里面的getEntity()能拿到当前下载速度convertSpeed，其他的entity拿到的convertSpeed都是null
![image](https://user-images.githubusercontent.com/11675597/67922017-74129180-fbe4-11e9-9ec8-bb6e1e375782.png)
![image](https://user-images.githubusercontent.com/11675597/67922081-9f957c00-fbe4-11e9-9678-35661edadb46.png)

**Comment by AriaLyy** [comment]
注解里面的速度是实时的，只有运行中的任务才有速度。
而`Aria.download(this).getTaskList()`是从数据库中获取的，而数据库是不保存速度的，因为也没必要，毕竟速度是不断变化的。

**Comment by xicong** [comment]
那么获取实时速度到方法只能通过DownloadTask么，其他地方获取到话都是没保存，获取出来就是null吗

**Comment by AriaLyy** [comment]
是的

**Comment by xicong** [comment]
好的，谢谢，大佬，还有个问题想问问你，就是我用的普通下载的多任务下载，但是在下载第一个之外其他任务的时候，要出现等待中状态好久好久才会下载

**Comment by AriaLyy** [comment]
修改最大任务数配置就可：https://aria.laoyuyu.me/aria_doc/start/config.html

**Comment by xicong** [comment]
改了，但是下载第2，3个任务第时候先是等待中状态出现好久才会开始下载

**Comment by xicong** [comment]
![image](https://user-images.githubusercontent.com/11675597/67923714-a4a8fa00-fbe9-11e9-9385-3072440a6bcd.png)
就像这个，明明设置的是多任务下载，但是第一个都快下载完了，第二个和第三个还出现等待中

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/67925619-d7092600-fbee-11e9-9d14-59f9e20fb799.png)
应该是这个东西导致的，后面改下数值就行了

**Comment by xicong** [comment]
好的，辛苦大佬了

**Comment by AriaLyy** [comment]
使用`3.7.3`

**Comment by xicong** [comment]
![image](https://user-images.githubusercontent.com/11675597/67930710-4dac2080-fbfb-11e9-86c4-3cdf5e320c0e.png)

![image](https://user-images.githubusercontent.com/11675597/67930725-58ff4c00-fbfb-11e9-8518-61c2e4c18ace.png)
大佬，感觉还是不对啊，下载第一个的时候其余的都在等待中，第一个下载完了之后，第二个和第六个才同时开始，

**Comment by xicong** [comment]
又测试了一次，刚开始的时候还是只有第一个在下载，第一个下载完后，执行了一下Aria.download(this).resumeAllTask();  
剩下的其中四个开始同时下载

**Comment by AriaLyy** [comment]
我这测试是正常的呢，😅
![image](https://user-images.githubusercontent.com/10437293/67936761-5145a480-fc07-11e9-96f9-a2b3b0966a5f.png)

**Comment by xicong** [comment]
好，辛苦了，我跟你demo在测试对比一下，看看是不是我代码写的有问题之类的
