### ISSUE TITLE
Aria.download(this).register();闪退

### ISSUE THREAD

**Issue by Roben1016** [AriaLyy/Aria#496]
## Aria版本
3.7.2

## 什么问题
在Fragment中的onCreate方法调用Aria.download(this).register()闪退, 项目是第一次集成Aria下载库,支持androidx, 项目使用组件化的方案, 在共用的lib_base module中添加的aria_core和compiler依赖, 其它module也添加了compiler依赖.

## 控制台日志
{java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.arialyy.aria.core.WidgetLiftManager.handleDialogLift(WidgetLiftManager.java:79)
        at com.arialyy.aria.core.WidgetLiftManager.handleDialogFragmentLift(WidgetLiftManager.java:39)
        at com.arialyy.aria.core.AriaManager.putReceiver(AriaManager.java:317)
        at com.arialyy.aria.core.AriaManager.download(AriaManager.java:269)
        at com.arialyy.aria.core.Aria.download(Aria.java:88)

**Comment by AriaLyy** [comment]
你是在DialogFragment中添加的吗？

**Comment by Roben1016** [comment]
不是的, 只是个普通的Fragment

**Comment by AriaLyy** [comment]
继承的fragment的完整包名能提供下吗？

**Comment by Roben1016** [comment]
我打断点download(this)进去, 看到你有遍历所有的parentFragment, 最后走到的是androidx.fragment.app.Fragment,  而我的这个Fragment最终继承的也是androidx.fragment.app.Fragment

**Comment by AriaLyy** [comment]
找到问题了，使用错了数组

**Comment by Roben1016** [comment]
好的, 什么时候更新个版本呢, 还有就是文档好像是针对以前版本的, 新版本好像有不太一样, 不知道什么时候更新下文档

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/ 这个就是最新文档了，主要是设置参数那块有修改，创建任务和恢复任务有修改https://aria.laoyuyu.me/aria_doc/start/start.html#%E5%88%9B%E5%BB%BA%E4%BB%BB%E5%8A%A1

**Comment by Roben1016** [comment]
以前很多查询任务的, 都是通过url查询, 现在通过url查询出来的好像都是List<DownloadEntity> 查询单个任务只能通过taskId, 顺便问一下, 关于分块下载这里, 是不是只要使用了分块下载, 就会分配三块呢, 还是会根据文件的大小分成不同数量.  如果有交流群的话, 大佬是否可以提供一下, 有个QQ交流群貌似不让加了

**Comment by AriaLyy** [comment]
那个崩溃的问题使用`3.7.3`

**Comment by Roben1016** [comment]
查询到一个的, 好像只有通过taskId才能只返回一个DownloadEntity的, 大佬, 给个交流群, 或者拉下吧201792615

**Comment by AriaLyy** [comment]
524329160，还是这个，前几个月被个祖安人喷了，一怒之下禁止加人

**Comment by Roben1016** [comment]
哈哈,好的
