### ISSUE TITLE
设置M3U8VodOption.merge(true)，会提示源索引文件不存在

### ISSUE THREAD

**Issue by joefei** [AriaLyy/Aria#498]
## Aria版本
3.7.4

## 什么问题
跑m3u8的点播下载demo，
设置M3U8VodOption->merge(true) ；（因为默认不会调用mergeFile这个函数）
报“源索引文件不存在”

## 如何复现此问题
设置M3U8VodOption->merge(true)

## 控制台日志
2019-11-04 12:16:25.236 30483-30589/com.arialyy.simple E/M3U8VodLoader: 源索引文件不存在

**Comment by AriaLyy** [comment]
将`generateIndexFile()`去掉

**Comment by joefei** [comment]
> 将`generateIndexFile()`去掉

好的 ，我试试。

**Comment by joefei** [comment]
可以了，谢谢！！！
