### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by pz-bottle** [AriaLyy/Aria#499]
## Aria版本
直接拷贝demo的版本

## 什么问题
下载速度一直为null，这个entity.getConvertSpeed()的值一直为null

**Comment by AriaLyy** [comment]
需要在配置文件中配置，https://aria.laoyuyu.me/aria_doc/start/config.html

**Comment by pz-bottle** [comment]
> 需要在配置文件中配置，https://aria.laoyuyu.me/aria_doc/start/config.html

嗯嗯，我先试试，谢谢

**Comment by pz-bottle** [comment]
> 需要在配置文件中配置，https://aria.laoyuyu.me/aria_doc/start/config.html

ok，可以了，谢谢大佬
