### ISSUE TITLE
请问该框架支持多个m3u8文件同时下载吗？

### ISSUE THREAD

**Issue by joefei** [AriaLyy/Aria#501]
## Aria版本
3.7.4

## 什么问题
请问该框架支持多个m3u8文件同时下载吗？

## 如何复现此问题
我尝试通过下面这种方式同时下载多个m3u8文件，不过失败了（第一个文件正常，第二个则无法播放）。所以想问下是否支持。
``
void downloadMutilM3u8(){
Aria.download(M3U8VodDLoadActivity.this)
                .load(第一个URL)
                .setFilePath(第一个地址, true)
                .m3u8VodOption(getM3U8Option())
                .create();

Aria.download(M3U8VodDLoadActivity.this)
                .load(第二个URL)
                .setFilePath(第二个地址, true)
                .m3u8VodOption(getM3U8Option())
                .create();
}
``

**Comment by AriaLyy** [comment]
错误日志是什么？

**Comment by joefei** [comment]
> 错误日志是什么？

同时下载的话，第二个m3u8文件（ts文件）无法播放，只有几K。

**Comment by AriaLyy** [comment]
能否提供下m3u8地址？

**Comment by joefei** [comment]
> 能否提供下m3u8地址？

m3u8地址：
http://qn.shytong.cn/b83137769ff6b555/11b0c9970f9a3fa0.mp4.m3u8

写法如下：
    private void startD() {
        mTaskId = Aria.download(M3U8VodDLoadActivity.this)
                .load(mUrl)
                .setFilePath(mFilePath, true)
                .m3u8VodOption(getM3U8Option())
                .create();

        Aria.download(M3U8VodDLoadActivity.this)
                .load("http://qn.shytong.cn/b83137769ff6b555/11b0c9970f9a3fa0.mp4.m3u8")
                .setFilePath(filePath2, true)
                .m3u8VodOption(getM3U8Option())
                .create();
    }

**Comment by AriaLyy** [comment]
单独下载这个url也有问题吗？

**Comment by AriaLyy** [comment]
getM3U8Option() 是如何设置的？

**Comment by joefei** [comment]
> 单独下载这个url也有问题吗？

单独下是没问题的。我测试过了。

**Comment by joefei** [comment]
> getM3U8Option() 是如何设置的？

    private M3U8VodOption getM3U8Option() {
        M3U8VodOption option = new M3U8VodOption();
        option
                .merge(true)
                .setVodTsUrlConvert(new VodTsUrlConverter());
//                .setMergeHandler(new TsMergeHandler());
        //.setBandWidthUrlConverter(new BandWidthUrlConverter(mUrl));
        return option;
    }

**Comment by AriaLyy** [comment]
能否多提供几个url地址，我这的url对应的文件都很大😂

**Comment by joefei** [comment]
> 能否多提供几个url地址，我这的url对应的文件都很大😂

http://qn.shytong.cn/8f4011f2a31bd347da42b54fe37a7ba8-transcode.m3u8

**Comment by AriaLyy** [comment]
日志中有没有这个：`操作太频繁了，缓一下吧～`？
不要使用下面这个种方法，我做了多次点击处理。两个任务之间的间隔至少需要500ms

```
void downloadMutilM3u8(){
Aria.download(M3U8VodDLoadActivity.this)
.load(第一个URL)
.setFilePath(第一个地址, true)
.m3u8VodOption(getM3U8Option())
.create();

// 在这做一个1s的延时
Aria.download(M3U8VodDLoadActivity.this)
.load(第二个URL)
.setFilePath(第二个地址, true)
.m3u8VodOption(getM3U8Option())
.create();
}
```

**Comment by joefei** [comment]
> 日志中有没有这个：`操作太频繁了，缓一下吧～`？
> 不要使用下面这个种方法，我做了多次点击处理。两个任务之间的间隔至少需要500ms
> 
> ```
> void downloadMutilM3u8(){
> Aria.download(M3U8VodDLoadActivity.this)
> .load(第一个URL)
> .setFilePath(第一个地址, true)
> .m3u8VodOption(getM3U8Option())
> .create();
> 
> // 在这做一个1s的延时
> Aria.download(M3U8VodDLoadActivity.this)
> .load(第二个URL)
> .setFilePath(第二个地址, true)
> .m3u8VodOption(getM3U8Option())
> .create();
> }
> ```

是的，有提示这个。
确实加了延迟就可以了，感谢作者大大！！！

**Comment by cblsyp** [comment]
除了这种方式 还有其他的类似http组合任务的方式   吗？

**Comment by AriaLyy** [comment]
没有
