### ISSUE TITLE
下载下载文件夹回调问题

### ISSUE THREAD

**Issue by FanBaobao132** [AriaLyy/Aria#502]
## Aria版本：com.arialyy.aria:aria-compiler:3.6.6

##ftp下载文件夹时：group task pre group task start，然后就没有了
实际是下载成功了，我是在oncreate中注册的 Aria.download(this).register();

  Aria.download(this)
                    .loadFtpDir(“ftp”地址)
                    .setDirPath(
                            保存文件路径)
                    .setGroupAlias("ftp文件夹下载")
                    //.setSubTaskFileName(getModule(GroupModule.class).getSubName())
                    .login("用户名", "密码")
                    .start();
//以下是回调
’
 /***
     * 文件夹下载
     * @param task
     */
    @DownloadGroup.onPre()
    protected void onPre(DownloadGroupTask task) {
        showProgressDialog("开始下载");
        Log.d(TAG, "group pre");
    }

    @DownloadGroup.onTaskPre()
    protected void onTaskPre(DownloadGroupTask task) {
        Log.d(TAG, "group task pre");
    }

    @DownloadGroup.onTaskStart()
    void taskStart(DownloadGroupTask task) {
        Log.d(TAG, "group task start");
    }

    @DownloadGroup.onTaskRunning()
    protected void running(DownloadGroupTask task) {
    }

    @DownloadGroup.onTaskResume()
    void taskResume(DownloadGroupTask task) {
        Log.d(TAG, "group task resume");
    }

    @DownloadGroup.onTaskStop()
    void taskStop(DownloadGroupTask task) {
        Log.d(TAG, "group task stop");
    }

    @DownloadGroup.onTaskCancel()
    void taskCancel(DownloadGroupTask task) {
    }

    @DownloadGroup.onTaskFail()
    void taskFail(DownloadGroupTask task) {
        Log.d(TAG, "group task fail");
    }

    @DownloadGroup.onTaskComplete()
    void taskComplete(DownloadGroupTask task) {
        Log.d(TAG, "任务组下载完成");
    }

**Comment by AriaLyy** [comment]
升级到`3.7.5`，我这测试是正常的
![image](https://user-images.githubusercontent.com/10437293/68539413-569caf00-03be-11ea-9711-45c474c09119.png)
![image](https://user-images.githubusercontent.com/10437293/68539414-57354580-03be-11ea-9f2c-af6c89095219.png)
![image](https://user-images.githubusercontent.com/10437293/68539416-5a303600-03be-11ea-8679-bb5d34bb96f5.png)
