### ISSUE TITLE
文件下载是报错.SQLiteConstraintException:但是可以下载成功，文件上传是也是这个但是上传失败 

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#505]
## Aria版本

  implementation 'com.arialyy.aria:core:3.7.4'
    annotationProcessor 'com.arialyy.aria:compiler:3.7.4'
    implementation 'com.arialyy.aria:ftpComponent:3.7.4'
## 什么问题

 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadEntity.downloadPath (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/491#issuecomment-550126141 这个？？

**Comment by gjk666** [comment]
？？什么意思没明白就是每次都会报这个错
但是不影响上传和下载

**Comment by gjk666** [comment]
大佬，使用ftp上传是不是只能单个文件上传 啊


发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午4:02
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"高江奎"<2426224101@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 文件下载是报错.SQLiteConstraintException:但是可以下载成功，文件上传是也是这个但是上传失败  (#505)




#491 (comment) 这个？？

**Comment by AriaLyy** [comment]
是的，后面再增加文件夹上传的功能

**Comment by gjk666** [comment]
你好。这个ftp上传的话我循环上传老是报一个错误，不循环就没有问题但是我的这个有好多个只能文件上传我把错误给您贴一下


/System.err: java.lang.ClassCastException: com.arialyy.aria.core.upload.UTaskWrapper cannot be cast to com.arialyy.aria.core.download.DTaskWrapper
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.http.download.HttpDLoaderUtil.createInfoThread(HttpDLoaderUtil.java:49)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.core.loader.AbsNormalLoaderUtil.start(AbsNormalLoaderUtil.java:108)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:211)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:193)

**Comment by AriaLyy** [comment]
上传的代码麻烦贴一下

**Comment by gjk666** [comment]
Aria.upload(this).register();
//上传资源
if (fruitList.size() &gt; 0) {
    for (int i = 0; i < fruitList.size(); i++) {
        taskId = AriaUtils.ariaUploadFile(context, fruitList.get(i).getName(), AriaApi.getAriaUploadUrl());
        fruitList.get(i).setFlag(false);
    }
}
/**
 * 上传文件(ftp上传)
 *
 * @param context
 * @param localUrl  本地待上传文件路径
 * @param uploadUrl 云端接收路径
 */
public static long ariaUploadFile(Context context, String localUrl, String uploadUrl) {
    FtpOption option = new FtpOption();
    option.login("ftpuser", "ftpuser2019");
    long taskId = Aria.upload(context)
            .loadFtp(localUrl)//上传文件本地地址
            .setUploadUrl(uploadUrl)//云端接收地址
            .option(option)
            .create();
    return taskId;
}
//任务执行中(上传)
@Upload.onTaskRunning
protected void toUplaodRunning(UploadTask task) {
    Log.e("===上传百分比进度===", "=======" + task.getPercent());
    Log.e("===上传速度===", "=======" + task.getConvertSpeed());
}

//任务完成(上传)
@Upload.onTaskComplete()
protected void toUplaodComplete(UploadTask task) {
    Aria.upload(this).loadFtp(taskId).cancel();
    Log.e("===上传完成===", "=======");
}

**Comment by AriaLyy** [comment]
循环间增加一个500ms的间隔看看

**Comment by gjk666** [comment]
我们之前用的一个:3.6.3这个版本是没问题的啊，现在换成:3.7.4'这个就有问题啦，睡一会网不好啦是不是就没用啦

**Comment by gjk666** [comment]
大佬，还是一样的问题

**Comment by AriaLyy** [comment]
3.7.6已经修复了这个问题。并且增加了一个强制上传的api`forceUpload()`
