### ISSUE TITLE
支持ftp多文件上传吗

### ISSUE THREAD

**Issue by FanBaobao132** [AriaLyy/Aria#511]
## 重现步骤

1.
2.
3.
4.

## 版本
* 框架版本

* 系统版本

**Comment by AriaLyy** [comment]
支持，但不支持类似组合任务但上传

**Comment by FanBaobao132** [comment]
那请问一次上传多个文件应该调用的是哪一个方法？谢谢百忙之中回复

**Comment by yanbin92** [comment]
private void upload() {
    List<String> paths = new ArrayList<>();
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/1.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/2.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/3.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/4.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/5.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/6.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/7.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/8.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/9.jpg");
    paths.add(Environment.getExternalStorageDirectory().getPath() + "/Download/img/img/10.jpg");
    for (String path : paths) {
      Aria.upload(this)
          .loadFtp(path)
          .setUploadUrl(mUrl)
          .option(getOption())
          .forceUpload()
          .create();
    }
  }
