### ISSUE TITLE
Hi，如果只需要核心的http下载组件，请问该如何裁剪库？

### ISSUE THREAD

**Issue by conan5** [AriaLyy/Aria#512]
麻烦请问一下，项目中只需要用到核心的http下载组件，应该如何正确裁剪，
看当前的代码结构是以module的形式来的，是否可以直接去除其余Module的依赖，
AppFrame可以移除吗

谢谢了！

**Comment by conan5** [comment]
尝试移除了一些依赖项，当前只保留了Aria, AriaAnnotations, AriaComplier, HttpComponent, PublicComponent几个Module，请问这样是否可以，还能继续精简嘛

**Comment by AriaLyy** [comment]
是的，这几个是基本的

**Comment by qinyang1018** [comment]
@conan5   可以正常用吗？ 我也想要个精简版

**Comment by conan5** [comment]
@qinyang1018 还没有用，昨天试了一下，可以把上面列出的不需要的module移除，同时，Aria, AriaAnnotations, AriaComplier, HttpComponent, PublicComponent几个Module中也有一些不需要的类，将那些删除后，应该是可以直接使用的，你可以试一下

**Comment by AriaLyy** [comment]
其实不用精简，打包时使用代码混淆，代码混淆时会移除所有没有使用的方法和类的

**Comment by conan5** [comment]
哦哦学习了，感谢！
