### ISSUE TITLE
3.7.5 下载小文件时 实际下载的文件大小会变成双倍

### ISSUE THREAD

**Issue by Pancts** [AriaLyy/Aria#516]
## 预期行为
使用http下载小文件时, 日志正常, 但是实际下载到的文件大小会变成双倍, 二进制查看前半部分是空的, 后半部分是正常的文件, 具体多大没测, 但是 300kb以下的文件都有这个问题,
还有组合任务不管文件大小下载到的文件也都是双倍大小和上面的情况一样

测试链接 https://i0.hdslb.com/bfs/sycp/creative_img/201911/849df85c8e0e9fe13ad7ed44b7b5dffa.jpg

另外
[#L173](https://github.com/AriaLyy/Aria/blob/master/Aria/src/main/java/com/arialyy/aria/core/download/CheckDGEntityUtil.java#L173)
这个位置的or条件会导致任务列表有其他完成任务时组合任务无法重命名

还有
[#L88](https://github.com/AriaLyy/Aria/blob/master/PublicComponent/src/main/java/com/arialyy/aria/util/DbDataHelper.java#L88)
这里如果下载地址后面包含"?"的情况会把文件名设置的非常长导致下载失败

## 版本
* 框架版本
3.7.5

* 系统版本
雷电模拟器 3.7.2
miui11 android10

**Comment by AriaLyy** [comment]
感谢反馈，我会尽快处理这个问题

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/69112606-99940c00-0abb-11ea-855b-ce5786c257a9.png)
文件名那个我这测试是正常的，如果你那边有问题，可以使用`setSubFileName`这个api给每一个url设置文件名

**Comment by Pancts** [comment]
ok 感谢大大
文件名特别长的时候会建立文件失败, 用setSubFileName就可以解决了

**Comment by AriaLyy** [comment]
3.7.6修复了这个双倍文件的问题
