### ISSUE TITLE
3.6.5依赖方式

### ISSUE THREAD

**Issue by luodongsheng258** [AriaLyy/Aria#517]
大神 我看文档里面依赖3.6.5的方式是这样的
compile 'com.arialyy.aria:aria-core:3.6.5'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.5'
但是依赖一直不成功 3.7.5的就可以 。那是不是3.6.5已经下线了？目前项目大不好切换AndroidX...

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/tree/v3.6.6
