### ISSUE TITLE
多种任务下载 MP4和m3u8的问题

### ISSUE THREAD

**Issue by MyAcooL** [AriaLyy/Aria#523]
列表里面有mp4和m3u8的地址 通过type判断采用哪种方式下载 m3u8能正常下载 点击下载mp4的时候或是一开始就先点击下载mp4 mp4的任务会一直显示等待中。无法下载 m3u8的下载完了 ，Mp4的任务也不会开始。

注： 一开始我用普通代码写，mp4和m3u8都能下载 只是进度条不能实时更新，后来我把下载界面的代码改为用databinding来写 进度条可以更新了 但是mp4的任务一直是等待中

后来添加的代码：
![image](https://user-images.githubusercontent.com/21095161/69212464-5a89b780-0b9c-11ea-9c07-43984e326cc9.png)

全部代码：
1：列表界面
public class DownLoadListActivity extends AppCompatActivity implements View.OnClickListener {

    private RecyclerView recyclerView;
    private List<FileListEntity> list=new ArrayList<>();
    private DownLoadListAdapter adapter;
    private static FileInputStream fis;
    private String  path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getPath()+"/video/";
    private String TAG="wangwu";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_down_load_list);
        Aria.init(this);
        Aria.download(this).register();
        initView();
        initData();
    }

    private void initData() {

        list.add(new FileListEntity("https://cn2.zuidadianying.com/ppvod/58736EE9F321629B82F7B6E2CABE458B.m3u8",
                "惊奇队长m3u8","100","1","https://cn2.zuidadianying.com",path+"/"+"惊奇队长m3u8.ts"));
        list.add(new FileListEntity("http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4",
                "111mp4","100","0","",""));
        list.add(new FileListEntity("http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4",
                "222mp4","100","0","",""));
        list.add(new FileListEntity("https://hong.tianzhen-zuida.com/20191118/14050_34b72ce4/1000k/hls/index.m3u8",
                "我还小第二集m3u8","100","1","https://hong.tianzhen-zuida.com/20191118/14050_34b72ce4/1000k/hls/",path+"/"+"我还小第二集m3u8.ts"));
        list.add(new FileListEntity("https://hong.tianzhen-zuida.com/20191118/14051_f3068514/1000k/hls/index.m3u8",
                "我还小第一集m3u8","100","1","https://hong.tianzhen-zuida.com/20191118/14051_f3068514/1000k/hls/",path+"/"+"我还小第一集m3u8.ts"));

        adapter.notifyDataSetChanged();

    }

    private void initView() {
        Objects.requireNonNull(getSupportActionBar()).hide();
        findViewById(R.id.stop).setOnClickListener(this);
        findViewById(R.id.downlist).setOnClickListener(this);
        findViewById(R.id.downNum).setOnClickListener(this);

        recyclerView = (RecyclerView) findViewById(R.id.recyclerView);
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(linearLayoutManager);
        recyclerView.addItemDecoration(new RecyclerView.ItemDecoration() {
            @Override
            public void getItemOffsets(@NonNull Rect outRect, @NonNull View view, @NonNull RecyclerView parent, @NonNull RecyclerView.State state) {
                super.getItemOffsets(outRect, view, parent, state);
                outRect.bottom=20;
            }
        });
        adapter=new DownLoadListAdapter(R.layout.download_list_item,list);
        recyclerView.setAdapter(adapter);
        adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                String fileType = list.get(position).getFileType();
                if (fileType.equals("1")){
                    // M3U8 下载
                    Aria.download(DownLoadListActivity.this)
                            .load(list.get(position).getFileUrl())
                            .setFilePath(path +"/"+list.get(position).getFileName()+".ts", true)
                            .m3u8VodOption(getM3U8Option(list.get(position).getFileBaseUrl(),list.get(position).getFileSavePath()))
                            .create();
                    Toast.makeText(DownLoadListActivity.this, "添加成功", Toast.LENGTH_SHORT).show();
                }else if (fileType.equals("0")){
                    // MP4 下载
                    Aria.download(DownLoadListActivity.this)
                            .load(list.get(position).getFileUrl())
                            .setFilePath(path +"/"+list.get(position).getFileName()+".mp4")
                            .create();
                    Toast.makeText(DownLoadListActivity.this, "添加成功", Toast.LENGTH_SHORT).show();
                }
            }
        });

    }
    private M3U8VodOption getM3U8Option(String baseUrl,String savePath) {
        M3U8VodOption option = new M3U8VodOption();
          option.setVodTsUrlConvert(new VodTsUrlConverter(baseUrl))
                  .setFileSize(100)
//                .setBandWidthUrlConverter(new BandWidthUrlConverter(baseUrl))
                .setMergeHandler(new TsMergeHandler(savePath));
        return option;
    }
    static class TsMergeHandler implements ITsMergeHandler {
        private String savePath;
        public TsMergeHandler(String savePath) {
            this.savePath=savePath;
        }
        public boolean merge(@Nullable M3U8Entity m3U8Entity, List<String> tsPath) {
            composeFile(savePath,tsPath);
            return true;
        }
    }

    static class VodTsUrlConverter implements IVodTsUrlConverter {
        private String baseUrl;
        public VodTsUrlConverter(String baseUrl) {
            this.baseUrl=baseUrl;
        }
        @Override public List<String> convert(String m3u8Url, List<String> tsUrls) {
            String parentUrl = baseUrl;
            List<String> newUrls = new ArrayList<>();
            for (String url : tsUrls) {
                newUrls.add(parentUrl + url);
            }
            return newUrls;
        }
    }

    static class BandWidthUrlConverter implements IBandWidthUrlConverter {
        String url;
        BandWidthUrlConverter(String url) {
            this.url = url;
        }

        @Override public String convert(String bandWidthUrl) {
            String parentUrl = url;
            return parentUrl + bandWidthUrl;
        }
    }
    @Override
    public void onClick(View v) {

        switch (v.getId()){
            // 停止
            case R.id.stop:
                Aria.download(this).stopAllTask();
                break;
                // 下载列表
            case R.id.downlist:
                startActivity(new Intent(this, MultiDownloadActivity.class));
                break;
                // 下载数设置
            case R.id.downNum:
                Toast.makeText(this, "点击了下载设置！", Toast.LENGTH_SHORT).show();
                break;
        }
    }
    @Download.onWait void taskWait(DownloadTask task) {
        Log.d(TAG, "wait ==> " + task.getDownloadEntity().getFileName());
    }
    @Download.onTaskStart void taskStart(DownloadTask task) {
        adapter.updateBtState(task.getKey(), false);
    }

    @Download.onTaskResume void taskResume(DownloadTask task) {
        adapter.updateBtState(task.getKey(), false);
    }

    @Download.onTaskStop void taskStop(DownloadTask task) {
        adapter.updateBtState(task.getKey(), true);
    }

    @Download.onTaskCancel void taskCancel(DownloadTask task) {
        adapter.updateBtState(task.getKey(), true);
    }

    @Download.onTaskFail void taskFail(DownloadTask task) {
        if (task == null || task.getEntity() == null){
            return;
        }
        adapter.updateBtState(task.getKey(), true);
    }

    @Download.onTaskComplete void taskComplete(DownloadTask task) {
//        Log.d(TAG, FileUtil.getFileMD5(new File(task.getFilePath())));
    }

    //      视频片段合成
    static void composeFile(String fileOutPath, List<String> tsPath) {
        Date date = new Date();
        String strDateFormat = "yyyy-MM-dd HH:mm:ss";
        SimpleDateFormat sdf = new SimpleDateFormat(strDateFormat);
//    System.out.println(sdf.format(date));
        Log.d("wangwu", "合并开始: "+sdf.format(date));
        FileOutputStream fileOutputStream=null;
        try {
            fileOutputStream= new FileOutputStream(new File(fileOutPath));
            byte[] bytes = new byte[1024];
            int length = 0;
            for (int i = 0; i < tsPath.size(); i++) {
                Log.d("wangwu", "当前合并项：：：: "+i);
                String nodePath = tsPath.get(i);
                File file = new File(nodePath);
                if (!file.exists())
                    continue;
                fis = new FileInputStream(file);
                while ((length = fis.read(bytes)) != -1) {
                    fileOutputStream.write(bytes, 0, length);
                }
                fis.close();
            }
            fileOutputStream.close();
        } catch (Exception e) {
            try {
                fis.close();
                fileOutputStream.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            Log.d("wangwu", "e失败原因：：: "+e.getMessage());
        }finally {
            try {
                fis.close();
                fileOutputStream.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        Date date1 = new Date();
        String strDateFormat1 = "yyyy-MM-dd HH:mm:ss";
        SimpleDateFormat sdf1 = new SimpleDateFormat(strDateFormat1);
        Log.d("wangwu", "合并结束: "+sdf1.format(date1));
    }

    //############################### 任务组 ##############################
    @DownloadGroup.onTaskComplete void groupTaskComplete(DownloadGroupTask task) {
        adapter.updateBtState(task.getKey(), true);
    }

    @DownloadGroup.onTaskStart void groupTaskStart(DownloadGroupTask task) {
        adapter.updateBtState(task.getKey(), false);
    }

    @DownloadGroup.onTaskResume void groupTaskResume(DownloadGroupTask task) {
        adapter.updateBtState(task.getKey(), false);
    }

    @DownloadGroup.onWait void groupTaskWait(DownloadGroupTask task) {
        ALog.d(TAG, String.format("group【%s】wait---", task.getTaskName()));
        adapter.updateBtState(task.getKey(), true);
    }

    @DownloadGroup.onTaskStop void groupTaskStop(DownloadGroupTask task) {
        adapter.updateBtState(task.getKey(), true);
        Log.d(TAG, String.format("group【%s】stop", task.getTaskName()));
    }

    @DownloadGroup.onTaskCancel void groupTaskCancel(DownloadGroupTask task) {
        adapter.updateBtState(task.getKey(), true);
    }

    @DownloadGroup.onTaskFail void groupTaskFail(DownloadGroupTask task) {
        if (task == null) {
            return;
        }
        adapter.updateBtState(task.getKey(), true);
        Log.d(TAG, String.format("group【%s】fail", task.getTaskName()));
    }

    @DownloadGroup.onTaskComplete void taskComplete(DownloadGroupTask task) {
        adapter.updateBtState(task.getKey(), true);
    }

}

2：下载界面:
public class MultiDownloadActivity extends BaseActivity<ActivityMultiDownloadBinding> {

    RecyclerView mList;
    private DownloadAdapter mAdapter;
    private List<AbsEntity> mData = new ArrayList<>();
    @Override
    protected int setLayoutId() {
        return R.layout.activity_multi_download;
    }
    @Override protected void init(Bundle savedInstanceState) {
        super.init(savedInstanceState);
        Aria.download(this).register();
//        setTitle("下载列表");
        List<AbsEntity> temps = Aria.download(this).getTotalTaskList();
        if (temps != null && !temps.isEmpty()) {

            for (AbsEntity temp : temps) {
                Log.d("wangwu", "state = " + temp.getState());
            }
            mData.addAll(temps);
        }
        mAdapter = new DownloadAdapter(this, mData);
        mList = getBinding().list;
        mList.setLayoutManager(new LinearLayoutManager(this));
        mList.setAdapter(mAdapter);
    }

    @Download.onPre void onPre(DownloadTask task) {
        mAdapter.updateState(task.getEntity());
        Log.d(TAG, task.getTaskName() + ", " + task.getState());
    }

    @Download.onWait void onWait(DownloadTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskStart void taskStart(DownloadTask task) {
        Log.d(TAG, task.getTaskName() + ", " + task.getState());
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskResume void taskResume(DownloadTask task) {
        Log.d(TAG, task.getTaskName() + ", " + task.getState());
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskStop void taskStop(DownloadTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskCancel void taskCancel(DownloadTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskFail void taskFail(DownloadTask task) {
        if (task == null || task.getEntity() == null){
            return;
        }
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskComplete void taskComplete(DownloadTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @Download.onTaskRunning void taskRunning(DownloadTask task) {
        mAdapter.setProgress(task.getEntity());
    }
    //////////////////////////////////// 下面为任务组的处理 /////////////////////////////////////////

    @DownloadGroup.onPre void onGroupPre(DownloadGroupTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onTaskStart void groupTaskStart(DownloadGroupTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onWait void groupTaskWait(DownloadGroupTask task) {
        Log.d(TAG, String.format("group【%s】wait---", task.getTaskName()));
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onTaskResume void groupTaskResume(DownloadGroupTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onTaskStop void groupTaskStop(DownloadGroupTask task) {
        Log.d(TAG, String.format("group【%s】stop", task.getTaskName()));
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onTaskCancel void groupTaskCancel(DownloadGroupTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onTaskFail void groupTaskFail(DownloadGroupTask task) {
        if (task != null) {
            Log.d(TAG, String.format("group【%s】fail", task.getTaskName()));
            mAdapter.updateState(task.getEntity());
        }
    }

    @DownloadGroup.onTaskComplete void groupTaskComplete(DownloadGroupTask task) {
        mAdapter.updateState(task.getEntity());
    }

    @DownloadGroup.onTaskRunning() void groupTaskRunning(DownloadGroupTask task) {
        Log.d(TAG, "groupTaskRunning: "+String.format("group【%s】running", task.getTaskName()));
        mAdapter.setProgress(task.getEntity());
    }

    @Override protected void onDestroy() {
        super.onDestroy();
        //Aria.download(this).unRegister();
    }
}

3：下载界面adapter:
public class DownloadAdapter extends AbsRVAdapter<AbsEntity, DownloadAdapter.SimpleHolder> {
    private static final String TAG = "DownloadAdapter";
    private Map<String, Integer> mPositions = new ConcurrentHashMap<>();

    public DownloadAdapter(Context context, List<AbsEntity> data) {
        super(context, data);
        int i = 0;
        for (AbsEntity entity : data) {
            mPositions.put(getKey(entity), i);
            i++;
        }
    }

    private String getKey(AbsEntity entity) {
        if (entity instanceof DownloadEntity) {
            return ((DownloadEntity) entity).getUrl();
        } else if (entity instanceof DownloadGroupEntity) {
            return ((DownloadGroupEntity) entity).getGroupHash();
        }
        return "";
    }

    @Override protected SimpleHolder getViewHolder(View convertView, int viewType) {
        if (viewType == 1) return new SimpleHolder(convertView);
        if (viewType == 2) return new GroupHolder(convertView);
        return null;
    }

    public void addDownloadEntity(DownloadEntity entity) {
        mData.add(entity);
        mPositions.put(entity.getUrl(), mPositions.size());
    }

    public int getItemViewType(int position) {
        AbsEntity entity = mData.get(position);
        if (entity instanceof DownloadEntity) return 1;
        if (entity instanceof DownloadGroupEntity) return 2;
        return -1;
    }

    @Override protected int setLayoutId(int type) {
        if (type == 1) {
            return R.layout.item_simple_download;
        } else if (type == 2) {
            return R.layout.item_group_download;
        }
        return R.layout.download_list_item_layout;
    }

    public synchronized void updateState(AbsEntity entity) {
        if (entity.getState() == IEntity.STATE_CANCEL) {
            mData.remove(entity);
            mPositions.clear();
            int i = 0;
            for (AbsEntity entity_1 : mData) {
                mPositions.put(getKey(entity_1), i);
                i++;
            }
            notifyDataSetChanged();
        } else {
            int position = indexItem(getKey(entity));
            if (position == -1 || position >= mData.size()) {
                return;
            }
            mData.set(position, entity);
            notifyItemChanged(position);
        }
    }

    /**
     * 更新进度
     */
    public synchronized void setProgress(AbsEntity entity) {
        String url = entity.getKey();
        int position = indexItem(url);
        if (position == -1 || position >= mData.size()) {
            return;
        }

        mData.set(position, entity);
        notifyItemChanged(position, entity);
    }

    private synchronized int indexItem(String url) {
        Set<String> keys = mPositions.keySet();
        for (String key : keys) {
            if (key.equals(url)) {
                return mPositions.get(key);
            }
        }
        return -1;
    }

    @Override protected void bindData(SimpleHolder holder, int position, final AbsEntity item) {
        handleProgress(holder, item);
    }

    @Override protected void bindData(SimpleHolder holder, int position, AbsEntity item,
                                      List<Object> payloads) {
        AbsEntity entity = (AbsEntity) payloads.get(0);
        updateSpeed(holder, entity);
    }

    /**
     * 只更新速度
     */
    private void updateSpeed(SimpleHolder holder, final AbsEntity entity) {

        holder.speed.setText(entity.getConvertSpeed());
        if (entity.getTaskType() == ITaskWrapper.M3U8_VOD
                || entity.getTaskType() == ITaskWrapper.M3U8_LIVE) {
            holder.progress.setProgress(entity.getPercent());
            holder.fileSize.setVisibility(View.GONE);
        } else {
            long size = entity.getFileSize();
            long progress = entity.getCurrentProgress();
            int current = size == 0 ? 0 : (int) (progress * 100 / size);
            holder.fileSize.setText(covertCurrentSize(progress) + "/" + CommonUtil.formatFileSize(size));
            holder.progress.setProgress(current);
        }
        //if (holder instanceof GroupHolder){
        //  handleSubChild((GroupHolder) holder, entity);
        //}
    }

    @SuppressLint("SetTextI18n")
    private void handleProgress(SimpleHolder holder, final AbsEntity entity) {
        String str = "";
        int color = android.R.color.holo_green_light;
        switch (entity.getState()) {
            case IEntity.STATE_WAIT:
                str = "等待中";
                break;
            case IEntity.STATE_OTHER:
            case IEntity.STATE_FAIL:
                str = "开始";
                break;
            case IEntity.STATE_STOP:
                str = "恢复";
                color = android.R.color.holo_blue_light;
                break;
            case IEntity.STATE_PRE:
            case IEntity.STATE_POST_PRE:
            case IEntity.STATE_RUNNING:
                str = "暂停";
                color = android.R.color.holo_red_light;
                break;
            case IEntity.STATE_COMPLETE:
                str = "完成";
                holder.progress.setProgress(100);
                break;
        }
        long size = entity.getFileSize();
        long progress = entity.getCurrentProgress();
        int current = size == 0 ? 0 : (int) (progress * 100 / size);
        holder.bt.setText(str);
        holder.bt.setTextColor(getColor(color));
        holder.progress.setProgress(current);

        BtClickListener listener = new BtClickListener(entity);
        holder.bt.setOnClickListener(listener);
        String name = (isSimpleDownload(entity) ? ((DownloadEntity) entity).getFileName()
                : ((DownloadGroupEntity) entity).getAlias());
        holder.name.setText("文件名：" + name);
        holder.speed.setText(entity.getConvertSpeed());
        holder.fileSize.setText(covertCurrentSize(progress) + "/" + CommonUtil.formatFileSize(size));
        //删除按钮事件
        holder.cancel.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                mData.remove(entity);
                notifyDataSetChanged();
                cancel(entity);
                //stop(entity);
            }
        });
        //if (holder instanceof GroupHolder){
        //  handleSubChild((GroupHolder) holder, entity);
        //}
    }

//    private void handleSubChild(GroupHolder holder, final AbsEntity entity) {
//        if (holder.childList.getSubData().size() > 0) {
//            holder.childList.updateChildProgress(((DownloadGroupEntity) entity).getSubEntities());
//        } else {
//            holder.childList.addData(((DownloadGroupEntity) entity).getSubEntities());
//        }
//    }

    private boolean isSimpleDownload(AbsEntity entity) {
        return entity instanceof DownloadEntity;
    }

    private String covertCurrentSize(long currentSize) {
        if (currentSize < 0) return "0";
        return CommonUtil.formatFileSize(currentSize);
    }

    private int getColor(int color) {
        return Resources.getSystem().getColor(color);
    }

    /**
     * 按钮事件
     */
    private class BtClickListener implements View.OnClickListener {
        private AbsEntity entity;

        BtClickListener(AbsEntity entity) {
            this.entity = entity;
        }
        @Override public void onClick(View v) {
            switch (entity.getState()) {
                case IEntity.STATE_WAIT:
                case IEntity.STATE_OTHER:
                case IEntity.STATE_FAIL:
                case IEntity.STATE_STOP:
                case IEntity.STATE_PRE:
                case IEntity.STATE_POST_PRE:
                    if (entity.getId() < 0) {
                        start(entity);
                    } else {
                        resume(entity);
                    }
                    start(entity);
                    break;
                case IEntity.STATE_RUNNING:
                    stop(entity);
                    break;
                case IEntity.STATE_COMPLETE:
                    Log.d(TAG, "任务已完成");
                    break;
            }
        }
    }

    private void cancel(AbsEntity entity) {
        if (!AppUtil.chekEntityValid(entity)) {
            return;
        }
        switch (entity.getTaskType()) {
            case ITaskWrapper.D_FTP:
                Aria.download(getContext())
                        .loadFtp(entity.getId())
                        //.login("lao", "123456")
                        .cancel(true);
                break;
            case ITaskWrapper.D_FTP_DIR:
                break;
            case ITaskWrapper.D_HTTP:
            case ITaskWrapper.M3U8_VOD:
                Aria.download(getContext()).load(entity.getId()).cancel(true);
                break;
            case ITaskWrapper.DG_HTTP:
                Aria.download(getContext()).load(entity.getId()).cancel(true);
                break;
        }
    }

    private void resume(AbsEntity entity) {
        switch (entity.getTaskType()) {
            case ITaskWrapper.D_FTP:
                //Aria.download(getContext()).loadFtp((DownloadEntity) entity).login("lao", "123456").create();
                Aria.download(getContext()).loadFtp(entity.getId()).resume();
                break;
            case ITaskWrapper.D_FTP_DIR:
                Aria.download(getContext()).loadFtpDir(entity.getId()).resume();
                break;
            case ITaskWrapper.D_HTTP:
            case ITaskWrapper.M3U8_VOD:
                Aria.download(getContext()).load(entity.getId()).resume();
                break;
            case ITaskWrapper.DG_HTTP:
                Aria.download(getContext()).loadGroup(entity.getId()).resume();
                break;
        }
    }

    private void start(AbsEntity entity) {
        switch (entity.getTaskType()) {
            case ITaskWrapper.D_FTP:
                //Aria.download(getContext()).loadFtp((DownloadEntity) entity).login("lao", "123456").create();
                Aria.download(getContext()).loadFtp(entity.getKey()).create();
                break;
            case ITaskWrapper.D_FTP_DIR:
                break;
            case ITaskWrapper.D_HTTP:
            case ITaskWrapper.M3U8_VOD:
                Aria.download(getContext()).load(entity.getKey()).create();
                break;
            case ITaskWrapper.DG_HTTP:
                Aria.download(getContext()).loadGroup(((DownloadGroupEntity) entity).getUrls()).create();
                break;
        }
    }

    private void stop(AbsEntity entity) {
        if (!AppUtil.chekEntityValid(entity)) {
            return;
        }

        switch (entity.getTaskType()) {
            case ITaskWrapper.D_FTP:
                Aria.download(getContext()).loadFtp(entity.getId()).stop();
                break;
            case ITaskWrapper.D_FTP_DIR:
                break;
            case ITaskWrapper.D_HTTP:
            case ITaskWrapper.M3U8_VOD:
                Aria.download(getContext()).load(entity.getId()).stop();
                break;
            case ITaskWrapper.DG_HTTP:
                Aria.download(getContext()).loadGroup(entity.getId()).stop();
                break;
        }
    }

    class SimpleHolder extends AbsHolder {
        ProgressBar progress;
        Button bt;
        TextView speed;
        TextView fileSize;
        TextView cancel;
        TextView name;

        SimpleHolder(View itemView) {
            super(itemView);
            progress = itemView.findViewById(R.id.progressBar);
            bt = itemView.findViewById(R.id.bt);
            speed = itemView.findViewById(R.id.speed);
            fileSize = itemView.findViewById(R.id.fileSize);
            cancel = itemView.findViewById(R.id.del);
            name = itemView.findViewById(R.id.name);
        }
    }

    class GroupHolder extends SimpleHolder {
//        SubStateLinearLayout childList;

        GroupHolder(View itemView) {
            super(itemView);
//            childList = itemView.findViewById(R.id.child_list);
        }
    }
}

## 预期行为
多任务下载mp4和m3u8

## 当前行为
m3u8能下载 ，mp4一直是等待中

## 重现步骤

1.
2.
3.
4.

## 错误日志

java.lang.reflect.InvocationTargetException

## 版本
* 框架版本
3.7.6
* 系统版本
安卓7.0 OppoR11

**Comment by MyAcooL** [comment]
![7DEH7$AW0Q( V1AS6CQFI7T](https://user-images.githubusercontent.com/21095161/69213133-33cc8080-0b9e-11ea-8735-b6f7032f20ee.png)

**Comment by AriaLyy** [comment]
使用`3.7.8-pre`

**Comment by MyAcooL** [comment]
这是新版本吗

**Comment by MyAcooL** [comment]
可以了 用了3.7.7 感谢大佬无私的奉献

**Comment by MyAcooL** [comment]
顺手打发了1块 等我赚大钱了 再回来多给点
