### ISSUE TITLE
下载速度的问题

### ISSUE THREAD

**Issue by MyAcooL** [AriaLyy/Aria#524]
## 预期行为
下载速度按demo里面的走

## 当前行为
下载速度一直是 0  /1/ 2b/s
获取到的speed也是0  1  2这种

## 重现步骤

1.上代码：

![image](https://user-images.githubusercontent.com/21095161/69221110-764b8880-0bb1-11ea-98a4-2d4a677d37de.png)
log:
![image](https://user-images.githubusercontent.com/21095161/69221161-94b18400-0bb1-11ea-9167-0ca2f6e0d9d9.png)
![image](https://user-images.githubusercontent.com/21095161/69221182-a09d4600-0bb1-11ea-8674-5bd40c8bee07.png)

![image](https://user-images.githubusercontent.com/21095161/69221468-4ea8f000-0bb2-11ea-937a-acd0804d150c.png)

2.
3.
4.

## 版本
* 框架版本
3.7.7
* 系统版本
安卓 7.0 OppoR11

**Comment by MyAcooL** [comment]
已解决

**Comment by cblsyp** [comment]
我们出现一样的问题。

**Comment by cblsyp** [comment]
请问你是怎么解决的

**Comment by MyAcooL** [comment]
0b 1b 2b的这个是m3u8的问题 因为不好获取到文件大小 所以我设置了100 Mp4的没有问题

**Comment by cblsyp** [comment]
那你这边下载的是m3u8，还是mp4.   设置100，是什么意思？ 在哪里设置100

**Comment by cblsyp** [comment]
以前测试的其他m3u8是可以的，速度是正常的 。

**Comment by MyAcooL** [comment]
速度不正常就是获取m3u8的大小问题 这个最好是每一个m3u8的大小都自己传进去

**Comment by cblsyp** [comment]
那现在你的m3u8  速度是正常的吗？ 每一个m3u8,你说的是一个url指向的每一个切片还是一个url指向的切片的大小的总和。

**Comment by MyAcooL** [comment]
速度不正常 切片大小的总和

**Comment by MyAcooL** [comment]
传入了文件大小显示也不正确

**Comment by AriaLyy** [comment]
使用`3.7.8-pre-1`版本
