### ISSUE TITLE
同一个url重新下载

### ISSUE THREAD

**Issue by xuqingquan1995** [AriaLyy/Aria#525]
同样的一个url开始下载后调用stop停止掉后，再次重新开启下载，日志输出：
`HttpFileInfoThread: 长度不一致，任务为新任务`
然后重新从0开始下载

## 预期行为

同一个url重新下载应该从之前的进度继续下载

## 当前行为

同一个url重新下载会重新从0开始下载

## 重现步骤
下载地址：
`"https://imtt.dd.qq.com/16891/apk/70BFFDB05AB8686F2A4CF3E07588A377.apk?fsname=com.tencent.tmgp.speedmobile_1.16.0.33877_1160033877.apk&csr=1bbd"`

## 版本
* 框架版本
3.7.7
* 系统版本

**Comment by AriaLyy** [comment]
你好，我这测试是正常的呢，或升级到`3.7.8-pre-1`看看
![image](https://user-images.githubusercontent.com/10437293/69243014-123eb980-0bdd-11ea-8c1f-3a73dea1d8bb.png)
