### ISSUE TITLE
FTP上传的注解回调方法在Kotlin不生效

### ISSUE THREAD

**Issue by annru** [AriaLyy/Aria#528]
使用kotlin语言开发的，上传功能，上传成功后并没有调用诸如@Upload.onTaskComplete void taskComplete(UploadTask task) {}相关的方法

使用的版本是3.6.3

是因为在kotlin中，注解回调方法失效了吗

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by annru** [comment]
不论是build还是运行，都没有报什么错  就是注解回调方法不执行

**Comment by annru** [comment]
FTP上传，文件都能正常上传到服务器

**Comment by AriaLyy** [comment]
升级到新版本

**Comment by annru** [comment]
> 升级到新版本

![image](https://user-images.githubusercontent.com/3982185/69298199-24a20d00-0c48-11ea-9825-bdc03fbb0d6f.png)
换成3.7.7后，在上传的时候报这个错了  换成你那个3.8.1_beta编译都过不了

**Comment by AriaLyy** [comment]
没有3.8.1_beta这个版本！！
