### ISSUE TITLE
远程依赖失败问题

### ISSUE THREAD

**Issue by MyAcooL** [AriaLyy/Aria#530]
## 预期行为
3.7.8-pre依赖
![image](https://user-images.githubusercontent.com/21095161/69297884-3b942f80-0c47-11ea-9893-5b2fe66d1a57.png)

## 当前行为
3.7.8-pre失败

## 重现步骤

1.
2.
3.
4.

## 错误日志
![image](https://user-images.githubusercontent.com/21095161/69297920-536bb380-0c47-11ea-8845-2abc15fbdbdb.png)

## 版本
* 框架版本
3.7.8-pre
* 系统版本
Android 7.0 OppoR11

**Comment by AriaLyy** [comment]
请检查网络
![image](https://user-images.githubusercontent.com/10437293/69298595-59629400-0c49-11ea-99ec-3ecd73d3149e.png)

**Comment by MyAcooL** [comment]
可以了 下载速度能正常显示了 感谢老哥 不过前面的依赖失败 是用了首页的依赖：
implementation 'com.arialyy.aria:core:v_3.7.8-pre-1'
annotationProcessor 'com.arialyy.aria:compiler:v_3.7.8-pre-1'
implementation 'com.arialyy.aria:ftpComponent:v_3.7.8-pre-1' # 如果需要使用ftp，请增加该组件
implementation 'com.arialyy.aria:m3u8Component:v_3.7.8-pre-1' # 如果需要使用m3u8下载功能，请增加该组件

我把v_去了就依赖成功了 是不是首页这里写错了。

成功的依赖：
    implementation 'com.arialyy.aria:core:3.7.8-pre-1'
    annotationProcessor 'com.arialyy.aria:compiler:3.7.8-pre-1'
    implementation 'com.arialyy.aria:ftpComponent:3.7.8-pre-1'
    implementation 'com.arialyy.aria:m3u8Component:3.7.8-pre-1'

**Comment by AriaLyy** [comment]
是写错了。。
