### ISSUE TITLE
从3.6.6升级到3.7.7后，软件覆盖安装，FTP的上传和下载都没有速度

### ISSUE THREAD

**Issue by cc1314** [AriaLyy/Aria#531]
控件从3.6.6升级到3.7.7后，软件覆盖安装，FTP的上传和下载都没有速度。如果卸载重新安装FTP上传和下载都没问题。

## 版本
* 框架版本
3.7.7
* 系统版本
android 9

**Comment by AriaLyy** [comment]
升级到`3.7.8-pre-1`
