### ISSUE TITLE
无法进行下载

### ISSUE THREAD

**Issue by cinpeCan** [AriaLyy/Aria#532]
1.在自定义Application的onCreate方法里调Aria.init(this);
2.在MainActivity的onCreate方法里调Aria.download(this).register();
3.添加配置文件在\VideoDownloader\app\src\main\assets\aria_config.xml;
4.在MainActivity里添加所有注解回调方法,例如:
```
    @Download.onTaskRunning
    void taskRunning(DownloadTask task) {
        Log.i("TAG", "[回调]在这里处理任务进行中");
    }
```
创建下载....
```
        long l = Aria.download(this)
                .load(uri)
                .setFilePath(Environment.getExternalStorageDirectory() + File.separator + "com.appdonwloader" + File.separator+"mytest.apk")
//                .option(option)
//                .resetState()
                .create();
```
以上都是正常遵守文档操作.===========

问题:
1.下载创建后,没有任何回调, 并且没有开始下载.
2.但是任务有被创建, 在第二次进行相同下载时提示文件已被占用.  可以获取这个DownEntity对象,状态为3(等待).

下载URL:
https://d-22.winudf.com/b/apk/Y29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE?_fn=UmVzdW1lIEJ1aWxkZXIgQXBwIEZyZWUgQ1YgTWFrZXIgd2l0aCBQREYgRm9ybWF0X3Y2LjlfYXBrZmFiLmNvbS5hcGs&k=be2310b053eea34faf648d1eb54ac5cf5dd840ea&uu=http%3A%2F%2F172.16.70.1%2Fb%2Fapk%2FY29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE%3Fk%3D0f24bfea0b8933dd7ae1394741aebebc5dd840ea
也尝试过包括:
设置"User-Agent",
使用reStart(),
使用option.setRequestType(RequestEnum.GET),
更换URL,
等等,

大概我的思路完全走错了,烦请帮我指正一下.

## 错误日志
```
11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]https://d-22.winudf.com/b/apk/Y29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE?_fn=UmVzdW1lIEJ1aWxkZXIgQXBwIEZyZWUgQ1YgTWFrZXIgd2l0aCBQREYgRm9ybWF0X3Y2LjlfYXBrZmFiLmNvbS5hcGs&k=be2310b053eea34faf648d1eb54ac5cf5dd840ea&uu=http%3A%2F%2F172.16.70.1%2Fb%2Fapk%2FY29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE%3Fk%3D0f24bfea0b8933dd7ae1394741aebebc5dd840ea
11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]attachment; filename="Resume Builder App Free CV Maker with PDF Format_v6.9_apkfab.com.apk"
11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]application/vnd.android.package-archive
11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]7396977
11-22 04:11:24.194 11509-12527/app.mission.video.downloader.download.hub.videos D/BaseCachePool: 任务【mytest.apk】进入缓存队列成功
11-22 04:11:24.194 11509-12527/app.mission.video.downloader.download.hub.videos D/StartCmd: 开始新任务, 任务状态：3
11-22 04:11:24.195 11509-12527/app.mission.video.downloader.download.hub.videos D/BaseExecutePool: 任务【mytest.apk】进入执行队列成功
11-22 04:11:24.195 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err: java.lang.reflect.InvocationTargetException
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.event.EventMsgUtil$2.run(EventMsgUtil.java:71)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err: Caused by: java.lang.IllegalArgumentException: xxxx
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.util.ComponentUtil.buildUtil(ComponentUtil.java:105)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.DownloadTask.createUtil(DownloadTask.java:79)
11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.AbsTask.getUtil(AbsTask.java:70)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:208)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:193)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(AbsTaskQueue.java:226)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.command.AbsNormalCmd.startTask(AbsNormalCmd.java:146)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.command.StartCmd.executeCmd(StartCmd.java:71)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.command.CommandManager.start(CommandManager.java:53)
11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err: 	... 7 more
```

[下载回调]...... 是打印WebView下载监听回调的5个参数, 不是Aria的.

## 版本
* 框架版本
implementation 'com.arialyy.aria:core:3.7.6'
annotationProcessor 'com.arialyy.aria:compiler:3.7.6'

* 系统版本
Android Gradle Plugin Version:3.5.1
Gradle Version:5.4.1
compileSdkVersion 29
buildToolsVersion = '28.0.3'
minSdkVersion 19
targetSdkVersion 29
已关闭混淆.

**Comment by cinpeCan** [comment]
> 
> 
> 1.在自定义Application的onCreate方法里调Aria.init(this);
> 2.在MainActivity的onCreate方法里调Aria.download(this).register();
> 3.添加配置文件在\VideoDownloader\app\src\main\assets\aria_config.xml;
> 4.在MainActivity里添加所有注解回调方法,例如:
> 
> ```
>     @Download.onTaskRunning
>     void taskRunning(DownloadTask task) {
>         Log.i("TAG", "[回调]在这里处理任务进行中");
>     }
> ```
> 
> 创建下载....
> long l = Aria.download(this)
> .load("http://dl.anycdn.cc/data/static/apk/maxtube262.apk")
> .setFilePath(Environment.getExternalStorageDirectory() + File.separator + "com.appdonwloader" + File.separator+"mytest.apk")
> // .option(option)
> // .resetState()
> .create();
> 以上都是正常遵守文档操作.===========
> 
> 问题:
> 1.下载创建后,没有任何回调, 并且没有开始下载.
> 2.但是任务有被创建, 在第二次进行相同下载时提示文件已被占用. 可以获取这个DownEntity对象,状态为3(等待).
> 
> 下载URL:
> https://d-22.winudf.com/b/apk/Y29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE?_fn=UmVzdW1lIEJ1aWxkZXIgQXBwIEZyZWUgQ1YgTWFrZXIgd2l0aCBQREYgRm9ybWF0X3Y2LjlfYXBrZmFiLmNvbS5hcGs&k=be2310b053eea34faf648d1eb54ac5cf5dd840ea&uu=http%3A%2F%2F172.16.70.1%2Fb%2Fapk%2FY29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE%3Fk%3D0f24bfea0b8933dd7ae1394741aebebc5dd840ea
> 也尝试过包括:
> 设置"User-Agent",
> 使用reStart(),
> 使用option.setRequestType(RequestEnum.GET),
> 更换URL,
> 等等,
> 
> 大概我的思路完全走错了,烦请帮我指正一下.
> ## 错误日志
> 
> ```
> 11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]https://d-22.winudf.com/b/apk/Y29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE?_fn=UmVzdW1lIEJ1aWxkZXIgQXBwIEZyZWUgQ1YgTWFrZXIgd2l0aCBQREYgRm9ybWF0X3Y2LjlfYXBrZmFiLmNvbS5hcGs&k=be2310b053eea34faf648d1eb54ac5cf5dd840ea&uu=http%3A%2F%2F172.16.70.1%2Fb%2Fapk%2FY29tLm5pdGhyYS5yZXN1bWVfOTBfN2ZiNTc0MWE%3Fk%3D0f24bfea0b8933dd7ae1394741aebebc5dd840ea
> 11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
> 11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]attachment; filename="Resume Builder App Free CV Maker with PDF Format_v6.9_apkfab.com.apk"
> 11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]application/vnd.android.package-archive
> 11-22 04:11:24.150 11509-11509/app.mission.video.downloader.download.hub.videos I/cinpe: [下载回调]7396977
> 11-22 04:11:24.194 11509-12527/app.mission.video.downloader.download.hub.videos D/BaseCachePool: 任务【mytest.apk】进入缓存队列成功
> 11-22 04:11:24.194 11509-12527/app.mission.video.downloader.download.hub.videos D/StartCmd: 开始新任务, 任务状态：3
> 11-22 04:11:24.195 11509-12527/app.mission.video.downloader.download.hub.videos D/BaseExecutePool: 任务【mytest.apk】进入执行队列成功
> 11-22 04:11:24.195 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err: java.lang.reflect.InvocationTargetException
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.event.EventMsgUtil$2.run(EventMsgUtil.java:71)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at java.lang.Thread.run(Thread.java:818)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err: Caused by: java.lang.IllegalArgumentException: xxxx
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.util.ComponentUtil.buildUtil(ComponentUtil.java:105)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.DownloadTask.createUtil(DownloadTask.java:79)
> 11-22 04:11:24.196 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.AbsTask.getUtil(AbsTask.java:70)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:208)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:193)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(AbsTaskQueue.java:226)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.command.AbsNormalCmd.startTask(AbsNormalCmd.java:146)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.command.StartCmd.executeCmd(StartCmd.java:71)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err:     at com.arialyy.aria.core.command.CommandManager.start(CommandManager.java:53)
> 11-22 04:11:24.197 11509-12527/app.mission.video.downloader.download.hub.videos W/System.err: 	... 7 more
> ```
> 
> [下载回调]...... 是打印WebView下载监听回调的5个参数, 不是Aria的.
> ## 版本
> 
>     * 框架版本
>       implementation 'com.arialyy.aria:core:3.7.6'
>       annotationProcessor 'com.arialyy.aria:compiler:3.7.6'
> 
>     * 系统版本
>       Android Gradle Plugin Version:3.5.1
>       Gradle Version:5.4.1
>       compileSdkVersion 29
>       buildToolsVersion = '28.0.3'
>       minSdkVersion 19
>       targetSdkVersion 29
>       已关闭混淆.

**Comment by AriaLyy** [comment]
升级到`3.7.8-pre-1`版本

**Comment by cinpeCan** [comment]
问题完美解决.
这是人生第一次提issue, 回复的好及时,  非常的感谢.!
