### ISSUE TITLE
不能同时开启多个普通下载

### ISSUE THREAD

**Issue by pz-bottle** [AriaLyy/Aria#534]
## 预期行为
同时开启两个两个普通下载，按道理来说一个已经下载完了，另外一个开始下载的。

## 当前行为
同时开启两个两个普通下载下载图片，但是一张图片下载完了，另外一张没有任何动静了。

## 重现步骤

1.
2.
3.
4.

## 版本
* 框架版本

* 系统版本

**Comment by AriaLyy** [comment]
请提供下日志，我这测试是正常的
