### ISSUE TITLE
恭喜老哥框架入选玉刚说 是不是该来个开车群了。

### ISSUE THREAD

**Issue by MyAcooL** [AriaLyy/Aria#536]
## 重现步骤

1.
2.
3.
4.

## 版本
* 框架版本

* 系统版本

**Comment by GentlemanGoogoo** [comment]
老哥够快

**Comment by AriaLyy** [comment]
一直是有群的，只不过我个人比较懒，不怎么活跃，再加上上次莫名其妙被个祖安人私聊骂了，一来二去就在readme中删去了群号，如果想进，就进这个群吧：524329160

**Comment by cblsyp** [comment]
哇 今天早上也看到了 ，准备留个言，希望大佬看一下一个issue.就是多个m3u8任务下载，以前的任务会重新进入缓冲队列的问题。

**Comment by AriaLyy** [comment]
这个已经看到了，抽空我处理下
