### ISSUE TITLE
某些机型上Activity里初始化报错

### ISSUE THREAD

**Issue by heygays** [AriaLyy/Aria#537]
小米6，android9.0 
![微信图片_20191126110104](https://user-images.githubusercontent.com/19758027/69595993-2438b600-103c-11ea-81e7-a12f9be95049.png)

**Comment by AriaLyy** [comment]
你是在哪初始化的？初始化代码是啥？

**Comment by heygays** [comment]
在oncreate之后，Aria.download(this).register();

**Comment by heygays** [comment]
好了，可以了，看文档的时候似乎没有说需要在Application里初始化

**Comment by AriaLyy** [comment]
应该是个bug，后面我看下是啥问题

**Comment by AriaLyy** [comment]
`3.7.9`修复了这个问题

**Comment by pupuenjoy** [comment]
下载m3u8文件 如何使用？
