### ISSUE TITLE
代理文件要如何生成呢 

### ISSUE THREAD

**Issue by maosizouguo** [AriaLyy/Aria#538]
## 重现步骤

1.
2.
3.
4.

## 版本
* 框架版本

* 系统版本

**Comment by maosizouguo** [comment]
代理文件要如何生成呢

**Comment by AriaLyy** [comment]
使用注解后自动生成

**Comment by maosizouguo** [comment]
我现在使用了注解标注下载状态的方法  但是没有用  这些方法都不会进  不知道问题出在哪里

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by maosizouguo** [comment]
还是不能生成注解&nbsp; 这个log能看出问题吗&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午3:06
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"746231685"<746231685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 代理文件要如何生成呢  (#538)




https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by maosizouguo** [comment]
annotationProcessor 'com.arialyy.aria:compiler:3.7.8-pre-1'   改成  kapt 'com.arialyy.aria:compiler:3.7.8-pre-1' 代理文件生成了 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"746231685"<746231685@qq.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午3:46
收件人:&nbsp;"AriaLyy/Aria"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [AriaLyy/Aria] 代理文件要如何生成呢  (#538)




还是不能生成注解&nbsp; 这个log能看出问题吗 


------------------ 原始邮件 ------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午3:06
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"746231685"<746231685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 代理文件要如何生成呢  (#538)




https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by AriaLyy** [comment]
3.7.8-pre-3版本吧，pre-1有bug

**Comment by maosizouguo** [comment]
嗯 好的 非常感谢&nbsp; &nbsp; &nbsp;还有一问题&nbsp; &nbsp;下载下来的文件&nbsp; 从手机文件管理中删除了&nbsp; 但是数据库里面还存在&nbsp; &nbsp;导致无法再次下载&nbsp; &nbsp;这个怎么解决呢&nbsp; &nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午3:51
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"746231685"<746231685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 代理文件要如何生成呢  (#538)




3.7.8-pre-3版本吧，pre-1有bug

**Comment by AriaLyy** [comment]
先删除以前的任务就可以了，后面我做一个文件存在的判断吧

**Comment by maosizouguo** [comment]
&nbsp; 大神 先删除以前的任务就可以了&nbsp; 但是从文件管理删除&nbsp; 不知道在哪里删除任务合适 ，我本来想的是 下载完成后就调&nbsp;Aria.download(context).load(entity.id).cancel(false)&nbsp; 删除数据库 但是不删除文件 ，但是这样的话&nbsp; &nbsp;调用Aria.download(this).allCompleteTask就拿不到已下载的list了 也被删了&nbsp;
可不可把下载的数据和加入队列的数据分开建表&nbsp; &nbsp; 不知道我表达清楚没有&nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午4:54
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"746231685"<746231685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 代理文件要如何生成呢  (#538)




先删除以前的任务就可以了，后面我做一个文件存在的判断吧

**Comment by AriaLyy** [comment]
我这测试了，下载完成后，不管文件是否存在，调用create或start都能下载...
![image](https://user-images.githubusercontent.com/10437293/69725020-2f810400-1158-11ea-8365-1f18d68bc070.png)
