### ISSUE TITLE
Aria.download(this).register();无法注册，

### ISSUE THREAD

**Issue by FlashQin** [AriaLyy/Aria#539]
我本来想实现一个下载列表，在列表注册，可以获取到实时的下载数据，但是我初始化估计失败了  在列表没有任何回调，退出重新进入页面可以更新一次最新的进度；
 Set<Integer> set = ProxyHelper.getInstance().checkProxyType(obj.getClass());
    if (set != null && !set.isEmpty()) {
      for (Integer type : set) {
        if (type == ProxyHelper.PROXY_TYPE_DOWNLOAD) {
          DownloadSchedulers.getInstance().register(obj, TaskEnum.DOWNLOAD);
        } else if (type == ProxyHelper.PROXY_TYPE_DOWNLOAD_GROUP) {
          DownloadGroupSchedulers.getInstance().register(obj, TaskEnum.DOWNLOAD_GROUP);
        } else if (type == ProxyHelper.PROXY_TYPE_M3U8_PEER) {
          DownloadSchedulers.getInstance().register(obj, TaskEnum.M3U8_PEER);
        } else if (type == ProxyHelper.PROXY_TYPE_DOWNLOAD_GROUP_SUB) {
          DownloadGroupSchedulers.getInstance().register(obj, TaskEnum.DOWNLOAD_GROUP_SUB);
        }
      }
    } else {
      ALog.w(TAG, "没有Aria的注解方法");
    }
最后进入的ALog.w(TAG, "没有Aria的注解方法");

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by FlashQin** [comment]
大哥我无法引入3.7.8版本
   annotationProcessor 'com.arialyy.aria:compiler:3.7.8'
    compile 'com.arialyy.aria:aria-core:3.7.8'
 或者
    compile('com.arialyy.aria:core:3.7.8'){
        exclude group: 'androidx.appcompat.app'
    }
都会报错误:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\workplace3.44\MyQin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\workplace3.44\MyQin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\workplace3.44\MyQin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:712: error: resource android:attr/fontVariationSettings not found.
  D:\workplace3.44\MyQin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:712: error: resource android:attr/ttcIndex not found.
  D:\workplace3.44\MyQin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1050: error: resource android:attr/textFontWeight not found.
  error: failed linking references.
  
  Command: C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\4778a434490112cc21cbeeed9bc9092c\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
          D:\Android\Sdk\platforms\android-27\android.jar\
          --manifest\
          D:\workplace3.44\MyQin\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\workplace3.44\MyQin\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\workplace3.44\MyQin\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\workplace3.44\MyQin\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --proguard-main-dex\
          D:\workplace3.44\MyQin\app\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\debug\processDebugResources\manifest_keep.txt\
          --custom-package\
          pro.black.rhtask.mymv\
          -0\
          apk\
          --output-text-symbols\
          D:\workplace3.44\MyQin\app\build\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0
  Output:  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\appcompat-1.1.0.aar\65127777942449c2e6fe1d2ec1df3b87\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
      
  D:\workplace3.44\MyQin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
      
  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\design-27.1.1.aar\9c55e9506d3d2255a789bb85b06527a1\res\values\values.xml:96:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.
      
  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\design-27.1.1.aar\9c55e9506d3d2255a789bb85b06527a1\res\values\values.xml:96:5-202: AAPT: error: resource android:attr/ttcIndex not found.
      
  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\design-27.1.1.aar\9c55e9506d3d2255a789bb85b06527a1\res\values\values.xml:109:5-120:36: AAPT: error: resource android:attr/textFontWeight not found.
      
  error: failed linking references.
  Command: C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\4778a434490112cc21cbeeed9bc9092c\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
          D:\Android\Sdk\platforms\android-27\android.jar\
          --manifest\
          D:\workplace3.44\MyQin\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\workplace3.44\MyQin\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\workplace3.44\MyQin\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\workplace3.44\MyQin\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --proguard-main-dex\
          D:\workplace3.44\MyQin\app\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\debug\processDebugResources\manifest_keep.txt\
          --custom-package\
          pro.black.rhtask.mymv\
          -0\
          apk\
          --output-text-symbols\
          D:\workplace3.44\MyQin\app\build\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by FlashQin** [comment]
特别希望能用您这个框架，麻烦帮个忙咯

**Comment by AriaLyy** [comment]
3.7 一般的版本是androidX的
support的最后一个版本是 3.6.6
