### ISSUE TITLE
start方法是否只能调用一次？

### ISSUE THREAD

**Issue by matbird** [AriaLyy/Aria#54]
因为我调用多次出现了图片出错的问题，能大概说明一下这个start和add的调用时机吗？

**Comment by AriaLyy** [comment]
add 只添加到队列中，但不进行下载。start是马上执行下载，start只会调用一次。

**Comment by matbird** [comment]
那感觉这里的设计有些不合理啊，举个例子，比如我在应用的A界面使用了start，之后到了其他的界面，我是使用add呢还是start呢，因为我也不能保证是否调用过了start。
个人建议就是start方法和add方法合并一下，

**Comment by AriaLyy** [comment]
这个无需担心，该add的时候就add，该start的时候就start。
对于一个任务，无论你add多少次，aria都只会执行一次这个命令；同理，start也是一样。
还有一点，**命令郑针对单个任务的**，而不是一个任务add，其它任务就不能add了。你可以在一个activity中交叉使用add和start都不会影响其它任务

**Comment by matbird** [comment]
但是之前确实是出现了这样的问题，就是我有一系列的图片需要下载，我做了一个循环，每个下载使用的都是start，结果就是绝大部分图片是出错的。 就是之前我提交的另外一个issue， #46 
但是我修改成，循环里面用add，然后再开启一个下载任务使用start，这样就没问题了。

**Comment by AriaLyy** [comment]
start的机制是，如果执行队列已经满了，再执行start，会挤掉队首的任务，你一次性全部start，意味着只有最后的几个任务是正在执行的。
而add 是将任务添加到缓冲队列，如果你全部add，最后再开启一个任务的start，意味着执行队列中只有一个任务，当该任务执行完后，会自动执行你add进缓冲队列的任务，这个时候，执行队列只有一个正在执行的任务。
而你那问题的原因是，你32个任务全部一次性start，有些图片刚进执行队列，就被挤出来了，被强制停止...

**Comment by AriaLyy** [comment]
目前打算再增加一个start的策略，如果执行队列已经满了，start命令将替代add命令，只会将任务添加到缓冲池而不会把执行池队首的任务挤出来，这个也就是你说的那个start和add合并的，不知道我的理解对不对？

**Comment by matbird** [comment]
对的，就是这个意思了 。不去管机制是什么，我想要的效果就是，无论start几次，不要影响我下载的结果就好了。
还有，希望大神尽快把任务组的功能给撸出来啊，就等着您了~

**Comment by AriaLyy** [comment]
任务组要等段时间了，最近加班快加成SB了 :joy::joy::joy::joy:

**Comment by matbird** [comment]
哈哈~~能力越大责任就越大嘛
