### ISSUE TITLE
重复下载文件

### ISSUE THREAD

**Issue by YoungBreakMain** [AriaLyy/Aria#540]
多任务下载 当一个任务由暂停状态变成下载状态 已经下载完成的任务又开始重新下载了

## 重现步骤

1.
2.
3.
4.

## 版本
* 框架版本

* 系统版本

**Comment by AriaLyy** [comment]
使用`3.7.8`这是`pre`版本的bug

**Comment by YoungBreakMain** [comment]
就这个版本有嘛？

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/69784925-f5fcd700-11f1-11ea-8a18-b7d8e997fa47.png)

**Comment by YoungBreakMain** [comment]
怎么做可以解决这个问题呢 谢谢了

**Comment by AriaLyy** [comment]
使用`3.7.8`版本
