### ISSUE TITLE
https文件下载失败

### ISSUE THREAD

**Issue by wenxueyangx** [AriaLyy/Aria#541]
我在下载一个https文件时候，发现报错了，应该是认证不安全，咱们支持https下载吗
## 重现步骤

1.
2.
3.
4.

## 错误日志
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): 下载失败【downloadUrl:https://10.155.0.135:32505//api/map/download/99edbaee89614177a35f9d3c53c793c4】
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): 【filePath:/storage/emulated/0/Android/data/com.cloudminds.pepper.hari/files/Download/MAP_ARCHIVE/FS3C.zip99edbaee89614177a35f9d3c53c793c4.zip】
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): ExceptionDetailed:
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): ====================Exception Info====================
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:327)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.Connection.connect(Connection.java:155)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:391)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:227)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:170)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:63)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): java.lang.Thread.run(Thread.java:818)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): 【Caused by】: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:114)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:565)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:323)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.Connection.connect(Connection.java:155)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:391)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:227)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:170)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:63)
11-27 19:57:09.097 E/HttpFileInfoThread( 2452): java.lang.Thread.run(Thread.java:818)

## 版本
* 框架版本
3.4.9
* 系统版本

**Comment by AriaLyy** [comment]
支持的，support升级到3.6.6版本

**Comment by wenxueyangx** [comment]
是说升级到3.6.6才支持是吗，当前的3.4.9不支持

**Comment by AriaLyy** [comment]
不是，这好像是以前的一个bug，3.6.6是support的最后一版本

**Comment by wenxueyangx** [comment]
更新到3.6.6后，看日志打印确实是下载了，但是去对应文件夹下找却没有文件，这是怎么回事？

**Comment by AriaLyy** [comment]
路径是你设置的，我这测试是正常的。。
![image](https://user-images.githubusercontent.com/10437293/69927414-e384e500-14f2-11ea-84d1-9997e6592109.png)
![image](https://user-images.githubusercontent.com/10437293/69927437-f0a1d400-14f2-11ea-9917-afcbfc0986c3.png)

**Comment by wenxueyangx** [comment]
文件下载支持指定post请求还是get请求吗？如果支持怎么设置呢？还有默认是什么请求呢

**Comment by wenxueyangx** [comment]
尝试了用老版本的3.4.9去下载我们原来的http开头的地址，我发现可以下载并且去对应文件夹下可以找到文件，但是当升级到3.6.6后，去下载相同的文件，虽然日志显示下载成功了，但是实际上去对应的文件下看却没有文件

**Comment by AriaLyy** [comment]
打开数据库`AndroidAria.db`，打开`DownloadEntity`这张表，根据你的url查找下对应的文件保存路径，看看是否正常
