### ISSUE TITLE
使用中出现NullPointerException

### ISSUE THREAD

**Issue by xuqingquan1995** [AriaLyy/Aria#542]
以下是有相关的错误日志
### 错误1 
java.lang.NullPointerException
Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

com.arialyy.aria.m3u8.M3U8RecordAdapter.initTaskThreadNum(M3U8RecordAdapter.java)
com.arialyy.aria.core.common.RecordHandler.initRecord(RecordHandler.java)
com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java)
com.arialyy.aria.core.loader.AbsLoader.startFlow(AbsLoader.java)
com.arialyy.aria.core.loader.AbsLoader.run(AbsLoader.java)
java.lang.Thread.run(Thread.java:818)

### 错误2 
java.io.File.fixSlashes(File.java:185)
java.io.File.<init>(File.java:134)
com.arialyy.aria.m3u8.BaseM3U8Loader.getCacheDir(BaseM3U8Loader.java)
com.arialyy.aria.m3u8.vod.M3U8VodLoader.initData(M3U8VodLoader.java)
com.arialyy.aria.m3u8.vod.M3U8VodLoader.onPostPre(M3U8VodLoader.java)
com.arialyy.aria.core.loader.AbsLoader.startFlow(AbsLoader.java)
com.arialyy.aria.core.loader.AbsLoader.run(AbsLoader.java)
java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
使用 TS 转换器查看下，你那边的ts列表是否获取成功

**Comment by AriaLyy** [comment]
我这测试是正常的呢，能否提供下m3u8的url?

**Comment by xuqingquan1995** [comment]
由于是bugly抓取的错误日志，所以并没有抓取到太多到日志信息，并且这两个错误出现到概率也比较高

**Comment by AriaLyy** [comment]
使用`3.7.10_pre_4`版本

**Comment by 748297973** [comment]
> 使用`3.7.10_pre_4`版本

@AriaLyy 3.8.6  bugly也是这个错误

**Comment by 748297973** [comment]
@xuqingquan1995 解决了吗
