### ISSUE TITLE
ftp多次上传文件，上传完成回调不是每次都进

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#543]
上传完成回调不是每次都进

**Comment by AriaLyy** [comment]
请提供下详细的日志啊

**Comment by gjk666** [comment]
那个大佬没有什么特殊的日志就是正常流程再走，然后图片也都上传上去啦，就是这个回调偶尔没有进

**Comment by AriaLyy** [comment]
你上传的代码是怎么写的？

**Comment by liu19890210** [comment]
大佬，请教个问题如应用市场app下载app
![1574932524(1)](https://user-images.githubusercontent.com/23651120/69793095-c609ff80-1202-11ea-84c7-67b92b9b252a.png)怎么在adapter渲染按钮

**Comment by AriaLyy** [comment]
@liu19890210 参考demo https://github.com/AriaLyy/Aria/blob/master/app/src/main/java/com/arialyy/simple/core/download/mutil/DownloadAdapter.java

**Comment by gjk666** [comment]
大佬那个append的权限怎么开呢好开吗

**Comment by AriaLyy** [comment]
你百度下，我使用的是FileZilla Server Interface，打个对勾就完事，其它的不太清楚
![image](https://user-images.githubusercontent.com/10437293/69799762-e0e27100-120e-11ea-9e73-8834c0761616.png)

**Comment by liu19890210** [comment]
@Download.onTaskStop void taskStop(DownloadTask task) {
&nbsp; &nbsp; mAdapter.updateState(task.getEntity());
&nbsp; }
debug不进这方法，是不是一定要用AbsEntity实体类，自己定义实体不行 ?&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 晚上6:42
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"601329828"<601329828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] ftp多次上传文件，上传完成回调不是每次都进 (#543)




你百度下，我使用的是FileZilla Server Interface，打个对勾就完事，其它的不太清楚

**Comment by gjk666** [comment]
好的大佬我试试

**Comment by liu19890210** [comment]
在fragment中注解不能用？@AriaLyy

**Comment by gjk666** [comment]
大佬上传中文图片名称乱码

**Comment by gjk666** [comment]
FtpUFileInfoThread: D_FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码

**Comment by AriaLyy** [comment]
使用charset 设置编码 
![image](https://user-images.githubusercontent.com/10437293/69852873-59553a80-12c0-11ea-8ed0-fa08ce31d6ba.png)

**Comment by gjk666** [comment]
FtpOption option = new FtpOption();
option.login("ftpuser", "ftpuser2019");
option.charSet("UTF-8");
Aria.upload(context)
        .loadFtp(localUrl)//上传文件本地地址
        .setUploadUrl(uploadUrl)//云端接收地址
        .option(option)
        .create();还是乱码啊

**Comment by AriaLyy** [comment]
文件名是什么？

**Comment by gjk666** [comment]
失败8.jpg

**Comment by AriaLyy** [comment]
上传url地址是什么

**Comment by gjk666** [comment]
本地地址====/data/user/0/com.hdtd.ibuilder/files/register/imgs/失败9.jpg

**Comment by AriaLyy** [comment]
使用`3.7.10_pre_2`这个版本，修复了3.7升级导致的中文乱码问题

**Comment by gjk666** [comment]
ERROR: Failed to resolve: com.arialyy.aria:ft.0pComponent:3.7
Show in Project Structure dialog
Affected Modules: app




这个新版本貌似依赖不了啊

**Comment by gjk666** [comment]
大佬我这边服务端已经开启append权限，但是我这边断网后没效果，而且重试只走一边

D/Camera: app passed NULL surface
D/FailureTaskHandler: 任务【97_1_video_1575529267.mp4】开始重试
W/System.err: java.net.ConnectException: Network is unreachable
&nbsp; &nbsp; &nbsp; &nbsp; at java.net.PlainSocketImpl.socketConnect(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
&nbsp; &nbsp; &nbsp; &nbsp; at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
&nbsp; &nbsp; &nbsp; &nbsp; at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
&nbsp; &nbsp; &nbsp; &nbsp; at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
&nbsp; &nbsp; &nbsp; &nbsp; at java.net.Socket.connect(Socket.java:605)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.SocketClient._connect(SocketClient.java:233)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.SocketClient.connect(SocketClient.java:175)
W/System.err:&nbsp; &nbsp; &nbsp;at com.arialyy.aria.ftp.AbsFtpInfoThread.connect(AbsFtpInfoThread.java:332)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:205)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:90)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Thread.run(Thread.java:761)
W/FtpUFileInfoThread: 遇到[ECONNREFUSED-连接被服务器拒绝]错误，已没有其他地址，链接失败；如果是ftps，请检查端口是否使用了ftp的端口而不是ftps的端口
W/System.err: com.arialyy.aria.exception.AriaIOException: Aria Net Exception:链接失败, url: ftp://101.132.33.64:21/home/ftpuser/videopic/historymonitor/jobs/20191205
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:217)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:90)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Thread.run(Thread.java:761)
D/AbsTaskQueue: 从执行池删除任务【97_1_video_1575529267.mp4】成功
I/AbsSchedulers: 没有等待中的任务
E/FtpUFileInfoThread: 任务【ftp://101.132.33.64:21/home/ftpuser/videopic/historymonitor/jobs/20191205】失败
D/AriaConfig: onAvailable

这个只走一边

**Comment by gjk666** [comment]
我再次联网继续同样的操作的时候提示的是这个E/CheckUtil: 上传失败，文件路径【/data/user/0/com.hdtd.ibuilder/files/video/20191205//97_1_video_1575529267.mp4】已经被其它任务占用，请设置其它保存路径&nbsp; 不是断点续传

**Comment by AriaLyy** [comment]
ECONNREFUSED-连接被服务器拒绝，这不是有提示了吗，恢复任务使用的是`resume`

**Comment by gjk666** [comment]
我在这个onResume的方法里面在此进行网络请求吗？

**Comment by gjk666** [comment]
刚刚发错啦大佬那个错误就是append没开的意思吗

**Comment by AriaLyy** [comment]
出现这个，一般是连接被拒绝

**Comment by gjk666** [comment]
大佬断点续传是这么写吗

//任务恢复
@Upload.onTaskResume
public void toUplaodContinue(UploadTask task) {
    List<UploadEntity&gt; list = Aria.upload(this).getAllNotCompleteTask();
    for (UploadEntity e : list) {
        Log.e("===断网上传失败id====","======"+e.getId());
        Aria.upload(this).loadFtp(e.getId()).resume();
    }
}
我这么写之后故意测试上传到一半断网再次进来再次上传log是这么打的    vcap: set exposure area Rect(-200, -200 - 200, 200) E/===断网上传失败id====: ======1 E/CheckUtil: 上传失败，文件路径【/data/user/0/com.hdtd.ibuilder/files/video/20191206//97_1_video_1575599752.mp4】已经被其它任务占用，请设置其它保存路径 I/Adreno: Invalid colorspace 1 I/Adreno: Invalid colorspace 1 D/FtpThreadTask: remotePath: /home/ftpuser/videopic/historymonitor/jobs/20191206/97_1_video_1575599752.mp4 I/Adreno: Invalid colorspace 1 I/Adreno: Invalid colorspace 1 I/Adreno: Invalid colorspace 1 E/========: ====上传进度====61 E/========: ====上传进度====61 E/========: ====上传进度====61 E/========: ====上传进度====61 E/========: ====上传进度====61 E/========: ====上传进度====61 E/========: ====上传进度====61 E/========: ====上传进度====61这是不是已经在断点续传啦只是那个权限没开

**Comment by AriaLyy** [comment]
不是，和创建任务是一样的，可以参考[L93](https://github.com/AriaLyy/Aria/blob/3871d8f0568c0da2b2f51b9e9be6e0ef085a7888/app/src/main/java/com/arialyy/simple/core/download/FtpDownloadActivity.java#L93) 这块case，前提是开通权限

**Comment by gjk666** [comment]
在那个回调里面写这个吗 mTaskId = Aria.download(this).loadFtp(mUrl)
 .setFilePath(mFilePath, true)
              .option(getFtpOption())
              .create();

**Comment by gjk666** [comment]
我刚刚那么写等啦10分钟就传上去啦不知道咋回事

**Comment by gjk666** [comment]
您的这个是一个文件上传根据-1来判断我这个页面会有好多的文件上传啊

**Comment by gjk666** [comment]
我这里等差不多10分钟会再次上传报一个错但是上传成功/ThreadTaskStateManager: isComplete, completeNum = 1
W/System.err: aria.apache.commons.net.ftp.FTPConnectionClosedException: FTP response 421 received.&nbsp; Server closed connection.
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.ftp.FTP.__getReply(FTP.java:376)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.ftp.FTP.__getReply(FTP.java:298)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.ftp.FTP.sendCommand(FTP.java:500)
W/System.err:&nbsp; &nbsp; &nbsp;at aria.apache.commons.net.ftp.FTP.sendCommand(FTP.java:617)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.ftp.FTP.sendCommand(FTP.java:591)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.ftp.FTP.quit(FTP.java:856)
&nbsp; &nbsp; &nbsp; &nbsp; at aria.apache.commons.net.ftp.FTPClient.logout(FTPClient.java:1099)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.BaseFtpThreadTaskAdapter.closeClient(BaseFtpThreadTaskAdapter.java:52)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.ftp.upload.FtpUThreadTaskAdapter.handlerThreadTask(FtpUThreadTaskAdapter.java:95)
&nbsp; &nbsp; &nbsp; &nbsp; at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)

**Comment by gjk666** [comment]
大佬你的意思是其实断点续传和重新创建任务是一样的是吗只是根据任务id是不是-1来判断

**Comment by gjk666** [comment]
大佬您是更新代码啦吗现在我没做任何操作如果在上传过程中上传失败下次在从小操作的话就会自动一直走正在上传的回调咋回事啊

//任务执行中(上传)
@Upload.onTaskRunning
protected void toUplaodRunning(UploadTask task) {
    Log.e("========","====上传进度===="+task.getPercent()+"====id=="+task.getEntity().getId());
}

E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1
E/========: ====上传进度====45====id==1

**Comment by AriaLyy** [comment]
最新代码是3.7.10

**Comment by gjk666** [comment]
大佬最新的这个代码，每次进来如果上传没有传完会自动在上传但是会一直卡在上次的那个进度是我这边服务器的原因吗

**Comment by gjk666** [comment]
大佬最新的这个代码，每次进来如果上传没有传完会自动在上传但是会一直卡在上次的那个进度是我这边服务器的原因吗

一直卡在这个代码
//任务执行中(上传)
@Upload.onTaskRunning
protected void toUplaodRunning(UploadTask task) {
    Log.e("========","====上传进度===="+task.getPercent()+"====id=="+task.getEntity().getId());
}
======: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1
E/========: ====上传进度====58====id==1




有时候过十几分钟一下子就传上去啦有时候就一直卡住

**Comment by gjk666** [comment]
hreadTaskStateManager: isComplete, completeNum = 1
W/System.err: aria.apache.commons.net.ftp.FTPConnectionClosedException: FTP response 421 received.&nbsp; Server closed connection.

**Comment by gjk666** [comment]
大佬在网络状态稳定的情况下每次断点续传在卡10分钟左右会成功
