### ISSUE TITLE
关于在下载视频的时候往对应的任务信息添加新的参数的问题

### ISSUE THREAD

**Issue by FlashQin** [AriaLyy/Aria#545]
大哥：：：：现在我要下载视频，我希望在开始下载的时候多添加一个视频封面的图片地址参数，这样我就可以在下载列表获取地址了；

在只是远程依赖，不重写相关类的情况下，能解决吗》

**Comment by AriaLyy** [comment]
使用组合任务：https://aria.laoyuyu.me/aria_doc/3.6/download/http_group.html
