### ISSUE TITLE
下载至无须权限的目录时，能否取消权限的校验？

### ISSUE THREAD

**Issue by wangzhizy** [AriaLyy/Aria#548]
## 版本
* 框架版本
3.7.9
* 系统版本

## 重现步骤

1.没有存储卡读写权限
2.下载至data/data/package/chache
3.会提示没有权限，无法下载

## 期望结果
开放一个API，调用后可跳过Aria内部的权限校验

**Comment by AriaLyy** [comment]
这不是我控制的，里面没有做权限的验证

**Comment by wangzhizy** [comment]
E/BuilderController: 启动失败，缺少权限：Manifest.permission.WRITE_EXTERNAL_STORAGE
这个不是Aria的Log吗

**Comment by wangzhizy** [comment]
### 经测试发现如下信息：
前提：
1. 下载写在工具类（kotlin）中;
1. 工具类的构造方法调用了`Aria.download(this).register();`
1. 没有进入任何一个调用了`Aria.download(this).register();`的Activity；

步骤：
1. 启动下载，提示`启动失败，缺少权限`;
1. 杀进程，重启，启动下载，提示`启动失败，缺少权限`;
1. 进入一个调用了`Aria.download(this).register();`的Activity；
1. 返回至上一页面；
1. 再次启动下载，可正常下载；
1. 杀进程，重启，启动下载，可正常下载;

**Comment by AriaLyy** [comment]
后面增加一个这个api吧

**Comment by AriaLyy** [comment]
使用`3.7.10_pre_3`版本，增加了`ignoreCheckPermissions()`这个api

**Comment by wangzhizy** [comment]
已使用`3.7.10_pre_3 `，测试没有问题；
感谢，速度真是惊人；
