### ISSUE TITLE
kotlin 上注解不生效  不回调

### ISSUE THREAD

**Issue by liroski** [AriaLyy/Aria#549]
## 版本
* 框架版本
3.7.9
* 系统版本

## 错误日志

E/DownloadReceiver: 没有Aria的注解方法
116-11116/com.didong.po W/CheckUtil: 保存路径【/storage/emulated/0/AlivcQuVideo/download/04b7e045342f4744a8006a5b56bbddac_0.mp4】已经被其它任务占用，当前任务将覆盖该路径的文件
2019-12-04 17:29:54.156 11116-11116/com.didong.po W/RecordUtil: 修改任务记录失败，新文件路径和旧文件路径一致
## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html
