### ISSUE TITLE
3.1.9添加依赖失败， 我用3.1.1版本可以依赖成功，是否忘记上传至仓库了？

### ISSUE THREAD

**Issue by FmrChina** [AriaLyy/Aria#55]
![image](https://user-images.githubusercontent.com/16148103/27326553-59dd64ce-55de-11e7-83c2-72255d777fd3.png)

**Comment by AriaLyy** [comment]
compile 'com.arialyy.aria:aria-core:3.1.9'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.1.9'

该死的，每次合并代码都忘记好好检查readme了...

**Comment by FmrChina** [comment]
![image](https://user-images.githubusercontent.com/16148103/27327277-ad2baa12-55e0-11e7-8866-8be7b083ad6a.png)
第二个工程没法依赖成功，这个需要另行配置么？

**Comment by AriaLyy** [comment]
```
android {
  defaultConfig {
    ........
    javaCompileOptions {
      annotationProcessorOptions {
        includeCompileClasspath false
      }
    }
  }
}
```
在defaultConfig 下增加 javaCompileOptions {...}

**Comment by FmrChina** [comment]
OK,

**Comment by FmrChina** [comment]
OK ，现在你可以关闭这个issue了.
