### ISSUE TITLE
批量下载时 不是每次都进回调   总有一两个文件已经下载完了 但是没有刷新

### ISSUE THREAD

**Issue by maosizouguo** [AriaLyy/Aria#550]
## 版本
* 框架版本

* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
能否提供下日志

**Comment by maosizouguo** [comment]
你看下日志能不能看出问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 上午10:52
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"746231685"<746231685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 批量下载时 不是每次都进回调   总有一两个文件已经下载完了 但是没有刷新 (#550)




能否提供下日志
