### ISSUE TITLE
下载的时候忽略部分404的ts文件，直接合成本地视频文件

### ISSUE THREAD

**Issue by liangruiyu** [AriaLyy/Aria#556]
我如何忽略掉个别 ts 文件请求404的，直接进行合并，而不是下载失败？如果不忽略的话就会导致某一个ts文件请求失败导致整个视频文件下载不成功，比如，我下载了99%，只有最后一个ts下载失败而无法合成视频文件，这样对用户体验是很不友好的

**Comment by AriaLyy** [comment]
使用`3.8_pre_1`版本，增加了`ignoreFailureTs`方法
