### ISSUE TITLE
DownloadReceiver: 没有Aria的注解方法

### ISSUE THREAD

**Issue by 1053346786** [AriaLyy/Aria#559]
## 版本
* 框架版本

* 系统版本

## 错误日志

DownloadReceiver: 没有Aria的注解方法

## 重现步骤

1.因为我要扩展字段所以用的lib库 没有直接引用
2.提示没有注解方法是因为缺少导入的东西吗？
3.
4.

**Comment by 1053346786** [comment]
请问如果我要只用下载 m3u8 这两个模块 我现在已经导入     implementation project(':Aria')
    implementation project(':AppFrame')
    implementation project(':M3U8Component')
    implementation project(path: ':AriaAnnotations')这四个了库了 还需要加入哪个库吗？

**Comment by AriaLyy** [comment]
需要下面几个库
api project(':AriaAnnotations')
  api project(path: ':PublicComponent')
implementation project(':M3U8Component')
kapt project(':AriaCompiler')
  implementation project(':Aria')

**Comment by BryantKawhi** [comment]
我只下载单个文件，导入库如下 implementation 'com.arialyy.aria:core:3.7.10'
    annotationProcessor 'com.arialyy.aria:compiler:3.7.10'   也报这个错，并且注解不生效

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html 看第七点
