### ISSUE TITLE
关于重定向链接的编码问题

### ISSUE THREAD

**Issue by AliveingSoul** [AriaLyy/Aria#56]
代码
```
                Aria.download(DetailActivity.this)
                        .load(info.getDownloadUrl())
                        .setDownloadPath("/sdcard/test.txt")
                        .addHeader("Charset","gb2312")
                        .addHeader("Accept-Charset","gb2312")
                        .start();
```
这是重定向的Response Headers
Connection:close
Content-Length:0
Content-Type:text/html; charset=gb2312
Date:Wed, 21 Jun 2017 06:54:51 GMT
Location:http://down2.xiaoshuofuwuqi.com/d/file/filetxt/20170608/14/%BA%DA%CE%D7%CA%A6%E1%C8%C6%F0.txt
Server:Microsoft-IIS/7.5
X-Powered-By:PHP/5.2.14
X-Powered-By:ASP.NET

log：30x跳转，新url为【http://down2.xiaoshuofuwuqi.com/d/file/filetxt/20170608/14/����ʦ����.txt】

搞不懂为什么

**Comment by AriaLyy** [comment]
使用 utf -8 试一下看看
