### ISSUE TITLE
获取taskId问题

### ISSUE THREAD

**Issue by lookballs** [AriaLyy/Aria#561]
文档中获取任务id

在Aria中，获取任务Id的方法有两种。

1. 通过创建任务的方法获取

通过#create()、#add()的方法返回，得到任务id

long taskId = Aria.download(this).load(url).setFilePath(filePath).create();

2. 通过实体获取

首先通过任务列表获取到对应的实体列表，然后通过#getId()获取到对应的任务id

**Comment by lookballs** [comment]
如果任务已存在，方法一是会直接返回-1的

**Comment by lookballs** [comment]
方法二的话又需要遍历获取指定单个任务的状态

**Comment by AriaLyy** [comment]
方法1是创建任务的，方法2是获取全部任务的，如果只是想取特定任务，有两种方法
1: 通过实体
DownloadEntity entity = Aria.download(this).getFirstDownloadEntity(url)
2: 自己做url  和 id 的映射

**Comment by lookballs** [comment]
DownloadEntity entity = Aria.download(this).getFirstDownloadEntity(url)这个的意思是一个url只会对应一个taskId？

**Comment by AriaLyy** [comment]
是的
