### ISSUE TITLE
已经被其它任务占用，请设置其它保存路径

### ISSUE THREAD

**Issue by BryantKawhi** [AriaLyy/Aria#562]
## 版本
* 框架版本  3.7.10

* 系统版本

3.7.10 中这个问题咋解决呢

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/api/task_handle.html#%E5%BF%BD%E7%95%A5%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84%E5%86%B2%E7%AA%81
