### ISSUE TITLE
getGroupTaskList()问题

### ISSUE THREAD

**Issue by lookballs** [AriaLyy/Aria#563]
例如：一个列表里面有两个任务组

第一步：先开始第一个任务组，下载完成后，退出页面再进入获取。这时getGroupTaskList()返回的size是1，也就是之前的第一个任务组。

第二步：然后开始第二个任务组，重复第一步的操作步骤。这时getGroupTaskList()返回的size是1，但是这时的任务组是第二个任务组。

疑问：getGroupTaskList()始终获取到已完成的状态下的列表都是最新的那一组？

**Comment by lookballs** [comment]
不是获取到的size应该是2？请问这个获取逻辑是怎样的呢？

**Comment by AriaLyy** [comment]
你是如何调用的？我这测试是正常的呢
![image](https://user-images.githubusercontent.com/10437293/70875581-5e6cf600-1ff1-11ea-86db-46f15ab0583b.png)
![image](https://user-images.githubusercontent.com/10437293/70875599-662c9a80-1ff1-11ea-8c18-fa87b244ef4b.png)
