### ISSUE TITLE
断点续传问题

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#564]
在进行断点续传时每次都需要等10分别左右才会继续上传，卡住这10分钟一直在走任务上传中这个回调（网络状态稳定）

**Comment by AriaLyy** [comment]
url 提供下，我测试看看

**Comment by gjk666** [comment]
ftp://101.132.33.64:21/home/ftpuser/videopic/historymonitor/jobs/

"ftpuser", "ftpuser2019"

**Comment by AriaLyy** [comment]
这个好像是你们的ftp服务器无法响应`abor`命令导致的，我这改下逻辑吧

**Comment by gjk666** [comment]
麻烦您了

**Comment by AriaLyy** [comment]
你这个ftp服务器的身份信息过期了，麻烦提供下登录的身份信息给我，我qq：511455842

**Comment by AriaLyy** [comment]
相同的问题，[see](https://github.com/AriaLyy/Aria/issues/569)
