### ISSUE TITLE
mp4视频下载失败问题

### ISSUE THREAD

**Issue by JD-CP** [AriaLyy/Aria#565]
* 框架版本
    implementation 'com.arialyy.aria:core:3.7.10'
    kapt 'com.arialyy.aria:compiler:3.7.10'

* 系统版本
   三星note8 Android9.0

## 错误日志
com.arialyy.aria.exception.AriaIOException: Aria Net Exception:任务下载失败，
errorCode：405, 
errorMsg: Method Not Allowed, url: http://sz-download.weiyun.com/ftn_handler/5fdc18cedfe7e625b56236819b2b61969d00ed80ac760490b3c2b826a240438b/%E6%94%BE%E8%AF%BE%E5%90%8E%E6%A1%8C%E6%B8%B8%E4%BF%B1%E4%B9%90%E9%83%A8-10.mp4

## 重现步骤

1.  集成该框架至我的项目中，首次下载没有问题，可以正常下载。
     然后反复暂停、恢复3-5遍左右，就会出现下载失败。回调 taskFail() 。
2. 下载 Aria project，本地运行，将上述的mp4视频下载地址，添加至demo中。直接下载失败。

麻烦大神有时间帮查一下原因吧！万分火急，跪谢🙏

**Comment by AriaLyy** [comment]
日志不是有提示了吗？
http 405 错误

**Comment by JD-CP** [comment]
奇怪的是 首次下载是正常的，但反复执行暂停、恢复操作几遍之后，就会报上面的错误了。

**Comment by AriaLyy** [comment]
我试了下，你的这个连接chrome上都无法下载..
![image](https://user-images.githubusercontent.com/10437293/70876445-96c20380-1ff4-11ea-9de1-2977df66f4bf.png)

**Comment by JD-CP** [comment]
已经确定问题所在了，是cdn的问题。有效四五次左右，就会失效。
