### ISSUE TITLE
大佬们请问你们怎样处理在下载过程中退出APP，再次进入app是下载任务呢依然正常，点击不会奔溃的？

### ISSUE THREAD

**Issue by pz-bottle** [AriaLyy/Aria#566]
## 版本
* 框架版本

* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
什么意思？如果崩溃请提供日志！

**Comment by pz-bottle** [comment]
就是任务在下载中，或者是暂停了，我将彻底app关闭，在我再次打开app是如任务列表点击已经暂停的项目通知他恢复下载时，好像发现任务已经出问题了，但是你给的demo是不会这样的，我想问问你你是怎样处理这个问题发生的？我在你demo代码中没有找到方法

**Comment by AriaLyy** [comment]
框架里面做的处理，demo没做处理

**Comment by pz-bottle** [comment]
嗯嗯，好那我现在测试一下然后发个奔溃日志给你帮我看看啊，谢谢大佬

**Comment by pz-bottle** [comment]
不好意思大佬，是我用错方法了，我用了reStart，我现在改回resume了
