### ISSUE TITLE
kotlin注解不成功

### ISSUE THREAD

**Issue by wenwenwen888** [AriaLyy/Aria#568]
版本：3.5.4

错误日志：[kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.arialyy.compiler.AriaProcessor (NON_INCREMENTAL), com.google.auto.service.processor.AutoServiceProcessor (NON_INCREMENTAL).

说明：
1,已加入
```
apply plugin: 'kotlin-kapt'
```
2,已使用最新版本的kotlin(1.3.61)
3,dependencies里的配置是
```
implementation 'com.arialyy.aria:aria-core:3.5.4'
kapt 'com.arialyy.aria:aria-compiler:3.5.4'
```
4,看了好久issues和注解无效说明，还是没看懂，烦请指教，谢谢大佬

**Comment by AriaLyy** [comment]
升级到新版本

**Comment by wenwenwen888** [comment]
@AriaLyy 确实升级就好，感谢大佬
