### ISSUE TITLE
断点续传断网卡住问题

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#569]
使用场景：
   上传文件断网在继续断点续传
出现状况：
   程序会一直走正在上传回调10分钟左右会上传成功

！！！如果不是断网是调用停止任务在恢复则一切正常

**Comment by AriaLyy** [comment]
ftp是双工的，客户端端口连接，服务端可能还有连接，这时客户端重新连接，如果服务器端创建socket失败，但是没有返回对应错误码，客户端将会卡住，需要服务器端处理

**Comment by AriaLyy** [comment]
使用 3.8.1  增加了一个等待创建socket，服务端没反应，自行断开的功能

**Comment by gjk666** [comment]
大佬那我更新一下版本是不是服务端就不用动啦，我这边的后台最近忙的不行一直没改服务端配置

**Comment by AriaLyy** [comment]
不是的，这只能保证客户端不被卡住，依然上传不了
