### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by JuTuTu** [AriaLyy/Aria#57]
上传文件时，出现错误：
06-21 06:20:44.217 27454-27454/ W/ExecutePool: 任务添加成功
06-21 06:20:44.478 27454-27463/ E/StrictMode: Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/databases/AriaLyyDb, table = null, query = SELECT rowid, * FROM UploadEntity WHERE filePath='/sdcard/test.mp4'
                                                          android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
错误是在查询文件后指针未关闭造成的，应该是我用的严格模式会出现这个问题，不过还是希望您能解决一下：）
[https://stackoverflow.com/questions/3068320/finalizing-a-cursor-that-has-not-been-deactivated-or-closed-non-fatal-error](url)

**Comment by AriaLyy** [comment]
好的，感谢您的反馈，这问题我会处理的
