### ISSUE TITLE
3.8版本，应用集成后第一次使用报错崩溃，日志如下

### ISSUE THREAD

**Issue by gaobaoshen** [AriaLyy/Aria#570]
#14402 android.database.sqlite.SQLiteException
no such table: TaskRecord (code 1 SQLITE_ERROR[1]): , while compiling: SELECT rowid, * FROM TaskRecord WHERE filePath=? AND taskType=?
com.arialyy.aria.orm.DelegateFind.exeNormalDataSql(DelegateFind.java:427)

1 android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
--
2 android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
3 android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
4 android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
5 android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
6 android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
7 android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
8 android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1865)
9 android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1804)
10 com.arialyy.aria.orm.DelegateFind.exeNormalDataSql(DelegateFind.java:427)
11 com.arialyy.aria.orm.DelegateFind.findData(DelegateFind.java:336)
12 com.arialyy.aria.orm.DelegateWrapper.findData(DelegateWrapper.java:138)
13 com.arialyy.aria.orm.DbEntity.findFirst(DbEntity.java:178)
14 com.arialyy.aria.util.DbDataHelper.getTaskRecord(DbDataHelper.java:44)
15 com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:74)
16 com.arialyy.aria.core.loader.AbsLoader.startFlow(AbsLoader.java:117)
17 com.arialyy.aria.core.loader.AbsLoader.run(AbsLoader.java:131)

**Comment by AriaLyy** [comment]
使用 3.8.1  增加了一个等待创建socket，服务端没反应，自行断开的功能
