### ISSUE TITLE
为什么M3U8下载的时候没有下载文件大小，和当前下载大小  只有一个下载进度？

### ISSUE THREAD

**Issue by luokun666** [AriaLyy/Aria#572]
## 版本
* 框架版本

* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
因为m3u8是一个切片的集合，协议里面并没有总长度，要获取总长度就要向服务器请求所有切片的信息，但是这样是不现实的，消耗的时间太长，资源消耗太多。
当前下载进度使用：getCurrentProgress

**Comment by ZhuSky** [comment]
能不能提供一个在类似的方法 ，下载和获取文件大小异步进行的那种

**Comment by ZhuSky** [comment]
@AriaLyy
