### ISSUE TITLE
SQLiteException

### ISSUE THREAD

**Issue by Mr-YangCheng** [AriaLyy/Aria#578]
## 版本
* 框架版本
   3.8.1
* 系统版本
  魅族15plus
## 错误日志

table DownloadEntity has no column named taskType (code 1): , while compiling: INSERT INTO DownloadEntity(isGroupChild,downloadPath,url,state,isRedirect,stopTime,taskType,fileName,isComplete,fileSize,percent,currentProgress,completeTime) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)

## 重现步骤

1.创建普通下载任务报错

**Comment by AriaLyy** [comment]
从低版本升级上来的？

**Comment by Mr-YangCheng** [comment]
@AriaLyy 是的，基本所有版本都用过

**Comment by AriaLyy** [comment]
> @AriaLyy 是的，基本所有版本都用过

从哪个版本升上来的？

**Comment by Mr-YangCheng** [comment]
3.5.2——>3.6.4——>3.7.3——>3.7.9——>3.7.10——>3.8

**Comment by AriaLyy** [comment]
有没有警告信息？

**Comment by AriaLyy** [comment]
使用`3.8.3_beta_1`看看

**Comment by AriaLyy** [comment]
根据群友提供的数据库，已经重现该问题，请使用`3.8.3_beta_5`版本
