### ISSUE TITLE
3.8下载暂停后，无法恢复

### ISSUE THREAD

**Issue by heygays** [AriaLyy/Aria#579]
## 版本
* 3.8 && 3.8.1

* MIUI10 && Android 9

## 重现步骤

1.下载一个m3u8文件，开始后点击暂停
2.再调用resume()，无法继续下载，一直0.0kb/s
3.依然下载一个m3u8文件，开始后切后台划掉应用
4.回到应用再次resume()，下载进度（entity.getPeerIndex() * 100 / entity.getPeerNum()）会清0，并且也一直是0.0kb/s

切回3.7.10后就正常了

**Comment by AriaLyy** [comment]
感谢反馈🙏

**Comment by AriaLyy** [comment]
能否提供下测试地址，我自己测试是正常的
![image](https://user-images.githubusercontent.com/10437293/71467082-a6afc380-27fc-11ea-9b74-bd78e8646c95.png)

**Comment by deepdream88** [comment]
> 能否提供下测试地址，我自己测试是正常的
> ![progr](https://user-images.githubusercontent.com/10437293/71467135-de1e7000-27fc-11ea-8dc6-d7ddc54ffd1e.gif)

啊，我这边也是，我从3.6版本开始用到3.8，下载m3u8的视频，都是不能中断，我现在只能直接隐藏暂停按钮了。

**Comment by deepdream88** [comment]
也许是服务器配置不同的原因。

**Comment by deepdream88** [comment]
https://youku.cdn7-okzy.com/20191213/16167_c3592a02/index.m3u8

**Comment by AriaLyy** [comment]
我用你这地址测试是可以的，需要自行修改ts地址和码率地址。
![sss](https://user-images.githubusercontent.com/10437293/72029846-36a44180-32c2-11ea-9dad-f49ad0ce7a2c.gif)
![image](https://user-images.githubusercontent.com/10437293/72029886-53d91000-32c2-11ea-92a9-5f25bc300fac.png)

**Comment by androidwzl** [comment]
版本3.85,，
### ### meu8下载暂停后，进度归0，恢复下载后从0开始。
测试地址:https://media6.smartstudy.com/ae/07/3997/2/dest.m3u8

**Comment by AriaLyy** [comment]
@androidwzl  见这 https://github.com/AriaLyy/Aria/issues/597

**Comment by androidwzl** [comment]
> @androidwzl 见这 #597

我是能够下载的，ts地址拼的也对，不需要选择码率，直接运行demo也是同样的问题（暂停进度归0，恢复进度归0）

**Comment by AriaLyy** [comment]
了解，我看下是啥问题

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/74597900-e62eb980-50a1-11ea-9c97-5fd80e32020d.png)
测试地址我没有访问权限，还有你这个m3u8是直播地址吗？如果是直播地址，每次停止都会从0开始

**Comment by androidwzl** [comment]
> ![image](https://user-images.githubusercontent.com/10437293/74597900-e62eb980-50a1-11ea-9c97-5fd80e32020d.png)
> 测试地址我没有访问权限，还有你这个m3u8是直播地址吗？如果是直播地址，每次停止都会从0开始

并不是直播地址。该地址昨天还可以访问，可以试试这个地址https://135zyv5.xw0371.com/2018/10/29/X05c7CG3VB91gi1M/playlist.m3u8，
跟地址关系不大，demo中自己的地址也是可以的。
目前的问题是，视屏下载点击暂停，进度条回归0，点击恢复后，又重新下载。

**Comment by AriaLyy** [comment]
已找到原因，和这个一样的问题，https://github.com/AriaLyy/Aria/issues/610

**Comment by AriaLyy** [comment]
@androidwzl 

3.8.6 已修复了这个问题
