### ISSUE TITLE
文件已经上传，但是程序找不到

### ISSUE THREAD

**Issue by mabaixiao** [AriaLyy/Aria#580]
## 版本
* 框架版本
3.8.1
* 系统版本
Android 9
## 错误日志

2019-12-25 16:45:48    FtpDFileInfoThread    
msg【】
Exception：ExceptionDetailed:
====================Exception Info====================
com.arialyy.aria.exception.AriaIOException: Aria Net Exception:文件不存在，url: ftp://58.210.178.52:21/battery1.0.0.apk, remotePath：/battery1.0.0.apk, code: 221, msg: null
com.arialyy.aria.ftp.AbsFtpInfoThread.failDownload(AbsFtpInfoThread.java:397)
com.arialyy.aria.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:121)
java.lang.Thread.run(Thread.java:784)
===================================================

## 重现步骤

1.设置FtpDownloadActivity中的用户名user，密码passw
2.设置FtpDownloadModule中的ftpDefUrl，url
3.运行
4.

**Comment by AriaLyy** [comment]
请使用Filezilla等ftp软件验证下，看看服务器上是否有这问题

**Comment by mabaixiao** [comment]
已经使用Filezilla试了，可以访问到有一个apk在上面的

**Comment by mabaixiao** [comment]
![微信图片_20191226115416](https://user-images.githubusercontent.com/27548964/71457016-1f038e00-27d7-11ea-9b0c-ca7318faa235.png)

**Comment by AriaLyy** [comment]
用的是哪个ftp服务器

**Comment by mabaixiao** [comment]
我们公司没有后台开发人员，IE部门说是公司的服务器，自己搭建的。。

**Comment by AriaLyy** [comment]
我说的是服务器软件哈，用的是哪个ftp服务器软件，我好自己测试下，或你提供一个可被我测试的地址。我看下是什么问题

**Comment by AriaLyy** [comment]
使用3.8.3_beta_1，然后将设置windows 标志 
```
option.setServerIdentifier(FtpOption.FTPServerIdentifier.SYST_NT);
```
