### ISSUE TITLE
androidQ

### ISSUE THREAD

**Issue by JD-CP** [AriaLyy/Aria#582]
你好，请问框架进行 androidQ 适配了嘛？现在有用户反馈 在android10手机下载视频，一直处于下载中，文件大小、下载速度等 都是显示0。

**Comment by AriaLyy** [comment]
可能是这个问题 https://github.com/AriaLyy/Aria/issues/581

**Comment by JD-CP** [comment]
嗯 本以为升级android10的用户不多 后来发现是我错了😭 请问作者 啥时候能解决这个问题啊🙏

**Comment by AriaLyy** [comment]
我晚上再上传个版本吧，用了另外一种不需要反射的方式

**Comment by AriaLyy** [comment]
使用`3.8.3_beta`看看
