### ISSUE TITLE
为什么没有自动生成代理文件

### ISSUE THREAD

**Issue by xiao00yao** [AriaLyy/Aria#585]
//断点续传框架
    implementation 'com.arialyy.aria:core:3.8.1'
    annotationProcessor 'com.arialyy.aria:compiler:3.8.1'

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        Aria.download(this).register();
        httpUpdate(object : CallBack<String>() {
            override fun onSuccess(t: String?) {
                mPGYUpdateBean = GsonUtils.fromJson(t, PGYUpdateBean::class.java)
                //存在更新显示按钮
                if (AppUtils.getAppVersionCode()<mPGYUpdateBean.data.buildVersionNo.toInt()){
                    updateBtn.visibility = View.VISIBLE
                }
            }

            override fun onError(e: ApiException?) {

            }

            override fun onStart() {

            }

            override fun onCompleted() {

            }

        },"蒲公英更新检查接口")
    }

//这个方法被注解了  ，但是没有生成代理文件
    @Download.onTaskRunning protected fun running(task: DownloadTask) {
        if(task.key == mPGYUpdateBean.data.downloadURL){
//            可以通过url判断是否是指定任务的回调
        }
        val percent = task.percent//任务进度百分比
        val speed = task.convertSpeed//转换单位后的下载速度，单位转换需要在配置文件中打开
        val speed1 = task.speed//原始byte长度速度
    }

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/544
