### ISSUE TITLE
数据库升级的问题 从3.6.4升级到3.8时报的错

### ISSUE THREAD

**Issue by yanbin92** [AriaLyy/Aria#586]
android.database.sqlite.SQLiteException: no such column: DownloadEntity.taskType (code 1): , while compiling: SELECT DownloadGroupEntity.rowid AS prowid,DownloadGroupEntity.completeTime AS pcompleteTime,DownloadGroupEntity.convertFileSize AS pconvertFileSize,DownloadGroupEntity.currentProgress AS pcurrentProgress,DownloadGroupEntity.fileSize AS pfileSize,DownloadGroupEntity.isComplete AS pisComplete,DownloadGroupEntity.percent AS ppercent,DownloadGroupEntity.state AS pstate,DownloadGroupEntity.stopTime AS pstopTime,DownloadGroupEntity.str AS pstr,DownloadGroupEntity.alias AS palias,DownloadGroupEntity.dirPath AS pdirPath,DownloadGroupEntity.groupHash AS pgroupHash,DownloadGroupEntity.urls AS purls,DownloadEntity.rowid AS crowid,DownloadEntity.completeTime AS ccompleteTime,DownloadEntity.convertFileSize AS cconvertFileSize,DownloadEntity.currentProgress AS ccurrentProgress,DownloadEntity.fileSize AS cfileSize,DownloadEntity.isComplete AS cisComplete,DownloadEntity.percent AS cpercent,DownloadEntity.state AS cstate,DownloadEntity.stopTime AS cstopTime,DownloadEntity.str AS cstr,DownloadEntity.fileName AS cfileName,DownloadEntity.isGroupChild AS cisGroupChild,DownloadEntity.isRedirect AS cisRedirect,DownloadEntity.redirectUrl AS credirectUrl,DownloadEntity.taskType AS ctaskType,DownloadEntity.url AS curl,DownloadEntity.disposition AS cdisposition,DownloadEntity.downloadPath AS cdownloadPath,DownloadEntity.groupHash AS cgroupHash,DownloadEntity.md5Code AS cmd5Code,DownloadEntity.serverFileName AS cserverFileName FROM DownloadGroupEntity INNER JOIN DownloadEntity ON DownloadGroupEntity.groupHash = DownloadEntity.groupHash WHERE DownloadGroupEntity.dirPath='%2Fstorage%2Femulated%2F0%2Fsantaidownload'

 Aria.download(DevicesSoftUpdateFragment.this)
                .loadGroup(groupUrls)     //读取下载地址
                .ignoreFilePathOccupy()
                .setDirPath(Environment.getExternalStorageDirectory().getAbsolutePath()
                        + "/santaidownload")
                .unknownSize()
                .setSubFileName(subFileNames)
                .create();

**Comment by AriaLyy** [comment]
数据库文件`AndroidAria.db`这个db文件能否提供下？qq群：524329160

**Comment by AriaLyy** [comment]
使用`3.8.3_beta_1`看看

**Comment by AriaLyy** [comment]
根据群友提供的数据库，已经重现该问题，请使用`3.8.3_beta_5`版本
