### ISSUE TITLE
3.8,3.8.1版本m3u8下载进度有问题，一直显示0

### ISSUE THREAD

**Issue by liangruiyuwanba** [AriaLyy/Aria#588]
3.8,3.8.1版本m3u8下载
@Download.onTaskRunning
    void running(DownloadTask task) {

该注解方法中的task.getpercent一直打印0，但是实际进度是有的，导致进度条不更新

**Comment by AriaLyy** [comment]
感谢反馈

**Comment by AriaLyy** [comment]
使用`3.8.3_beta_5`版本
