### ISSUE TITLE
设计小提议

### ISSUE THREAD

**Issue by Yanqilong** [AriaLyy/Aria#59]
现在下载的回调函数改为注解方式了，onPre注解的的参数需要传递下载链接。假如刚进页面的时候我的链接DOWNLOAD_URL不存在，需要请求网络后才能知道下载链接，这怎么办？

而且这样如果应对会变化的下载链接呢？

@Download.onPre(DOWNLOAD_URL)
protected void onPre(DownloadTask task) {}

**Comment by AriaLyy** [comment]
可以这样
```
@Download.onPre
protected void onPre(DownloadTask task) {
   if (task.getKey().eques(DOWNLOAD_URL)){
     .....
   }
}
```
onPre(xxxx)括号中的有参数则表示该被注解的方法只能被xxx下载地址的链接执行

**Comment by Yanqilong** [comment]
搜噶，谢谢

**Comment by Yanqilong** [comment]
删除任务后，再次下载还会从以前的进度开始算起， 不是应该从零开始吗？用的demo测试

**Comment by Yanqilong** [comment]
还有一个问题
添加了一下依赖后
compile 'com.arialyy.aria:aria-core:3.2.0'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.0'

使用注解没有没有生成代理类啊，各种rebuild run 都没有生成，我说调试半天不执行回调，我还是还原上个版本代码，demo测试了是有回调，自己写没有，用的是相同代码，大大这问题出在哪里？

**Comment by AriaLyy** [comment]
任务删除那，是哪一个链接，能发给我一下吗？正常来说，删除了任务就会从0开始，我自己测试的都是正常的。

你先clean工程，然后make一下，然后，工程的\build\generated\source\apt\debug\目录下搜索有没有`xxxxx$$DownloadListenerProxy`一类的java文件，如果没有，表示apt生成代理文件失败，点击AS右下角的Gradle Console查看build有没有警告或错误一类的代码

**Comment by Yanqilong** [comment]
任务删除运行的是demo哇，直接从github clone下来的，点击->下载DEMO->单任务下载，里面会出现这种情况。。。。删除任务后文件大小还是会从上次开始计算。

clear或者make项目也没生产代理类对象, Aria.download(this).register();有调用，执行的流出，都是demo弄过去的，不会弄错。自己搞个demo试试，我这真不行，呜呜。。。。

**Comment by AriaLyy** [comment]
我重新开了一个工程，使用3.2.0的lib是可以的啊，你检查你注解的方法
```
  @Download.onPre
  protected void sss(DownloadTask task){
  }
```
被注解的方法不能是private，并且只能有一个参数，该参数只能为DownloadTask，或UploadTask否则生成代理会失败
