### ISSUE TITLE
重置任务状态得API没了？

### ISSUE THREAD

**Issue by Zhuangyongbing** [AriaLyy/Aria#592]
Aria.download(this).resetState();这个API用不了了

**Comment by AriaLyy** [comment]
```
Aria.download(this)
          .load(url)
          .setFilePath(path)
          .resetState()
          .create();
```

**Comment by Zhuangyongbing** [comment]
- 无法单独判断得？
 E/CheckUtil: 下载失败，文件夹路径【/storage/emulated/0/xiangjiao_file/image/】已经被其它任务占用，请设置其它文件路径
2019-12-31 10:50:16.861 28103-28103/com.linkfun.enjoydisk I/AbsSchedulers: 没有等待中的任务
这种情况下我需要在点击之前先判断任务是否存在是得话要重置任务状态，并重新下载

**Comment by Zhuangyongbing** [comment]
噢噢噢  知道了 不好意思  谢谢，我绕坑了

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/api/task_handle.html#%E5%BF%BD%E7%95%A5%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84%E5%86%B2%E7%AA%81

**Comment by Zhuangyongbing** [comment]
Aria.download(this).taskExists(listUrl)这个API是查看任务组是否存在 ，debug是不存在得 但是loge提示下载失败，文件夹路径【/storage/emulated/0/xiangjiao_file/image/】已经被其它任务占用，请设置其它文件路径，   我需要根据任务组得状态去重置任务再下载，这个能怎么解决一下？

**Comment by Zhuangyongbing** [comment]
现在下载进度一直为0 下载地址是OK得 网上可以访问

**Comment by AriaLyy** [comment]
看logcat 日志的提示

**Comment by Zhuangyongbing** [comment]
com.arialyy.aria.exception.AriaIOException: 文件下载失败，savePath: /storage/emulated/0/xiangjiao_file/up/fce0f098-be6b-4198-b6d5-5b0c6a5f74a8.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=lfminio%2F20191231%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191231T034853Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&X-Amz-Signature=237bae59a427b9f8060adbd37afad16aa603a41a7b2e355cac3a5d603338f70e, url: http://cloudsave.linkfun.cc:9001/images/9/201912/fce0f098-be6b-4198-b6d5-5b0c6a5f74a8.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=lfminio%2F20191231%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191231T034853Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&X-Amz-Signature=237bae59a427b9f8060adbd37afad16aa603a41a7b2e355cac3a5d603338f70e
2019-12-31 11:48:59.291 13368-13504/com.linkfun.enjoydisk W/System.err: /storage/emulated/0/xiangjiao_file/up/fce0f098-be6b-4198-b6d5-5b0c6a5f74a8.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=lfminio%2F20191231%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191231T034853Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&X-Amz-Signature=237bae59a427b9f8060adbd37afad16aa603a41a7b2e355cac3a5d603338f70e.0.part (File name too long)


是因为文件名太长的原因？

**Comment by AriaLyy** [comment]
有可能，手动改个名字看看
