### ISSUE TITLE
3.6.6 -> 3.8.1 error

### ISSUE THREAD

**Issue by goodgoodstudy366** [AriaLyy/Aria#593]
SQLiteLog: (1) table DownloadEntity has no column named taskType

**Comment by AriaLyy** [comment]
没有对应的数据，我这一直复现不出来，可以尝试使用`3.8.3_beta_1`看看，如果还是有问题，可以加群：524329160 提供数据库我给测试

**Comment by AriaLyy** [comment]
根据群友提供的数据库，已经重现该问题，请使用3.8.3
