### ISSUE TITLE
请问如何获取当前正在执行的任务或者任务列表？

### ISSUE THREAD

**Issue by Joker-Q4** [AriaLyy/Aria#594]

**Comment by Joker-Q4** [comment]
或者如何将等待中的任务设置高优先级，而不是直接创建高优先级任务？

**Comment by AriaLyy** [comment]
没有这个api，后面会增加，现在可以这样做：
1、获取所有任务列表
2、遍历该列表，取出状态为`IEntity.STATE_RUNNING`的任务

**Comment by Joker-Q4** [comment]
好的，谢谢

**Comment by AriaLyy** [comment]
使用`3.8.3_beta_5`版本，查看 https://aria.laoyuyu.me/aria_doc/api/task_list.html，可获取执行中的任务

**Comment by Joker-Q4** [comment]
好的，谢谢！😄
