### ISSUE TITLE
为啥不把 IVodTsUrlConverter setBandWidthUrlConverter 放到M3u8InfoThread 里面

### ISSUE THREAD

**Issue by z876335662** [AriaLyy/Aria#598]
为啥不把 IVodTsUrlConverter setBandWidthUrlConverter 放到M3u8InfoThread 里面去处理 。解析M3U8配置然后设置对应的url 。

**Comment by AriaLyy** [comment]
IVodTsUrlConverter 是获取完成ts文件后才能调用的，出于解藕的考虑，所以不放在m3u8infothread中，setBandWidthUrlConverter 是在m3u8infothread中的
