### ISSUE TITLE
下载的时候能否，传一个用户自己的对象，用来显示内容

### ISSUE THREAD

**Issue by AndMy** [AriaLyy/Aria#6]
能否传一个对象进去，因为显示的内容比较多？

**Comment by AriaLyy** [comment]
抱歉，我不太清楚你的需求，能把你的需求描述详细一点吗？
你所说的传一个对象进去，是传递到哪里？

**Comment by AndMy** [comment]
应该是保存到下载的数据库吧，正在下载和下载完成的时候，显示的内容
比如：是歌曲的话，内容就多了，歌曲名、谁唱的、介绍、作词者等等
就是传一个对象，让开发者自己obj.setxxx();进去就可以了

不知道我的描述，清楚不？

**Comment by AriaLyy** [comment]
你的意思是，希望能直接使用Aria.whit(this).load(download_url).setObj(obj);  然后在回调函数中使用Task.getObj()来获取信息吗？
现在Aria暂时没有这个功能，你可以考虑给你的歌曲信息写一张表（Sing），把歌曲都存在数据库中，当Aria下载完成你的歌曲后，你可以在回调函数中调用Task.getDownloadUrl()方法获取歌曲的下载地址，然后通过该下载地址在Sing表中查出对应的歌曲信息

**Comment by AndMy** [comment]
嗯嗯，就是这么做的，不过还得说声谢谢，这么细心的回答我的问题
可以在下个版本加上这个功能？

**Comment by AriaLyy** [comment]
不用客气，你的反馈就是对我最好的感谢。
下个版本会考虑这个功能^_^

**Comment by AndMy** [comment]
嗯嗯，你人挺好，我之前也遇到过其他开源的问题，他们都不理我
只有你回复我，好人啊

**Comment by AriaLyy** [comment]
.....
