### ISSUE TITLE
onTaskCancel回掉函数中的任务并没有真正取消

### ISSUE THREAD

**Issue by guxun12** [AriaLyy/Aria#60]
Hi，最近在使用中发现一个潜在问题，复现场景如下：
```
target.load(DOWNLOAD_URL).setDownloadPath(PATH).add();
target.cancel();

@onTaskCancel()
void onTaskCancel(){
    target.load(DOWNLOAD_URL).setDownloadPath(PATH).add();
}

```
此时会提示"添加命令执行失败，【该任务已经存在】"，原因可能是TaskQueue中的缓存池任务没有及时删除，在执行AddCmd操作时存在旧的缓存对象。并且通过Log打印发现CachePool移除任务的时间要比onTaskCancel回调晚几十毫秒的样子。
PS：我目前是在回掉函数中延迟执行add操作解决的:-D

**Comment by AriaLyy** [comment]
元素从队列出队有一个时间的过程，回头我处理一下
