### ISSUE TITLE
FTP上传进度问题

### ISSUE THREAD

**Issue by abcweihua** [AriaLyy/Aria#602]
FTP上传过程中没有实时进度，上传完成直接跳到100%，有没有小伙伴能修复

**Comment by AriaLyy** [comment]
看是否是标志的问题，https://aria.laoyuyu.me/aria_doc/api/ftp_params.html#%E5%9B%9B%E3%80%81%E4%B8%8B%E8%BD%BD%E8%BF%87%E7%A8%8B%E6%97%A0%E6%B3%95%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6%E5%9C%B0%E5%9D%80

**Comment by abcweihua** [comment]
设置标志还是不行，另外，多任务同时下载，怎么实现多任务断点上传，目前只能记录第一个任务的断点

**Comment by AriaLyy** [comment]
使用的版本是多少？断点上传不不需要你处理，正常的stop，resume便可

**Comment by abcweihua** [comment]
> 使用的版本是多少？断点上传不不需要你处理，正常的stop，resume便可

最新版本的，上传一个断点是正常的，多个文件上传时，如果暂停再开始，只有一个有断点，其它的都是从头开始

**Comment by AriaLyy** [comment]
好的，我后面验证下看看

**Comment by abcweihua** [comment]
> 好的，我后面验证下看看

找到问题了，是数据库记录的问题，但下载进度taskRunning确实没有回调

**Comment by AriaLyy** [comment]
使用`3.8.4_beta_1`版本

**Comment by yanbin92** [comment]
问一下3.8.4_beta_1 这问题好了吗
