### ISSUE TITLE
m3u8下载的getTaskType有错误

### ISSUE THREAD

**Issue by Pancts** [AriaLyy/Aria#610]
## 版本 
* 框架版本
3.8.5
* 系统版本
9.0

下载m3u8点播和直播时中途停止会重置TaskType为1, 并且文件大小也会重置为0
还有DownloadEntity的getTaskType方法有一些问题, m3u8的下载地址也是http协议, 所以在这方法里会被认为是http任务

测试环境是用的aria simple

**Comment by AriaLyy** [comment]
已找到原因，今晚会上传一个新版本

**Comment by AriaLyy** [comment]
3.8.6 已修复了这个问题
