### ISSUE TITLE
下载失败，重定向url错误

### ISSUE THREAD

**Issue by zhangqilu** [AriaLyy/Aria#611]
## 版本
* 框架版本
   //Aria 下载
    implementation 'com.arialyy.aria:core:3.8.5'
    kapt 'com.arialyy.aria:compiler:3.8.5'
* 系统版本
全部系统

## 错误日志
E/CheckUtil: url【donuts.aigauss.com/doc_fPhW2DBGj3_1578932414.png】错误
    com.arialyy.aria.exception.TaskException: Aria Task Exception:, 下载失败，重定向url错误
    com.arialyy.aria.http.download.HttpDFileInfoTask.handleUrlReTurn(HttpDFileInfoTask.java:311)
    com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:224)
    com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:86)
    com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:98)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
    java.lang.Thread.run(Thread.java:784)

## 重现步骤
http://donuts.aigauss.com/doc_fPhW2DBGj3_1578932414.png

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/74620510-5efe4600-5174-11ea-8ea3-d4aa3b1d1cbc.png)
我这下载是完成正常的呢～～
