### ISSUE TITLE
android 10 组合任务，子任务处理完，不开启下载

### ISSUE THREAD

**Issue by Richard0403** [AriaLyy/Aria#615]
## 版本
* 框架版本
3.8.5
* 系统版本
Android 10
## 错误日志
无错误日志
## 重现步骤

1. 组合任务， 差不多80多个子任务
2. create之后，不能启动下载

使用代码如下（已经注册registe）

`taskId = Aria.download(this)
                .loadGroup(subUrls) //读取下载地址
                .setDirPath(FileUtil.VIDEO_PATH) //设置文件保存的完整路径
                .setSubFileName(subFileNames)
                .unknownSize()
                .ignoreCheckPermissions()
                .ignoreFilePathOccupy()
                .create();   //启动下载`

**Comment by AriaLyy** [comment]
80 个子任务不要使用`.unknownSize()`，要不然会很久才能下载，这个需要获取完成所有子任务大小才会开始下载
