### ISSUE TITLE
点击下载直接崩溃了

### ISSUE THREAD

**Issue by wenwenwen888** [AriaLyy/Aria#616]
## 版本
* 框架版本
3.8

* 系统版本
OPPO K1 Android 8.1.0

## 错误日志
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method c.o2.t.i0.f, parameter task
    at com.xxx.DetailFragment.f(Unknown Source:2)
    at com.xxx.DetailFragment$$DownloadListenerProxy.onTaskFail(SourceFile:2)
    at com.xxx.DetailFragment$$DownloadListenerProxy.onTaskFail(SourceFile:1)
    at com.arialyy.aria.core.scheduler.TaskSchedulers.normalTaskCallback(SourceFile:16)
    at com.arialyy.aria.core.scheduler.TaskSchedulers.handlePreFailTask(SourceFile:17)
    at com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage(SourceFile:2)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:197)
    at android.app.ActivityThread.main(ActivityThread.java:7022)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

## 重现步骤
测试人员反馈点击下载就崩了，看了测试视频确实如此，暂不明确重现步骤，其他机型暂时没发现问题

**Comment by AriaLyy** [comment]
看这个 https://github.com/AriaLyy/Aria/issues/613

**Comment by wenwenwen888** [comment]
@AriaLyy 你好，刚才我也查过这个issue，我这边使用的是一个参数的fail
是指下面这个方法吧？
···
@Download.onTaskFail
fun taskFail(task: DownloadTask) {
}
···

**Comment by AriaLyy** [comment]
好的，你是使用3.8还是3.8.5版本？

**Comment by wenwenwen888** [comment]
3.8
```
implementation 'com.arialyy.aria:core:3.8'
kapt 'com.arialyy.aria:compiler:3.8'
```

**Comment by AriaLyy** [comment]
这应该是检查阶段出现的错误，后面我再增加一个专门处理检查阶段出错的注解。
你现在可以先升级到`3.8.5`，再3.8.5中，是有一个空的判断
![image](https://user-images.githubusercontent.com/10437293/74632769-1b6b0280-519b-11ea-8a0e-a38cfb760728.png)

**Comment by wenwenwen888** [comment]
好的，谢谢

**Comment by topab** [comment]
@AriaLyy 版本号>= 3.8.10 好像也出现这个问题了，具体版本不知道，因为我最开始使用这个的时候是3.8.10

**Comment by topab** [comment]
09-23 10:20:39.570 19988 19988 E AndroidRuntime: FATAL EXCEPTION: main
14109-23 10:20:39.570 19988 19988 E AndroidRuntime: Process: **, PID: 19988
14209-23 10:20:39.570 19988 19988 E AndroidRuntime: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter task
14309-23 10:20:39.570 19988 19988 E AndroidRuntime: at FileActivity.taskFail(Unknown Source:2)
14409-23 10:20:39.570 19988 19988 E AndroidRuntime: at FileActivity$$DownloadListenerProxy.onTaskFail(FileActivity$$DownloadListenerProxy.java:25)
14509-23 10:20:39.570 19988 19988 E AndroidRuntime: at FileActivity$$DownloadListenerProxy.onTaskFail(FileActivity$$DownloadListenerProxy.java:12)
14609-23 10:20:39.570 19988 19988 E AndroidRuntime: at com.arialyy.aria.core.scheduler.TaskSchedulers.normalTaskCallback(TaskSchedulers.java:467)
14709-23 10:20:39.570 19988 19988 E AndroidRuntime: at com.arialyy.aria.core.scheduler.TaskSchedulers.handlePreFailTask(TaskSchedulers.java:391)
14809-23 10:20:39.570 19988 19988 E AndroidRuntime: at com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage(TaskSchedulers.java:179)
14909-23 10:20:39.570 19988 19988 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
15009-23 10:20:39.570 19988 19988 E AndroidRuntime: at android.os.Looper.loop(Looper.java:219)
15109-23 10:20:39.570 19988 19988 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8347)
15209-23 10:20:39.570 19988 19988 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
15309-23 10:20:39.570 19988 19988 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
15409-23 10:20:39.570 19988 19988 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by topab** [comment]
![image](https://user-images.githubusercontent.com/60641837/94131021-058b9180-fe90-11ea-837a-3d472c977821.png)
jeitu截图好像好看点

**Comment by topab** [comment]
方法是这个
@Download.onTaskFail
    fun taskFail(task: DownloadTask) {
}

**Comment by AriaLyy** [comment]
@topab url 地址麻烦给下哈

**Comment by topab** [comment]
![image](https://user-images.githubusercontent.com/60641837/94148296-04b32980-fea9-11ea-8e26-a0ad48eb9d18.png)
@AriaLyy  
您好，我这边也不知道具体怎么触发的，我这边看到日志打印这个文件地址已贴出，感谢。感觉复制的日志太难看了，我贴的图片。
https://api.sdccx.cn/files/officeFiles/176-采购201910y.doc

**Comment by taichushouwang** [comment]
@topab 把
```
fun taskFail(task: DownloadTask) {
}
```

```
fun taskFail(task: DownloadTask?) {
}
```
就是将参数改成**可空类型**

@AriaLyy 我看了一下这两位的问题好像都是因为用的是kotlin的写法，然后他们的参数都是写成不能为空，但是你这个回调里面，一般出错的话，DownloadTask都会返回空，所以就会报这个错误。
