### ISSUE TITLE
下载的任务队列可能有误

### ISSUE THREAD

**Issue by cblsyp** [AriaLyy/Aria#620]
## 版本
* 框架版本
3.8.7-beta-1

情况说明： 
A:
新建十个任务   设置同时在线的任务为3   now模式
1.开始三个任务正常下载   
2.暂停第三个  第四个开始下载
3.第一 四集  下好  第五  第六  然后依次下载  
正常   

B:（任务队列的管理有点问题  ）   now  模式
新建十个任务   设置同时在线的任务为3  
1.开始三个任务正常下载   
2.暂停第三个  第四个开始下载
3.然后让第三个重新下载 执行Resume   第三个的任务状态变为  等待中 

第一 第二  第四 下载完成     

6 7 8   正在下载中  此时任务三在等待中  

第六任务下载好了 之后 第七  第八任务自动暂停了（测试第7 8 任务还没有下载完成）     然后三个任务  也就是刚才暂停 然后执行了resume的任务继续下载   下载完成之后  第7 8 仍然是暂停的状态   然后9以后的任务都处于等待中  

不正常   

区别  情况B  中的任务三执行了resume方法

**Comment by cblsyp** [comment]
补充一点  在我的任务队列中  返现 任务12竟然下好了  。  上面的十个任务是例子。  我一共下载了15.  执行的队列和缓冲的队列除了问题。

**Comment by AriaLyy** [comment]
使用`3.8.7-beta-2`，开启wait模式，使用resume(true) 恢复任务
