### ISSUE TITLE
创建任务失败一般都有什么原因呢？taskId = -1

### ISSUE THREAD

**Issue by ifmvo** [AriaLyy/Aria#621]
`
val taskId = Aria.download(this)
            .load("https://scontent-hkg3-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/85181655_2632630233678700_3953168513589642656_n.jpg?_nc_ht=scontent-hkg3-1.cdninstagram.com&_nc_cat=104&_nc_ohc=utA6GzF1dXcAX-OPr8T&oh=2e60a238ea4245bc384ccfa94697393b&oe=5E7FF882")     //读取下载地址
            .setFilePath(Constant.Path.Save_Path_Phone + "123.png") //设置文件保存的完整路径
            .create()

        logi(tag, "添加ID：$taskId")
`

**Comment by windfone** [comment]
你这个问题怎么解决的，我有时候会一直这样
