### ISSUE TITLE
请问这个异常为什么出现？

### ISSUE THREAD

**Issue by 951AB159BA** [AriaLyy/Aria#624]
2020-02-26 11:14:05.240 4849-4937/com.umeye.demo E/M3U8Listener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    读取M3U8信息失败，读取不到#EXTM3U标签

这个标签是有的#EXTM3U

我看切片都下载成功和切片完成，但是我看到有些几行写着M3U8VodLoader: 记录为空或记录已完成

**Comment by AriaLyy** [comment]
地址能否提供下？
