### ISSUE TITLE
重启恢复下载M3U8提示没协议

### ISSUE THREAD

**Issue by 748297973** [AriaLyy/Aria#626]
## 版本
* 框架版本
3.8.6
* 系统版本
Android 10
## 错误日志

 E/>>>K8Movies: [ (DownloadingItemList.java:63)#initView ] state = 0
 E/>>>K8Movies: [ (DownloadingItemList.java:88)#onPre ] ========>准备
 E/M3U8Listener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    no protocol: 1000k/hls/index.m3u8
    com.arialyy.aria.m3u8.M3U8InfoTask.failDownload(M3U8InfoTask.java:356)
    com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:106)
    com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:147)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
    java.lang.Thread.run(Thread.java:919)
    ===================================================
 E/>>>K8Movies: [ (DownloadingItemList.java:128)#taskFail ] ========>下载失败 : com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
no protocol: 1000k/hls/index.m3u8
`### **补充**
Demo也会出现
com.arialyy.simple E/M3U8Listener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    地址错误，请使用IVodTsUrlConverter处理你的url信息
    com.arialyy.aria.m3u8.vod.M3U8VodLoader$4.onSucceed(M3U8VodLoader.java:519)
    com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:201)
    com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:104)
    com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:143)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
    java.lang.Thread.run(Thread.java:919)
    ===================================================

## 重现步骤

1.码率转换器和Ts转换器设置好,正常解析下载
2.退出App再进入开始任务就这样了

**Comment by AriaLyy** [comment]
检查你的Ts转换器是否被回收了

**Comment by 748297973** [comment]
demo中也这样

**Comment by 748297973** [comment]
> 检查你的Ts转换器是否被回收了

demo中也这样

**Comment by 748297973** [comment]
> > 检查你的Ts转换器是否被回收了
> 
> demo中也这样

我的错误是这个
E/>>>K8Movies: [ (DownloadingItemList.java:128)#taskFail ] ========>下载失败 : com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
no protocol: 1000k/hls/index.m3u8

**Comment by 748297973** [comment]
是有问题还是Ts转换器被回收了

**Comment by 748297973** [comment]
> 检查你的Ts转换器是否被回收了

是有问题还是Ts转换器被回收了

**Comment by AriaLyy** [comment]
m3u8 地址发我看看

**Comment by 748297973** [comment]
> m3u8 地址发我看看

https://v1.szjal.cn/20190819/Ql6UD1od/index.m3u8

**Comment by 748297973** [comment]
> > m3u8 地址发我看看
> 
> https://v1.szjal.cn/20190819/Ql6UD1od/index.m3u8



> m3u8 地址发我看看

最终的是`https://v1.szjal.cn/ppvod/A0C8AE2D9866B973BEF3DF557653C37D.m3u8`这样的
demo中你的连接也是这样

**Comment by AriaLyy** [comment]
恢复任务那也加上转换器

**Comment by 748297973** [comment]
> 恢复任务那也加上转换器

感谢
