### ISSUE TITLE
注解不生效

### ISSUE THREAD

**Issue by 578618770wts** [AriaLyy/Aria#627]
## 版本 3.8.6
* 框架版本

* 系统版本

## 重现步骤

1.关于Aria注解不生效，Aria版本为3.8.6
2.按照文档要求5.1：
**a.首先工程中没有使用apply plugin: 'android-apt'**
![image](https://user-images.githubusercontent.com/11731695/75618559-3b42f300-5bab-11ea-8907-f6a1def6c799.png)
**b.版本一致，都是3.8.6**
![image](https://user-images.githubusercontent.com/11731695/75618565-50b81d00-5bab-11ea-8add-085c29da77fc.png)
**c.没有打印错误日志**
`没有打印错误日志，同时也加了 javaCompileOptions {
      annotationProcessorOptions {
        includeCompileClasspath true
      }
    }`
![image](https://user-images.githubusercontent.com/11731695/75618589-9ffe4d80-5bab-11ea-900d-58b4f4bbafcf.png)
**使用的是Java，同时也在下载的页面进行了注册**
![image](https://user-images.githubusercontent.com/11731695/75618603-bdcbb280-5bab-11ea-9bf7-83b88f4d8553.png)
** 下载完成，但是没有执行回调**
![image](https://user-images.githubusercontent.com/11731695/75618608-cf14bf00-5bab-11ea-84b1-817a825daa9a.png)
最后有报这个错
![image](https://user-images.githubusercontent.com/11731695/75622483-c0460080-5bdb-11ea-8b2e-fbbad5a5ddb0.png)
但是为什么会没有配置文件呢，我的版本是一致的呀，只有版本不一致的时候才会生成配置文件出错呀？
请问是什么问题呢？

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html

**Comment by CattleFoot** [comment]
我也遇到类似问题，在debug模式apk情况下是ok的，但是用release包跑的话则没有Aria的注解方法，我是封装了个工具类，以lib的形式依赖到主module app的。

**Comment by equationl** [comment]
遇到和楼主一摸一样的问题，唯一不同的是我没有报找不到配置文件的错误。
查阅编译输出发现如下信息：
`> Configure project :app
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.github.bumptech.glide:compiler:4.11.0', 'com.arialyy.aria:compiler:3.8.6'.`

按照提示将annotationProcessor换为kapt成功解决该问题。
需要注意的是，我的项目是kotlin和java混用，aria下载相关的代码使用的是java实现的，所以为啥也需要换成kapt我也不太明白，但或许可以参考这个：[Android project with Java and Kotlin files, kapt or annotationProcessor?](https://stackoverflow.com/questions/50027741/android-project-with-java-and-kotlin-files-kapt-or-annotationprocessor)
