### ISSUE TITLE
组合任务问题

### ISSUE THREAD

**Issue by zxianwei** [AriaLyy/Aria#634]
* 框架版本
3.8.6

* 系统版本
android 9.0
## 错误日志

无
## 重现步骤
1.使用组合任务下载，启动了多个组合任务，有的组合任务到达99%的时候就不会继续走了，其实文件已经下载好了(打开文件看的文件大小确认的)；还有一个问题当退出App后一个组合里有一个子任务是没有完成，再次进入App但是无法查到这个子任务的状态了，就是说这个子任务停在哪里了没法启动。

**Comment by AriaLyy** [comment]
已知问题，使用3.8.7-beta-5

**Comment by zxianwei** [comment]
上述问题没有复现，现在不知是不3.8.7-beta-5版本的问题，我每次获取组合任务id总是得到1或者2或者-1，步骤：相同url下载放入不同文件夹中就会出现这个问题。
