### ISSUE TITLE
FTP上传过程中断开网络，网络正常后重新start当前任务（断网时正在上传的任务），上传异常，重试失败。错误码为：150, msg：150 Opening data channel for file upload to server of “”

### ISSUE THREAD

**Issue by weixutong** [AriaLyy/Aria#636]
## 版本
* 框架版本
3.66
* 系统版本
8.0
## 错误日志

2020-03-12 08:25:33.827 8448-8588/com.gs_file_transfer:FTPUpload E/AbsThreadTask: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaIOException: 文件上传错误，错误码为：150, msg：150 Opening data channel for file upload to server of "/disk0/2020-03-12/a.mp4", restarting at offset 3768347
    , filePath: /sdcard/DCIM/a.mp4
    IOException caught while copying.
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.upload(FtpThreadTask.java:167)
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:86)
    com.arialyy.aria.core.upload.uploader.FtpThreadTask.call(FtpThreadTask.java:38)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    java.lang.Thread.run(Thread.java:764)
    ===================================================

## 重现步骤

1.ftp正常上传中突然断网
2.断网时cancel任务
3.联网后重新start任务,上传失败。异常信息 ：com.arialyy.aria.exception.AriaIOException: 文件上传错误，错误码为：150, msg：150 Opening data channel for file upload to server of “”

**Comment by AriaLyy** [comment]
这个是服务器那边的问题，一般是上传是出现的情况，原因是，你断网了，但是服务器器端那边却没有及时断开链接，导致文件被占用者，无法被其它线程写入，然后你重新上传，就会出现这个问题。
解决方法：
修改上传文件的名字
