### ISSUE TITLE
m3u8 任务 并没有记载已下载大小，

### ISSUE THREAD

**Issue by z376368673** [AriaLyy/Aria#637]
m3u8 任务 下载中 ，退出app 后再进来 获取任务 当前currentProgress = 0 
应该记录退出时 已下载的大小  不然恢复任务后 无法知道已下载多少了

## 版本
* 框架版本

* 系统版本

**Comment by AriaLyy** [comment]
是做了处理的，5s中保存一次记录

**Comment by z376368673** [comment]
中间过程不管几秒保存一次 ，为了性能你有你的考虑 ，但是：
 当任务 暂停时  一定要保存一次 已下载的文件大小 ，
当任务 完成时  一定要保存一次 已下载的文件大小  和 文件总大小

**Comment by AriaLyy** [comment]
你说的这些都是做了的，但是我不会保存每个切片暂定时的进度，因为绝大多数情况下，切片都很小

**Comment by z376368673** [comment]
E/ContentValues: updateState:currentProgress = 60479157
E/ContentValues: updateState:Progress = 80
E/ContentValues: 你点击了暂停任务
E/ContentValues: updateState:currentProgress = 60479157
E/ContentValues: updateState:Progress = 0
E/ContentValues: 你点击了恢复任务
E/ContentValues: updateState:currentProgress = 60479157
E/ContentValues: updateState:Progress = 0
这是我加的输出日志，
  @Download.onTaskRunning
    fun taskRunning(task: DownloadTask) {
        Log.e(ContentValues.TAG, "updateState:currentProgress = " + task.downloadEntity.currentProgress)
        Log.e(ContentValues.TAG, "updateState:Progress = " +  task.downloadEntity.percent)
        adapter.updateState(task.entity)
    }

重新开启后 percent = 0 了 
而且 currentProgress 数值不对了 本来40多兆的文件 结果 currentProgress  累计到 60多兆了

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/597 速度为0可能和转换器有关系

**Comment by AriaLyy** [comment]
可以使用`3.8.10`版本，增加了默认的转换器
