### ISSUE TITLE
Bugly上传的错误

### ISSUE THREAD

**Issue by GXSZone** [AriaLyy/Aria#638]
## 版本
* 框架版本 3.8.6

* 系统版本
5.1.1   6.0    8.1.0
### 错误一

`
**Attempt** to invoke interface method 'int java.util.List.size()' on a null object reference
com.arialyy.aria.core.common.RecordHelper.handleBlockRecord(Unknown Source:16)

1 com.arialyy.aria.core.common.RecordHelper.handleBlockRecord(Unknown Source:16)
2 com.arialyy.aria.http.HttpRecordHandler.handlerTaskRecord(Unknown Source:28)
3 com.arialyy.aria.core.common.RecordHandler.getRecord(Unknown Source:61)
4 com.arialyy.aria.core.loader.NormalLoader.startThreadTask(Unknown Source:67)
5 com.arialyy.aria.core.loader.NormalLoader$1.onSucceed(Unknown Source:2)
6 com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(Unknown Source:800)
7 com.arialyy.aria.http.download.HttpDFileInfoTask.run(Unknown Source:67)
8 com.arialyy.aria.core.loader.NormalLoader.handleTask(Unknown Source:15)
9 com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(Unknown Source:29)
10 com.arialyy.aria.core.loader.AbsNormalLoader.run(Unknown Source:37)
11 java.lang.Thread.run(Thread.java:764)
`
### 错误二
`
**Attempt** to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference

com.arialyy.aria.m3u8.M3U8InfoTask.handleBandWidth(Unknown Source:20)
1 com.arialyy.aria.m3u8.M3U8InfoTask.handleBandWidth()
2 com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect()
3 com.arialyy.aria.m3u8.M3U8InfoTask.run()
4 com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask()
5 com.arialyy.aria.core.loader.AbsNormalLoader.startFlow()
6 com.arialyy.aria.core.loader.AbsNormalLoader.run()
7 java.lang.Thread.run(Thread.java:818)

`
### 错误三
`
**java.lang.NullPointerException**
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

1 com.arialyy.aria.m3u8.vod.VodRecordHandler.handlerTaskRecord()
2 com.arialyy.aria.core.common.RecordHandler.getRecord()
3 com.arialyy.aria.m3u8.vod.M3U8VodLoader.startThreadTask()
4 com.arialyy.aria.m3u8.vod.M3U8VodLoader.access$2500()
5 com.arialyy.aria.m3u8.vod.M3U8VodLoader$4.onSucceed()
6 com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect()
7 com.arialyy.aria.m3u8.M3U8InfoTask.run()
8 com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask()
9 com.arialyy.aria.core.loader.AbsNormalLoader.startFlow()
10 com.arialyy.aria.core.loader.AbsNormalLoader.run()
11 java.lang.Thread.run(Thread.java:818)

###ANR
AppFreeze!

**com.arialyy.aria.util.CommonUtil.java.lang.String getFileMD5(java.io.InputStream)(CommonUtil.java:5)**

libcore.io.Linux.readBytes(Native Method)
2 libcore.io.Linux.read(Linux.java:184)
3 libcore.io.BlockGuardOs.read(BlockGuardOs.java:254)
4 libcore.io.IoBridge.read(IoBridge.java:501)
5 java.io.FileInputStream.read(FileInputStream.java:307)
6 java.io.FileInputStream.read(FileInputStream.java:276)
7 com.arialyy.aria.util.CommonUtil.java.lang.String getFileMD5(java.io.InputStream)(CommonUtil.java:5)
8 com.arialyy.aria.util.CommonUtil.java.lang.String getFileMD5(java.io.File)(CommonUtil.java:2)
9 com.movies.k8.adapter.setting.view.item.DownloadingItemList.void taskComplete(com.arialyy.aria.core.task.DownloadTask)(DownloadingItemList.java:1)
10 com.movies.k8.adapter.setting.view.item.DownloadingItemList$$DownloadListenerProxy.void onTaskComplete(com.arialyy.aria.core.task.DownloadTask)(DownloadingItemList$$DownloadListenerProxy.java:2)
11 com.movies.k8.adapter.setting.view.item.DownloadingItemList$$DownloadListenerProxy.void onTaskComplete(com.arialyy.aria.core.task.ITask)(DownloadingItemList$$DownloadListenerProxy.java:1)

`

## 重现步骤

bugly上传,无从下手

**Comment by AriaLyy** [comment]
可以使用 3.8.7-beta-8

**Comment by 748297973** [comment]
@AriaLyy 谢谢

**Comment by 748297973** [comment]
@AriaLyy 
` Task :app:compileDebugJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: compiler-3.8.7-beta-8.jar (com.arialyy.aria:compiler:3.8.7-beta-8).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
注: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]

FAILURE: Build failed with an exception.

 What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
 java.lang.NoClassDefFoundError: com/arialyy/annotations/Download$onWait
`

**Comment by AriaLyy** [comment]
好的，我明天重新上传下看看
