### ISSUE TITLE
下载 m3u8 完成后的文件是什么格式？

### ISSUE THREAD

**Issue by wangkunlin** [AriaLyy/Aria#639]
作者，你好，我还没试用这个库，我的需求是 下载 m3u8 后，希望能存储成 mp4 或者 mp3 格式的。请问，这块需求能实现么？还是说要自己做转码？

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/download/m3u8_live.html#11%E3%80%81%E8%87%AA%E5%8A%A8%E5%90%88%E5%B9%B6ts%E6%96%87%E4%BB%B6

手动合并或自动合并就是了

**Comment by wangkunlin** [comment]
我试用了 m3u8 的下载，发现一个问题，我要下载的 playlist 文件是 gzip 压缩过的，但用 Aria 下载后，没有判断 header ，就直接读取 body 了。所以导致下载失败了。
![image](https://user-images.githubusercontent.com/8307768/76740097-45b6dc80-67a8-11ea-81e8-51a7aaf7955c.png)

**Comment by wangkunlin** [comment]
版本是 3.8.5

**Comment by AriaLyy** [comment]
你的header是做什么作用的？能否提供下url给我测试？

**Comment by wangkunlin** [comment]
就是 我的 response 的body 是 经过 gzip 压缩的，我的意思是 你看截图的代码，读取 body 的时候，没有先判断 response 的 header，直接读取的，不经过 gzip 解压缩，肯定是读取失败的.

**Comment by AriaLyy** [comment]
`3.8.12`已修复了这个问题
