### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by yangshaopeng** [AriaLyy/Aria#64]
异步下载任务的时候建议用线程池提高效率。

**Comment by AriaLyy** [comment]
任务的下载是使用线程池的
DownloadUtil有这么一段代码
```java
SingleThreadTask task = new SingleThreadTask(CONSTANCE, mListener, entity);
    mTask.put(0, task);
    mFixedThreadPool.execute(task);
```

**Comment by yangshaopeng** [comment]
开始下载的时候我看走的是这个流程。
/**
 * 多线程断点续传下载文件，开始下载
 */
@Override public void startDownload() {
  CONSTANCE.cleanState();
  mListener.onPre();
  new Thread(this).start();
}
      还有个问题请教一下：在监听下载进度的时候，是用@Download.onTaskRunning,那他的参数是写死的吗？必须是写下载路径吗？有没有比较灵活的方法？

**Comment by AriaLyy** [comment]
那个只是获取文件信息的请求而已，不涉及到下载部分
你也可以通过你的下载信息来判断，DownloadEntity包括了你所有的下载信息
```
@Download.onTaskRunning
void test(DownloadTask task){
  DownlaodEntity entity = task.getEntity();
}
```

**Comment by yangshaopeng** [comment]
嗯  好   回复速度很给力

**Comment by AriaLyy** [comment]
:smile:

**Comment by yangshaopeng** [comment]
你有在项目中用这个框架吗？效果怎么样啊

**Comment by AriaLyy** [comment]
在一个游戏管理的项目中用，效果还行，半年来在生产环境上没出现过太大的问题，下载部分还没有被用户投诉过

**Comment by yangshaopeng** [comment]
准备在项目中用一下，主要是下载模块。
谢谢作者做出的贡献啊。

**Comment by AriaLyy** [comment]
感谢支持:blush:
