### ISSUE TITLE
DownGroup下载不回调onstart

### ISSUE THREAD

**Issue by DaveBoy** [AriaLyy/Aria#641]
3.8.7-beta-8

**Comment by DaveBoy** [comment]
AbsGroupLoaderUtil 中重写了方法  但是相对于AbsNormalLoaderUtil来说，缺少某些回调方法的调用，如mListener.onPre();

**Comment by AriaLyy** [comment]
已经新加了，以前是所有的util都继承AbsNormalLoaderUtil，后面重构，将其分开了后，忘记加了。。。
