### ISSUE TITLE
在Kotlin下无法正常编译

### ISSUE THREAD

**Issue by leveychen** [AriaLyy/Aria#642]
问题描述：
无法正常编译

## 版本
* 框架版本
````kotlin
apply plugin: 'kotlin-kapt'
implementation 'com.arialyy.aria:core:3.8.6'
kapt 'com.arialyy.aria:compiler:3.8.6'
````
* 系统版本
````kotlin
Android Studio 3.6.1
Kotlin 1.3.71
Gradle build plugin 3.6.1
Gradle 5.6.4
````

````kotlin
  //已在Activity中注册和注解监听
Aria.download(this).register()

@Download.onTaskRunning
fun onRunning(task:DownloadTask){
    S.log("onRunning = " + task.key)
}
@Download.onTaskComplete
fun onComplete(task:DownloadTask){
    S.log("onComplete = " + task.filePath)
}
````
## 错误日志

编译错误:

build的时候提示了这个，然后出现了下图的错误
````kotlin
> Task :app:kaptDebugKotlin
[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.arialyy.compiler.AriaProcessor (NON_INCREMENTAL).
````
![image](https://user-images.githubusercontent.com/3397361/77856708-8d6b4880-722b-11ea-818e-bd923771b67a.png)

错误乱码了，似乎是继承了 android.app.activity 导致的
编译生成的代理文件
[MainActivity$DownloadListenerProxy.txt](https://github.com/AriaLyy/Aria/files/4399420/MainActivity.DownloadListenerProxy.txt)

## 重现步骤

1. 编译必现

## 特殊说明
当使用annotationProcessor 时
````kotlin
annotationProcessor 'com.arialyy.aria:compiler:3.8.6'
````
正常编译，下载功能可用(可以正确的下载到文件)，但注解监听也无法使用

**Comment by DaveBoy** [comment]
我这边kt能正常使用呢。
使用annotationProcessor注解无效是因为没有生成代理类吧 。。。kt项目中只能用kapt

**Comment by leveychen** [comment]
> 我这边kt能正常使用呢。
> 使用annotationProcessor注解无效是因为没有生成代理类吧 。。。kt项目中只能用kapt

我这边使用kapt，项目直接编译不了，提示上图错误

**Comment by AriaLyy** [comment]
参考下这个：https://stackoverflow.com/a/57680406/5221528

**Comment by leveychen** [comment]
> 参考下这个：https://stackoverflow.com/a/57680406/5221528

这个没有效果，问题依旧

**Comment by leveychen** [comment]
> 参考下这个：https://stackoverflow.com/a/57680406/5221528

当前版本支持不用注解而是全局回调么？

**Comment by AriaLyy** [comment]
支持的，gradle版本是多少？

**Comment by leveychen** [comment]
> 支持的，gradle版本是多少？

gradle-5.6.4-all

**Comment by LeonShannon** [comment]
试试将annotationProcessor，改为kapt
