### ISSUE TITLE
http上传即使设置了task.cancel(false)还是把本地文件删除了

### ISSUE THREAD

**Issue by vinsonien** [AriaLyy/Aria#646]
## 版本
* 框架版本
3.8.6
* 系统版本
android 10 手机华为mate20
## 重现步骤

1.创建一个http普通的上传任务，本地文件来自相册的MP4文件
2.@Upload.onTaskStart回调后 我断开网络（目的为了触发上传错误）
3.@Upload.onTaskFail 回调后我调用Aria.upload(c).load(taskToEntity.getId()).cancel(false);
4.发现本地文件被删除了 
后来发现 即使调用 .cancel(false); .cancel(true);.cancel();.removeAllTask(); 都会把我本地文件删除
5.不过正常流程 @Upload.onTaskComplete回调后 调用Aria.upload(c).load(taskToEntity.getId()).cancel(false);并没有删除本地文件的现象

**Comment by AriaLyy** [comment]
已知问题，后面版本会修复

**Comment by vinsonien** [comment]
好的，感谢，期待新的版本

**Comment by AriaLyy** [comment]
`3.8.10`1已修复了这个问题
