### ISSUE TITLE
网速正常，但是下载速度很慢，200多兆的视频要下半个多小时

### ISSUE THREAD

**Issue by SZJing** [AriaLyy/Aria#647]
网速正常，但是下载速度很慢，200多兆的视频要下半个多小时。设置成不限下载速度，可是还是下载的很慢。

**Comment by AriaLyy** [comment]
这要看你资源的速度，我自己测试速度是正常的

**Comment by SZJing** [comment]
谢谢，我测试了，同样的资源，我用自带的浏览器下载也比较慢，只有迅雷下载快些。看来应该就是资源的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午8:40
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"嘿"<1345014056@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 网速正常，但是下载速度很慢，200多兆的视频要下半个多小时 (#647)





 
这要看你资源的速度，我自己测试速度是正常的
