### ISSUE TITLE
请问在使用ftp下载的时候提示：遇到【ECONNREFUSED-连接被服务器拒绝】错误，是什么原因造成的呢？

### ISSUE THREAD

**Issue by Amoour** [AriaLyy/Aria#649]
## 版本
* 框架版本
3.8.6
* 系统版本
9.0
## 错误日志

2020-04-07 18:29:51.435 19107-19349/com.example.ftptestdemo W/FtpDFileInfoTask: 遇到[ECONNREFUSED-连接被服务器拒绝]错误，已没有其他地址，链接失败；如果是ftps，请检查端口是否使用了ftp的端口而不是ftps的端口
2020-04-07 18:29:51.444 19107-19349/com.example.ftptestdemo E/BaseDListener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaFTPException: Aria SFTP Exception:
    创建ftp客户端失败
    com.arialyy.aria.ftp.AbsFtpInfoTask.failDownload(AbsFtpInfoTask.java:331)
    com.arialyy.aria.ftp.AbsFtpInfoTask.createFtpClient(AbsFtpInfoTask.java:149)
    com.arialyy.aria.ftp.AbsFtpInfoTask.run(AbsFtpInfoTask.java:94)
    com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:98)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
    java.lang.Thread.run(Thread.java:764)
    ===================================================
2020-04-07 18:29:51.445 19107-19107/com.example.ftptestdemo D/DTaskQueue: 从执行池删除任务【100MB】成功

## 重现步骤

1.在点击下载的时候出现问题
2.在使用FileZilla测试的时候，提示该服务器不支持ftp over TLS 
3.在选择了加密方式为只使用明文FTP后可以正常连接操作，请问在Aria中有办法可以设置吗？
4.

**Comment by AriaLyy** [comment]
提示这个原因一般是无法连接到服务器
提示该服务器不支持ftp over TLS，应该是服务器端不支持ftps导致的

**Comment by Amoour** [comment]
那么安卓端能不能像FileZilla那样选择明文FTP后可以正常连接操作呢？

**Comment by Amoour** [comment]
> 提示这个原因一般是无法连接到服务器
> 提示该服务器不支持ftp over TLS，应该是服务器端不支持ftps导致的

**Comment by Amoour** [comment]
> 提示这个原因一般是无法连接到服务器
> 提示该服务器不支持ftp over TLS，应该是服务器端不支持ftps导致的
那么安卓端能不能像FileZilla那样选择明文FTP后可以正常连接操作呢？
