### ISSUE TITLE
对于不支持ftp over tls的服务器，是否可以增加明文ftp传输方式呢?

### ISSUE THREAD

**Issue by Amoour** [AriaLyy/Aria#650]
对于不支持ftp over tls的服务器，导致连接被拒绝，是否可以增加明文ftp传输方式呢?

**Comment by AriaLyy** [comment]
这个就是ftps，ftps参考https://aria.laoyuyu.me/aria_doc/api/ftp_params.html#%E4%BA%8C%E3%80%81ftps
