### ISSUE TITLE
项目混淆后所有任务组的子任务回调失效，不混淆就没问题

### ISSUE THREAD

**Issue by peakjing** [AriaLyy/Aria#654]
你好！

框架版本：3.8.6
系统版本：android6.0

没有任何错误日志

## 重现步骤
1.按文档正确配置混淆文件
2.混淆代码
3.下载文件，onSubTaskPre  。。。 onSubTaskComplete 所有任务组子任务回调都会失效，不混淆就没问题
4.同样混淆情况下，非子任务回调 onPre 。。。onTaskComplete都没问题

**Comment by DaveBoy** [comment]
明天我帮你测试一下看看

**Comment by DaveBoy** [comment]
找了半天。。。。原来是sub生成的代理类没加入keep
-keep class **$$DGSubListenerProxy{ *; }

**Comment by DaveBoy** [comment]
@AriaLyy 更新一下混淆规则

**Comment by AriaLyy** [comment]
@DaveBoy 👌

**Comment by peakjing** [comment]
谢谢！～

**Comment by AlceZhang** [comment]
我的情况跟你一样。版本3.6.5的，加上还是一样。没有任何错误日志 混淆完就不行了，没回调

**Comment by huangxiaoyu** [comment]
> 我的情况跟你一样。版本3.6.5的，加上还是一样。没有任何错误日志 混淆完就不行了，没回调

我的也是   我的gradle是4.1.1   另一个项目3.6.1的可以
