### ISSUE TITLE
关于在Service中使用的问题

### ISSUE THREAD

**Issue by colaly** [AriaLyy/Aria#655]
## 版本
* 框架版本 3.8.6
继承Service的DownloadService可以实现下载回调，但是继承IntentService的DownloadIntentService在下载过程中没有执行下载回调，是不支持IntentService这种子类吗？

**Comment by AriaLyy** [comment]
首先，你需要清楚IntentService的工作机制，其次你需要确认在进行回调的时候，IntentService是否已经被销毁了，如果IntentService已经被销毁了，是不会执行回调的。

**Comment by colaly** [comment]
用IntentService的目的只是为了偷懒，不想手动的在任务结束的时候手动的去结束掉Service。在用IntentService的时候控制台有下载相关的log,但是就是没有执行回调。
