### ISSUE TITLE
测试5G下载速度

### ISSUE THREAD

**Issue by Amoour** [AriaLyy/Aria#656]
## 版本 
* 框架版本
3.86
* 系统版本
10
## 错误日志

在测试5G下载速度的时候，当速度超过1024mb/s时，task.getSpeed()返回的值为负的

## 重现步骤

1.
2.
3.
4.

**Comment by DaveBoy** [comment]
莫得5g，反向debug一下康康

**Comment by AriaLyy** [comment]
能否提供更详细的日志？代码zs中是已经做了判断的，我测试CommonUtil.formatFileSize()这个方法，是可以正常格式化进度的。
![image](https://user-images.githubusercontent.com/10437293/79625235-2372fe80-815a-11ea-9ce3-013070778803.png)
