### ISSUE TITLE
header没有存储到数据库吗？

### ISSUE THREAD

**Issue by EvlinLee** [AriaLyy/Aria#66]
之前提了个issue，#[11](https://github.com/AriaLyy/Aria/issues/11)，关于增加header的，但是看到DownloadEntity没有相应的字段。如果下载暂停了，退出程序后进来恢复下载是否就无法下载了呢？

**Comment by AriaLyy** [comment]
感谢反馈，header后续版本真增加保存到数据库的功能

**Comment by AriaLyy** [comment]
compile 'com.arialyy.aria:aria-core:3.2.6'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.6'
新版本已经支持head的保存了
