### ISSUE TITLE
Bug 反馈

### ISSUE THREAD

**Issue by FlashQin** [AriaLyy/Aria#664]
android.database.sqlite.SQLiteCantOpenDatabaseException
unable to open database file (Sqlite code 14), (OS error - 24:Too many open files)

com.arialyy.aria.orm.DelegateUpdate.updateData(DelegateUpdate.java:64)

**Comment by AriaLyy** [comment]
3.8.8 已修复了这个问题

**Comment by alee1970** [comment]
Cursor window allocation of 2048 kb failed.
com.arialyy.aria.orm.DelegateFind.exeNormalDataSql(DelegateFind.java:441)

android.database.CursorWindow.<init>(CursorWindow.java:108)
android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
com.arialyy.aria.orm.DelegateFind.exeNormalDataSql(DelegateFind.java:441)
com.arialyy.aria.orm.DelegateFind.findData(DelegateFind.java:340)
com.arialyy.aria.orm.DelegateWrapper.findData(DelegateWrapper.java:137)
com.arialyy.aria.orm.DbEntity.findFirst(DbEntity.java:178)
com.arialyy.aria.util.RecordUtil.delTaskRecord(RecordUtil.java:231)
com.arialyy.aria.core.listener.BaseUListener.handleCancel(BaseUListener.java:42)
com.arialyy.aria.core.listener.BaseListener.saveData(BaseListener.java:186)
com.arialyy.aria.core.listener.BaseListener.onCancel(BaseListener.java:110)
com.arialyy.aria.core.loader.AbsNormalLoader.cancel(AbsNormalLoader.java:233)
com.arialyy.aria.core.loader.AbsNormalLoaderUtil.cancel(AbsNormalLoaderUtil.java:77)
com.arialyy.aria.core.task.AbsTask.cancel(AbsTask.java:264)
com.butel.redcross.lib.ftp.FtpService.taskFail(FtpService.java:166)
com.butel.redcross.lib.ftp.FtpService$$UploadListenerProxy.onTaskFail(FtpService$$UploadListenerProxy.java:45)
com.butel.redcross.lib.ftp.FtpService$$UploadListenerProxy.onTaskFail(FtpService$$UploadListenerProxy.java:12)
com.arialyy.aria.core.scheduler.TaskSchedulers.normalTaskCallback(TaskSchedulers.java:457)
com.arialyy.aria.core.scheduler.TaskSchedulers.normalTaskCallback(TaskSchedulers.java:416)
com.arialyy.aria.core.scheduler.TaskSchedulers.handleFailTask(TaskSchedulers.java:518)
com.arialyy.aria.core.scheduler.TaskSchedulers.handleNormalEvent(TaskSchedulers.java:330)
com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage(TaskSchedulers.java:192)

[error:java.io.IOException: Cannot run program "logcat": error=24, Too many open files]
请问，这个也是这个BUG导致的吗，使用的版本是3.8.6
