### ISSUE TITLE
bugly上报空指针异常

### ISSUE THREAD

**Issue by Roben1016** [AriaLyy/Aria#665]
机型  锤子 DE106
系统版本 8.1.0
aria版本 3.8.6

![Aria崩溃日志1](https://user-images.githubusercontent.com/15700182/81160308-7bb05a00-8fbc-11ea-97c2-74493373e8c6.png)
![Aira错误机型](https://user-images.githubusercontent.com/15700182/81160314-7f43e100-8fbc-11ea-9ac7-0029b28dd56f.png)

**Comment by AriaLyy** [comment]
使用`3.8.7-beta-12`

**Comment by Roben1016** [comment]
@AriaLyy 不敢升级了, 我APP内部更新也是用的这个库, 之前一直用的3.8.6，后面升级到3.8.7，当时没有测试就发布，后面直接内部更新都失败了，就是下载失败，不知道改了啥，哎
