### ISSUE TITLE
3.8.6 开启aria_conifg开启检查网络有时候会导致下载卡主不动

### ISSUE THREAD

**Issue by 1wayticket** [AriaLyy/Aria#667]
## 版本
* 框架版本
v3.8.6

* 系统版本
主要是华为手机系统上

## 错误日志

com.arialyy.aria.core.command.StartCmd
executeCmd{
```
    if (!NetUtils.isConnected(AriaConfig.getInstance().getAPP())) {
      ALog.e(TAG, "启动任务失败，网络未连接");
      return;
    }
```
}

## 重现步骤

1.默认开启4g和wifi
2.关闭wifi10s
3.开启wifi
4.开始下载
会走到检查网络 然后启动任务失败 直接return 没有创建下载任务 导致下载流程一直卡在默认的初始位置,而且downloadId给的还不是-1

**Comment by AriaLyy** [comment]
使用`3.8.7-beta-12`
原因是：https://github.com/AriaLyy/Aria/issues/614
