### ISSUE TITLE
下载小于1M的apk文件，存在文件不完整的现象。

### ISSUE THREAD

**Issue by nwhhades** [AriaLyy/Aria#668]
## 版本
* 框架版本
3.7.4
* 系统版本
4.4(19)
## 错误日志

![image](https://user-images.githubusercontent.com/31042987/81266340-2e44f300-9077-11ea-8f32-7eb97175e287.png)
## 重现步骤

1.  下载一个小于1M的apk文件   
2.  下载完成后对比原文件MD5  
3.  下载文件于原文件MD5不相等

问题发现：发现apk文件大于1M后下载正常。

**Comment by shoucanjun** [comment]
3.8.10 也是存在同样的问题，md5 不一致。

**Comment by AriaLyy** [comment]
文件下载地址麻烦提供下，我自己测试是正常的
![image](https://user-images.githubusercontent.com/10437293/90084481-02a56900-dd48-11ea-9df8-dbf05b049b7f.png)

**Comment by AriaLyy** [comment]
这个也有可能是服务端的算法不同导致的，可以先用浏览器把文件下载完成，本地电脑测试看看该文件的md5
