### ISSUE TITLE
下载失败，保存路径【/storage/emulated/0/bwsofa/videos/1/AD.ts】已经被其它任务占用，请设置其它保存路径

### ISSUE THREAD

**Issue by scb7709** [AriaLyy/Aria#672]
## 版本
com.arialyy.aria:m3u8Component:3.8.6
* 框架版本

* 系统版本

## 错误日志

不管设置什么下载地址都报错：

下载失败，保存路径【/storage/emulated/0/bwsofa/videos/1/AD.ts】已经被其它任务占用，请设置其它保存路径

## 重现步骤

测试连接：1，
https://bitmovin-a.akamaihd.net/content/playhouse-vr/m3u8s/105560_video_360_1000000.m3u8
测试连接2,
http://bili.meijuzuida.com/20190807/21128_967be9cd/1000k/hls/index.m3u8

**Comment by AriaLyy** [comment]
修改保存路径或使用`ignoreFilePathOccupy`

**Comment by scb7709** [comment]
保存路径改成任意其他路径都一样的，ignoreFilePathOccupy这个方法怎么使用啊 ，是那个类的？

**Comment by scb7709** [comment]
可以下载了 但是https的m3u8链接不能下载

**Comment by AriaLyy** [comment]
m3u8 的下载见：https://github.com/AriaLyy/Aria/issues/597

**Comment by scb7709** [comment]
不好意思 我刚配错了 可以下在 现在只有最后一个问题，，就是m3u8下载能返回当前下载的切片回调，，我的进度条是 总切片数作为总长度，当前已下载的切片作为进度 来算的，但是现在我没法获取当前下载的切片数

**Comment by AriaLyy** [comment]
https://aria.laoyuyu.me/aria_doc/download/m3u8_vod_jump_peer.html

**Comment by scb7709** [comment]
我这边普通mp4下载  task.getConvertSpeed()获取的速度一直null
