### ISSUE TITLE
E/CheckFtpDirEntityUtil: 文件夹路径【/data/user/0/com.hdtd.ibuilder/files/userpic/】已被其它任务占用，请重新设置文件夹路径

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#677]
文件第二次下载覆盖问题
当前版本:
    implementation 'com.arialyy.aria:core:3.8_pre_2'
    annotationProcessor 'com.arialyy.aria:compiler:3.8_pre_2'
    implementation 'com.arialyy.aria:ftpComponent:3.8_pre_2'

**Comment by fairytale110** [comment]
CheckUtil: 下载失败，保存路径【/data/user/0/xxx.dev/files/apks/toutiao.apk】已经被其它任务占用，请设置其它保存路径

**Comment by gjk666** [comment]
??

**Comment by gjk666** [comment]
在某些情况下，你的文件保存路径可能已经被占用了，但是你只能使用这个路径保存文件，可以使用#setFilePath(filePath, true)接口强制使用该文件保存路径。这个在当下版本中已经没有这个api啦

**Comment by changzhan** [comment]
你的问题解决了吗

**Comment by AriaLyy** [comment]
使用`ignoreFilePathOccupy()`

**Comment by gjk666** [comment]
好的
