### ISSUE TITLE
使用同一下载地址创建多个保存路径不同的下载任务，提示任务已存在

### ISSUE THREAD

**Issue by loperSeven** [AriaLyy/Aria#680]
如标题所述
现有需求为需要将同一下载地址的文件下载并储存到不同文件夹，阅读源码发现框架内是使用url来作为唯一下载标识的，请问这个可以自定义吗，比如使用url+保存路径，#issue 404 有类似这个问题的描述，但好像只是taskId？求教

**Comment by AriaLyy** [comment]
不支持这个功能，可以下载完成后直接删除任务
