### ISSUE TITLE
m3u8某些链接不能下载

### ISSUE THREAD

**Issue by scb7709** [AriaLyy/Aria#681]
## 版本
* 框架版本

* 系统版本

## 错误日志
 这个类似的链接：https://you-cdn.maque-zuida.com/20191225/a9zmyvDP/index.m3u8
下载失败
 ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    【1000000】码率不存在

我使用您的demo 也是一样的 不能下载
## 重现步骤

1. 测试链接 https://you-cdn.maque-zuida.com/20191225/a9zmyvDP/index.m3u8
2.
3.
4.

**Comment by AriaLyy** [comment]
需要设置码率
```
 M3U8VodOption option = new M3U8VodOption();
    option.setBandWidth(200000);
```
