### ISSUE TITLE
等待中的任务无法删除

### ISSUE THREAD

**Issue by darrennight** [AriaLyy/Aria#683]
## 版本
* 框架版本
        implementation 'com.arialyy.aria:core:3.8.7'
        annotationProcessor 'com.arialyy.aria:compiler:3.8.7'
        implementation 'com.arialyy.aria:m3u8Component:3.8.7'

## 重现步骤

1.添加多个普通下载任务
2.删除任务
3.等待中的任务不能被删除，下载中的和下载完成的可以被删除
4.3.8.6版本可以删除等待中的任务，3.8.7版本删除失败

**Comment by AriaLyy** [comment]
和https://github.com/AriaLyy/Aria/issues/684一样的问题

**Comment by AriaLyy** [comment]
3.8.8 已修复了这个问题
