### ISSUE TITLE
当开始下载文件失败后，执行取消任务，任务记录清除不掉。

### ISSUE THREAD

**Issue by happyyzf** [AriaLyy/Aria#684]
## 版本
* 3.8.7

* android 10

## 错误日志

I/DTaskQueue: 获取任务，key：https://1259560029.vod2.myqcloud.com/6d4dc769vodcq1259560029/7d1e38515285890803537467219/f0.mp4
E/DeleteDRecord: 删除下载记录失败，记录为空，filePath：/storage/emulated/0/DCIM/Camera/941.mp4
D/BaseDListener: 删除任务完成
D/DTaskQueue: 从缓存池删除任务【941.mp4】成功
D/TaskSchedulers: 删除任务【941.mp4】成功，尝试开始下一任务

## 重现步骤

1.执行一个无法正常下载的文件链接（比如由于腾讯云账号欠费导致文件无法正常下载）
2.在下载记录列表中，执行删除任务或者记录removeRecord()或者cancel()
3.刷新任务列表，任务还在。

我看DeleteDRecord.getInstance().deleteRecord(...)方法中
先去获取下载文件，如果获取文件失败，直接return 导致后面的清除任务数据未执行。
出现这个异常情况的起始原因是，创建下载任务时文件下载url异常，导致未生成下载文件，后面这个任务记录就清除不掉了。
    TaskRecord record = DbDataHelper.getTaskRecord(entity.getFilePath(), entity.getTaskType());
    if (record == null) {
      ALog.e(TAG, "删除下载记录失败，记录为空，filePath：" + entity.getFilePath());
      return;
    }

**Comment by AriaLyy** [comment]
3.8.8 已修复了这个问题

**Comment by happyyzf** [comment]
thanks
