### ISSUE TITLE
启动下载失败

### ISSUE THREAD

**Issue by darrennight** [AriaLyy/Aria#685]
下载的任务已经添加到队列了 
06-02 18:37:21.942 17966 18746 D BaseCachePool: 任务【第一集.mp4】进入缓存队列成功
06-02 18:37:21.942 17966 18746 D DLoadExecutePool: 任务【权力游戏第三季_第一集.mp4】进入执行队列成功
06-02 18:37:21.959 17966 18746 D BaseCachePool: 任务【第二集.mp4】进入缓存队列成功
06-02 18:37:21.959 17966 18746 D BaseCachePool: 任务【第三集.mp4】进入缓存队列成功
06-02 18:37:21.960 17966 18746 D BaseCachePool: 任务【第四集.mp4】进入缓存队列成功
06-02 18:37:21.960 17966 18746 D BaseCachePool: 任务【第五集.mp4】进入缓存队列成功
06-02 18:37:21.960 17966 18746 D BaseCachePool: 任务【第六集.mp4】进入缓存队列成功
06-02 18:37:21.960 17966 18746 D BaseCachePool: 任务【第七集.mp4】进入缓存队列成功
06-02 18:37:21.960 17966 18746 D BaseCachePool: 任务【第八集.mp4】进入缓存队列成功
06-02 18:37:21.960 17966 18746 D BaseCachePool: 任务【第九集.mp4】进入缓存队列成功

Ignoring header Cookie because its value was null.
06-02 18:37:22.137 17966 18747 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.common.RecordHelper.handleSingleThreadRecord(RecordHelper.java:157)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.http.HttpRecordHandler.handlerTaskRecord(HttpRecordHandler.java:57)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:88)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.NormalLoader.startThreadTask(NormalLoader.java:111)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.NormalLoader$1.onSucceed(NormalLoader.java:150)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:249)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleUrlReTurn(HttpDFileInfoTask.java:341)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:239)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:85)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:98)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
06-02 18:37:22.142 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
06-02 18:37:22.142 17966 18747 W System.err: 	at java.lang.Thread.run(Thread.java:818)
06-02 18:37:23.154 17966 18759 D JIGUANG-JCore-IMPL: [JCommonInterface] onEvent action:deviceinfo
06-02 18:37:23.168 17966 18759 W art     : Method processed more than once: int cn.jiguang.r.a.e()
06-02 18:37:23.169 17966 18759 W art     : Method processed more than once: void cn.jiguang.p.a.<clinit>()
06-02 18:37:23.170 17966 18759 W art     : Method processed more than once: java.lang.String cn.jiguang.r.c.a(android.content.Context, java.lang.String)
06-02 18:37:23.181 17966 18759 E JIGUANG-JCore: [ReportUtils] wrap data failed
06-02 18:37:23.201 17966 18747 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.common.RecordHelper.handleSingleThreadRecord(RecordHelper.java:157)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.http.HttpRecordHandler.handlerTaskRecord(HttpRecordHandler.java:57)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:88)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.NormalLoader.startThreadTask(NormalLoader.java:111)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.NormalLoader$1.onSucceed(NormalLoader.java:150)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:249)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleUrlReTurn(HttpDFileInfoTask.java:341)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:239)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:85)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:98)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
06-02 18:37:23.201 17966 18747 W System.err: 	at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
06-02 18:37:23.201 17966 18747 W System.err: 	at java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
是哪个版本？

**Comment by darrennight** [comment]
> 是哪个版本？

3.8.6版本
