### ISSUE TITLE
HTTP 下载任务使用 cancel 方法并传入removeFile=false时，文件仍然会被删除

### ISSUE THREAD

**Issue by xz-dev** [AriaLyy/Aria#686]
## 版本
* 框架版本
3.8.7

* 系统版本
10

## 错误日志

执行完毕 cancel 命令后的日志为
<code>D/BaseDListener: 删除任务完成</code>

## 重现步骤

1. HTTP 下载任务完成（文件存在）
2. 执行 cancel 命令
``` kotlin
Aria.download(this).load(taskId)
    .ignoreCheckPermissions()
    .cancel(false)
```
3. 文件被删除

**Comment by AriaLyy** [comment]
3.8.8 已修复了这个问题
