### ISSUE TITLE
android.database.sqlite.SQLiteDiskIOException

### ISSUE THREAD

**Issue by OneGreenHand** [AriaLyy/Aria#690]
## 版本
* 框架版本
3.8.7
* 系统版本
Android 6.0  VIVO Y67A
## 错误日志

disk I/O error (code 4874)
com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java:176)
解决方案
该异常表示磁盘输入/输出错误，可能是数据操作太频繁导致的。
应用程序启动时，调用RSSDatabase的构造函数，UI Thread锁定了你的目标的数据库，随后你又尝试插入数据到被UI线程锁定的数据库。 将抛出一个异常，因为db被lock了。

## 重现步骤

这是在bugly捕获的，目前只发现了一次
1 android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
2 android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:613)
3 android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
4 android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
5 android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:886)
6 android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:874)
7 android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:894)
8 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
9 android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
10 com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java:176)
11 com.arialyy.aria.orm.SqlHelper.getReadableDatabase(SqlHelper.java:166)
12 com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:140)
13 com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:39)
14 com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:47)
15 com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:140)
16 com.arialyy.aria.core.AriaManager.initData(AriaManager.java:117)
17 com.arialyy.aria.core.AriaManager.init(AriaManager.java:108)
18 com.arialyy.aria.core.Aria.get(Aria.java:117)
19 com.arialyy.aria.core.Aria.download(Aria.java:90)

**Comment by AriaLyy** [comment]
为了处理 https://github.com/AriaLyy/Aria/issues/664 的bug，增加了一个创建sqlite缓存文件夹的功能，可能是多次执行了那个sql导致的

**Comment by AriaLyy** [comment]
3.8.9 已处理处理了这个问题

**Comment by OneGreenHand** [comment]
大佬🐮🍺
