### ISSUE TITLE
下载m3u8状态一直是预处理，也不走fail回调，start回调也不走

### ISSUE THREAD

**Issue by dary123** [AriaLyy/Aria#692]
## 版本
* 框架版本
3.8.8
* 系统版本
android 8.1.0
## 错误日志

下载m3u8状态一直是预处理，也不走fail回调，start回调也不走
## 重现步骤

1.执行create创建下载任务
2.register注册监听
3.不走任何m3u8相关的回调，state状态一直是5
4.下载url是http://youku.cdn7-okzy.com/20200123/16815_fbe419ed/index.m3u8，使用的下载直播文件方式，设置了合并为true，设置保存文件路径后缀是.mp4

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/84586004-03a14380-ae48-11ea-9897-e36621a24410.png)
我这是可以的，请参考 https://github.com/AriaLyy/Aria/issues/597 设置码率转换器和TS转换器

**Comment by AriaLyy** [comment]
或者使用3.8.9版本，该版本增加了默认的转换器
