### ISSUE TITLE
为什么一定要申请文件读写权限呢

### ISSUE THREAD

**Issue by protectedMan** [AriaLyy/Aria#693]
框架内部如果确实有文件读写的要求，放在缓存目录不好吗？
![image](https://user-images.githubusercontent.com/17565737/84615509-cdbd9700-aefb-11ea-9a8e-d716a0ba4fa6.png)

**Comment by AriaLyy** [comment]
有一个API可以忽略这个检查`ignoreCheckPermissions()`

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/548
