### ISSUE TITLE
下载失败，数据库中已存在相同的url的组任务

### ISSUE THREAD

**Issue by changzhan** [AriaLyy/Aria#694]
## 版本 
* 框架版本  3.6.3升级至3.8.9 报错

* 系统版本 

## 错误日志

![image](https://user-images.githubusercontent.com/31200770/84616331-4887b180-aefe-11ea-8fa1-2dda4d6236c9.png)

## 重现步骤

1.下载一个组图片任务
2. 第一次下载失败，报filenotfound，但是在浏览器上地址能打开
3. 重新跑代码进入下载
4. 报上述错误

**Comment by AriaLyy** [comment]
使用这个 `ignoreFilePathOccupy`
