### ISSUE TITLE
不使用默认的转换器的问题

### ISSUE THREAD

**Issue by JKlover** [AriaLyy/Aria#703]
## 版本
* 3.8.9
我看了一下源码发现
 /**
   * 设置使用默认的码率转换器和TS转换器，默认打开
   * @param useDefConvert true 使用默认的转换器，false 关闭默认的转换器
   */
  public OP setUseDefConvert(boolean useDefConvert) {
    this.useDefConvert = true;
    ALog.d(TAG, "使用默认的码率转换器和TS转换器，如果无法下载，请参考：https://github.com/AriaLyy/Aria/issues/597 定制转换器");
    return (OP) this;
  }
里面是写死的，setUseDefConvert(false)是没有效果的，希望作者早日修复
导致很多m3u8都无法下载

**Comment by AriaLyy** [comment]
感谢反馈，确实是我的问题，已经改过来了

**Comment by AriaLyy** [comment]
3.8.10 已经修复了这个问题

**Comment by 13512780735** [comment]
有什么办法在进程关闭之后再进来时继续下载？
