### ISSUE TITLE
有时会出现下载失败的问题

### ISSUE THREAD

**Issue by zlhuang** [AriaLyy/Aria#704]
06-29 15:05:26.698 25455-12277/com.liftcore.download_simply E/BaseDListener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaHTTPException: 下载失败，filePath: /storage/emulated/0/Download/com.aqua.slide_5cf4b69e90e6a.apk, url: https://downs.muzhiwan.com/2019/06/03/com.aqua.slide_5cf4b69e90e6a.apk
    Unable to resolve host "downs.muzhiwan.com": No address associated with hostname
    com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:88)
    com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
    java.lang.Thread.run(Thread.java:818)
    ===================================================

**Comment by AriaLyy** [comment]
这个是网络错误出现的
