### ISSUE TITLE
在DialogFragment中内存泄漏

### ISSUE THREAD

**Issue by Roben1016** [AriaLyy/Aria#705]
## 版本
* 框架版本
3.8.6

* 系统版本
android 10
## 重现步骤
在DialogFragment中的onDestroy方法中已解除注册, unRegister,但在LeakCanary中仍然报出内存泄漏

![Aria内存泄漏1](https://user-images.githubusercontent.com/15700182/85995146-8cb39f80-ba30-11ea-8a52-42d7358c0035.jpg)

![Aria内存泄漏2](https://user-images.githubusercontent.com/15700182/85995194-96d59e00-ba30-11ea-9beb-fea1c312cf1d.jpg)

**Comment by AriaLyy** [comment]
检查下使用的是getcontext() 还是this，如果是`getContext`将其修改为`this`
```
Aria.download(this).register();
Aria.download(this).unregister();
```

**Comment by Roben1016** [comment]
使用的是this

**Comment by AriaLyy** [comment]
是在匿名内部类中使用的吗？最近发现一个在匿名内部类使用this导致的内存泄漏问题

**Comment by Roben1016** [comment]
> 是在匿名内部类中使用的吗？最近发现一个在匿名内部类使用this导致的内存泄漏问题

不是的, 在onCreate中注册, onDestroy中解除注册
![Aria内存泄漏3](https://user-images.githubusercontent.com/15700182/88260534-26e8c980-ccf7-11ea-82d5-be33ec1b73a3.png)
![Aria内存泄漏4](https://user-images.githubusercontent.com/15700182/88260543-2c461400-ccf7-11ea-9587-9956ed09aa5c.png)
是不是因为我在主页MainActivity中也注册监听了回调的原因呢?MainActivity是singleTask

**Comment by AriaLyy** [comment]
`3.8.12`已修复了这个问题
