### ISSUE TITLE
android 9 异常

### ISSUE THREAD

**Issue by Jasperben** [AriaLyy/Aria#708]
java.lang.SecurityException: Permission Denial: not allowed to send broadcast ARIA_TASK_INFO_ACTION from pid=3102, uid=10052

**Comment by AriaLyy** [comment]
如何出现的？是否是系统应用？

**Comment by Jasperben** [comment]
系统应用

**Comment by AriaLyy** [comment]
我没有做过系统应用，可以在框架成增加受保护的广播

frameworks/base/core/res/AndroidManifest.xml

```
<protected-broadcast android:name="ARIA_TASK_INFO_ACTION" />
```
