### ISSUE TITLE
启用use block后无法下载文件

### ISSUE THREAD

**Issue by yizems** [AriaLyy/Aria#710]
## 版本
3.7.8-pre-3

* 系统版本
android 10

## 错误日志
错误日志显示为   合并文件长度大于 文件长度, 文件长度为0;  具体情况有点复杂, 看下面的日志吧

## 重现步骤
我们原先的项目是使用 spring 做的, 后来改为ktor 实现,发现该框架的 分块下载就无法使用了,但是又无法确定原因,所以希望能得到一些帮助

charles 抓包 header 如下, 每次请求会产生4个记录

![image](https://user-images.githubusercontent.com/16949474/86928614-6051fe80-c167-11ea-9177-abcb125f35a7.png)

1: 
![image](https://user-images.githubusercontent.com/16949474/86928704-7eb7fa00-c167-11ea-9d39-44208c1353ad.png)
2:
![image](https://user-images.githubusercontent.com/16949474/86928729-87103500-c167-11ea-8cbc-4d48bf352735.png)

3: 
![image](https://user-images.githubusercontent.com/16949474/86928746-8d9eac80-c167-11ea-9e76-7e060d4c0fe4.png)

4.
![image](https://user-images.githubusercontent.com/16949474/86928772-955e5100-c167-11ea-858a-b00004626e23.png)

从charles 的日志上来看, 文件应该是下载完整了,但是不知道到底哪里导致的 文件长度 为 0 ,最后合并的时候报错

**Comment by yizems** [comment]
我已经找到原因, 因为后台没有返回`content length`

`HttpDFileInfoTask`

```java
private static class FileLenAdapter implements IHttpFileLenAdapter {

    @Override public long handleFileLen(Map<String, List<String>> headers) {
      if (headers == null || headers.isEmpty()) {
        ALog.e(TAG, "header为空，获取文件长度失败");
        return -1;
      }
      List<String> sLength = headers.get("Content-Length");
      if (sLength == null || sLength.isEmpty()) {
        return -1;
      }
      String temp = sLength.get(0);
      long len = TextUtils.isEmpty(temp) ? -1 : Long.parseLong(temp);
      // 某些服务，如果设置了conn.setRequestProperty("Range", "bytes=" + 0 + "-");
      // 会返回 Content-Range: bytes 0-225427911/225427913
      if (len < 0) {
        List<String> sRange = headers.get("Content-Range");
        if (sRange == null || sRange.isEmpty()) {
          len = -1;
        } else {
          int start = temp.indexOf("/");
          len = Long.parseLong(temp.substring(start + 1));
        }
      }

      return len;
    }
  }
```

后台程序是不会返回这个的, 会返回 content-range 端,需要解析起来并加起来确认总长度,所以 这一块我自定义一个 adapter 即可;

或者后台改下 ktor 源码加上也行;  

如果 Aria 能加上这个处理当然更好

**Comment by AriaLyy** [comment]
会返回 content-range 端,需要解析起来并加起来确认总长度，这个是啥意思？
我不太清楚这块的逻辑，如果你能贡献下你的adpter，或提交个PR，那是最好不过了😊

**Comment by yizems** [comment]
我知道问题了, 是 get 请求 没有返回 content length 导致的,  我想问下, 为何不适用 head 的请求方式获取 资源的信息呢?

**Comment by AriaLyy** [comment]
历史遗留问题，后面会优化

**Comment by AriaLyy** [comment]
从`3.8.12`起，已增加head请求配置，配置文件增加 <useHeadRequest value="true"/>，但是并不是所有服务器都支持head请求
