### ISSUE TITLE
文件下载不了。。

### ISSUE THREAD

**Issue by asd8635938** [AriaLyy/Aria#711]
## 版本
* 框架版本

* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
麻烦提供下下载地址

**Comment by sbwhy** [comment]
我的也是 创建任务报 -1，创建失败，浏览器一打开就行

**Comment by topab** [comment]
> 麻烦提供下下载地址



> 麻烦提供下下载地址
您好，我这边下载一个0kb的文件，直接走了 onfail能看看吗，感谢
https://22-1251738822.cos.ap-chengdu.myqcloud.com/%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6.docx

**Comment by AriaLyy** [comment]
`3.8.12`已修复了这个问题

**Comment by EvanZch** [comment]
> `3.8.12`已修复了这个问题

使用3.8.12，同样遇到这个问题，跟文件大小有关系，文件过小就会下载失败，同样提示分块错误

**Comment by topab** [comment]
> > `3.8.12`已修复了这个问题
> 
> 使用3.8.12，同样遇到这个问题，跟文件大小有关系，文件过小就会下载失败，同样提示分块错误

我这上面出现的问题解决，你可以贴个下载链接试试,我这3B 跟5Kb试了下，没问题。

**Comment by topab** [comment]
> > > `3.8.12`已修复了这个问题
> > 
> > 
> > 使用3.8.12，同样遇到这个问题，跟文件大小有关系，文件过小就会下载失败，同样提示分块错误
> 
> 我这上面出现的问题解决，你可以贴个下载链接试试,我这3B 跟5Kb试了下，没问题。

https://22-1251738822.cos.ap-chengdu.myqcloud.com/测试11.txt
https://22-1251738822.cos.ap-chengdu.myqcloud.com/测试22.txt
我这没问题，上面链接时一个3B 一个5kb，上面还有空文件链接，你可以试试。

**Comment by EvanZch** [comment]
> > > > `3.8.12`已修复了这个问题
> > > 
> > > 
> > > 使用3.8.12，同样遇到这个问题，跟文件大小有关系，文件过小就会下载失败，同样提示分块错误
> > 
> > 
> > 我这上面出现的问题解决，你可以贴个下载链接试试,我这3B 跟5Kb试了下，没问题。
> 
> [https://22-1251738822.cos.ap-chengdu.myqcloud.com/测试11.txt](https://22-1251738822.cos.ap-chengdu.myqcloud.com/%E6%B5%8B%E8%AF%9511.txt)
> [https://22-1251738822.cos.ap-chengdu.myqcloud.com/测试22.txt](https://22-1251738822.cos.ap-chengdu.myqcloud.com/%E6%B5%8B%E8%AF%9522.txt)
> 我这没问题，上面链接时一个3B 一个5kb，上面还有空文件链接，你可以试试。

嗯，你的这个链接可以，我的链接可能有问题，服务端做了处理，链接一旦下载完成马上失效，我直接用浏览器下载没问题，但是使用库在这种情况下是下载大文件没问题，小文件就会出现下载下来0b的情况，关闭了分块。
