### ISSUE TITLE
m3u8下载错误出现的问题

### ISSUE THREAD

**Issue by NerdAnonymous** [AriaLyy/Aria#712]
当m3u8下载链接不正确的时候，列表不能正常下载，这时候进行cancel方法，不管参数是true还是false，都会走到DeleteM3u8Record: 删除下载记录失败，记录为空，filePath：/data/user/0/com.xxx.tv/files/m3u8Cache/114/1128这个里面，然后记录就没有删除成功.
出错版本 3.8.10

**Comment by AriaLyy** [comment]
`3.8.12`已修复了这个问题
