### ISSUE TITLE
encodeStr()方法似乎错误地编码了特殊字符 \

### ISSUE THREAD

**Issue by chmod4755** [AriaLyy/Aria#715]
https://github.com/AriaLyy/Aria/blob/e64f3b1240d5033235b6622f3dcd7ac089b5aad1/PublicComponent/src/main/java/com/arialyy/aria/orm/SqlUtil.java#L355

根据[HTML URL编码表](https://www.w3schools.com/tags/ref_urlencode.asp)，%2B的原字符为"+"，看起来上面的方法想先处理特殊字符"+"（虽然我不知道为什么），但实际\ \ \ \ +在java字符串中所表达的正则表达式是 \ \ +，也就是匹配N个连续的特殊字符\，会把字符\错误地编码为%2B。
## 版本
* 框架版本 每个版本

* 系统版本

## 错误日志
addtask传入的Json.

`"file_name":"道歉信\u0026感谢信"`

读出来后变成了
`"file_name":"道歉信%2Bu0026感谢信"`

**Comment by AriaLyy** [comment]
感谢反馈，后面会修复该问题

**Comment by chmod4755** [comment]
> 感谢反馈，后面会修复该问题

作者大大反馈真快～我才提交pull request进来就看到问题被回复了

**Comment by AriaLyy** [comment]
当初好像是为了解决URLEncoder.encoder()空格和加号的问题的，经过验证你的方法是有效的
![image](https://user-images.githubusercontent.com/10437293/88146085-fbe67300-cc2d-11ea-9863-785741b5be37.png)
