### ISSUE TITLE
m3u8有关key的下载

### ISSUE THREAD

**Issue by 961900832** [AriaLyy/Aria#718]
## 版本
* 框架版本
3.8.10

## 重现步骤

你好，在下载m3u8时，.m3u8文件里的地址是相对路径：
- 文件1网络路径：http://www.xxx.com/JJDAQBAV/index.m3u8
 ```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=600000,RESOLUTION=720x404
600kb/hls/index.m3u8
```
- 文件2网络路径：http://www.xxx.com/JJDAQBAV/600kb/hls/index.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="key.key"
#EXTINF:5.038367,
kEtOsxW3175000.ts
```
- key的网络路径：http://www.xxx.com/JJDAQBAV/600kb/hls/key.key

这个使用场景下遇到一个问题，IKeyUrlConverter 的回调函数里 m3u8Url 是文件1的地址，而key的路径是相对于文件2地址的。这种情况下有没有使key能够相对于路径2去修改的解决办法？

**Comment by AriaLyy** [comment]
你这是多码率的m3u8把，可以使用 M3U8Option的`setKeyPath()`设置key的保存地址的

**Comment by 961900832** [comment]
不好意思，我没有表述清楚。这是一个单码率的m3u8。其中文件1是主列表（带宽选择列表），文件2是媒体列表（ts文件列表）。其中key的网络路径是在文件2中出现的，而且是相对于文件2的网络路径的。
- 文件1的网络路径：`http://www.xxx.com/JJDAQBAV/index.m3u8`
- 文件2的网络路径：`http://www.xxx.com/JJDAQBAV/600kb/hls/index.m3u8`
- key的网络路径：`http://www.xxx.com/JJDAQBAV/600kb/hls/key.key`

key 在文件2中出现的形式是：
```
#EXT-X-KEY:METHOD=AES-128,URI="key.key"
```
现在的问题是key的网络路径在`IKeyUrlConverter`的`convert`函数中是获取的文件1的网络路径，而key的网络路径是相对于文件2的。想问一下这种情况下，有没有好的办法使key获取到文件2的网络路径。

**Comment by AriaLyy** [comment]
可以通过`IBandWidthUrlConverter`获取码率的m3u8文件列表地址，然后你可以将其保存下来，然后再放到`IKeyUrlConverter`中

**Comment by 961900832** [comment]
嗯嗯，好的，谢谢~

还有一个问题：
在上边这个场景中 `IBandWidthUrlConverter`  与 `IKeyUrlConverter` 的回调函数中`m3u8Url` 是 相同的，都是`http://www.xxx.com/JJDAQBAV/index.m3u8`
而`IVodTsUrlConverter`的回调函数中`m3u8Url`是 `http://www.xxx.com/JJDAQBAV/600kb/hls/index.m3u8`。

如果按直觉的话，`IVodTsUrlConverter` 和 `IKeyUrlConverter` 应该是相同的一个`m3u8Url`的，因为它们是在同一个文件中的。


但是事实上`IKeyUrlConverter`是与`IBandWidthUrlConverter` 相同的。请问这里设计上的考虑吗？

**Comment by AriaLyy** [comment]
是这样设计的，后面可以改为和ts列表一样的url

**Comment by 961900832** [comment]
好的，明白了，多谢

**Comment by AriaLyy** [comment]
后面会在转换器中增加一个ts列表的字段，我先这个issues打开了

**Comment by AriaLyy** [comment]
`3.8.12`增加了一个m3u8地址的功能
```
  /**
   * 将被加密的密钥下载地址转换为可使用的http下载地址
   *
   * @param m3u8Url 主m3u8的url地址
   * @param tsListUrl m3u8切片列表url地址
   * @param keyUrl 加密的url地址
   * @return 可正常访问的http地址
   */
  String convert(String m3u8Url, String tsListUrl, String keyUrl);

```
