### ISSUE TITLE
任务根据id删除后 ，download.allNotCompleteTask依然存在

### ISSUE THREAD

**Issue by Zmydhy** [AriaLyy/Aria#720]
![image](https://user-images.githubusercontent.com/9899249/88605884-d0400e80-d0ad-11ea-9f0c-65463787234a.png)

       Aria.download(this).load(ids).cancel(true)

 val allNotCompleteTask = download.allNotCompleteTask

**Comment by AriaLyy** [comment]
重现的步骤是什么？我这测试是正常的呢

**Comment by pys200603027** [comment]
我这了复现了这个问题，把本地文件删除后，无法删除记录，remove会判断 文件是否存在

**Comment by pys200603027** [comment]
代码调用可能是这么写的
```
 //1. 删除本地文件目录
        File localDirFile = new File(downloadItem.getLocalPath());
        if (localDirFile.exists()) {
            FileUtil.deleteDir(localDirFile);
        }
        
        //2. 删除记录
        HttpNormalTarget target = Aria.download(context).load(downloadItem.getTaskId());
        if (target != null) {
//            target.cancel();
            target.removeRecord();
        }
```

对应代码IDeleteRecord

```
@Override public void deleteRecord(String filePath, boolean removeTarget,
      boolean needRemoveEntity) {
    if (TextUtils.isEmpty(filePath)) {
      throw new NullPointerException("删除记录失败，文件路径为空");
    }
    if (!filePath.startsWith("/")) {
      throw new IllegalArgumentException(String.format("文件路径错误，filePath：%s", filePath));
    }
    DownloadEntity entity = DbEntity.findFirst(DownloadEntity.class, "downloadPath=?", filePath);
    if (entity == null) {
      ALog.e(TAG, "删除下载记录失败，没有在数据库中找到对应的实体文件，filePath：" + filePath);
      return;
    }
    deleteRecord(entity, removeTarget, needRemoveEntity);
  }
```

**Comment by AriaLyy** [comment]
用`3.8.12`看看，在`3.8.12`中，如果记录为空，是会删除实体的。 
[L83](https://github.com/AriaLyy/Aria/blob/fed2b4111fcf87ba3c574d881567bc50249a1046/PublicComponent/src/main/java/com/arialyy/aria/util/DeleteM3u8Record.java#L83) 已经增加了记录判空的操作

**Comment by pys200603027** [comment]
> 用`3.8.12`看看，在`3.8.12`中，如果记录为空，是会删除实体的。
> [L83](https://github.com/AriaLyy/Aria/blob/fed2b4111fcf87ba3c574d881567bc50249a1046/PublicComponent/src/main/java/com/arialyy/aria/util/DeleteM3u8Record.java#L83) 已经增加了记录判空的操作

我这边试了下没问题

**Comment by ZS-ZhangsShun** [comment]
3.8.15  我也遇到同样的问题，当前同时正在下载的最大任务是2，此时你删除第三条任务就会失败，因为这条记录还没有启动，此时sd卡中的文件夹会被删除，但是删除第二条任务后，第三条任务还是被触发并且会在sd中创建文件夹
