### ISSUE TITLE
M3u8支持设置header吗？

### ISSUE THREAD

**Issue by pys200603027** [AriaLyy/Aria#724]
你好作者，感谢提供好用的下载库

如题，M3u8点播下载支持设置header吗？

**Comment by AriaLyy** [comment]
支持的

**Comment by pys200603027** [comment]
> 支持的

是在哪里设置呢？ 我在`M3U8VodOption`中没有找到设置header的方法

**Comment by AriaLyy** [comment]
.option(new HttpOption())

**Comment by pys200603027** [comment]
> .option(new HttpOption())

好的非常感谢
