### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by double4pilipinas** [AriaLyy/Aria#725]
version:3.8.10

com.android.okhttp.okio.Buffer.writeByte(Buffer.java:973)
--
2 com.android.okhttp.internal.Platform.concatLengthPrefixed(Platform.java:130)
3 com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:84)
4 com.android.okhttp.Connection.connectTls(Connection.java:230)
5 com.android.okhttp.Connection.connectSocket(Connection.java:199)
6 com.android.okhttp.Connection.connect(Connection.java:172)
7 com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
8 com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
9 com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
10 com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
11 com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
12 com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
13 com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
14 com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
15 com.networkbench.agent.impl.instrumentation.NBSHttpsURLConnectionExtension.connect(SourceFile)
16 com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java)
17 com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java)
18 com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java)
19 com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java)
20 java.lang.Thread.run(Thread.java:760)

**Comment by double4pilipinas** [comment]
com.android.okhttp.okio.Buffer.writeByte(Buffer.java:973)
--
2 com.android.okhttp.internal.Platform.concatLengthPrefixed(Platform.java:130)
3 com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:84)
4 com.android.okhttp.Connection.connectTls(Connection.java:230)
5 com.android.okhttp.Connection.connectSocket(Connection.java:199)
6 com.android.okhttp.Connection.connect(Connection.java:172)
7 com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
8 com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
9 com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
10 com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)

**Comment by AriaLyy** [comment]
okio 的bug https://github.com/square/okhttp/issues/3938
