### ISSUE TITLE
下载m3u8文件，杀掉进程后，下载进度从0开始，无法继续从上次进度开始。

### ISSUE THREAD

**Issue by clark2048** [AriaLyy/Aria#726]
## 版本
* 框架版本
3.8.10
* 系统版本
8.0
## 错误日志

无

## 重现步骤

1.下载m3u8文件，不关闭app能正常下载和暂停。
2.杀掉进程，再次进入，  Aria.download(context).load(entity.getId()).resume(true) 恢复任务。下载进度又从0开始了，无法从上次的进度开始任务。

**Comment by AriaLyy** [comment]
框架是开始下载后5s保存一次进度的，如果你在开始下载的5s内就kill进程，是会导致进度丢失
