### ISSUE TITLE
文件下载不了，老是到99%就失败了

### ISSUE THREAD

**Issue by 13512780735** [AriaLyy/Aria#727]
## 版本
* 框架版本

* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by 13512780735** [comment]
下载链接是http://s.d28.ihuolong.net/dlios.php?YTMxME5GMlRwY050MEZOMGxzS2dYemgvakNkTXBLd2xKbE5MTUxIVnZjVW13SU9iWXZuUzBLcDZYR0xBRVovMmRPLzIxcGIyNGd5bEd5UzcyTWF6Y0hjSkRMdW5HSVBhYzlkK3QvQ2dzNHpBaHZEQkdQai9wZHk1UmVLZUtCYnRzYUZ1ZXYxTUNIbDBNUUcxZ3k2UThzN3hkR0hERzZ4WU9DM0lPTTJJVjVKNisvakdXTU1sbi8wUnoxdlZKbE9Id2JBSnJSdEZySkhwTWdib2pEQ09rcWh5RkVCVlhjQW56ZVdndHdSbXc0TkNkMFZKV09PRytWdS8%3D

**Comment by AriaLyy** [comment]
失败时logcat提示什么错误？

**Comment by 13512780735** [comment]
08-10 15:55:46.448 16046-16152/com.example.test01 E/HttpDFileInfoTask: header为空，获取文件长度失败
08-10 15:55:46.452 16046-16152/com.example.test01 E/BaseDListener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaHTTPException: 下载失败，filePath: /storage/emulated/0/Download/上传下载.zip, url: http://s.d28.ihuolong.net/dlios.php?NTY2NGxUREFCZWFBWU1uTDNuUEk3UTV0dU8wdjdMR0ZROTZxcTBJYVl3c0NvWFZmemxCSXpzTndZK3p0VjVnSnJOc3hneU1DdUFqSkNRQ1d0NGlkamNEd1BxRS9DaEVacS9vWk9CNTRHR0hPOTlDbmgyMXRHVmliSk9lS3puTjByeFBDbW5RVUxuYWk2YTRNdHQ5SkkzNXVTVmhFN1Z1dGFtRjdudjRDcHI0Zi82Y1M2MzUvdGpHSjFWMC9Ha3NNY3pQUnVQYVV4aUFqYVVGajVDY0JxQW5lRDE2K0I1YXdwVG1FUkQrV3VZVlFERnBRSFlYY0h1V2RhNHQxVE5NTA%3D%3D
    Unexpected status line: ��HTTP/1.1 206 Partial Content
    com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:88)
    com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
    java.lang.Thread.run(Thread.java:818)
    ===================================================

**Comment by 13512780735** [comment]
这是要添加header吗？并且看了分块下载的时候，分块下完了，但是不会合并，这是什么原因呀？

**Comment by AriaLyy** [comment]
获取不到文件长度，建议自己设置文件长度，或者不使用分块，使用单线程下载

**Comment by 13512780735** [comment]
怎样自己设置文件长度，我试了用单线程的，但是只能下载图片格式的，如zip压缩包类的就下载不了，大神

**Comment by 13512780735** [comment]
因为下载链接是阿里云返回的，加密的url，难道是这个原因获取不到长度？

**Comment by 13512780735** [comment]
或者说zip下载后解压不了，文件损坏了，使用单线程的话

**Comment by AriaLyy** [comment]
单线程一般是不会出现文件损坏的问题的

**Comment by AriaLyy** [comment]
文件长度获取不到原因很多，最大的可能是服务端在head中不返回长度
