### ISSUE TITLE
对于无后缀名的URL,要怎样下载？求解

### ISSUE THREAD

**Issue by 13512780735** [AriaLyy/Aria#729]
## 版本
* 框架版本

* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by 13512780735** [comment]
http://s.d28.ihuolong.net/dlios.php?ZTdmZEs4NDRTUnd6ZEQ4bmd5djM4c2NDcTNrUXYyWVhPdXF0MHVmdTl1dXE4Vk83K2ExaEZLb0hzY2NuaEpiV1lGYm80Qzd2MWdDc1NRd0g0bTVsVmMyblRRV0tHNnFHc045SUhtOGN0aVZqSEF3a1pvR2ozOUhpbDIyOHNSNHpRcnIrMFJZdDRzZ1FzWEt5c1FFdGx3eVQyMlJNN0JoaWIvbHJ1T1NDSWUrMmhjYzFBQUg0OVQ3NHZ0djRQc0VJT1BtbFNtMUM0OVFVNVlka3RuemFLbGJDQlRJLzNUMWtGTHNQbTFyVVdVa1ljbzZ4aWFsUHZNdk0weSt4SG9J             下载链接是这样的无后缀名

**Comment by AriaLyy** [comment]
下载和后缀名没有关系的

**Comment by 13512780735** [comment]
想问下，你 30x跳转这个是什么情况会执行呀？每次下载不成功的都是执行了这个

**Comment by 13512780735** [comment]
Ignoring header Cookie because its value was null.报这个错误是因为咩有加请求头吗？

**Comment by 13512780735** [comment]
分块的时候，最后合并不了，停留在99%

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/89875944-80566100-dbf0-11ea-9e66-644aa84ac46c.png)
我测试是可以的...

**Comment by 13512780735** [comment]
这个链接你测试下载正常？能加个Q告诉我下不，谢谢

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/89962459-51370280-dc77-11ea-95e2-5a762a3355ef.png)
