### ISSUE TITLE
得到一个Failed to notify project evaluation listener错误

### ISSUE THREAD

**Issue by xgbxmgg** [AriaLyy/Aria#73]
在Android studio2.3.3下使用gradle3.4通过命令（如gradle clean）执行task任务时出现以下错误：
`10:18:20.026 [ERROR]   FAILURE: Build failed with an exception.
10:18:20.026 [ERROR]  
10:18:20.026 [ERROR]   * What went wrong:
10:18:20.026 [ERROR]   A problem occurred configuring project ':Aria'.
10:18:20.026 [ERROR]   > Failed to notify project evaluation listener.
10:18:20.026 [ERROR]      > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
10:18:20.026 [ERROR]  
10:18:20.026 [ERROR]   * Exception is:
10:18:20.027 [ERROR]   org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':Aria'.
10:18:20.027 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:87)
10:18:20.027 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
10:18:20.027 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:69)
10:18:20.027 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:33)
10:18:20.027 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:103)
10:18:20.027 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
10:18:20.027 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
10:18:20.027 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
10:18:20.027 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
10:18:20.027 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:49)
10:18:20.027 [ERROR]     at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:654)
10:18:20.027 [ERROR]     at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:132)
10:18:20.027 [ERROR]     at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
10:18:20.028 [ERROR]     at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
10:18:20.028 [ERROR]     at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
10:18:20.028 [ERROR]     at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:195)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
10:18:20.028 [ERROR]     at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:157)
10:18:20.028 [ERROR]     at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:44)
10:18:20.028 [ERROR]     at org.gradle.initialization.DefaultGradleLauncher$1.run(DefaultGradleLauncher.java:122)
10:18:20.028 [ERROR]     at org.gradle.internal.work.DefaultWorkerLeaseService$2.execute(DefaultWorkerLeaseService.java:124)
10:18:20.028 [ERROR]     at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:116)
10:18:20.028 [ERROR]     at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:99)
10:18:20.028 [ERROR]     at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
10:18:20.028 [ERROR]     at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
10:18:20.028 [ERROR]     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
10:18:20.028 [ERROR]     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
10:18:20.028 [ERROR]     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
10:18:20.028 [ERROR]     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
10:18:20.028 [ERROR]     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:51)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
10:18:20.028 [ERROR]     at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
10:18:20.029 [ERROR]     at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
10:18:20.029 [ERROR]     at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
10:18:20.029 [ERROR]     at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
10:18:20.029 [ERROR]     at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:50)
10:18:20.029 [ERROR]     at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
10:18:20.029 [ERROR]     at org.gradle.util.Swapper.swap(Swapper.java:38)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
10:18:20.029 [ERROR]     at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
10:18:20.029 [ERROR]     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
10:18:20.029 [ERROR]     at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
10:18:20.029 [ERROR]     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
10:18:20.029 [ERROR]   Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
10:18:20.030 [ERROR]     at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
10:18:20.030 [ERROR]     at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
10:18:20.030 [ERROR]     at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
10:18:20.030 [ERROR]     at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
10:18:20.030 [ERROR]     at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
10:18:20.030 [ERROR]     at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
10:18:20.030 [ERROR]     at com.sun.proxy.$Proxy23.afterEvaluate(Unknown Source)
10:18:20.030 [ERROR]     at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:75)
10:18:20.030 [ERROR]     ... 76 more
10:18:20.030 [ERROR]   Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
10:18:20.030 [ERROR]     at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:131)
10:18:20.030 [ERROR]     at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:39)
10:18:20.030 [ERROR]     at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:148)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.TaskContainerAdaptor.create(TaskContainerAdaptor.java:59)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:47)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:89)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.TaskManager.createJavacTask(TaskManager.java:1102)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.LibraryTaskManager$10.call(LibraryTaskManager.java:272)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.LibraryTaskManager$10.call(LibraryTaskManager.java:268)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.LibraryTaskManager.createTasksForVariantData(LibraryTaskManager.java:267)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:485)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:293)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:290)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
10:18:20.030 [ERROR]     at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:286)
10:18:20.030 [ERROR]     at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
10:18:20.030 [ERROR]     at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
10:18:20.030 [ERROR]     at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
10:18:20.030 [ERROR]     at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
10:18:20.030 [ERROR]     at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
10:18:20.030 [ERROR]     at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
10:18:20.030 [ERROR]     at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
10:18:20.030 [ERROR]     at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
10:18:20.030 [ERROR]     at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
10:18:20.031 [ERROR]     at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
10:18:20.031 [ERROR]     at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
10:18:20.031 [ERROR]     at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
10:18:20.031 [ERROR]     at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
10:18:20.031 [ERROR]     ... 83 more
10:18:20.031 [ERROR]  
10:18:20.031 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
10:18:20.031 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1s
`

**Comment by AriaLyy** [comment]
你这是mac的命令吧，在win下，我使用gradle 3.5版本使用clean命令并没有出现你遇到的问题，估计是mac下gradle的问题，或者你在mac下使用3.5版本试下
