### ISSUE TITLE
3.8.10 上传文件之后检查原文件和上传后的文件的md5不一致

### ISSUE THREAD

**Issue by shoucanjun** [AriaLyy/Aria#730]
3.8.10 上传文件之后检查原文件和上传后的文件的md5不一致
## 版本
* 框架版本
3.8.10
* 系统版本
红米K20 Pro
## 错误日志

我有用网页在线检测md5的方式检测过，用源文件和上传到服务器上的文件去检测。
文件是完整的可以打开，但是文件md5不一致。
## 重现步骤
 String cookie = cookieHeader();
        HashMap<String, String> formParams = new HashMap<>();
        formParams.put("Path", currentPath);
        HttpOption option = new HttpOption()
                .setRequestType(RequestEnum.POST)
                .setAttachment("File")
                .useServerFileName(true)
                .addHeader("Cookie", cookie)
                .setFormFields(formParams);

 long taskId = Aria.upload(context.get())
                .load(destFile.getPath()) // 文件路径
                .setUploadUrl(uploadHost.toString())
                .ignoreFilePathOccupy()
                .option(option)
                .create();

**Comment by AriaLyy** [comment]
检查下自家服务器的md5算法

**Comment by shoucanjun** [comment]
> 检查下自家服务器的md5算法

我用postman方式上传上去md5都是一致的。

![Screenshot_2020-08-12-20-25-30-019_org telegram m](https://user-images.githubusercontent.com/8786132/90087294-fa9cf780-dd4e-11ea-99c8-103590dd7647.jpg)

**Comment by AriaLyy** [comment]
应该是表单上传完成后只增加了`\r\n`而没有增加`boundary分割`，导致流末尾增加了两个byte

**Comment by shoucanjun** [comment]
就是header要加上 类似这个么
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryxfAhssba47FL3Jyh

**Comment by AriaLyy** [comment]
不是，另外的问题

**Comment by shoucanjun** [comment]
![8F`L _9 U52 GFP64PICCSV](https://user-images.githubusercontent.com/8786132/90209841-f6400f80-de1e-11ea-84d8-25cddfe1819e.png)
大佬，我应该只需要导入这5个module就行了吧。基础功能的话。

**Comment by AriaLyy** [comment]
是的

**Comment by shoucanjun** [comment]
之前的配置文件aria_config.xml  还是放在启动module里面么？
另外注解方面貌似没有生效，是还要根据“注解不生效方案”加入这个？

```
如果你是Android studio的module中引用的Aria，那么你还需要再app模块中添加同样的导入代码
 compile 'com.arialyy.aria:aria-core:{version code}'
 annotationProcessor 'com.arialyy.aria:aria-compiler:{version code}'
```

**Comment by shoucanjun** [comment]
> 3.8.11-beta-1

谢谢大佬
