### ISSUE TITLE
加密m3u8下载

### ISSUE THREAD

**Issue by guangmingxiong9999** [AriaLyy/Aria#731]
## 版本
* 框架版本
 implementation 'com.arialyy.aria:core:3.8.11-beta'
 implementation 'com.arialyy.aria:m3u8Component:3.8.11-beta'
* 系统版本

## 错误日志

加密的m3u8视频下载，ts文件和key文件都能下载成功，但是m3u8文件为空
请问这是为什么呢
![Uploading image.png…]()

**Comment by guangmingxiong9999** [comment]
![image](https://user-images.githubusercontent.com/19978284/90124200-9a2fa980-dd92-11ea-966c-90a8aea1f43d.png)

**Comment by AriaLyy** [comment]
是否设置了合并，这只是一个临时文件，切片都在.cc.m3u8_0中

**Comment by guangmingxiong9999** [comment]
@AriaLyy  没有设置合并，切片是在.cc.m3u8_0文件夹中，ccc.m3u8这个有数据的文件在哪呢，链接是http://pp3zvsk2n.bkt.clouddn.com/20200806/sd/15967206011811803/38475fadd55e4ecea3.m3u8 这种加密的
![image](https://user-images.githubusercontent.com/19978284/90202741-1a94ef80-de11-11ea-9cd9-d6464364c735.png)

**Comment by AriaLyy** [comment]
我使用你的url地址，是可以下载成功并合并成功的。
![image](https://user-images.githubusercontent.com/10437293/90205853-5b8f0300-de15-11ea-9041-d6421609b9e8.png)
我使用的是自动合并功能，如果你需要手动合并ts切片，需要创建自定义合并器，m3U8Entity里面含有密钥等信息，可以自行处理解密请求。
```
 static class TsMergeHandler implements ITsMergeHandler {
    public boolean merge(@Nullable M3U8Entity m3U8Entity, List<String> tsPath) {
      ALog.d("TsMergeHandler", "合并TS....");
      return false;
    }
  }
```

**Comment by guangmingxiong9999** [comment]
@AriaLyy 因为我的视频是加密的，自动合并的话不能播放，我用 option.setUseDefConvert(true);
    option.generateIndexFile();这种创建索引的方式可以了，但是URI的key值 少加了个双引号""，导致不能播放，有什么方法加上双引号吗

**Comment by guangmingxiong9999** [comment]
@AriaLyy 因为我的视频是加密的，自动合并的话不能播放，我用 option.setUseDefConvert(true);
option.generateIndexFile();这种创建索引的方式可以了，但是URI的key值 少加了个双引号""，导致不能播放，有什么方法加上双引号吗  ![image](https://user-images.githubusercontent.com/19978284/90207940-2cc75b80-de1a-11ea-826e-5ea51eb514be.png)

**Comment by AriaLyy** [comment]
使用`3.8.11-beta-1`版本，修复了uri没有双引号的问题

**Comment by guangmingxiong9999** [comment]
@AriaLyy  可以了，谢谢大佬

**Comment by scb7709** [comment]
楼主 您好 ，包含.key 的 视频 使用自动合成后不能播放，，您怎么具体怎么处理的啊  不使用自动合成的话  自己怎么操作呢？

**Comment by AttackPangHu** [comment]
楼主，我这边本地的key和ts都下好了，但是播放本地的索引文件时，exo播放器报错，ExoPlayerImplInternal: Source error. 
应该是加解密出的问题，请问我这个索引文件有问题吗？

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-DISCONTINUITY
#EXT-X-KEY:METHOD=AES-128,URI="/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/87550e2509560098399b553328ef148d.key",IV=null
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/0.ts
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/1.ts
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/2.ts
#EXTINF:3.003,

**Comment by cl19881314** [comment]
option.generateIndexFile(); 加上这个下载后加密的m3u8就可以播放了
