### ISSUE TITLE
M3U8 下载提示 404

### ISSUE THREAD

**Issue by ZhuSky** [AriaLyy/Aria#732]
m3u8 下载 配置都是默认
## 版本
* 框架版本
com.arialyy.aria:core:3.8.10
* 系统版本
Android 5.1
## 错误日志

 ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    下载失败错误，错误码：404
    com.arialyy.aria.m3u8.M3U8InfoTask.failDownload(M3U8InfoTask.java:357)
    com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:212)
    com.arialyy.aria.m3u8.M3U8InfoTask.handleBandWidth(M3U8InfoTask.java:352)
    com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:175)
    com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:104)
    com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:145)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
    java.lang.Thread.run(Thread.java:818)
    ===================================================

## 重现步骤

1. 下载地址：https://mv.cbi88.com/20200806/QjyIlyor/2000kb/hls/index.m3u8
2. 下载出错，但是这个地址确实可以播放
3.
4.

**Comment by javakam** [comment]
涛声依旧 `3.8.12`
```
添加任务，key： https://vod3.buycar5.cn/20201118/ttum6IRH/index.m3u8
新码率url：    https://vod3.buycar5.cn/20201118/ttum6IRH//20201118/ttum6IRH/1000kb/hls/index.m3u8
```
