### ISSUE TITLE
下载进行中时，杀进程问题

### ISSUE THREAD

**Issue by guangmingxiong9999** [AriaLyy/Aria#735]
## 版本
* 框架版本
 implementation 'com.arialyy.aria:core:3.8.11-beta-1'
 implementation 'com.arialyy.aria:m3u8Component:3.8.11-beta-1'
* 系统版本

## 错误日志

  ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    地址错误，请使用IVodTsUrlConverter处理你的url信息
    com.arialyy.aria.m3u8.vod.M3U8VodLoader$4.onSucceed(M3U8VodLoader.java:532)
    com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:209)
    com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:104)
    com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:146)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
    java.lang.Thread.run(Thread.java:764)
    ===================================================

## 重现步骤

1. 下载进行中时，杀掉进程
2.重新打开进入，当前是STATE_STOP 停止状态
3. 调用   Aria.download(this)
                        .load(taskid)   
                        .resume();  报错
4.

**Comment by guangmingxiong9999** [comment]
失败状态下 调用  Aria.download(this) .load(taskID.reStart();
不能重新下载 
![image](https://user-images.githubusercontent.com/19978284/90225690-59906880-de44-11ea-8cc8-70573f5ff5a9.png)

**Comment by guangmingxiong9999** [comment]
使用  Aria.download(this).removeAllTask(true); 删除所有任务时，会留一个key文件没有删除，m3u8文件和ts文件夹都能删除

**Comment by AriaLyy** [comment]
> 失败状态下 调用 Aria.download(this) .load(taskID.reStart();
> 不能重新下载
> ![image](https://user-images.githubusercontent.com/19978284/90225690-59906880-de44-11ea-8cc8-70573f5ff5a9.png)

是否是快速点击了几次，我这测试是正常的呢

**Comment by AriaLyy** [comment]
> 使用 Aria.download(this).removeAllTask(true); 删除所有任务时，会留一个key文件没有删除，m3u8文件和ts文件夹都能删除

是有这问题，后面会修复

**Comment by AriaLyy** [comment]
`3.8.12`已修复了key没被删除的问题，至于另外一个我这没有复现

**Comment by guangmingxiong9999** [comment]
@AriaLyy 停止的状态（STATE_STOP） 调用   Aria.download(this)
                        .load(taskId)    
                        .resume();    // 恢复任务
然后报错
  2020-08-17 15:38:51.308 30045-30270/com.xkb.education E/M3U8Listener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    地址错误，请使用IVodTsUrlConverter处理你的url信息
    com.arialyy.aria.m3u8.vod.M3U8VodLoader$4.onSucceed(M3U8VodLoader.java:532)
    com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:209)
    com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:104)
    com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:146)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
    java.lang.Thread.run(Thread.java:764)
    ===================================================
