### ISSUE TITLE
注解依赖问题

### ISSUE THREAD

**Issue by guangmingxiong9999** [AriaLyy/Aria#736]
## 版本
* 框架版本
    implementation 'com.arialyy.aria:core:3.8.11-beta-1'
    implementation 'com.arialyy.aria:m3u8Component:3.8.11-beta-1'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.8.11-beta-1'
* 系统版本

## 错误日志

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileOfficnetDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:officnetDebugAnnotationProcessorClasspath'.
   > Could not find com.arialyy.aria:aria-compiler:3.8.11-beta-1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.pom
       - https://dl.google.com/dl/android/maven2/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.jar
       - https://jcenter.bintray.com/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.pom
       - https://jcenter.bintray.com/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.jar
       - https://repo.maven.apache.org/maven2/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.pom
       - https://repo.maven.apache.org/maven2/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.jar
       - https://jitpack.io/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.pom
       - https://jitpack.io/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.jar
       - https://dl.bintray.com/umsdk/release/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.pom
       - https://dl.bintray.com/umsdk/release/com/arialyy/aria/aria-compiler/3.8.11-beta-1/aria-compiler-3.8.11-beta-1.jar
       - file:/F:/ANDROID/branches/branch_1.5.0/app/libs/aria-compiler-3.8.11-beta-1.jar
       - file:/F:/ANDROID/branches/branch_1.5.0/app/libs/aria-compiler.jar
     Required by:
         project :app

## 重现步骤

1.依赖注解监听，运行时报错
2. 没有使用apply plugin: 'android-apt'，已添加 
 javaCompileOptions {
      annotationProcessorOptions {
        includeCompileClasspath true
      }
    }
3.
4.

**Comment by AriaLyy** [comment]
应该是bintry网络抽风导致这个module上传失败了

**Comment by AriaLyy** [comment]
使用`3.8.12`

**Comment by guangmingxiong9999** [comment]
@AriaLyy 还是不行呀，是不是我配置有问题呢

**Comment by AriaLyy** [comment]
使用这个命令强制刷新graldew的依赖
```
./gradlew clean build --refresh-dependencies
```

**Comment by guangmingxiong9999** [comment]
@AriaLyy  不行呀
![image](https://user-images.githubusercontent.com/19978284/90377174-30711180-e0aa-11ea-84e7-443332c9775c.png)
