### ISSUE TITLE
开启下载任务,退出并取消注册后台还是在正常下载

### ISSUE THREAD

**Issue by MoonBlueSky** [AriaLyy/Aria#737]
## 版本
* 框架版本
3.8.12
* 系统版本
android 10
## 错误日志

![image](https://user-images.githubusercontent.com/38198300/90309501-bf9bef00-df1b-11ea-83b3-a1a23e987ed2.png)
可以看到取消注册之后,没有停止下载任务,同样的问题在demo中也可以复现

## 重现步骤

1.点击开始下载任务
2.点击返回退出应用
3.触发取消注册框架的方法
4.观察网速占用及日志
5.重新打开应用
6.下载进度仍在继续

## 问题
退出前是要手动取消所有任务吗,可以自己监听或者在注销时停止所有任务吗,毕竟退出了还在下载,这本来就不符合逻辑
麻烦作者大大帮忙看看哈

**Comment by AriaLyy** [comment]
如果希望退出界面，马上停止所有任务，请使用`stopAll()`方法，注册是注册任务状态的监听器，并不会操作任务
