### ISSUE TITLE
我有2个Service负责不同的下载业务，回调会互相干扰

### ISSUE THREAD

**Issue by heygays** [AriaLyy/Aria#740]
如题，因为场景不同，所需的下载配置项也不一样，所以我定制了2个Service来负责下载，也就注册了2次。都实现了DownloadListener。只要开始下载，A,BService都会回调，导致业务逻辑错乱。比如我A，BService都启动了，但是A先完成，然后B也会收到完成的回调，后续逻辑就错了。

**Comment by AriaLyy** [comment]
task 有 url, 通过url判断

**Comment by heygays** [comment]
> task 有 url, 通过url判断

url肯定是不一样的，而且我BService根本没启用下载的情况下也会收到回调。

**Comment by AriaLyy** [comment]
回调是广播的信息，每个地方有注解的地方都会回调，唯一的方案是通过url进行判断

**Comment by heygays** [comment]
好的，知道了，感谢解答！
