### ISSUE TITLE
如何透过SimpleExoPlayer播放已下载的m3u8影片

### ISSUE THREAD

**Issue by ric-lau** [AriaLyy/Aria#741]
```  
    val media = ProgressiveMediaSource
                               .Factory(DefaultDataSourceFactory(this, BuildConfig.APPLICATION_ID))
                               .createMediaSource(file.toUri())
    player.prepare(media)
```
Error:
`
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
`

**Comment by AriaLyy** [comment]
索引方式：直接播放m3u8的索引文件
合并ts方式：直接播放合并后的ts文件

**Comment by ric-lau** [comment]
尝试一些网上免费 m3u8 能成功播放。
但目前在做的专案的 m3u8 依然未能播放，查看该m3u8发现有多条 EXT-X-KEY，未知是否此原因令影片未能播放。
先谢过大神

m3u8節錄如下
```
#EXTM3U
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXT-X-KEY:METHOD=AES-128,URI="https://xxx.com/api/getkey.jsp;jsessionid=SESSION?number=0"
#EXTINF:10,
http://xxx.com/1.ts
#EXTINF:10,
http://xxx.com/2.ts
#EXT-X-KEY:METHOD=AES-128,URI="https://xxx.com/api/getkey.jsp;jsessionid=SESSION?number=1"
#EXTINF:10,
http://xxx.com/17.ts
#EXTINF:10,
http://xxx.com/18.ts
#EXT-X-ENDLIST
```

**Comment by erdayeniu** [comment]
> 试点一些网上免费 m3u8 能成功播放。
> 但目前在做的专案的 m3u8 仍继续播放，查看该 m3u8 发现的条 EXT-X-KEY，未知原因导致无法播放。
> 先谢过大神
> 
> m3u8节录如下
> 
> ```
> #EXTM3U
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-TARGETDURATION:10
> #EXT-X-KEY:METHOD=AES-128,URI="https://xxx.com/api/getkey.jsp;jsessionid=SESSION?number=0"
> #EXTINF:10,
> http://xxx.com/1.ts
> #EXTINF:10,
> http://xxx.com/2.ts
> #EXT-X-KEY:METHOD=AES-128,URI="https://xxx.com/api/getkey.jsp;jsessionid=SESSION?number=1"
> #EXTINF:10,
> http://xxx.com/17.ts
> #EXTINF:10,
> http://xxx.com/18.ts
> #EXT-X-ENDLIST
> ```

你好，我也是这样的问题，下载完成后不能播放，请问你是怎么处理的

**Comment by ric-lau** [comment]
I am using another library named RxFetch to download all ts files and keys, and then create another local m3u8 file by replacing the original m3u8 from network source to local, i.e `https://example.com.ts` to `file://local/path.ts`. Finally, you can play the local m3u8 with ExoPlayer as usual.
