### ISSUE TITLE
一次性提交大量任务并开始下载时会有很多任务处于停止状态且不会重新开始

### ISSUE THREAD

**Issue by genylife** [AriaLyy/Aria#742]
版本：3.8.10

线程池大小2，最大任务数2

一次性提交24个任务并开始，很多任务都处于停止状态

**Comment by AriaLyy** [comment]
使用的模式是`now`还是`wait`?

**Comment by genylife** [comment]
使用的是wait模式，看起来像是并发的问题。
停止的原因是队列满了加任务时会出队一个任务并停止掉

**Comment by xz-dev** [comment]
遇到了相同的问题，且任务暂停时不会回调注册的暂停函数，任务需要手动暂停再开始才能恢复
