### ISSUE TITLE
android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by pys200603027** [AriaLyy/Aria#744]
```
cannot rollback - no transaction is active (code 1)

com.arialyy.aria.orm.DelegateUpdate.updateManyData(DelegateUpdate.java:11)
```

## 版本
* 框架版本 3.8.10

* 系统版本 Android 9.0

## 错误日志

```

1 android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
--
2 android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:569)
3 android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
4 android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
5 android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:566)
6 com.arialyy.aria.orm.DelegateUpdate.updateManyData(DelegateUpdate.java:11)
7 com.arialyy.aria.orm.DelegateWrapper.updateManyData(DelegateWrapper.java:1)
8 com.arialyy.aria.orm.DbEntity.saveAll(DbEntity.java:14)
9 com.arialyy.aria.core.common.RecordHandler.saveRecord(RecordHandler.java:4)
10 com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:14)
11 com.arialyy.aria.m3u8.vod.M3U8VodLoader.startThreadTask(M3U8VodLoader.java:2)
12 com.arialyy.aria.m3u8.vod.M3U8VodLoader.access$2300(M3U8VodLoader.java:1)
13 com.arialyy.aria.m3u8.vod.M3U8VodLoader$4.onSucceed(M3U8VodLoader.java:20)
14 com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:47)
15 com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:8)
16 com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:3)
17 com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:8)
18 com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:4)
19 java.lang.Thread.run(Thread.java:764)


```

## 重现步骤
bugly 获取到的日志

**Comment by OneGreenHand** [comment]
我也有这个问题
问题描述
android.database.sqlite.SQLiteException
Can't upgrade read-only database from version 0 to 58: AndroidAria.db
依赖版本
3.8.10以下吧
设备机型
OPPO A37M
系统版本
Android 5.1,level 22
问题详情
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:244)
android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java:179)
com.arialyy.aria.orm.SqlHelper.getReadableDatabase(SqlHelper.java:166)
com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:140)
com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:39)
com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:47)
com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:140)
com.arialyy.aria.core.AriaManager.initData(AriaManager.java:117)
com.arialyy.aria.core.AriaManager.init(AriaManager.java:108)
com.arialyy.aria.core.Aria.get(Aria.java:117)
com.arialyy.aria.core.Aria.download(Aria.java:90)

**Comment by AriaLyy** [comment]
你这个应该是用户自己拷贝了数据库，而没有拷贝数据库的版本信息导致的，我这并没有数据库版本为0的情况

**Comment by OneGreenHand** [comment]
这样子的吗
