### ISSUE TITLE
Download.onNoSupportBreakPoint注解 

### ISSUE THREAD

**Issue by Jasperben** [AriaLyy/Aria#745]
/**
   * "@Download.onNoSupportBreakPoint"注解，如果该任务不支持断点，Aria会调用该方法
   *
   * @deprecated 该注解将在后续版本删除
   */
  @Deprecated
  @Retention(RetentionPolicy.CLASS) @Target(ElementType.METHOD) @interface onNoSupportBreakPoint {
    String[] value() default { AriaConstance.NO_URL };
  }

这个方法有没有替代的方法

**Comment by AriaLyy** [comment]
没有，这个没啥用处，后面会移除

**Comment by zhuhonglei** [comment]
> 没有，这个没啥用处，后面会移除

别去掉呀,很有用,不支持断点的任务,就不让用户暂停下载了
