### ISSUE TITLE
下载的文件大小不一致

### ISSUE THREAD

**Issue by Jasperben** [AriaLyy/Aria#746]
版本：3.8.12

下载大文件：实际大小：810M，下载完成后的大小：650M

useBlock value="true"开启，会分三块进行下载，但是三个块的大小加起来跟实际文件大小一致，但是下载完成合并文件之后文件就变成了650M

useBlock value="false"  下载后文件大小正常

所以我怀疑是分块下载之后合并包出现了问题

**Comment by AriaLyy** [comment]
必现的吗？

**Comment by Jasperben** [comment]
有一台机器必现  但是其他机器没有发现问题 （所以机器都是同一型号）

**Comment by AriaLyy** [comment]
我看下能不能重现吧。。
