### ISSUE TITLE
m3u8下载能否实现这样需求： 下载的时候 按照给下载设置的（ .setFilePath(local) ） 路径。直接把这个 m3u8的 文件下载到本地（包含的切片信息，例如：把任意m3u8链接放到 google 浏览器就会自动下载 这个文件）。然后下载

### ISSUE THREAD

**Issue by scb7709** [AriaLyy/Aria#751]
## 版本
* 框架版本：-----需求

* 系统版本--------需求

## 错误日志

无

## 重现步骤

m3u8下载能否实现这样需求： 下载的时候 按照给下载设置的（ .setFilePath(local) ） 路径。直接把这个 m3u8的 文件下载到本地（包含的切片信息，例如：把任意m3u8链接放到 google 浏览器就会自动下载 这个文件）。然后下载完每个.ts小文件之后   在把刚在的那个本地的 fire  对应的每个.ts 切片换成本地的.ts 切片   当然如果有key.key  也要 下载后换成本地的 。。。。。最后全部下载完之后也不用合成，，我播放器直接就播这个全部是本地.ts

**Comment by AriaLyy** [comment]
直接播放索引
```
M3U8VodOption option = new M3U8VodOption();
    option.setUseDefConvert(true);
    option.generateIndexFile();
```

**Comment by scb7709** [comment]
您好 我已经实现下载了 但是直接播放本地那个地址 是不能播放的，在SD里找到那个文件 用手机自带的其他视频软件 也不能播放，是需要什么操作么？    我的本地地址是  /storage/emulated/0/bwsofa/videos/77/170.m3u8    其内部信息是   

#EXTM3U

#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:5

#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/0.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/1.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/2.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/3.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/4.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/5.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/6.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/7.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/8.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/9.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/10.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/11.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/12.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/13.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/14.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/15.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/16.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/17.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/18.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/19.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/20.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/21.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/22.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/23.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/24.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/25.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/26.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/27.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/28.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/29.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/30.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/31.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/32.ts
#EXTINF:4.003966666666667,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/33.ts
#EXTINF:0.8651333333333184,
/storage/emulated/0/bwsofa/videos/77/.170.m3u8_0/34.ts
#EXT-X-ENDLIST
