### ISSUE TITLE
考虑把核心下载功能封装为工具jar包吗?

### ISSUE THREAD

**Issue by Stars-One** [AriaLyy/Aria#752]
如题,我打算使用Kotlin引用这个牛批的下载框架编写一个下载器软件,但是好像是Android才能使用?

**Comment by AriaLyy** [comment]
这里面有很多东西都使用了android的api

**Comment by Stars-One** [comment]
那能简单介绍介绍多线程的实现关键点吗?还有多线程下载应该需要考虑哪几方面的问题?下载相关的类大概在哪个包里?我想参考着自己实现
