### ISSUE TITLE
下载完成后taskComplete回调方法执行两次

### ISSUE THREAD

**Issue by duanjunyuan** [AriaLyy/Aria#753]
## 版本
com.arialyy.aria:core:3.8.12
com.arialyy.aria:compiler:3.8.12

## 错误信息
taskComplete回调方法会执行两次

## 重现步骤
1.在某个fragment初始化时Aria.download(this).register()，但是在销毁时不执行Aria.download(this).unRegister()
2.在该fragment中开启一个单文件下载任务
3.在上述任务完成后，去android设备对应目录下删除刚才下载的文件
4.重新进入该fragment、下载与上次相同的文件，当下载完成时，taskComplete会执行两次

**Comment by AriaLyy** [comment]
注解是全局的，因此你需要通过task.getUrl()判断是否是当前的fragment的url

**Comment by duanjunyuan** [comment]
> 是只下载一个文件，然后回调了两次？

是的
