### ISSUE TITLE
使用索引下载option.generateIndexFile();怎么改变内部小链接的地址（需要拼接本地服务器地址）

### ISSUE THREAD

**Issue by scb7709** [AriaLyy/Aria#756]
## 版本
* 框架版本
implementation 'com.arialyy.aria:core:3.8.12'
annotationProcessor 'com.arialyy.aria:compiler:3.8.12'
implementation 'com.arialyy.aria:m3u8Component:3.8.12'
或者 任意版本
* 系统版本
任意安卓版本
## 错误日志

无
## 重现步骤

使用索引下载option.generateIndexFile();怎么改变内部小链接的地址（需要拼接本地服务器地址）。

setMergeHandler（），generateIndexFile();这个方法不能共存。但是我本地播放的话  内部小链接地址是需要拼接本地服务器地址的
 /**
   * 如果你希望使用自行处理ts文件的合并，可以使用{@link ITsMergeHandler}处理ts文件的合并
   * 需要注意的是：只有{@link #merge(boolean)}设置合并ts文件，该方法才会生效
   */
  public OP setMergeHandler(ITsMergeHandler mergeHandler) {
    CheckUtil.checkMemberClass(mergeHandler.getClass());
    this.mergeHandler = mergeHandler;
    return (OP) this;
  }

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/597
