### ISSUE TITLE
Aria.download(this).register(); 报错什么情况

### ISSUE THREAD

**Issue by blxc321** [AriaLyy/Aria#76]
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err: 

java.lang.ClassNotFoundException: com.arialyy.aria.ProxyClassCounter

android studio  gradle:
用的这个版本的
compile 'com.arialyy.aria:aria-core:3.2.6'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.6'

07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at java.lang.Class.classForName(Native Method)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at java.lang.Class.forName(Class.java:400)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at java.lang.Class.forName(Class.java:326)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at com.arialyy.aria.core.upload.ProxyHelper.init(ProxyHelper.java:49)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at com.arialyy.aria.core.upload.ProxyHelper.<init>(ProxyHelper.java:35)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at com.arialyy.aria.core.upload.ProxyHelper.getInstance(ProxyHelper.java:41)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at com.arialyy.aria.core.download.DownloadReceiver.register(DownloadReceiver.java:91)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at xyz.limaolin.myapplication.ui.fragment.activity.MusicManageActivity.onCreate(MusicManageActivity.java:38)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-20 05:19:50.727 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.arialyy.aria.ProxyClassCounter" on path: DexPathList[[zip file "/data/app/xyz.limaolin.myapplication-1/base.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_dependencies_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_0_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_1_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_2_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_3_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_4_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_5_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_6_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_7_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_8_apk.apk", zip file "/data/app/xyz.limaolin.myapplication-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/xyz.limaolin.myapplication-1/lib/x86, /data/app/xyz.limaolin.myapplication-1/base.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_dependencies_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_0_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_1_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_2_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_3_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_4_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_5_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_6_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_7_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_8_apk.apk!/lib/x86, /data/app/xyz.limaolin.myapplication-1/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-20 05:19:50.728 24534-24534/xyz.limaolin.myapplication W/System.err: 	... 20 more

**Comment by AriaLyy** [comment]
clean 一下试试，估计是com.arialyy.aria.ProxyClassCounter没有生成成功
