### ISSUE TITLE
无法下载文本文件

### ISSUE THREAD

**Issue by nbwzlyd** [AriaLyy/Aria#771]
我想下载一个文本文件到本地。链接如下
https://gitee.com/huang-junhua/iptv/raw/master/guonei.m3u8
然后本地去解析，但是报错
报错如下
<img width="960" alt="WX20200922-205105@2x" src="https://user-images.githubusercontent.com/10379082/93884752-dfda7d00-fd15-11ea-9443-7a1d5e7684b8.png">

**Comment by nbwzlyd** [comment]
用android自带的DownlaodManger没问题

**Comment by AriaLyy** [comment]
m3u8 无法下载参考这个：https://github.com/AriaLyy/Aria/issues/597

**Comment by nbwzlyd** [comment]
> m3u8 无法下载参考这个：#597

不不不，你理解错了，我是想下载这个文本文件，不是下载视频，就是纯下载下来这个文本文件，然后自己去解析m3u8

**Comment by AriaLyy** [comment]
感谢反馈，已确认问题，后面会修复

**Comment by AriaLyy** [comment]
3.8.15 已经修复了这个问题
