### ISSUE TITLE
下载完成后 出错了

### ISSUE THREAD

**Issue by Jasperben** [AriaLyy/Aria#772]
SSL handshake aborted: ssl=0x95e26208: I/O error during system call, Connection reset by peer
com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:93)
com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
使用场景是什么？

**Comment by Jasperben** [comment]
下载大文件  已经走了onTaskComplete方法  这个时候报错了
