### ISSUE TITLE
下载报错、程序崩溃android.database.sqlite.SQLiteDiskIOException

### ISSUE THREAD

**Issue by simple-11** [AriaLyy/Aria#773]
下载视频的时候报错，发生次数：2,450   ，影响用户数：783
android.database.sqlite.SQLiteDiskIOException disk I/O error (code 4874) com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java)

bugly给提示：
该异常表示磁盘输入/输出错误，可能是数据操作太频繁导致的。
应用程序启动时，调用RSSDatabase的构造函数，UI Thread锁定了你的目标的数据库，随后你又尝试插入数据到被UI线程锁定的数据库。 将抛出一个异常，因为db被lock了。

目前使用的版本：
aria_download=com.arialyy.aria:core:3.8.12
aria_download_compiler=com.arialyy.aria:compiler:3.8.12
aria_download_m3u8=com.arialyy.aria:m3u8Component:3.8.12
错误日志：

Caused by:
--
5 android.database.sqlite.SQLiteDiskIOException:disk I/O error (code 4874)
6 android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
7 android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:605)
8 android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
9 android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
10 android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:886)
11 android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:874)
12 android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:894)
13 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
14 android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
15 com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java:179)
16 com.arialyy.aria.orm.SqlHelper.getReadableDatabase(SqlHelper.java:166)
17 com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:140)
18 com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:39)
19 com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:47)
20 com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:114)
21 com.arialyy.aria.core.AriaManager.initData(AriaManager.java:91)
22 com.arialyy.aria.core.AriaManager.init(AriaManager.java:82)
23 com.arialyy.aria.core.Aria.get(Aria.java:118)
24 com.arialyy.aria.core.Aria.init(Aria.java:128)

**Comment by AriaLyy** [comment]
我研究下看看

**Comment by simple-11** [comment]
好的。

**Comment by simple-11** [comment]
你好，我们这边视频加了防盗链，导致现在不能下载m3u8视频资源了，请问需要配置什么吗？

**Comment by AriaLyy** [comment]
是对m3u8加密了吗？

**Comment by simple-11** [comment]
没有加密，防盗链那个解决了，你还是看一下  SQLiteDiskIOException:disk 这个导致的init初始化崩溃吧。

**Comment by simple-11** [comment]
网络APN | Wi-Fi | 是否ROOT | 否
-- | -- | -- | --
可用内存大小 | 518.82 MB ( 27.92% ) | 可用存储空间 | 0.00 KB ( 0.00% )
可用SD卡大小 | 0.00 KB ( 0.00% ) | Bugly SDK版本号 | 3.2.33-3.7.471
ROM详情 | XiaoMi/MIUI/V10

报错的手机都没有容量
可用SD卡大小 | 0.00 KB ( 0.00% )    可用存储空间 | 0.00 KB ( 0.00% )

**Comment by simple-11** [comment]
#87452 android.database.sqlite.SQLiteException
not a writable directory (code 1): , while compiling: PRAGMA temp_store_directory = '/data/data/com.fubo.miyou/cache/AriaDbCacheDir'

com.networkbench.agent.impl.instrumentation.NBSSQLiteInstrumentation.execSQL(SourceFile)


网络APN | Wi-Fi | 是否ROOT | 否
-- | -- | -- | --
可用内存大小 | 518.82 MB ( 27.92% ) | 可用存储空间 | 0.00 KB ( 0.00% )
可用SD卡大小 | 0.00 KB ( 0.00% ) | Bugly SDK版本号 | 3.2.33-3.7.471
ROM详情 | XiaoMi/MIUI/V10


涉及到你这个下载库的异常，有一个统一的共同点：就是SD卡大小 | 0.00 KB ( 0.00% ) 可用存储空间 | 0.00 KB ( 0.00% )

**Comment by wangkai9799** [comment]
请问这个问题修复了吗？
