### ISSUE TITLE
M3U8下载链接会自动加上我的域名

### ISSUE THREAD

**Issue by JavanLuo** [AriaLyy/Aria#779]
举例：
M3U8文件地址是  http://www.baidu.com/1.m3u8

Log显示 读取到其中一切片的地址是 http://v3.baidupcs.com/video/1.ts

开始下载，Log中报错信息如下：
 连接错误，http错误码：404，http://www.baidu.com/http://v3.baidupcs.com/video/1.ts

原因就是 下载时自动加上了我的域名
请问这个问题该怎样解决

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/597

**Comment by JavanLuo** [comment]
<img width="748" alt="截屏2020-10-17 下午4 08 14" src="https://user-images.githubusercontent.com/57438412/96331835-14322680-1093-11eb-8901-987c002bcc63.png">

是看了 配置说明 还会出现这种情况。
在转换时打Log 发现没有进去，Log 没有输出，找不到原因
