### ISSUE TITLE
下载本地KEY的问题

### ISSUE THREAD

**Issue by AttackPangHu** [AriaLyy/Aria#780]
## 版本
* 框架版本 3.8.14

* 系统版本

## 重现步骤
就是我之前下载到本地的M3U8文件一直不能播，exo播放器报错，然后我找到了原因，是因为我服务器上的M3U8的key没有向量，然后这边generateIndexFile的时候，写入#EXT-X-KEY的时候，自动的加上了IV=NULL 然后读取到这个IV的时候EXO播放器就报错bigIntegerNull的异常，就是能不能自定义写入IV或者原M3U8没有IV的时候，不写入IV=NULL

**Comment by AriaLyy** [comment]
应该是原始的m3u8文件中没有iv信息

**Comment by AttackPangHu** [comment]
是的，這個時候如果原文件沒有IV的時候，在generateIndexFile裡面可以加個判斷，沒有IV就不寫入IV=NULL

**Comment by AttackPangHu** [comment]
> 应该是原始的m3u8文件中没有iv信息

这个问题我已经PR了，你看下我提交的内容，没问题的话，合并下然后重新发布吧

**Comment by AriaLyy** [comment]
没有看到请求呢？～～

**Comment by AttackPangHu** [comment]
我看看，稍等下

**Comment by AttackPangHu** [comment]
我是直接在master上提交的，没有新建自己的分支，我看到提交记录

**Comment by AriaLyy** [comment]
使用`3.8.15-bate-1`应该是可以了

**Comment by AttackPangHu** [comment]
好的，謝謝，辛苦了。
