### ISSUE TITLE
3.8.12 可能线程泄露

### ISSUE THREAD

**Issue by FargoZheng** [AriaLyy/Aria#781]
## 版本
* 3.8.12

* android 9.0

## 错误日志
![微信截图_20201009122531](https://user-images.githubusercontent.com/24689258/95543249-99319600-0a2a-11eb-803a-24b80c0f744a.png)

## 重现步骤

每次下载m3u8之后，都会有这条线程cpu 100%，而启动另一个m3u8任务之后，上一个不会release，可能是线程泄露了

**Comment by Wudelin** [comment]
下载m3u8 后cpu 飙高，必现
