### ISSUE TITLE
大文件下载失败，文件有2.06G，用Demo测试也是下载失败

### ISSUE THREAD

**Issue by wlxfxy** [AriaLyy/Aria#79]

**Comment by AriaLyy** [comment]
我这边用demo测试是可以下载2G的文件的，估计你那是内存卡空间不足，或者你文件长度是放在header头里面的（这个问题控制会报文件长度小于0的错误，现在已经处理）。如果不是这两个问题的话，你那能不能提供下日志？
![nba 2k](http://upload-images.jianshu.io/upload_images/1824042-d7c7201b7ce4bc46.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by wlxfxy** [comment]
07-24 15:20:27.850 12382-12463/com.arialyy.simple E/FileInfoThread: 任务【】下载失败，文件长度小于0
07-24 15:20:27.850 12382-12463/com.arialyy.simple E/SimpleDownloadUtil: 任务【】下载失败，文件长度小于0
用demo测试，log打印的这两条错误日志

**Comment by AriaLyy** [comment]
【】里面是什么都没有吗？

**Comment by wlxfxy** [comment]
有的，只不过是公司项目，源文件不好放在上面，需要的话我私信你/(ㄒoㄒ)/~~

**Comment by AriaLyy** [comment]
这个懂了，问题应该是出在文件长度那，文件长度应该是放在header中，导致我无法通过getContentLength()获取正确的长度，这问题代码已经改了，晚上会重新上传到jcenter

**Comment by wlxfxy** [comment]
好的，辛苦了O(∩_∩)O

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:aria-core:3.2.8'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.8'
```
已经修复了该问题

**Comment by wlxfxy** [comment]
thx

**Comment by wlxfxy** [comment]
还是不行，错误日志如下：
===============================================================
E/SingleThreadTask: 获取流失败
   ExceptionDetailed:
      ====================Exception Info====================
                                                               java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=0 dst.length=65536 dstPos=38298 length=-38298
                                                               java.lang.System.arraycopy(Native Method)
                                                               com.arialyy.aria.util.BufferedRandomAccessFile.writeAtMost(BufferedRandomAccessFile.java:325)
                                                               com.arialyy.aria.util.BufferedRandomAccessFile.write(BufferedRandomAccessFile.java:298)
                                                               com.arialyy.aria.core.download.downloader.SingleThreadTask.run(SingleThreadTask.java:115)
                                                               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               java.lang.Thread.run(Thread.java:841)
                                                               ===================================================
 ExceptionDetailed:
====================Exception Info====================
                                                         java.io.IOException: ftruncate failed: EINVAL (Invalid argument)
                                                         java.io.RandomAccessFile.setLength(RandomAccessFile.java:628)
                                                         com.arialyy.aria.core.download.downloader.Downloader.createNewFile(Downloader.java:371)
                                                         com.arialyy.aria.core.download.downloader.Downloader.handleBreakpoint(Downloader.java:330)
                                                         com.arialyy.aria.core.download.downloader.Downloader.startFlow(Downloader.java:102)
                                                         com.arialyy.aria.core.download.downloader.Downloader.run(Downloader.java:82)
                                                         java.lang.Thread.run(Thread.java:841)
                                                         【Caused by】: libcore.io.ErrnoException: ftruncate failed: EINVAL (Invalid argument)
                                                         libcore.io.Posix.ftruncate(Native Method)
                                                         libcore.io.BlockGuardOs.ftruncate(BlockGuardOs.java:102)
                                                         java.io.RandomAccessFile.setLength(RandomAccessFile.java:626)
                                                         com.arialyy.aria.core.download.downloader.Downloader.createNewFile(Downloader.java:371)
                                                         com.arialyy.aria.core.download.downloader.Downloader.handleBreakpoint(Downloader.java:330)
                                                         com.arialyy.aria.core.download.downloader.Downloader.startFlow(Downloader.java:102)
                                                         com.arialyy.aria.core.download.downloader.Downloader.run(Downloader.java:82)
                                                         java.lang.Thread.run(Thread.java:841)
                                                         ===================================================

**Comment by AriaLyy** [comment]
这就奇怪了，加个群，把地址发我看看吧，群：524329160

**Comment by wlxfxy** [comment]
OK
