### ISSUE TITLE
杀掉进程的问题

### ISSUE THREAD

**Issue by AttackPangHu** [AriaLyy/Aria#792]
## 版本
* 框架版本  
3.8.15-bate-1
* 系统版本

## 重现步骤

1.杀掉进程后，我调用恢复所有下载，但是M3U8下载报错，错误信息是Aria M3U8 Exception:
    下载失败错误，错误码：403，然后我Debug看M3U8Entity的downloadUrl和filePath是一样的

**Comment by AttackPangHu** [comment]
我们服务器这边做了sign认证的，就是M3U8的download地址能不能换成第二级的真实地址？

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/597 可以自己定义转换器

**Comment by AttackPangHu** [comment]
2020-10-21 15:54:16.552 29018-29196/com.prince.hyv2 E/M3U8Listener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    no protocol

**Comment by AttackPangHu** [comment]
我是自定义的转换器，也能下载，就是恢复下载有问题，有一个o protocol的错误

**Comment by AttackPangHu** [comment]
就是做了防盗链的处理，就是最外层的M3U8只能请求一次，然后拿解析后的第二层M3U8的真实地址下载，就是自定义转换器转换后的地址，但是本地SQLite保存的是最外层的地址，不是转换器转换后的地址，导致恢复下载的时候还是去请求最外层的地址，但是最外层的地址做了防盗链处理，所以这个时候，恢复下载就没用了

**Comment by AttackPangHu** [comment]
刚看了源码，在handleBandWidth的时候，只是把bandWidthM3u8Url拿来一次性使用，没有保存起来。如果要恢复下载，下次是请求的最外层的M3U8，但如果最外层的访问不了的话，就无法下载了，M3U8这里能不能做下处理，就是如果自定义了handleBandWidth，你的DBEntity保存downloadUrl的时候，保存处理后的M3U8地址

**Comment by AttackPangHu** [comment]
@M3U8.onPeerStart   @M3U8.onPeerComplete    @M3U8.onPeerFail  我看到你demo里有几个M3U8的注解，文档没看到，我等下去研究下，看到你有在dataCall里面修改了downloadEntity的url，不知道这里可不可以做处理

**Comment by AttackPangHu** [comment]
找到个折中的方案了，就是在解析第二层M3U8的时候，我把真实的地址赋值给downloadEntity，然后调用sava()修改了sqlite。
