### ISSUE TITLE
用了这个下载后,360加固后就下载不了了.反复测试两次。

### ISSUE THREAD

**Issue by YLAndsoft** [AriaLyy/Aria#794]
用了这个下载后,360加固后就下载不了了.反复测试两次。最后只能换一个加固平台了。

**Comment by clairelee826** [comment]
我没有出现这个问题

**Comment by YLAndsoft** [comment]
我在测试一下去吧.如果还是出现我就把错误日志发到交流群里问问。

**Comment by kokobebekoko** [comment]
> 
> 
> 用了这个下载后,360加固后就下载不了了.反复测试两次。最后只能换一个加固平台了。

你好问下 解决了吗 我也遇到这个问题了
