### ISSUE TITLE
使用实现DownloadTaskListener等接口监听回调时，下载完成后调用Aria.download(this).unRegister()，实现DownloadTaskListener的监听类并没有销毁移除，导致其他加监听下载出现多个回调

### ISSUE THREAD

**Issue by sunlunchang1994** [AriaLyy/Aria#795]
## 版本
* 框架版本
3.8.14
* 系统版本

## 错误日志

没有错误日志

## 重现步骤

1.在下载文件的model实现DownloadTaskListener进行下载监听
2.下载完成后在调用Aria.download(this).unRegister()（其中this和注册时是同一个对象）
3.再次进入该页面该model重复1、2步骤
4.实现DownloadTaskListener的回调中会出现2次监听结果，多次进入回调结果会随调用次数增减
目前是在unRegister()后手动调用TaskSchedulers.getInstance().unRegister(this)来解决的

**Comment by PockerKID** [comment]
用3.8.15，也是在下载文件的model初始化时Register，然后下次初始化新的之前会把旧的先unRegister(不是下载完立即unRegister)，然后新的初始化好，下同一个文件，下载完毕会触发两次onComplete。搜了下issues，我测试步骤跟 #753 老哥的步骤差不多，第一次下载下了98%左右停掉了，然后拷贝了一份文件，继续下完后删掉；然后把98%的文件拷回到之前的目录，重新new 一个model走一遍下载，然后就会出发两次了。继续重复的话，触发次数也在增加。
目前按照 @sunlunchang1994 的方法，在unRegister()后手动调用TaskSchedulers.getInstance().unRegister(this)确实可以暂时解决这个问题
