### ISSUE TITLE
#EXT-X-PRIVINF 类型的m3u8文件切片地址返回的不对

### ISSUE THREAD

**Issue by ZhuSky** [AriaLyy/Aria#796]
## 版本
* 框架版本

* 系统版本

## 错误日志

![image](https://user-images.githubusercontent.com/18596232/97828064-fdc9d300-1d00-11eb-8d19-f55b908a79b3.png)

## 重现步骤

1. 播放地址：https:\/\/5.voooe.cn\/cache\/youku\/4e00b49a6e4f11155967c2cb3385a2ab.m3u8
2. ts分片地址 返回的全部都是EXT-X-PRIVINF:FILESIZE=xxxxx 这样的，导致下载失败

@AriaLyy 有啥方法能处理一下吗？
感谢🙏

**Comment by AriaLyy** [comment]
这个标签应该不影响吧～～

**Comment by ZhuSky** [comment]
![image](https://user-images.githubusercontent.com/18596232/98061746-8bcfc600-1e87-11eb-861d-06ba94528f29.png)

@AriaLyy 
IVodTsUrlConverter 返回的切片url不对

**Comment by ZhuSky** [comment]
版本：
 api 'com.arialyy.aria:core:3.8.14'
 annotationProcessor 'com.arialyy.aria:compiler:3.8.14'
 api 'com.arialyy.aria:m3u8Component:3.8.14'

**Comment by ZhuSky** [comment]
@AriaLyy 目前有什么办法能解决吗？

**Comment by AriaLyy** [comment]
这个不是标准协议，这是你们自己加的吧，[rfc8216](https://tools.ietf.org/html/rfc8216)没有这个字段~~

**Comment by ZhuSky** [comment]
😂 那都不重要，主要是我现在卡在这了，不知道怎么处理了

**Comment by ZhuSky** [comment]
您有什么好办法呢🙏🙏🙏

**Comment by AriaLyy** [comment]
可以把源码下下来，自己修改[L157](https://github.com/AriaLyy/Aria/blob/0152187aa8aa74b54d7085818e934f76a3fedf24/M3U8Component/src/main/java/com/arialyy/aria/m3u8/M3U8InfoTask.java#L157)这块里面的代码

**Comment by ZhuSky** [comment]
好的，🙏多谢

**Comment by ZhuSky** [comment]
对了 问您一下，这个问题有计划在后续的版本中修复嘛？
