### ISSUE TITLE
SFTP使用M3U8插件何意？

### ISSUE THREAD

**Issue by guodongAndroid** [AriaLyy/Aria#798]
![image](https://user-images.githubusercontent.com/19586334/98344285-ffbbcb00-204d-11eb-8424-704559080440.png)

**Comment by AriaLyy** [comment]
手抖了～～

**Comment by guodongAndroid** [comment]
我这边提示以下错误：
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.ietf.jgss.Oid"

**Comment by guodongAndroid** [comment]
![image](https://user-images.githubusercontent.com/19586334/98350828-d489a980-2056-11eb-89ad-eb943e9b0bcd.png)

**Comment by AriaLyy** [comment]
感谢反馈，已经修复了那个手抖的问题，至于class not found 应该是网络的问题，依赖库没有下下来
