### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by yangqb** [AriaLyy/Aria#8]
有的文件无法下载http://kotlinlang.org/docs/kotlin-docs.pdf
有的需要SSL认证

**Comment by AriaLyy** [comment]
感谢您的反馈，现在已经在考虑如何实现SSL (https:)协议的下载，预计下一个版本会支持该协议的下载地址

**Comment by AriaLyy** [comment]
你好，你提供的这个地址，我没有使用https链接一样可以进行下载......你检查下网络，看看是不是由于网络原因导致该地址不能下载

**Comment by yangqb** [comment]
我加了SSL认证导致无法下载，错误信息ClassCastException，但是这是http链接

**Comment by AriaLyy** [comment]
你SSL认证是加在哪的？

**Comment by yangqb** [comment]
DownloadUtil类里面的run方法加的，错误出现在这句代码上HttpsURLConnection https = (HttpsURLConnection)url.openConnection();

**Comment by AriaLyy** [comment]
如果你的地址是Http协议请求，那么url.openConnection();返回的是HttpURLConnection而不是HttpsURLConnection，这时如果你强制转换HttpsURLConnection，那么将导致ClassCastException类型转换异常，添加ssl认证方法，建议参考https://developer.android.com/training/articles/security-ssl.html?hl=zh-cn

**Comment by yangqb** [comment]
非常感谢 已经解决了，但是还有一个问题，任务下载好像要等大概几十秒才会开始下载，这个是正常的吗

**Comment by AriaLyy** [comment]
HttpUrlConnection 连接是阻塞的，由于网络或者服务器响应等原因，等待时长各不相同。在Aria里，由于有OnPre回调，因此在获取文件信息线程那不做阻塞处理，如果你在onStart执行更新界面的操作，就会出现界面等在的情况，为了让界面看起来没有等待，你可以在onPre方法中先行处理你的界面。
而暂停和取消使用了线程池，处理了阻塞连接，所以你可以直接使用onStop等回调直接更新界面
