### ISSUE TITLE
根据ID删除单个任务无效

### ISSUE THREAD

**Issue by AttackPangHu** [AriaLyy/Aria#812]
## 版本
* 3.8.15

* 系统版本
 Android10

## 重现步骤
Aria.download(this).load(mAdapter.getItem(position).getId()).cancel(false);
调用上面那段代码后，有的任务能删除，有的删除不了。我adapter能删除，但是我下次进入下载管理界面，重新从下载数据库读存在的任务时，一些删除的任务又出来了
我获取所有存在的任务的API  Aria.download(this).getTotalTaskList()

**Comment by ZS-ZhangsShun** [comment]
我也遇到同样的问题，当前同时正在下载的最大任务是2，此时你删除第三条任务就会失败

**Comment by ZS-ZhangsShun** [comment]
我也遇到同样的问题，当前同时正在下载的最大任务是2，此时你删除第三条任务就会失败
