### ISSUE TITLE
关于M3U8恢复下载的问题

### ISSUE THREAD

**Issue by AttackPangHu** [AriaLyy/Aria#813]
## 版本
* 3.8.15

## 重现步骤

就是我M3U8的下载，调用resumeAllTask没用，会报错com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    地址错误，请使用IVodTsUrlConverter处理你的url信息。这里解决需要重新配置M3U8的一些转换器，这里能不能提个需求，就是可以提供个全局配置M3U8的API，这样的话，调用resumeAllTask的时候，M3U8的任务也可以正常下载。

**Comment by qq570026938** [comment]
我也遇到相关问题了
