### ISSUE TITLE
kotlin  没有Aria的注解方法

### ISSUE THREAD

**Issue by dx-shaar** [AriaLyy/Aria#823]
## 版本
* 框架版本
3.8.15
* 系统版本
5.1
## 错误日志

E/DownloadReceiver: 没有Aria的注解方法，详情见

## 重现步骤

class HttpDownloadFile {
    fun downloadApk(url: String){
        Aria.download(this).register();
        // 首先保存图片 创建文件夹
        val appDir = File(Environment.getExternalStorageDirectory(), "cs")
        if (!appDir.exists()) {
            appDir.mkdir()
        }
        Aria.download(this)
                .load(url)     //读取下载地址
                .setFilePath(appDir.path + "/app.apk") //设置文件保存的完整路径
                .create();
    }

    @Download.onTaskRunning
    fun running(task: DownloadTask?) {
        Log.d("downapk", "running")
    }
}

app build.gradle 
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
module
    annotationProcessor  "com.arialyy.aria:compiler:${Versions.ariaVersions}"

**Comment by dx-shaar** [comment]
kotlin 1.4.21

**Comment by EmMper** [comment]
好好看看别人写的readme你也不至于提这个问题。

>通过注解获取任务执行状态 注意：
注解回掉采用Apt的方式实现，所以，你不需要担心这会影响你机器的性能

>如果你使用的是kotlin，请使用kotlin官方提供的方法配置apt，[kotlin kapt官方配置传送门](https://www.kotlincn.net/docs/reference/kapt.html)
