### ISSUE TITLE
组下载涉及的几个问题

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#84]
有两个疑问，麻烦百忙之中给予解答：
1.Aria.download(this).removeAllTask(true)执行完之后，Aria.download(this).getTotleTaskList().size()返回的个数是否应该是0？目前执行remove之后，任务个数不变，多次执行会报如下错误：
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                        at com.arialyy.aria.core.command.normal.CancelAllCmd.handleDownloadRemove(CancelAllCmd.java:63)

2.假设第一次组下载了三个文件，执行完成之后，调用removeAllTask方法，删除任务，再次使用组下载之前的三个文件，是否应该是新的task？会重新下载一次？

**Comment by AriaLyy** [comment]
1.好的，感谢反馈，这应该是代码的问题，回头我处理下
2.是的，是新任务

**Comment by lyxc** [comment]
目前可能是由于第一个问题的原因，导致第二个问题不会重新生成新的task，重新下载，而是在onTaskRunning回调中进度task.getPercent() 始终是100%

**Comment by AriaLyy** [comment]
```java
compile 'com.arialyy.aria:aria-core:3.2.12'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.12'
```
3.1.12已经修复了该问题
