### ISSUE TITLE
用LeakCanary检测到内存泄露，怎么解决呀？

### ISSUE THREAD

**Issue by liyqxtu** [AriaLyy/Aria#849]
D/LeakCanary: ​
====================================
HEAP ANALYSIS RESULT
====================================
1 APPLICATION LEAKS

References underlined with "~~~" are likely causes.
Learn more at https://squ.re/leaks.

283364 bytes retained by leaking objects
Signature: ebd3e1d690ac086395fd74da015c7bbb66c2cad
┬───
│ GC Root: System class
│
├─ com.arialyy.aria.core.scheduler.TaskSchedulers class
│    Leaking: NO (a class is never leaking)
│    ↓ static TaskSchedulers.INSTANCE
│                            ~~~~~~~~
├─ com.arialyy.aria.core.scheduler.TaskSchedulers instance
│    Leaking: UNKNOWN
│    Retaining 284.1 kB in 6195 objects
│    ↓ TaskSchedulers.mObservers
│                     ~~~~~~~~~~
├─ java.util.concurrent.ConcurrentHashMap instance
│    Leaking: UNKNOWN
│    Retaining 284.1 kB in 6193 objects
│    ↓ ConcurrentHashMap.table
│                        ~~~~~
├─ java.util.concurrent.ConcurrentHashMap$Node[] array
│    Leaking: UNKNOWN
│    Retaining 284.0 kB in 6192 objects
│    ↓ ConcurrentHashMap$Node[].[1]
│                               ~~~
├─ java.util.concurrent.ConcurrentHashMap$Node instance
│    Leaking: UNKNOWN
│    Retaining 283.7 kB in 6186 objects
│    ↓ ConcurrentHashMap$Node.val
│                             ~~~
├─ java.util.concurrent.ConcurrentHashMap instance
│    Leaking: UNKNOWN
│    Retaining 283.5 kB in 6184 objects
│    ↓ ConcurrentHashMap.table
│                        ~~~~~
├─ java.util.concurrent.ConcurrentHashMap$Node[] array
│    Leaking: UNKNOWN
│    Retaining 283.5 kB in 6183 objects
│    ↓ ConcurrentHashMap$Node[].[0]
│                               ~~~
├─ java.util.concurrent.ConcurrentHashMap$Node instance
│    Leaking: UNKNOWN
│    Retaining 283.4 kB in 6182 objects
│    ↓ ConcurrentHashMap$Node.val
│                             ~~~
╰→ com.xx.xx.fragment.xxFragment instance
     Leaking: YES (ObjectWatcher was watching this because com.xx.xx.fragment.xxFragment received
     Fragment#onDestroy() callback and Fragment#mFragmentManager is null)
     Retaining 283.4 kB in 6181 objects
     key = 497e5760-8bce-4ce0-bda5-a255d26e0c8f
     watchDurationMillis = 5157
     retainedDurationMillis = 129
====================================

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/851
