### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yangshaopeng** [AriaLyy/Aria#85]
你好，在AbsEntity.java里面，能不能将扩展字段str的类型换位object，因为我有可能存储的是一个bean对象，而不止是一个字符串，这样想对不对？

**Comment by AriaLyy** [comment]
数据库存储不了复杂的obj对象的，对于bean可以通过gson序列化为字符串，在读的时候，使用gson将字符串反序列化为bean对象

**Comment by yangshaopeng** [comment]
你好，如果我有一个DownloadEntity实例，怎么更改数据库中的值？是直接调用setStr()？还有每次在监听的时候，比如在onTaskRunning中，传过来的DownloadTask对象是从数据库中取的值吗？

**Comment by AriaLyy** [comment]
不需要监听，直接调用代码就行
```java
Aria.download(this).load(url).setExtendField(............);
```

**Comment by yangshaopeng** [comment]
先调用了Aria.download(mContext).load(downLoadEntity.getDownloadUrl()).setExtendField(str)，将扩展字段保存在数据库，
然后获取正在下载的集合，Aria.download(this).getTaskList()；
但是获取下载集合的时候，扩展字段的值为空，是不是保存数据库的时候没起作用？我看了一下好像没有执行保存数据库的操作？

**Comment by AriaLyy** [comment]
我明白问题出在哪了，当初我测试的时候是调用了'setDownloadPath'的方法，如果只是保存不做下载，是不能触发数据库的。
感谢你的反馈，该问题我已经处理

**Comment by yangshaopeng** [comment]
嗯嗯好，最近项目在用这个框架，好多还要麻烦你，那什么时候能更新到最新的版本？谢谢

**Comment by AriaLyy** [comment]
一般是晚上，公司的网络走了VPN，上传版本到`bintray.com`总是失败..

**Comment by yangshaopeng** [comment]
。。。。。。。。。。。。
那就明天再弄这个东西吧

**Comment by yangshaopeng** [comment]
你好，请问一下有没有提供删除已经下载或者正在下载apk文件的api？

**Comment by AriaLyy** [comment]
```java
compile 'com.arialyy.aria:aria-core:3.2.12'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.12'
```
3.1.12已经修复了该问题

调用
```java
Aria.download(this).load(url).cancel();
```
可以把正在下载的apk文件删除，如果是cancel(true)，会把下载完成或未下载完成的文件都删除

**Comment by yangshaopeng** [comment]
好的   thank you

**Comment by Horicer** [comment]
建议作者在扩展参数里面加一个 序列化的参数，这样就可以传入一个对象，不用转JSON

**Comment by AriaLyy** [comment]
序列化这东西一般使用fastJson或Gson就可以解决了，加序列化的功能，意义不是很大
