### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by Horicer** [AriaLyy/Aria#87]
点击下载报以下异常：
android.database.sqlite.SQLiteException: near "'123.mp4'": syntax error (code 1): , while compiling: UPDATE DownloadEntity SET completeTime='0', convertFileSize='', currentProgress='0', fileSize='25574099', isComplete='false', state='5', str='', fileName='405830547348361216', isGroupChild='false', isRedirect='false', redirectUrl='', url='****************.mp4', disposition='inline; filename="123.mp4"; filename*=utf-8' '123.mp4', downloadPath='/storage/emulated/0/tengdou/Download/video/405830547348361216', groupName='', md5Code='', serverFileName='' where rowid=1

**Comment by AriaLyy** [comment]
问题原因是七牛的服务器返回的这个字符串`"'inline; filename="123.mp4"; filename=utf-8' '123.mp4'"`导致的字符串编码问题。

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:aria-core:3.2.13'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.13'
```
已经修复了该问题
