### ISSUE TITLE
文件下载总是400

### ISSUE THREAD

**Issue by wenwenwen888** [AriaLyy/Aria#88]
任务【http://120.76.208.96:8855/LawFile/20170803/1501747249989测试.docx 】下载失败，错误码：400

我看了一下#36 的答案 
```
.addHeader("Accept-Encoding", "gzip, deflate")
```
和
```
.addHeader("Accept-Encoding", "identity")
```
都没能解决我的问题 . 

奇怪的是用AS自带的AVD居然能下载 , 用真机(HTCM8)测试就报400 , 求解答

**Comment by wenwenwen888** [comment]
刚刚测试了一下 , 好像是因为有中文的问题...
但是为毛在模拟器上即使有中文也可以正常下载 , 
而真机就不行...

**Comment by AriaLyy** [comment]
估计是机器默认编码的问题，你使用addHeader设置请求编码看看

**Comment by wenwenwen888** [comment]
解决了 , 我是直接把我url的中文转成URL编码就OK了 . 

加addHeader设置请求编码是怎么写 ?

**Comment by AriaLyy** [comment]
```
addHeader("Accept-Charset", "utf-8");
```
但是估计应该没有，按照你的作法，应该是中文导致的乱码，服务器不认识你的url导致的

**Comment by wenwenwen888** [comment]
```
addHeader("Accept-Charset", "utf-8");
```
还是不行 , 希望以后可以解决这个中文需要URL编码的问题
这问题关了 , 感谢答复 , 感谢开源

**Comment by AriaLyy** [comment]
好的，感谢支持
