### ISSUE TITLE
下载时在注解回调里showdialog会出现Unable to add window这个错

### ISSUE THREAD

**Issue by fansangg** [AriaLyy/Aria#89]
当我点击下载，然后在onTaskStart去showdialog，然后下载完成，dialog dismiss，退出activity再重新进来，点击下载，showdialog时就会出现Unable to add window

**Comment by fansangg** [comment]
我尝试在点击事件里showdialog,然后在complete这个回调里去dismiss这个dialog,这个dialog居然变成了null

**Comment by fansangg** [comment]
原来是我finish的时候忘记unregister

**Comment by AriaLyy** [comment]
你的注解是在activity中的还是在dialog中的？如果是activity的话，是不用手动unregister的，dialog如果没有设置dismiss事件的话，也不用手动unregister的。
还有一个可能，你使用的是哪个版本的代码？3.2.13之前的版本代码中存在不能自动unregister的可能。

**Comment by fansangg** [comment]
注解是在activity里,版本是3.2.6,不手动unregister的话就会出现上述情况

**Comment by AriaLyy** [comment]
这是以前的一个bug，该bug在3.2.13之后已经处理

**Comment by fansangg** [comment]
我更新到3.2.15版本之后
下载失败
logcat显示

E/BaseExecutePool: 请传入有效的任务key
E/BaseCachePool: 请传入有效的下载链接
D/BaseCachePool: 任务添加成功
W/BaseExecutePool: 任务添加成功
E/BaseExecutePool: 请传入有效的任务key
E/BaseCachePool: 请传入有效的下载链接
D/CommonUtil: 创建文件成功:/storage/emulated/0/smarthomeData/sync.json
E/AbsThreadTask: 下载链接异常
                 ExceptionDetailed:
                 ====================Exception Info====================
                 java.net.MalformedURLException: no protocol: 
                 java.net.URL.<init>(URL.java:589)
                 java.net.URL.<init>(URL.java:486)
                 java.net.URL.<init>(URL.java:435)
                 com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:51)
                 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                 java.lang.Thread.run(Thread.java:761)
                 ===================================================
E/AbsThreadTask: 任务【sync.json】执行失败
E/BaseExecutePool: 请传入有效的任务key
E/BaseCachePool: 请传入有效的下载链接
W/AbsTaskQueue: 重试下载失败，task 为null

上传时

W/System.err: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
W/System.err:     at android.os.Handler.<init>(Handler.java:200)
W/System.err:     at android.os.Handler.<init>(Handler.java:128)
W/System.err:     at com.arialyy.aria.core.upload.UploadTask$Builder.setOutHandler(UploadTask.java:85)
W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createUploadTask(TaskFactory.java:97)
W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:68)
W/System.err:     at com.arialyy.aria.core.queue.UploadTaskQueue.createTask(UploadTaskQueue.java:70)
W/System.err:     at com.arialyy.aria.core.queue.UploadTaskQueue.createTask(UploadTaskQueue.java:34)
W/System.err:     at com.arialyy.aria.core.command.normal.AbsNormalCmd.createTask(AbsNormalCmd.java:136)
W/System.err:     at com.arialyy.aria.core.command.normal.StartCmd.executeCmd(StartCmd.java:52)
W/System.err:     at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:158)
W/System.err:     at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:165)

**Comment by AriaLyy** [comment]
下载问题，是版本兼容性的问题，现在已经解决了
第二个问题是，线程中使用Aria导致Handler失败，目前，这两个问题都已经处理了
```
compile 'com.arialyy.aria:aria-core:3.2.17'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.17'
```

**Comment by fansangg** [comment]
下载的问题
比如我下载的数据命名为1.txt，大小为100kb，然后我在服务器增加了内容，大小变为200kb，重新下载到相同路径下1.txt，但是这个文件只能写入100kb的内容。

**Comment by AriaLyy** [comment]
这个不算bug，我是故意这样处理的，如果数据库中有该链接对应的数据，我就直接利用该信息直接进行下载，这样就减少了一次http请求。因为在我的想法中，只要文件不同了，那么下载地址也应该发生变化。
如果你需要这个功能的话，下个版本我会增加一个api，用于每次下载都重新请求文件信息

**Comment by AriaLyy** [comment]
3.2.18版本新增加了一个刷新信息的接口
```java
Aria.download(this).load(url, true).start();
```

**Comment by fansangg** [comment]
thanks
