### ISSUE TITLE
你好，问一下为什么在子类可以监听下载状态，而在父类不行？

### ISSUE THREAD

**Issue by yangshaopeng** [AriaLyy/Aria#91]
如题！

**Comment by AriaLyy** [comment]
在哪里注册就监听哪，在编译的时候，Aria根据类名和注解生成代理文件，如，一个Parent类有两个Child1、Child2，并且他们3个同时使用了@Download.onTaskStart，那么就会生成三个代理类Parent$$DownloadProxyListener、Child1$$DownloadProxyListener、Child2$$DownloadProxyListener；
而在注册的时候，this传递主要是传递了当前类的类名，Aria会根据当前注册的类名，使用不同的代理文件进行回调。
而在父类中，如果父类不是实现类，this指向的是当前Child，而不是它自己。

**Comment by yangshaopeng** [comment]
我是在父类进行注册，然后再父类进行监听，但不知道什么原因父类监听不到@Download.onTaskRunning注解的方法。

**Comment by AriaLyy** [comment]
你父类是否是实现类？

**Comment by yangshaopeng** [comment]
父类是个BaseActivity，并进行了注册Aria.download(this).register()，然后监听了一些下载状态的方法，比如@Download.onTaskRunning，@Download.onTaskStart等，再没做其它，不知道你说的实现指的是不是这个？

**Comment by AriaLyy** [comment]
实现类指的是你在该类是否被new出来，Activity的话，是否被展示到界面上，看你字面上的意思，BaseActivity可以被看成是超类，真正的实现类似child

**Comment by yangshaopeng** [comment]
父类有什么方法能监听到下载状态？

**Comment by AriaLyy** [comment]
使用调用父类的函数的方法便可，在child中，parent可以理解为child的一部分

```java
class parent{
  int state = Ientity.PRE;
 
//开始下载
 void onPostStart(DownloadTask task){
}

//下载中
void isRunning(DownloadTask task){

}

}

class child extends parent{
 
@Download.onTaskStart void start(DownloadTask task){
 onPostStart(task);
}

//其它状态类似


}

```

**Comment by yangshaopeng** [comment]
看来是子类必须要实现@Download.onTaskStart等注解的一些方法了？

**Comment by AriaLyy** [comment]
对的

**Comment by yangshaopeng** [comment]
好的  thanks
