### ISSUE TITLE
设置一组任务下载完成的回调

### ISSUE THREAD

**Issue by kaishuiWang** [AriaLyy/Aria#92]
@Download.onTaskComplete，对于单个任务这个方法可以，但是对于一组任务的时候，这个方法我试了下，不起作用，该如何解决，谢谢

**Comment by AriaLyy** [comment]
不起作用，原因可能有：
1、其中一个任务没有下载完成
2、其中一个下载任务下载失败
如果可以的话，能否贴上控制台日志或提供那两个下载地址？

**Comment by kaishuiWang** [comment]
08-12 15:50:07.706 15339-29454/com.king.reading I/HttpThreadTask: 任务【p010004.mp3】线程__0__下载完毕
08-12 15:50:07.798 15339-15339/com.king.reading W/AbsSchedulers: 没有下一任务
08-12 15:50:07.811 15339-15339/com.king.reading W/AbsSchedulers: 没有下一任务

@DownloadGroup.onTaskComplete
    public void taskComplete(DownloadGroupTask downloadTask){
        Toast.makeText(SysApplication.getApplication(),"音频下载完成"+mCurrent,Toast.LENGTH_SHORT).show();
    }
这个方法没有执行

**Comment by AriaLyy** [comment]
如果只有一个任务组，一般是不会出现这个日志的

你是怎样调用任务组的？你所使用的是哪个版本的代码？

下面是调用任务组的方式。
```java
Aria.download(this).load(List<String>  urls).start();
```

**Comment by kaishuiWang** [comment]
1.Aria.download(this)
                .load(urls)
                .setDownloadDirPath(playerPath)
                .setGroupAlias("任务组测试")
                .setSubTaskFileName(urls)
                .start();

2.@DownloadGroup.onTaskComplete() void taskComplete(DownloadGroupTask task) {
        Toast.makeText(getApplication(),"音频下载完成",Toast.LENGTH_SHORT).show();

    }

3.compile 'com.arialyy.aria:aria-core:3.2.17'
这是相关的信息

**Comment by AriaLyy** [comment]
你加没加这个 `annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.17'` ？
