### ISSUE TITLE
能不能整理一份框架的原理图，这样更容易理解整个框架的结构和使用方法

### ISSUE THREAD

**Issue by fishingcats** [AriaLyy/Aria#93]

**Comment by AriaLyy** [comment]
最近项目比较忙，等过段时间好好整理一下api和图纸

**Comment by Losefeather** [comment]
我想询问下关于ftp断点续传的问题，我不知道在框架里面如何实现的，我在用ftpClient.storeFile这个方法的时候，返回总是false，只有在断点续传的时候遇到过 。直接上传没有问题您用到过一样的问题吗
