### ISSUE TITLE
下载handleNewTask()这个地方有问题

### ISSUE THREAD

**Issue by fishingcats** [AriaLyy/Aria#94]
@Override protected void handleNewTask() {
//    if (CommonUtil.isDiskFull(mEntity.getFileSize())){
//      mListener.onDiskFull();
//    }
    CommonUtil.createFile(mTempFile.getPath());
    BufferedRandomAccessFile file = null;
    try {
      file = new BufferedRandomAccessFile(new File(mTempFile.getPath()), "rwd", 8192);
      //设置文件长度
      file.setLength(mEntity.getFileSize());
//      throw new IOException("test handleNewTask");
    } catch (IOException e) {
      failDownload("下载失败【downloadUrl:"
          + mEntity.getUrl()
          + "】\n【filePath:"
          + mEntity.getDownloadPath()
          + "】\n"
          + CommonUtil.getPrintException(e));
    } finally {
      if (file != null) {
        try {
          file.close();
        } catch (IOException e) {
          e.printStackTrace();
        }
      }
    }
  }
如果磁盘满了或者其他原因，进入IO异常的case，仍然会开启下载：
private void handleBreakpoint() {
         。。。
    if (isNewTask) {
      handleNewTask();
    }
        。。。
    startSingleTask(recordL);
  }

**Comment by AriaLyy** [comment]
感谢反馈，回头我查看下源码是啥问题导致的

**Comment by AriaLyy** [comment]
3.2.20 已经修复了该问题
