### ISSUE TITLE
下载重试机制有漏洞？

### ISSUE THREAD

**Issue by fishingcats** [AriaLyy/Aria#96]
08-16 17:03:03.493 5049-18072/com.iflytek.appstoreauto E/AbsThreadTask: 下载失败【http://rs.0.gaoshouyou.com/d/51/46/58514d126c46b8a3f27fc8c7db3b09ec.apk】
                                                                        ExceptionDetailed:
                                                                        ====================Exception Info====================
                                                                        java.net.SocketTimeoutException
                                                                        java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
                                                                        java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                        java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
                                                                        java.io.BufferedInputStream.read(BufferedInputStream.java:283)
                                                                        com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)
                                                                        java.io.InputStream.read(InputStream.java:162)
                                                                        com.arialyy.aria.core.download.downloader.HttpThreadTask.run(HttpThreadTask.java:81)
                                                                        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        java.lang.Thread.run(Thread.java:841)
                                                                        ===================================================

**Comment by fishingcats** [comment]
HttpThreadTask这个线程里面，下载异常了只打印异常信息，不做重新下载的处理么？

**Comment by fishingcats** [comment]
下载失败重试的机制是什么样的？针对下载任务重试，还是针对任务的每一个下载线程都有重试？

**Comment by AriaLyy** [comment]
重试是针对任务的，目前还没有做针对线程的重试。 这个仔细想一下，确实有些问题，如果多条线程同时下载，只有一条线程出错，那么就会导致重试机制失效。感谢反馈。

**Comment by fishingcats** [comment]
这个问题短期内可有修复计划，没有的话，我就自己添加了。

**Comment by AriaLyy** [comment]
这个已经修复了，目前正在验证

**Comment by AriaLyy** [comment]
3.2.22已经修复了这个问题

**Comment by fishingcats** [comment]
OK 辛苦啦
