### ISSUE TITLE
关于断点下载

### ISSUE THREAD

**Issue by q461935514** [AriaLyy/Aria#97]
想问问下用的url支持断点下载但是用的你的库下载时候提示该下载不支持断点下载，新人求罩！

**Comment by AriaLyy** [comment]
能提供下Url吗？我的断点的判断是根据206来处理的

**Comment by q461935514** [comment]
http://120.25.196.56:8000/filereq?id=15692406294&ipncid=105635&client=android&filename=20170819185541.avi

**Comment by AriaLyy** [comment]
我是按照http标准返回码做的是否支持断点续传判断：
当我在头部设置`Content-Range:0-`时，如果支持断点续传返回的应该是206，不支持断点续传时应该返回200。
而你这链接返回码是200。。。

**Comment by q461935514** [comment]
额。。。是不是我们这边用的HTTP1.1的导致不行。。。

**Comment by AriaLyy** [comment]
应该不是，我也接触过http1.1的，估计返回码是后台写成200的
