### ISSUE TITLE
请问是否能获取下载失败的原因？

### ISSUE THREAD

**Issue by yanyiqun001** [AriaLyy/Aria#98]

**Comment by AriaLyy** [comment]
目前没有这个api，只能在控制台查看

**Comment by yanyiqun001** [comment]
是这样的，我的下载地址不是指向一个文件，而是一个流，访问这个地址下载大部分是失败的，偶尔可以= =，而我用HttpUrlConnection读取流数据写入文件的方式是没问题的，不知道原因在哪

**Comment by AriaLyy** [comment]
指向流式什么意思，302跳转吗？

**Comment by yanyiqun001** [comment]
就是文件在另一个服务器上，服务端把文件的输出流写到这个地址了，我访问这个地址下载文件

**Comment by AriaLyy** [comment]
能否提供一下地址？

**Comment by yanyiqun001** [comment]
不好意思有点不方便了~因为还需要传递cookie的

**Comment by AriaLyy** [comment]
那到时候增加一个获取错误的api吧
