### ISSUE TITLE
下载文件添加任务状态获取，发现一系列获取任务状态方法不执行

### ISSUE THREAD

**Issue by candebbs** [AriaLyy/Aria#99]
我在RecyclerView中的item下载文件，
我加了代码：
```
    /** 任务执行时的注解，任务正在执行时进行回调 */
    @Download.onTaskRunning()
    void taskRunning(DownloadTask task) {
```

发现无法执行代码，
加了
`Aria.download(this).register();`
请问是为什么？我看demo会自动生成MultiTaskActivity$$DownloadListenerProxy，该文件为Aria自动生成的代理文件，请不要修改该文件的任何代码！
请问这是怎样生成的？

**Comment by AriaLyy** [comment]
代理文件是编译的时候自动生成的

compile 'com.arialyy.aria:aria-core:3.2.22'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.22'

你添加annotationProcessor 没有？
如果添加了，编译的时候，控制台的messages有没有警告提示？
你工程中没有使用apt插件？

**Comment by candebbs** [comment]
首先添加了

```
compile 'com.arialyy.aria:aria-core:3.2.22'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.22'
```
使用apply plugin: 'android-apt'

**Comment by AriaLyy** [comment]
是apply plugin: 'android-apt'导致的问题

请将使用apt的其它类库切换到annotationProcessor

参考链接：http://www.cnblogs.com/whoislcj/p/6148410.html

**Comment by candebbs** [comment]
谢谢，可以了
